export type Lang = "en" | "tr";

export const copy = {
  en: {
    nav: { about: "About", aboutHref: "/about", lab: "Lab", labHref: "/lab", calculators: "Calculators", calculatorsHref: "/calculators", blog: "Blog", blogHref: "/blog", stack: "Stack", stackHref: "/stack", contact: "Contact", contactHref: "/contact", cta: "Get in touch", lang: "TR", langHref: "/tr" },
    hero: {
      line1: "Growth you can measure.",
      line2: "Products that keep users.",
      lead: "I'm Ali Demirbaş, a growth marketer for mobile products. I build acquisition, CRM and lifecycle programs on data - not guesswork.",
      sub: "Currently leading mobile app growth at Aksigorta in Istanbul, after growth roles at Vodafone, Getir and Wingie Enuygun Group.",
      ctaPrimary: "Get in touch",
      ctaSecondary: "LinkedIn",
      reassurance: ["Mobile App Growth Lead, Aksigorta", "7+ years in growth", "Istanbul"],
    },
    lab: {
      label: "Lab",
      title: "Things I've been building",
      intro: "A collection of open-source tools, experiments and side projects. Mostly marketing and growth, sometimes not.",
      viewAll: "Explore the archive",
      projects: [
        {
          name: "Lifecycle Marketing Journey Builder",
          slug: "claude-lifecycle",
          desc: "Looks at the customer data you already track and builds lifecycle journeys around what you can actually measure, segment and act on.",
          tags: ["Claude Code Plugin", "CRM", "Lifecycle Marketing", "26 journey patterns", "9 industries"],
          links: [
            { label: "Explore the Journey Builder", href: "/lab/claude-lifecycle" },
            { label: "View on GitHub", href: "https://github.com/ali-demirbas/claude-lifecycle" },
            { label: "Try the demo", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
          ],
        },
        {
          name: "Canonical Journey Library",
          slug: "lifecycle-card-archive",
          desc: "{count} domain-neutral lifecycle state machines - trigger, condition, wait, outcome, exit, handoff - with the orchestration rules that decide which one owns a person at a given moment.",
          tags: ["CRM", "Lifecycle Marketing", "{count} journeys", "{categories} categories", "{rules} orchestration rules"],
          links: [{ label: "Explore the library", href: "/lab/journeys" }],
        },
        {
          name: "A/B Test Playbook",
          slug: "ab-test-playbook",
          desc: "211 A/B test scenarios across real product journeys, with guidance on what to test, what to measure and what can invalidate the result.",
          tags: ["Claude Code Plugin", "A/B Testing", "CRO", "211 scenarios"],
          links: [
            { label: "Explore the playbook", href: "/lab/ab-testing" },
            { label: "View on GitHub", href: "https://github.com/ali-demirbas/ab-test-playbook" },
          ],
        },
        {
          name: "Marketing Dashboard Builder",
          slug: "dashboard-builder",
          desc: "Takes messy exports from different marketing platforms, checks what can actually be compared, and turns the data into a decision-ready dashboard.",
          tags: ["Claude Code Plugin", "Marketing Analytics", "11 dashboard templates", "17 tests"],
          links: [
            { label: "Explore the tool", href: "/lab/dashboard-builder" },
            { label: "View on GitHub", href: "https://github.com/ali-demirbas/dashboard-builder" },
          ],
        },
        {
          name: "Google Ads Change History Explorer",
          slug: "google-ads-change-history-dashboard",
          desc: "Turns a Google Ads change-history export into a searchable dashboard - what changed, who changed it, when, and how significant it was.",
          tags: ["Python", "Google Ads", "Offline Dashboard", "57 self-tests"],
          links: [{ label: "View on GitHub", href: "https://github.com/ali-demirbas/google-ads-change-history-dashboard" }],
        },
        {
          name: "Numerspace",
          slug: "numerspace",
          desc: "75+ free calculator tools spanning finance, health, career, marketing and daily life - built for a fast, accurate answer, no account or paywall.",
          tags: ["Web App", "Calculator Tools", "75+ tools", "EN/TR"],
          links: [{ label: "Visit numerspace.com", href: "https://www.numerspace.com" }],
        },
      ],
      shell: {
        backToSite: "Back to site",
      },
      page: {
        title: "Canonical Journey Library",
        intro:
          "{count} domain-neutral lifecycle state machines across {categories} categories, held together by {rules} orchestration rules. Filter by goal, lifecycle stage or what the trigger is allowed to conclude, or search - each entry is a graph, not a sequence.",
        searchPlaceholder: "Search journeys...",
        goalLabel: "Goal / use case",
        lifecycleStageLabel: "Lifecycle stage",
        lifecycleStageHint:
          "Only 4 of 26 categories are anchored to a point in the customer lifecycle - the rest run the same regardless of where someone is, so most journeys show as cross-lifecycle.",
        evidenceLabel: "Trigger evidence",
        filtersLabel: "Filters",
        showMore: "Show more",
        showLess: "Show less",
        clearAll: "Clear all",
        results: "journeys",
        empty: "Nothing matches those filters.",
        nodesLabel: "nodes",
        entityLabel: "Entity",
        competesLabel: "Competes",
        distinctLabel: "Distinct from",
        preemptedLabel: "Pre-empted by",
        guardrailsLabel: "Guardrails",
        ruleLabel: "Reusable rule",
        flowLabel: "Graph",
        more: "more",
        less: "less",
        terminalLabel: "terminal",
        close: "Close",
        backToLibrary: "All journeys",
        mergedNote:
          "{from} was merged into {to}. That id is no longer a journey of its own; what it covered lives here.",
        evidence: {
          authoritative: "authoritative",
          declared: "declared",
          behavioral: "behavioral",
          inferred: "inferred",
        },
        evidenceHint:
          "What the trigger is allowed to conclude. Authoritative evidence can establish an outcome; declared, behavioral and inferred evidence can prioritise work or ask for verification, and cannot conclude one.",
      },
    },
    about: {
      metaTitle: "About - Ali Demirbaş",
      metaDesc: "Digital Marketing · Analytics · Growth Strategy",
      eyebrow: "About",
      title: "Professional Profile",
      sub: "Digital Marketing · Analytics · Growth Strategy",
      moreLink: "More about me",
      // Home page teaser only - kept separate from `lead` below (the
      // /about page's own opening line) so editing one doesn't change
      // the other; the two pages make different first impressions on
      // purpose.
      teaserLead:
        "I build reliable measurement frameworks that help digital products grow sustainably. My work includes implementing GA4 and GTM tracking systems, optimizing Adjust MMP setups, and designing evidence-based CRO programs that turn user insights into measurable business growth. I approach marketing as an iterative process built on accurate data, structured experimentation, and continuous optimization.",
      lead:
        "With over eight years of experience in digital marketing and growth, I have worked on strategies designed to support the growth objectives of different products and business models.",
      body:
        "My experience spans analytics, user acquisition, product, and growth strategy. I use data to evaluate digital marketing performance, understand user behavior, and identify opportunities for growth. Across campaign management, measurement, and optimization, I focus on keeping marketing initiatives aligned with business goals and delivering measurable outcomes.",
      experience: "Experience",
      timeline: [
        {
          kind: "single",
          year: "2026",
          co: "Aksigorta",
          logo: "/logos/aksigorta.svg",
          role: "Mobile App Growth Lead",
          period: "Apr 2026 – Present",
          desc: "Leading mobile app growth strategy, driving user acquisition and engagement for one of Turkey's largest insurers.",
        },
        {
          kind: "single",
          year: "2024",
          co: "Vodafone",
          logo: "/logos/vodafone.svg",
          role: "Growth Marketing Lead",
          period: "Aug 2024 – Apr 2026",
          desc: "Led growth marketing across digital channels, combining data-driven acquisition with lifecycle programs.",
        },
        {
          kind: "single",
          year: "2023",
          co: "Getir",
          logo: "/logos/getir.svg",
          role: "Growth – CRM Analytics Executive",
          period: "Sep 2023 – Aug 2024",
          desc: "Managed CRM analytics and growth initiatives for rapid commerce, optimizing retention and LTV.",
        },
        {
          kind: "group",
          year: "2021",
          co: "Wingie Enuygun Group",
          logo: "/logos/enuygun.png",
          span: "Full-time · 2 yrs",
          roles: [
            {
              role: "Experienced Lifecycle Marketing Specialist (Growth)",
              period: "Jan 2023 – Aug 2023",
              desc: "Owned lifecycle and CRM programs end-to-end across the group's travel brands.",
            },
            {
              role: "Lifecycle Marketing Specialist (Growth)",
              period: "Sep 2021 – Jan 2023",
              desc: "Built and ran lifecycle marketing programs for a leading online travel platform.",
            },
          ],
        },
        {
          kind: "single",
          year: "2020",
          co: "Albayrak Grubu",
          logo: "/logos/albayrak.svg",
          role: "Digital Marketing Specialist",
          period: "Oct 2020 – Aug 2021",
          desc: "Managed digital marketing campaigns across group companies.",
        },
        {
          kind: "single",
          year: "2019",
          co: "Doğuş Oto",
          logo: "/logos/dogus-oto.svg",
          role: "Jr. Digital Marketing Specialist",
          period: "Sep 2019 – Aug 2020",
          desc: "Digital marketing execution for one of Turkey's leading automotive dealer groups.",
        },
      ],
    },
    stack: {
      metaTitle: "Stack - Ali Demirbaş",
      metaDesc: "The tools Ali Demirbaş instruments, queries and optimizes growth with every day.",
      eyebrow: "Stack",
      title: "Stack",
      sub: "Tools I use to design, build, measure and grow.",
      // Home page teaser only - the /stack page keeps its own title/sub above.
      homeTitle: "Tools I use",
      homeIntro: "The tools I use to design experiments, build reliable measurement, analyze user behavior, and optimize growth.",
      homeMore: "Explore my toolkit",
    },
    contact: {
      metaTitle: "Contact - Ali Demirbaş",
      metaDesc: "Reach Ali Demirbaş by email or connect on LinkedIn.",
      eyebrow: "Contact",
      title: "Let's collaborate on something great.",
      sub: "I'm always looking to collaborate on interesting projects with great people. Need a supportive hand? I have two!",
      linkedinLabel: "Connect on LinkedIn",
      linkedinGo: "View profile",
      emailLabel: "Send an email",
      emailGo: "Email me",
      emailPill: "E-Mail",
      reasonsTitle: "What brings you here",
      reasons: [
        { title: "A role or opportunity", desc: "Open to growth/CRM leadership roles - full-time or fractional." },
        { title: "A project or collaboration", desc: "Lifecycle marketing, measurement setup, or one of the open-source Lab tools." },
        { title: "A question", desc: "About a calculator, a journey pattern, or anything else on this site." },
      ],
      scheduleTitle: "Schedule a call",
      scheduleSub: "Book a 30 minute intro call.",
      formTitle: "Send a message",
      formName: "Name",
      formEmail: "Email",
      formCompany: "Company website (optional)",
      formSubject: "Subject",
      formMessage: "Your message",
      formSubmit: "Open in email",
      formNote: "Opens a pre-filled draft in your email app - this site has no backend to send it for you.",
    },
    /* Journey Builder PRODUCT PAGE (/lab/claude-lifecycle). New page this
       round - the project previously existed only as a Lab index card
       pointing at GitHub. Every number this copy refers to is derived from
       the canonical library at build time (journey-marketing.ts), never
       typed in here, and every quoted field (trigger events, branch
       labels, timeout reasons, handoff payloads) is read straight off the
       real journey record rather than paraphrased. */
    journeyBuilder: {
      metaTitle: "Lifecycle Marketing Journey Builder - Ali Demirbaş",
      metaDesc: "A canonical library of lifecycle journeys as state machines: triggers, branches, waits, handoffs and exits - not campaign templates.",
      eyebrow: "Lab / Journey Builder",
      title: "Lifecycle journeys as state machines, not campaign templates.",
      sub: "Every journey here is a graph: what starts it and what deliberately doesn't, where it forks and what each arm means, how long it waits and what happens when that runs out, and which lifecycle owns the person next.",
      ctaLibrary: "Explore the library",
      ctaJourney: "Open this journey",
      proof: ["Open source", "Claude Code plugin", "Nothing to sign up for"],
      canvas: {
        nodes: "nodes",
        rejoins: "rejoins at Reconcile",
      },
      scale: {
        journeys: "canonical journeys",
        categories: "categories",
        nodes: "nodes",
        kinds: "node types",
      },
      story1: {
        eyebrow: "Triggers",
        title: "It starts on evidence, or it doesn't start.",
        body: "Most bad lifecycle automation is a journey that fired on one weak signal. Every trigger here names what it needs — and, separately, the lookalike signals that are not enough on their own.",
        caption: "Trigger evidence",
        requires: "Requires",
        insufficient: "Insufficient alone",
      },
      story2: {
        eyebrow: "Branching",
        title: "Every fork has both arms named.",
        body: "A condition with one arm is a filter wearing a decision's clothes — it hides what happens to everyone who fails it. So a condition here carries at least two branches, each with the real rule that routes into it.",
        caption: "A real fork",
        conditionsLabel: "conditions in the library",
        note: "Neither arm is a dead end: both route to a named node.",
      },
      story3: {
        eyebrow: "Time",
        title: "Waiting is a decision with a deadline.",
        body: "A wait with no timeout strands people on an event that may never arrive. A timeout with nowhere to go is an exit pretending to be patience. Every wait here names both arms and says whether activity pushes the deadline back.",
        caption: "One wait, both arms",
        waitsLabel: "waits in the library",
        opens: "Wait opens",
        onEvent: "On event",
        onTimeout: "On timeout",
        note: "A bounded window that any engagement extends is not bounded.",
      },
      anatomy: {
        eyebrow: "Anatomy",
        title: "One journey, every part labelled.",
        body: "This is a real canonical journey, unmodified. Read it once and the model behind all of them is clear: a trigger, forks with named arms, a bounded wait, an action that appends rather than overwrites, a handoff, and exits that say when a new instance may start.",
        legendTitle: "Node types across the library",
      },
      inspector: {
        eyebrow: "Zoom in",
        title: "A handoff is not just an arrow.",
        body: "When ownership moves to another lifecycle, something has to survive the boundary. A handoff names its destination, the condition it fires on, and exactly what it carries across — so the receiving journey starts informed rather than blank.",
        to: "to",
        on: "on",
        carries: "carries",
        handoffsLabel: "handoffs across the library",
      },
      library: {
        eyebrow: "The library",
        title: "{count} journeys. Built to be read.",
        body: "Filed by category, each one a graph you can open and follow node by node. They are domain-neutral state machines, not sector templates — the distinction is what keeps two journeys from being the same journey twice.",
        cta: "Explore the journey library",
        nodes: "nodes",
        moreCategories: "more",
      },
      how: {
        eyebrow: "How it works",
        title: "Find it, read it, adapt it.",
        body: "The library is the product. These are the three things you actually do with it.",
        steps: [
          { title: "Find the journey", body: "Filter by category, lifecycle stage, goal or the kind of evidence a trigger runs on." },
          { title: "Read the logic", body: "Follow the graph node by node — every branch, wait and handoff is written out, with the rule behind it." },
          { title: "Adapt it", body: "Take the state machine into your own stack. The logic is the deliverable; message copy was never in scope." },
        ],
      },
      related: {
        title: "Related",
        abTest: "A/B Test Playbook",
        abTestDesc: "The experimentation side of the same practice.",
      },
    },
    abTesting: {
      metaTitle: "A/B Test Playbook - Ali Demirbaş",
      metaDesc: "211 real growth-test scenarios for Claude Code: what to test, which KPI to track, what not to do.",
      eyebrow: "Lab / A/B Testing",
      title: "An A/B test engine that won't let you skip the guardrail.",
      sub: "ab-test-playbook is an open-source Claude Code plugin built from 211 real e-commerce, mobile app and SaaS growth-test scenarios. It helps you pick a proven test for where a user is in their journey, keeps new ones disciplined to one variable at a time, and runs the real statistics instead of eyeballing significance.",
      install: {
        title: "Install",
        options: [
          {
            label: "Plugin marketplace",
            code: "/plugin marketplace add ali-demirbas/ab-test-playbook\n/plugin install ab-test-playbook@ab-test-playbook",
          },
          {
            label: "Local clone",
            code: "git clone https://github.com/ali-demirbas/ab-test-playbook.git\nclaude --plugin-dir ./ab-test-playbook",
          },
          {
            label: "skills.sh",
            code: "npx skills add ali-demirbas/ab-test-playbook --all",
          },
        ],
      },
      framework: {
        title: "Every scenario follows the same three-box discipline",
        boxes: [
          { title: "What to test", desc: "The specific questions the experiment has to answer - not \"test the button\", but every hypothesis the result needs to settle." },
          { title: "KPIs to track", desc: "One primary metric that decides the winner, plus at least one guardrail that must not get worse while it improves." },
          { title: "What not to do", desc: "The mistakes that quietly invalidate the test - the ones a rushed setup makes without anyone noticing until the results are unreadable." },
        ],
      },
      principlesTitle: "Five rules the plugin won't bend on",
      principles: [
        { title: "One variable, always", desc: "Every variant pair changes exactly one thing. Ask for a multivariate test and it gets split into separate ones - insist, and the output says plainly that no one will know which change produced the result." },
        { title: "One primary metric", desc: "The first KPI in the list decides the winner. Presenting five metrics as equally important is exactly how a losing test gets called a win." },
        { title: "No guardrail, no scenario", desc: "Every scenario ships with at least one metric that must not degrade - margin, refund rate, speed, support tickets. If a change could affect accessibility, that's a guardrail candidate too." },
        { title: "Protection isn't a growth lever", desc: "CAPTCHA, identity or age verification, two-factor login, legal consent steps - never proposed as friction to remove, even if asked. Those exist for protection, not conversion; the plugin says so and generates nothing." },
        { title: "Confidence is stated, not implied", desc: "Every suggestion says how strong the evidence behind it is - the user's own data, an archive precedent, an industry pattern, or a hunch. A weak-evidence idea can still be offered, but never dressed up as certain." },
      ],
      exampleTitle: "One real scenario from the archive",
      example: {
        idx: "ECOM-CART",
        title: "Does a visible coupon-code field increase cart abandonment?",
        intro: "A visible coupon box can send a user with no code off-site to \"go find a discount.\" Moving the code behind a link can close that leak - but it can also reduce campaign usage.",
        testBox: {
          label: "What to test",
          items: [
            "Leak: does moving the coupon field behind a link reduce abandonment?",
            "Segment: do new and returning users search for coupons differently?",
            "Copy: does \"I have a discount code\" perform differently from \"Apply coupon\"?",
            "Campaign: does the effect reverse during active campaign periods?",
            "Error: what's the abandonment rate for users whose code fails?",
          ],
        },
        kpiBox: {
          label: "KPIs to track",
          items: [
            "Revenue Per Visitor (RPV) - the primary metric",
            "Order Completion Rate",
            "Coupon Usage Rate (guardrail)",
            "Checkout Step Abandonment",
            "Campaign Participation (guardrail)",
          ],
        },
        dontBox: {
          label: "What not to do",
          items: [
            "Don't remove the coupon field entirely - users with a code will be frustrated.",
            "Don't leave an invalid-code error ambiguous.",
            "Don't launch or end an active campaign during the test.",
            "Don't hide the coupon field so far it becomes unfindable.",
            "Don't change both the position and the copy in the same test.",
          ],
        },
      },
      faqTitle: "FAQ",
      faqIntro: "Answers drawn from the plugin's own methodology docs, not external citations.",
      faq: [
        {
          q: "What should I A/B test first?",
          a: "Rank candidates with ICE (Impact x Confidence x Ease), not gut feeling. A low-effort test on a high-traffic page beats an ambitious test on a low-traffic one.",
        },
        {
          q: "How many visitors do I need for an A/B test?",
          a: "Not a rule-of-thumb number - it's computed from your actual baseline conversion rate and the minimum effect size you care about detecting. Without real traffic data, no duration or sample-size promise is made.",
        },
        {
          q: "Can I peek at results early and stop when they look significant?",
          a: "No - repeatedly checking a test and stopping the moment it looks significant inflates the false-positive rate well above 5%, even with no real difference. Decide sample size or duration up front, look once. The one exception: a guardrail metric visibly breaking mid-test.",
        },
        {
          q: "Why run a test for at least two full weeks?",
          a: "Not a statistical-power requirement - a coverage requirement. Weekday/weekend behavior and payday effects need to be represented in the data, even if the sample-size target is hit in three days.",
        },
        {
          q: "What are common A/B testing mistakes that invalidate a result?",
          a: "Changing more than one variable at once; declaring a winner from the first days of data; reading conversion rate alone on a price test (revenue per visitor can drop even as CR rises); redesigning \"Variant A\" instead of testing the real page as-is; running overlapping tests on the same page.",
        },
        {
          q: "Is this playbook the right tool for every product?",
          a: "No, and it says so. It fits B2C e-commerce, consumer mobile apps and self-serve SaaS with real weekly traffic. It fits poorly for low-traffic enterprise sales pages, long sales cycles, or heavily regulated flows - for those, it points to qualitative methods instead of forcing a split test where it doesn't belong.",
        },
      ],
      repoLink: "View on GitHub",
      demoLink: "Live demo",
      /* PRODUCT-PAGE STORYTELLING COPY (this round). The keys above are
         untouched - metaTitle/metaDesc/title/sub/install/framework/
         principles/example/faq are the same verified strings the page
         already shipped, still sourced from the plugin's own README/
         methodology docs. Everything below is new copy written for the
         redesigned composition, and every number in it is derived from
         the real dataset at build time (see ab-test-marketing.ts), not
         typed in here. */
      product: {
        heroCtaLibrary: "Explore the library",
        heroProof: ["Open source", "Claude Code plugin", "Nothing to sign up for"],
        brief: {
          label: "Scenario brief",
          control: "Control",
          variant: "Variant",
          testedSlot: "Tested element",
          testedSlotValue: "Coupon code field",
          sideA: "Coupon field open in the cart, a directly visible box",
          sideB: "Coupon field hidden behind an “I have a discount code” link",
          primaryKpi: "Primary KPI",
          primaryKpiValue: "Revenue Per Visitor (RPV)",
          guardrail: "Guardrail",
          guardrailValue: "Coupon Usage Rate must not collapse",
        },
        scale: {
          scenarios: "scenarios",
          surfaces: "product surfaces",
          categories: "categories",
          guardrails: "guardrail rules",
        },
        story1: {
          eyebrow: "Coverage",
          title: "Start from the surface you're actually on.",
          body: "The library isn't a flat list of tips. Every scenario is filed against the product surface it belongs to — a product page test and a checkout test fail in different ways — so you narrow by where the problem is before anyone argues about what to change.",
          caption: "Scenarios by surface",
        },
        story2: {
          eyebrow: "Discipline",
          title: "One variable, or it isn't a test.",
          body: "Every scenario names the single slot that changes and holds the rest of the page identical. Most of the library ships with the control and the variant already written out, so there's no room to quietly change two things and call the result a finding.",
          caption: "Control vs variant",
          diffNote: "Everything else on the page stays identical.",
          sidesNote: "scenarios ship with the two sides already written",
        },
        story3: {
          eyebrow: "Guardrails",
          title: "Every scenario ships with what must not break.",
          body: "A guardrail is the metric that has to hold while the primary one improves — margin, refund rate, coupon usage, accessibility. They aren't optional here: no scenario in the library carries fewer than five.",
          caption: "What not to do",
          ledgerNote: "guardrail rules across the library",
        },
        library: {
          eyebrow: "The library",
          title: "{count} experiments. One place to find the next one.",
          body: "Filed by category and surface, searchable, and readable without installing anything. Each entry carries the variable under test, the primary KPI and the guardrails.",
          cta: "Explore all tests",
          filterLabel: "Browse by category",
        },
        how: {
          eyebrow: "How it works",
          title: "Find it, build it, read it.",
          body: "Three steps — and the third is the one most tests get wrong.",
          steps: [
            { title: "Find the opportunity", body: "Narrow by the surface you're working on, then pick from the scenarios already filed against it." },
            { title: "Design the experiment", body: "The scenario hands you the hypothesis, one primary KPI and the guardrails. Exactly one variable moves." },
            { title: "Read the result", body: "Decide with the statistics, not the chart. A double-digit lift can still be noise." },
          ],
          step1: { label: "Surface", matches: "scenarios on this surface" },
          step2: { hypothesis: "Hypothesis", kpi: "Primary KPI", guardrail: "Guardrail" },
          step3: {
            control: "Control",
            variant: "Variant",
            uplift: "Relative uplift",
            pValue: "p-value",
            verdict: "Significant at 95%?",
            verdictValue: "No — keep running",
            note: "A worked example from this site's own Significance calculator: a +16% lift that doesn't clear the bar.",
            calculators: "Run it on your own numbers",
            test: "two-proportion z-test",
          },
        },
        rulesEyebrow: "The rules",
        installEyebrow: "Install",
        faqEyebrow: "Questions",
      },
    },
    finalCta: {
      title: "Let's talk growth.",
      body: "Whether it's a role, a project or a question about lifecycle marketing - my inbox is open.",
      button: "mehmetalidemirbas@gmail.com",
      linkedin: "Connect on LinkedIn",
    },
    notFound: {
      metaTitle: "Page not found - Ali Demirbaş",
      eyebrow: "404",
      title: "This page doesn't exist.",
      body: "The link may be outdated, or the page may have moved.",
      cta: "Back to home",
      labLink: "Explore the Lab",
    },
    footer: {
      left: "Ali Demirbaş, 2026",
      right: "Istanbul",
      quickLinks: "Quick links",
      projects: "Lab projects",
      connect: "Connect",
      home: "Home",
    },
  },
  tr: {
    nav: { about: "Hakkımda", aboutHref: "/tr/about", lab: "Lab", labHref: "/tr/lab", calculators: "Hesaplayıcılar", calculatorsHref: "/tr/calculators", blog: "Blog", blogHref: "/tr/blog", stack: "Yığın", stackHref: "/tr/stack", contact: "İletişim", contactHref: "/tr/contact", cta: "İletişime geç", lang: "EN", langHref: "/" },
    hero: {
      line1: "Ölçülebilir büyüme.",
      line2: "Kullanıcıyı tutan ürünler.",
      lead: "Ben Ali Demirbaş, mobil ürünler için growth marketer. Edinim, CRM ve lifecycle programlarını tahminle değil veriyle kuruyorum.",
      sub: "Şu an İstanbul'da Aksigorta'da mobil uygulama büyümesini yönetiyorum; öncesinde Vodafone, Getir ve Wingie Enuygun Group'ta growth rollerindeydim.",
      ctaPrimary: "İletişime geç",
      ctaSecondary: "LinkedIn",
      reassurance: ["Mobile App Growth Lead, Aksigorta", "Growth'ta 7+ yıl", "İstanbul"],
    },
    lab: {
      label: "Lab",
      title: "Yaptığım şeyler",
      intro: "Açık kaynak araçlar, deneyler ve yan projelerden oluşan bir koleksiyon. Çoğunlukla pazarlama ve growth, bazen değil.",
      viewAll: "Arşivi keşfet",
      projects: [
        {
          name: "Lifecycle Pazarlama Journey Üretici",
          slug: "claude-lifecycle",
          desc: "Zaten takip ettiğin müşteri verisine bakar, ölçebildiğin, segmentleyebildiğin ve aksiyon alabildiğin şeyler üzerine lifecycle journey'ler kurar.",
          tags: ["Claude Code Eklentisi", "CRM", "Lifecycle Pazarlama", "26 journey deseni", "9 sektör"],
          links: [
            { label: "Journey Builder'ı incele", href: "/tr/lab/claude-lifecycle" },
            { label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/claude-lifecycle" },
            { label: "Demoyu dene", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
          ],
        },
        {
          name: "Canonical Journey Kütüphanesi",
          slug: "lifecycle-card-archive",
          desc: "Sektörden bağımsız {count} lifecycle state machine - trigger, condition, wait, outcome, exit, handoff - ve belirli bir anda bir kişinin sahibinin hangi journey olduğunu belirleyen orkestrasyon kuralları.",
          tags: ["CRM", "Lifecycle Pazarlama", "{count} journey", "{categories} kategori", "{rules} orkestrasyon kuralı"],
          links: [{ label: "Arşivi keşfet", href: "/tr/lab/journeys" }],
        },
        {
          name: "A/B Test Playbook",
          slug: "ab-test-playbook",
          desc: "Gerçek ürün journey'leri üzerinden 211 A/B test senaryosu - ne test edileceği, ne ölçüleceği ve sonucu geçersiz kılabilecek şeyler konusunda rehberlikle birlikte.",
          tags: ["Claude Code Eklentisi", "A/B Test", "CRO", "211 senaryo"],
          links: [
            { label: "Playbook'u incele", href: "/tr/lab/ab-testing" },
            { label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/ab-test-playbook" },
          ],
        },
        {
          name: "Pazarlama Dashboard Üretici",
          slug: "dashboard-builder",
          desc: "Farklı pazarlama platformlarından gelen dağınık exportları alır, gerçekten karşılaştırılabilir olanı kontrol eder ve veriyi karar-hazır bir dashboard'a çevirir.",
          tags: ["Claude Code Eklentisi", "Pazarlama Analitiği", "11 dashboard şablonu", "17 test"],
          links: [
            { label: "Aracı incele", href: "/tr/lab/dashboard-builder" },
            { label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/dashboard-builder" },
          ],
        },
        {
          name: "Google Ads Değişiklik Geçmişi Gezgini",
          slug: "google-ads-change-history-dashboard",
          desc: "Google Ads değişiklik geçmişi export'unu aranabilir bir dashboard'a çevirir - ne değişti, kim değiştirdi, ne zaman ve ne kadar büyük bir değişiklikti.",
          tags: ["Python", "Google Ads", "Çevrimdışı Dashboard", "57 self-test"],
          links: [{ label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/google-ads-change-history-dashboard" }],
        },
        {
          name: "Numerspace",
          slug: "numerspace",
          desc: "Finans, sağlık, kariyer, pazarlama ve günlük hayatı kapsayan 75+ ücretsiz hesaplama aracı - üyelik ya da ücret duvarı olmadan hızlı, doğru sonuç için kuruldu.",
          tags: ["Web Uygulaması", "Hesaplama Araçları", "75+ araç", "EN/TR"],
          links: [{ label: "numerspace.com'u ziyaret et", href: "https://www.numerspace.com" }],
        },
      ],
      shell: {
        backToSite: "Siteye dön",
      },
      page: {
        title: "Canonical Journey Kütüphanesi",
        intro:
          "{categories} kategoriye yayılmış, sektörden bağımsız {count} lifecycle state machine ve bunları bir arada tutan {rules} orkestrasyon kuralı. Amaca, yaşam döngüsü aşamasına veya trigger kanıtına göre filtrele ya da ara. Kütüphane içeriği İngilizce yazıldı; her kayıt bir dizi değil, bir graf.",
        searchPlaceholder: "Journey ara...",
        goalLabel: "Amaç / kullanım senaryosu",
        lifecycleStageLabel: "Yaşam döngüsü aşaması",
        lifecycleStageHint:
          "26 kategoriden yalnızca 4'ü müşteri yaşam döngüsünde belirli bir noktaya bağlı - geri kalanı kişinin nerede olduğundan bağımsız aynı şekilde çalışır, bu yüzden çoğu journey yaşam döngüsünden bağımsız görünür.",
        evidenceLabel: "Trigger kanıtı",
        filtersLabel: "Filtreler",
        showMore: "Daha fazla göster",
        showLess: "Daha az göster",
        clearAll: "Temizle",
        results: "journey",
        empty: "Bu filtrelerle eşleşen kayıt yok.",
        nodesLabel: "düğüm",
        entityLabel: "Varlık",
        competesLabel: "Rekabet",
        distinctLabel: "Şundan farklı",
        preemptedLabel: "Şu olursa biter",
        guardrailsLabel: "Guardrail",
        ruleLabel: "Yeniden kullanılabilir kural",
        flowLabel: "Graf",
        more: "Detay",
        less: "Gizle",
        terminalLabel: "Terminal",
        close: "Kapat",
        backToLibrary: "Tüm journey'ler",
        mergedNote:
          "{from}, {to} içine alındı. Bu ID artık ayrı bir journey değil; kapsadığı her şey burada.",
        evidence: {
          authoritative: "authoritative",
          declared: "declared",
          behavioral: "behavioral",
          inferred: "inferred",
        },
        evidenceHint:
          "Trigger'ın neyi sonuçlandırmasına izin verildiği. Authoritative kanıt bir sonuç kurabilir; declared, behavioral ve inferred kanıt işi önceliklendirebilir veya doğrulama isteyebilir, sonuç kuramaz.",
      },
    },
    about: {
      metaTitle: "Hakkımda - Ali Demirbaş",
      metaDesc: "Dijital Pazarlama · Analitik · Büyüme Stratejisi",
      eyebrow: "Hakkımda",
      title: "Profesyonel Profil",
      sub: "Dijital Pazarlama · Analitik · Büyüme Stratejisi",
      moreLink: "Hakkımda daha fazlası",
      teaserLead:
        "Dijital ürünlerin sürdürülebilir şekilde büyümesine yardımcı olan güvenilir ölçümleme sistemleri kuruyorum. Çalışmalarım; GA4 ve GTM izleme sistemleri kurmayı, Adjust MMP kurulumlarını optimize etmeyi ve kullanıcı içgörülerini ölçülebilir iş büyümesine dönüştüren kanıta dayalı CRO programları tasarlamayı kapsıyor. Pazarlamaya; doğru veriye, yapılandırılmış deneylere ve sürekli optimizasyona dayanan yinelemeli bir süreç olarak yaklaşıyorum.",
      lead:
        "Dijital pazarlama ve büyüme alanında sekiz yılı aşkın deneyimimle, farklı ürünlerin ve iş modellerinin büyüme hedeflerini destekleyecek stratejiler üzerinde çalıştım.",
      body:
        "Deneyimim analitik, kullanıcı kazanımı, ürün ve büyüme stratejisini kapsıyor. Dijital pazarlama performansını değerlendirmek, kullanıcı davranışını anlamak ve büyüme fırsatlarını belirlemek için veriyi kullanıyorum. Kampanya yönetimi, ölçümleme ve optimizasyon boyunca, pazarlama girişimlerini iş hedefleriyle uyumlu tutmaya ve ölçülebilir sonuçlar üretmeye odaklanıyorum.",
      experience: "Deneyim",
      timeline: [
        {
          kind: "single",
          year: "2026",
          co: "Aksigorta",
          logo: "/logos/aksigorta.svg",
          role: "Mobil Uygulama Büyüme Lideri",
          period: "Nis 2026 – Günümüz",
          desc: "Türkiye'nin en büyük sigorta şirketlerinden biri için mobil uygulama büyüme stratejisini yönetiyor, kullanıcı kazanımı ve etkileşimi yürütüyorum.",
        },
        {
          kind: "single",
          year: "2024",
          co: "Vodafone",
          logo: "/logos/vodafone.svg",
          role: "Büyüme Pazarlaması Lideri",
          period: "Ağu 2024 – Nis 2026",
          desc: "Dijital kanallarda büyüme pazarlamasını yönettim; veriye dayalı kullanıcı kazanımını yaşam döngüsü programlarıyla birleştirdim.",
        },
        {
          kind: "single",
          year: "2023",
          co: "Getir",
          logo: "/logos/getir.svg",
          role: "Büyüme – CRM Analitiği Uzmanı",
          period: "Eyl 2023 – Ağu 2024",
          desc: "Hızlı ticaret için CRM analitiği ve büyüme girişimlerini yönettim; elde tutma ve yaşam boyu değeri optimize ettim.",
        },
        {
          kind: "group",
          year: "2021",
          co: "Wingie Enuygun Group",
          logo: "/logos/enuygun.png",
          span: "Tam zamanlı · 2 yıl",
          roles: [
            {
              role: "Kıdemli Yaşam Döngüsü Pazarlama Uzmanı (Büyüme)",
              period: "Oca 2023 – Ağu 2023",
              desc: "Grubun seyahat markaları genelinde yaşam döngüsü ve CRM programlarını uçtan uca yürüttüm.",
            },
            {
              role: "Yaşam Döngüsü Pazarlama Uzmanı (Büyüme)",
              period: "Eyl 2021 – Oca 2023",
              desc: "Önde gelen bir çevrimiçi seyahat platformu için yaşam döngüsü pazarlama programları kurdum ve yürüttüm.",
            },
          ],
        },
        {
          kind: "single",
          year: "2020",
          co: "Albayrak Grubu",
          logo: "/logos/albayrak.svg",
          role: "Dijital Pazarlama Uzmanı",
          period: "Eki 2020 – Ağu 2021",
          desc: "Grup şirketleri genelinde dijital pazarlama kampanyalarını yönettim.",
        },
        {
          kind: "single",
          year: "2019",
          co: "Doğuş Oto",
          logo: "/logos/dogus-oto.svg",
          role: "Jr. Dijital Pazarlama Uzmanı",
          period: "Eyl 2019 – Ağu 2020",
          desc: "Türkiye'nin önde gelen otomotiv bayi gruplarından biri için dijital pazarlama uygulamaları yürüttüm.",
        },
      ],
    },
    stack: {
      metaTitle: "Yığın - Ali Demirbaş",
      metaDesc: "Her gün büyümeyi ölçmek, sorgulamak ve optimize etmek için kullandığım araçlar.",
      eyebrow: "Yığın",
      title: "Yığın",
      sub: "Tasarlamak, üretmek, ölçmek ve büyümek için kullandığım araçlar.",
      homeTitle: "Kullandığım araçlar",
      homeIntro: "Deney tasarlamak, güvenilir ölçümleme kurmak, kullanıcı davranışını analiz etmek ve büyümeyi optimize etmek için kullandığım araçlar.",
      homeMore: "Araç setimi keşfet",
    },
    contact: {
      metaTitle: "İletişim - Ali Demirbaş",
      metaDesc: "Ali Demirbaş'a e-posta ile veya LinkedIn üzerinden ulaşın.",
      eyebrow: "İletişim",
      title: "Hadi güzel bir şey için iş birliği yapalım.",
      sub: "İlginç projelerde harika insanlarla iş birliği yapmaya her zaman açığım. Destek eli mi lazım? İki tane var bende!",
      linkedinLabel: "LinkedIn'de bağlantı kur",
      linkedinGo: "Profili görüntüle",
      emailLabel: "E-posta gönder",
      emailGo: "Bana e-posta at",
      emailPill: "E-posta",
      reasonsTitle: "Ne için yazıyor olabilirsin",
      reasons: [
        { title: "Bir rol veya fırsat", desc: "Growth/CRM liderliği rollerine açığım - tam zamanlı veya fraksiyonel." },
        { title: "Bir proje veya iş birliği", desc: "Lifecycle pazarlama, ölçümleme kurulumu veya açık kaynak Lab araçlarından biri." },
        { title: "Bir soru", desc: "Bir hesaplayıcı, bir journey deseni veya bu sitedeki başka bir şey hakkında." },
      ],
      scheduleTitle: "Görüşme planla",
      scheduleSub: "30 dakikalık bir tanışma görüşmesi ayarlayın.",
      formTitle: "Mesaj gönder",
      formName: "İsim",
      formEmail: "E-posta",
      formCompany: "Şirket web sitesi (opsiyonel)",
      formSubject: "Konu",
      formMessage: "Mesajınız",
      formSubmit: "E-postada aç",
      formNote: "E-posta uygulamanızda hazır doldurulmuş bir taslak açar - bu sitede bunu sizin yerinize gönderecek bir sunucu yok.",
    },
    /* Bkz. EN tarafındaki not. */
    journeyBuilder: {
      metaTitle: "Lifecycle Marketing Journey Builder - Ali Demirbaş",
      metaDesc: "Lifecycle journey'lerin durum makinesi olarak kanonik kütüphanesi: tetikleyiciler, dallanmalar, beklemeler, devirler ve çıkışlar - kampanya şablonu değil.",
      eyebrow: "Lab / Journey Builder",
      title: "Kampanya şablonu değil, durum makinesi olarak lifecycle journey'ler.",
      sub: "Buradaki her journey bir graf: onu ne başlatır ve bilinçli olarak ne başlatmaz, nerede çatallanır ve her kolun anlamı nedir, ne kadar bekler ve o süre dolduğunda ne olur, kişinin sahipliği sonra hangi lifecycle'a geçer.",
      ctaLibrary: "Kütüphaneyi keşfet",
      ctaJourney: "Bu journey'i aç",
      proof: ["Açık kaynak", "Claude Code eklentisi", "Kayıt gerekmiyor"],
      canvas: {
        nodes: "düğüm",
        rejoins: "Reconcile'da birleşir",
      },
      scale: {
        journeys: "kanonik journey",
        categories: "kategori",
        nodes: "düğüm",
        kinds: "düğüm tipi",
      },
      story1: {
        eyebrow: "Tetikleyiciler",
        title: "Kanıtla başlar, yoksa başlamaz.",
        body: "Kötü lifecycle otomasyonunun çoğu, tek bir zayıf sinyalle ateşlenmiş bir journey'dir. Buradaki her tetikleyici neye ihtiyaç duyduğunu adlandırır — ve ayrıca, tek başına yeterli olmayan benzer sinyalleri.",
        caption: "Tetikleyici kanıtı",
        requires: "Gerekenler",
        insufficient: "Tek başına yetersiz",
      },
      story2: {
        eyebrow: "Dallanma",
        title: "Her çatalın iki kolu da adlandırılmış.",
        body: "Tek kollu bir koşul, karar kılığına girmiş bir filtredir — o koşulu geçemeyen herkese ne olduğunu gizler. Bu yüzden buradaki her koşul en az iki dal taşır, her biri kendisine yönlendiren gerçek kuralla birlikte.",
        caption: "Gerçek bir çatal",
        conditionsLabel: "koşul kütüphanede",
        note: "Hiçbir kol çıkmaz sokak değil: ikisi de adlandırılmış bir düğüme gider.",
      },
      story3: {
        eyebrow: "Zaman",
        title: "Beklemek, son tarihi olan bir karardır.",
        body: "Zaman aşımı olmayan bir bekleme, insanları hiç gelmeyebilecek bir olayda mahsur bırakır. Gidecek yeri olmayan bir zaman aşımı ise sabır taklidi yapan bir çıkıştır. Buradaki her bekleme iki kolunu da adlandırır ve etkileşimin süreyi uzatıp uzatmadığını söyler.",
        caption: "Bir bekleme, iki kol",
        waitsLabel: "bekleme kütüphanede",
        opens: "Bekleme başlar",
        onEvent: "Olay gerçekleşirse",
        onTimeout: "Süre dolarsa",
        note: "Her etkileşimin uzattığı sınırlı bir pencere, sınırlı değildir.",
      },
      anatomy: {
        eyebrow: "Anatomi",
        title: "Tek bir journey, her parçası etiketli.",
        body: "Bu, değiştirilmemiş gerçek bir kanonik journey. Bir kez okuyunca hepsinin arkasındaki model netleşiyor: bir tetikleyici, adlandırılmış kollu çatallar, sınırlı bir bekleme, üzerine yazmak yerine ekleyen bir aksiyon, bir devir ve yeni bir örneğin ne zaman başlayabileceğini söyleyen çıkışlar.",
        legendTitle: "Kütüphane genelinde düğüm tipleri",
      },
      inspector: {
        eyebrow: "Yakınlaş",
        title: "Devir sadece bir ok değildir.",
        body: "Sahiplik başka bir lifecycle'a geçtiğinde, bir şeyin bu sınırdan sağ çıkması gerekir. Bir devir; hedefini, hangi koşulda ateşlendiğini ve tam olarak neyi taşıdığını adlandırır — böylece devralan journey boş değil, bilgili başlar.",
        to: "hedef",
        on: "koşul",
        carries: "taşıdığı",
        handoffsLabel: "devir kütüphanede",
      },
      library: {
        eyebrow: "Kütüphane",
        title: "{count} journey. Okunmak için kurulmuş.",
        body: "Kategoriye göre dosyalanmış, her biri açıp düğüm düğüm takip edebileceğin bir graf. Sektör şablonu değil, alandan bağımsız durum makineleri — bu ayrım, iki journey'in aynı journey olmasını engelleyen şey.",
        cta: "Journey kütüphanesini keşfet",
        nodes: "düğüm",
        moreCategories: "kategori daha",
      },
      how: {
        eyebrow: "Nasıl çalışır",
        title: "Bul, oku, uyarla.",
        body: "Ürün kütüphanenin kendisi. Onunla yaptığın üç şey bunlar.",
        steps: [
          { title: "Journey'i bul", body: "Kategoriye, lifecycle aşamasına, hedefe veya tetikleyicinin dayandığı kanıt türüne göre filtrele." },
          { title: "Mantığı oku", body: "Grafı düğüm düğüm takip et — her dal, bekleme ve devir, arkasındaki kuralla birlikte yazılmış." },
          { title: "Uyarla", body: "Durum makinesini kendi sistemine taşı. Teslim edilen şey mantık; mesaj metni hiçbir zaman kapsamda değildi." },
        ],
      },
      related: {
        title: "İlgili",
        abTest: "A/B Test Playbook",
        abTestDesc: "Aynı pratiğin deney tarafı.",
      },
    },
    abTesting: {
      metaTitle: "A/B Test Playbook - Ali Demirbaş",
      metaDesc: "Claude Code için 211 gerçek büyüme testi senaryosu: ne test edilir, hangi KPI izlenir, ne yapılmamalı.",
      eyebrow: "Lab / A/B Test",
      title: "Guardrail'i atlamana izin vermeyen bir A/B test motoru.",
      sub: "ab-test-playbook, 211 gerçek e-ticaret, mobil uygulama ve SaaS büyüme testi senaryosundan kurulu, açık kaynak bir Claude Code eklentisi. Kullanıcının journey'deki yerine göre kanıtlanmış bir test seçmene yardım eder, yenilerini tek değişken disipliniyle tasarlar ve göz kararı yerine gerçek istatistiği çalıştırır.",
      install: {
        title: "Kurulum",
        options: [
          {
            label: "Plugin marketplace",
            code: "/plugin marketplace add ali-demirbas/ab-test-playbook\n/plugin install ab-test-playbook@ab-test-playbook",
          },
          {
            label: "Yerel klon",
            code: "git clone https://github.com/ali-demirbas/ab-test-playbook.git\nclaude --plugin-dir ./ab-test-playbook",
          },
          {
            label: "skills.sh",
            code: "npx skills add ali-demirbas/ab-test-playbook --all",
          },
        ],
      },
      framework: {
        title: "Her senaryo aynı üç kutu disiplinini izler",
        boxes: [
          { title: "Test edilmesi gerekenler", desc: "Deneyin cevaplaması gereken somut sorular - \"butonu test et\" değil, sonucun çözmesi gereken her hipotez." },
          { title: "Takip edilecek KPI'lar", desc: "Kazananı belirleyen tek bir birincil metrik, artı iyileşirken bozulmaması gereken en az bir guardrail." },
          { title: "Yapılmaması gerekenler", desc: "Testi sessizce geçersiz kılan hatalar - sonuçlar okunamaz hâle gelene kadar kimsenin fark etmediği türden." },
        ],
      },
      principlesTitle: "Eklentinin eğmediği beş kural",
      principles: [
        { title: "Her zaman tek değişken", desc: "Her varyant çifti tam olarak bir şeyi değiştirir. Çok değişkenli bir test istenirse ayrı testlere bölünür - ısrar edilirse çıktı açıkça 'sonuç hangi değişiklikten geldi bilinemeyecek' der." },
        { title: "Tek birincil metrik", desc: "Listedeki ilk KPI kazananı belirler. Beş metriği eşit önemde sunmak, tam olarak kaybeden bir testin kazanan ilan edilme yoludur." },
        { title: "Guardrail'siz senaryo yok", desc: "Her senaryo, bozulmaması gereken en az bir metrikle gelir - marj, iade oranı, hız, destek talebi. Bir değişiklik erişilebilirliği etkileyebilecekse, o da bir guardrail adayıdır." },
        { title: "Koruma bir büyüme kolu değildir", desc: "CAPTCHA, kimlik veya yaş doğrulama, iki adımlı giriş, yasal onay adımları - istense bile hiçbir zaman kaldırılacak sürtünme olarak önerilmez. Bunlar koruma içindir, dönüşüm için değil; eklenti bunu söyler ve senaryo üretmez." },
        { title: "Güven söylenir, ima edilmez", desc: "Her öneri, arkasındaki kanıtın ne kadar güçlü olduğunu söyler - kullanıcının kendi verisi, arşiv emsali, sektör örüntüsü ya da sezgi. Zayıf kanıtlı bir fikir yine sunulabilir ama asla kesinmiş gibi giydirilmez." },
      ],
      exampleTitle: "Arşivden gerçek bir senaryo",
      example: {
        idx: "ECOM-CART",
        title: "Açık kupon kodu alanı sepet terkini artırır mı?",
        intro: "Görünür bir kupon kutusu, kodu olmayan kullanıcıyı 'indirim arayayım' diye siteden çıkarabilir. Kodu bağlantı arkasına almak bu kaçağı kapatabilir ama kampanya kullanımını düşürebilir.",
        testBox: {
          label: "Test edilmesi gerekenler",
          items: [
            "Kaçak: Kupon alanını bağlantı arkasına almak terk oranını düşürüyor mu?",
            "Segment: Yeni ve dönen kullanıcıda kupon arama davranışı farklı mı?",
            "Metin: 'İndirim kodum var' ile 'Kupon kullan' farklı sonuç veriyor mu?",
            "Kampanya: Kampanya dönemlerinde etki tersine dönüyor mu?",
            "Hata: Kod girip başarısız olan kullanıcının terk oranı ne kadar?",
          ],
        },
        kpiBox: {
          label: "Takip edilecek KPI'lar",
          items: [
            "Ziyaretçi Başına Gelir (RPV) - birincil metrik",
            "Sipariş Tamamlama Oranı",
            "Kupon Kullanım Oranı (guardrail)",
            "Ödeme Adımı Terk Oranı",
            "Kampanya Katılımı (guardrail)",
          ],
        },
        dontBox: {
          label: "Yapılmaması gerekenler",
          items: [
            "Kupon alanını tamamen kaldırmayın; kodu olan kullanıcı öfkelenir.",
            "Geçersiz kod hatasını belirsiz bırakmayın.",
            "Test sırasında aktif kampanya kurmayın veya kaldırmayın.",
            "Kupon alanını fark edilmez hâle getirecek kadar gizlemeyin.",
            "Aynı testte hem konumu hem metni değiştirmeyin.",
          ],
        },
      },
      faqTitle: "SSS",
      faqIntro: "Cevaplar eklentinin kendi metodoloji dokümanlarından, dış kaynaklardan değil.",
      faq: [
        {
          q: "İlk olarak neyi A/B test etmeliyim?",
          a: "Adayları içgüdüyle değil ICE (Etki × Güven × Kolaylık) ile sıralayın. Yüksek trafikli bir sayfada düşük efor gerektiren bir test, düşük trafikli bir sayfadaki iddialı bir testten daha iyidir.",
        },
        {
          q: "Bir A/B test için kaç ziyaretçiye ihtiyacım var?",
          a: "Bu bir kestirme kural değil - gerçek baz dönüşüm oranınızdan ve önemsediğiniz minimum etki büyüklüğünden hesaplanır. Gerçek trafik verisi olmadan hiçbir süre veya örneklem vaadi verilmez.",
        },
        {
          q: "Sonuçlara erken bakıp anlamlı göründüğünde durabilir miyim?",
          a: "Hayır - bir testi tekrar tekrar kontrol edip anlamlı göründüğü an durmak, gerçek bir fark olmasa bile yanlış-pozitif oranını %5'in çok üzerine çıkarır. Örneklem büyüklüğünü veya süreyi baştan belirleyin, bir kez bakın. Tek istisna: bir guardrail metriğinin test ortasında gözle görülür şekilde bozulması.",
        },
        {
          q: "Neden en az iki tam hafta test çalıştırmalıyım?",
          a: "İstatistiksel güç gereksinimi değil - kapsama gereksinimi. Hafta içi/hafta sonu davranışı ve maaş günü etkilerinin veride temsil edilmesi gerekir, örneklem hedefine üç günde ulaşılsa bile.",
        },
        {
          q: "Bir sonucu geçersiz kılan yaygın A/B test hataları nelerdir?",
          a: "Aynı testte birden fazla değişkeni değiştirmek; ilk günlerin verisinden kazanan ilan etmek; bir fiyat testinde yalnızca dönüşüm oranına bakmak (CR artarken ziyaretçi başına gelir düşebilir); gerçek sayfa test edilirken 'Variant A'yı yeniden tasarlamak; aynı sayfaya çakışan trafikte iki test çalıştırmak.",
        },
        {
          q: "Bu playbook her ürün için doğru araç mı?",
          a: "Hayır, ve bunu açıkça söylüyor. B2C e-ticaret, tüketici mobil uygulamaları ve gerçek haftalık trafiği olan self-serve SaaS için uyar. Düşük trafikli kurumsal satış sayfaları, uzun satış döngüleri veya ağır regüle akışlar için daha az uyar - onlar için niteliksel yöntemlere işaret eder.",
        },
      ],
      repoLink: "GitHub'da görüntüle",
      demoLink: "Canlı demo",
      /* Bkz. EN tarafındaki not: yukarıdaki anahtarlar değişmedi, aşağıdaki
         blok bu turun yeni ürün sayfası kurgusu için yazıldı. İçindeki her
         sayı gerçek veri setinden derleme anında türetiliyor. */
      product: {
        heroCtaLibrary: "Kütüphaneyi keşfet",
        heroProof: ["Açık kaynak", "Claude Code eklentisi", "Kayıt gerekmiyor"],
        brief: {
          label: "Senaryo brifi",
          control: "Kontrol",
          variant: "Varyant",
          testedSlot: "Test edilen öğe",
          testedSlotValue: "Kupon kodu alanı",
          sideA: "Kupon kodu alanı sepette açık, doğrudan görünür bir kutu",
          sideB: "Kupon alanı “İndirim kodum var” bağlantısı arkasında gizli",
          primaryKpi: "Birincil KPI",
          primaryKpiValue: "Ziyaretçi Başına Gelir (RPV)",
          guardrail: "Guardrail",
          guardrailValue: "Kupon Kullanım Oranı çökmemeli",
        },
        scale: {
          scenarios: "senaryo",
          surfaces: "ürün yüzeyi",
          categories: "kategori",
          guardrails: "guardrail kuralı",
        },
        story1: {
          eyebrow: "Kapsam",
          title: "Gerçekten üzerinde olduğun yüzeyden başla.",
          body: "Kütüphane düz bir ipucu listesi değil. Her senaryo ait olduğu ürün yüzeyine göre dosyalanmış — bir ürün sayfası testiyle bir ödeme testi farklı biçimlerde bozulur — böylece neyin değişeceği tartışılmadan önce sorunun nerede olduğuna göre daraltıyorsun.",
          caption: "Yüzeye göre senaryolar",
        },
        story2: {
          eyebrow: "Disiplin",
          title: "Tek değişken, yoksa o bir test değil.",
          body: "Her senaryo değişen tek alanı adlandırır ve sayfanın geri kalanını aynı tutar. Kütüphanenin büyük bölümü kontrol ve varyant yazılmış hâlde gelir; böylece sessizce iki şeyi değiştirip sonuca “bulgu” demenin yeri kalmaz.",
          caption: "Kontrol / varyant",
          diffNote: "Sayfadaki diğer her şey aynı kalır.",
          sidesNote: "senaryo iki tarafı yazılmış hâlde geliyor",
        },
        story3: {
          eyebrow: "Guardrail'ler",
          title: "Her senaryo, bozulmaması gerekenle birlikte gelir.",
          body: "Guardrail, birincil metrik iyileşirken yerinde kalması gereken metriktir — marj, iade oranı, kupon kullanımı, erişilebilirlik. Burada opsiyonel değiller: kütüphanedeki hiçbir senaryo beşten azıyla gelmiyor.",
          caption: "Yapılmaması gerekenler",
          ledgerNote: "kütüphane genelinde guardrail kuralı",
        },
        library: {
          eyebrow: "Kütüphane",
          title: "{count} deney. Bir sonrakini bulacağın tek yer.",
          body: "Kategoriye ve yüzeye göre dosyalanmış, aranabilir ve hiçbir şey kurmadan okunabilir. Her kayıt test edilen değişkeni, birincil KPI'ı ve guardrail'leri taşır.",
          cta: "Testlerin tamamını keşfet",
          filterLabel: "Kategoriye göre gez",
        },
        how: {
          eyebrow: "Nasıl çalışır",
          title: "Bul, kur, oku.",
          body: "Üç adım — ve çoğu testin yanlış yaptığı adım üçüncüsü.",
          steps: [
            { title: "Fırsatı bul", body: "Üzerinde çalıştığın yüzeye göre daralt, sonra o yüzeye dosyalanmış senaryolardan seç." },
            { title: "Deneyi tasarla", body: "Senaryo sana hipotezi, tek bir birincil KPI'ı ve guardrail'leri verir. Tam olarak tek değişken hareket eder." },
            { title: "Sonucu oku", body: "Grafikle değil istatistikle karar ver. Çift haneli bir artış hâlâ gürültü olabilir." },
          ],
          step1: { label: "Yüzey", matches: "senaryo bu yüzeyde" },
          step2: { hypothesis: "Hipotez", kpi: "Birincil KPI", guardrail: "Guardrail" },
          step3: {
            control: "Kontrol",
            variant: "Varyant",
            uplift: "Göreli artış",
            pValue: "p-değeri",
            verdict: "%95'te anlamlı mı?",
            verdictValue: "Hayır — devam et",
            note: "Bu sitenin kendi Anlamlılık hesaplayıcısından işlenmiş bir örnek: eşiği geçemeyen %16'lık bir artış.",
            calculators: "Kendi sayılarınla çalıştır",
            test: "iki oranlı z-testi",
          },
        },
        rulesEyebrow: "Kurallar",
        installEyebrow: "Kurulum",
        faqEyebrow: "Sorular",
      },
    },
    finalCta: {
      title: "Büyümeyi konuşalım.",
      body: "Bir rol, bir proje ya da lifecycle marketing üzerine bir soru - kutum açık.",
      button: "mehmetalidemirbas@gmail.com",
      linkedin: "LinkedIn'de bağlan",
    },
    notFound: {
      metaTitle: "Sayfa bulunamadı - Ali Demirbaş",
      eyebrow: "404",
      title: "Bu sayfa bulunamadı.",
      body: "Bağlantı eski olabilir veya sayfa taşınmış olabilir.",
      cta: "Ana sayfaya dön",
      labLink: "Lab'i keşfet",
    },
    footer: {
      left: "Ali Demirbaş, 2026",
      right: "İstanbul",
      quickLinks: "Hızlı bağlantılar",
      projects: "Lab projeleri",
      connect: "Bağlan",
      home: "Ana sayfa",
    },
  },
} as const;

export const LINKEDIN = "https://www.linkedin.com/in/ali-demirbas/";
export const EMAIL = "mehmetalidemirbas@gmail.com";
