export type Lang = "en" | "tr";

export const copy = {
  en: {
    nav: { about: "About", aboutHref: "/about", lab: "Lab", labHref: "/lab", stack: "Stack", stackHref: "/stack", contact: "Contact", contactHref: "/contact", cta: "Get in touch", lang: "TR", langHref: "/tr" },
    hero: {
      line1: "Growth you can measure.",
      line2: "Products that keep users.",
      lead: "I'm Ali Demirbaş, a growth marketer for mobile products. I build acquisition, CRM and lifecycle programs on data - not guesswork.",
      sub: "Currently leading mobile app growth at Aksigorta in Istanbul, after growth roles at Vodafone, Getir and Wingie Enuygun Group.",
      ctaPrimary: "Get in touch",
      ctaSecondary: "LinkedIn",
      reassurance: ["Mobile App Growth Lead, Aksigorta", "7+ years in growth", "Istanbul"],
    },
    lab: {
      label: "Lab",
      title: "Things I've been building",
      intro: "A collection of open-source tools, experiments and side projects. Mostly marketing and growth, sometimes not.",
      viewAll: "Explore the archive",
      projects: [
        {
          name: "Lifecycle Marketing Journey Builder",
          slug: "claude-lifecycle",
          desc: "Looks at the customer data you already track and builds lifecycle journeys around what you can actually measure, segment and act on.",
          tags: ["Claude Code Plugin", "CRM", "Lifecycle Marketing", "26 journey patterns", "9 industries"],
          links: [
            { label: "View on GitHub", href: "https://github.com/ali-demirbas/claude-lifecycle" },
            { label: "Try the demo", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
          ],
        },
        {
          name: "CRM Journey Teardown Archive",
          slug: "lifecycle-card-archive",
          desc: "A collection of 70 lifecycle journeys, each broken down into how the flow works, what to test, which metrics to watch and what to avoid.",
          tags: ["CRM", "Lifecycle Marketing", "70 teardowns", "10 industries", "TR/EN"],
          links: [{ label: "Explore the archive", href: "/lab/journeys" }],
        },
        {
          name: "A/B Test Playbook",
          slug: "ab-test-playbook",
          desc: "211 A/B test scenarios across real product journeys, with guidance on what to test, what to measure and what can invalidate the result.",
          tags: ["Claude Code Plugin", "A/B Testing", "CRO", "211 scenarios"],
          links: [
            { label: "Explore the playbook", href: "/lab/ab-testing" },
            { label: "View on GitHub", href: "https://github.com/ali-demirbas/ab-test-playbook" },
          ],
        },
        {
          name: "Marketing Dashboard Builder",
          slug: "dashboard-builder",
          desc: "Takes messy exports from different marketing platforms, checks what can actually be compared, and turns the data into a decision-ready dashboard.",
          tags: ["Claude Code Plugin", "Marketing Analytics", "11 dashboard templates", "17 tests"],
          links: [{ label: "View on GitHub", href: "https://github.com/ali-demirbas/dashboard-builder" }],
        },
        {
          name: "Google Ads Change History Explorer",
          slug: "google-ads-change-history-dashboard",
          desc: "Turns a Google Ads change-history export into a searchable dashboard - what changed, who changed it, when, and how significant it was.",
          tags: ["Python", "Google Ads", "Offline Dashboard", "57 self-tests"],
          links: [{ label: "View on GitHub", href: "https://github.com/ali-demirbas/google-ads-change-history-dashboard" }],
        },
        {
          name: "Numerspace",
          slug: "numerspace",
          desc: "75+ free calculator tools spanning finance, health, career, marketing and daily life - built for a fast, accurate answer, no account or paywall.",
          tags: ["Web App", "Calculator Tools", "75+ tools", "EN/TR"],
          links: [{ label: "Visit numerspace.com", href: "https://www.numerspace.com" }],
        },
      ],
      shell: {
        backToSite: "Back to site",
      },
      page: {
        title: "CRM Journey Archive",
        intro: "70 lifecycle journey teardowns across sectors and channels. Filter by sector or channel, or search - each entry is a flow I have researched and documented.",
        searchPlaceholder: "Search journeys...",
        sectorLabel: "Sector",
        channelsLabel: "Channels",
        allSectors: "All sectors",
        allChannels: "All channels",
        results: "journeys",
        empty: "Nothing matches those filters.",
        back: "Back to home",
      },
    },
    about: {
      metaTitle: "About - Ali Demirbaş",
      metaDesc: "Digital Marketing · Analytics · Growth Strategy",
      eyebrow: "About",
      title: "Professional Profile",
      sub: "Digital Marketing · Analytics · Growth Strategy",
      moreLink: "More about me",
      // Home page teaser only - kept separate from `lead` below (the
      // /about page's own opening line) so editing one doesn't change
      // the other; the two pages make different first impressions on
      // purpose.
      teaserLead:
        "I build reliable measurement frameworks that help digital products grow sustainably. My work includes implementing GA4 and GTM tracking systems, optimizing Adjust MMP setups, and designing evidence-based CRO programs that turn user insights into measurable business growth. I approach marketing as an iterative process built on accurate data, structured experimentation, and continuous optimization.",
      lead:
        "With over eight years of experience in digital marketing and growth, I have worked on strategies designed to support the growth objectives of different products and business models.",
      body:
        "My experience spans analytics, user acquisition, product, and growth strategy. I use data to evaluate digital marketing performance, understand user behavior, and identify opportunities for growth. Across campaign management, measurement, and optimization, I focus on keeping marketing initiatives aligned with business goals and delivering measurable outcomes.",
      experience: "Experience",
      timeline: [
        {
          kind: "single",
          year: "2026",
          co: "Aksigorta",
          logo: "/logos/aksigorta.svg",
          role: "Mobile App Growth Lead",
          period: "Apr 2026 – Present",
          desc: "Leading mobile app growth strategy, driving user acquisition and engagement for one of Turkey's largest insurers.",
        },
        {
          kind: "single",
          year: "2024",
          co: "Vodafone",
          logo: "/logos/vodafone.svg",
          role: "Growth Marketing Lead",
          period: "Aug 2024 – Apr 2026",
          desc: "Led growth marketing across digital channels, combining data-driven acquisition with lifecycle programs.",
        },
        {
          kind: "single",
          year: "2023",
          co: "Getir",
          logo: "/logos/getir.svg",
          role: "Growth – CRM Analytics Executive",
          period: "Sep 2023 – Aug 2024",
          desc: "Managed CRM analytics and growth initiatives for rapid commerce, optimizing retention and LTV.",
        },
        {
          kind: "group",
          year: "2021",
          co: "Wingie Enuygun Group",
          logo: "/logos/enuygun.png",
          span: "Full-time · 2 yrs",
          roles: [
            {
              role: "Experienced Lifecycle Marketing Specialist (Growth)",
              period: "Jan 2023 – Aug 2023",
              desc: "Owned lifecycle and CRM programs end-to-end across the group's travel brands.",
            },
            {
              role: "Lifecycle Marketing Specialist (Growth)",
              period: "Sep 2021 – Jan 2023",
              desc: "Built and ran lifecycle marketing programs for a leading online travel platform.",
            },
          ],
        },
        {
          kind: "single",
          year: "2020",
          co: "Albayrak Grubu",
          logo: "/logos/albayrak.svg",
          role: "Digital Marketing Specialist",
          period: "Oct 2020 – Aug 2021",
          desc: "Managed digital marketing campaigns across group companies.",
        },
        {
          kind: "single",
          year: "2019",
          co: "Doğuş Oto",
          logo: "/logos/dogus-oto.svg",
          role: "Jr. Digital Marketing Specialist",
          period: "Sep 2019 – Aug 2020",
          desc: "Digital marketing execution for one of Turkey's leading automotive dealer groups.",
        },
      ],
    },
    stack: {
      metaTitle: "Stack - Ali Demirbaş",
      metaDesc: "The tools Ali Demirbaş instruments, queries and optimizes growth with every day.",
      eyebrow: "Stack",
      title: "Stack",
      sub: "Tools I use to design, build, measure and grow.",
      // Home page teaser only - the /stack page keeps its own title/sub above.
      homeTitle: "Tools I use",
      homeIntro: "The tools I use to design experiments, build reliable measurement, analyze user behavior, and optimize growth.",
      homeMore: "Explore my toolkit",
    },
    contact: {
      metaTitle: "Contact - Ali Demirbaş",
      metaDesc: "Reach Ali Demirbaş by email or connect on LinkedIn.",
      eyebrow: "Contact",
      title: "Let's collaborate on something great.",
      sub: "I'm always looking to collaborate on interesting projects with great people. Need a supportive hand? I have two!",
      linkedinLabel: "Connect on LinkedIn",
      linkedinGo: "View profile",
      emailLabel: "Send an email",
      emailGo: "Email me",
      emailPill: "E-Mail",
      scheduleTitle: "Schedule a call",
      scheduleSub: "Book a 30 minute intro call.",
      formTitle: "Send a message",
      formName: "Name",
      formEmail: "Email",
      formCompany: "Company website",
      formMessage: "Your message",
      formSubmit: "Open in email",
      formNote: "Opens a pre-filled draft in your email app - this site has no backend to send it for you.",
    },
    abTesting: {
      metaTitle: "A/B Test Playbook - Ali Demirbaş",
      metaDesc: "211 real growth-test scenarios for Claude Code: what to test, which KPI to track, what not to do.",
      eyebrow: "Lab / A/B Testing",
      title: "An A/B test engine that won't let you skip the guardrail.",
      sub: "ab-test-playbook is an open-source Claude Code plugin built from 211 real e-commerce, mobile app and SaaS growth-test scenarios. It helps you pick a proven test for where a user is in their journey, keeps new ones disciplined to one variable at a time, and runs the real statistics instead of eyeballing significance.",
      install: {
        title: "Install",
        options: [
          {
            label: "Plugin marketplace",
            code: "/plugin marketplace add ali-demirbas/ab-test-playbook\n/plugin install ab-test-playbook@ab-test-playbook",
          },
          {
            label: "Local clone",
            code: "git clone https://github.com/ali-demirbas/ab-test-playbook.git\nclaude --plugin-dir ./ab-test-playbook",
          },
          {
            label: "skills.sh",
            code: "npx skills add ali-demirbas/ab-test-playbook --all",
          },
        ],
      },
      framework: {
        title: "Every scenario follows the same three-box discipline",
        boxes: [
          { title: "What to test", desc: "The specific questions the experiment has to answer - not \"test the button\", but every hypothesis the result needs to settle." },
          { title: "KPIs to track", desc: "One primary metric that decides the winner, plus at least one guardrail that must not get worse while it improves." },
          { title: "What not to do", desc: "The mistakes that quietly invalidate the test - the ones a rushed setup makes without anyone noticing until the results are unreadable." },
        ],
      },
      principlesTitle: "Five rules the plugin won't bend on",
      principles: [
        { title: "One variable, always", desc: "Every variant pair changes exactly one thing. Ask for a multivariate test and it gets split into separate ones - insist, and the output says plainly that no one will know which change produced the result." },
        { title: "One primary metric", desc: "The first KPI in the list decides the winner. Presenting five metrics as equally important is exactly how a losing test gets called a win." },
        { title: "No guardrail, no scenario", desc: "Every scenario ships with at least one metric that must not degrade - margin, refund rate, speed, support tickets. If a change could affect accessibility, that's a guardrail candidate too." },
        { title: "Protection isn't a growth lever", desc: "CAPTCHA, identity or age verification, two-factor login, legal consent steps - never proposed as friction to remove, even if asked. Those exist for protection, not conversion; the plugin says so and generates nothing." },
        { title: "Confidence is stated, not implied", desc: "Every suggestion says how strong the evidence behind it is - the user's own data, an archive precedent, an industry pattern, or a hunch. A weak-evidence idea can still be offered, but never dressed up as certain." },
      ],
      exampleTitle: "One real scenario from the archive",
      example: {
        idx: "ECOM-CART",
        title: "Does a visible coupon-code field increase cart abandonment?",
        intro: "A visible coupon box can send a user with no code off-site to \"go find a discount.\" Moving the code behind a link can close that leak - but it can also reduce campaign usage.",
        testBox: {
          label: "What to test",
          items: [
            "Leak: does moving the coupon field behind a link reduce abandonment?",
            "Segment: do new and returning users search for coupons differently?",
            "Copy: does \"I have a discount code\" perform differently from \"Apply coupon\"?",
            "Campaign: does the effect reverse during active campaign periods?",
            "Error: what's the abandonment rate for users whose code fails?",
          ],
        },
        kpiBox: {
          label: "KPIs to track",
          items: [
            "Revenue Per Visitor (RPV) - the primary metric",
            "Order Completion Rate",
            "Coupon Usage Rate (guardrail)",
            "Checkout Step Abandonment",
            "Campaign Participation (guardrail)",
          ],
        },
        dontBox: {
          label: "What not to do",
          items: [
            "Don't remove the coupon field entirely - users with a code will be frustrated.",
            "Don't leave an invalid-code error ambiguous.",
            "Don't launch or end an active campaign during the test.",
            "Don't hide the coupon field so far it becomes unfindable.",
            "Don't change both the position and the copy in the same test.",
          ],
        },
      },
      faqTitle: "FAQ",
      faqIntro: "Answers drawn from the plugin's own methodology docs, not external citations.",
      faq: [
        {
          q: "What should I A/B test first?",
          a: "Rank candidates with ICE (Impact x Confidence x Ease), not gut feeling. A low-effort test on a high-traffic page beats an ambitious test on a low-traffic one.",
        },
        {
          q: "How many visitors do I need for an A/B test?",
          a: "Not a rule-of-thumb number - it's computed from your actual baseline conversion rate and the minimum effect size you care about detecting. Without real traffic data, no duration or sample-size promise is made.",
        },
        {
          q: "Can I peek at results early and stop when they look significant?",
          a: "No - repeatedly checking a test and stopping the moment it looks significant inflates the false-positive rate well above 5%, even with no real difference. Decide sample size or duration up front, look once. The one exception: a guardrail metric visibly breaking mid-test.",
        },
        {
          q: "Why run a test for at least two full weeks?",
          a: "Not a statistical-power requirement - a coverage requirement. Weekday/weekend behavior and payday effects need to be represented in the data, even if the sample-size target is hit in three days.",
        },
        {
          q: "What are common A/B testing mistakes that invalidate a result?",
          a: "Changing more than one variable at once; declaring a winner from the first days of data; reading conversion rate alone on a price test (revenue per visitor can drop even as CR rises); redesigning \"Variant A\" instead of testing the real page as-is; running overlapping tests on the same page.",
        },
        {
          q: "Is this playbook the right tool for every product?",
          a: "No, and it says so. It fits B2C e-commerce, consumer mobile apps and self-serve SaaS with real weekly traffic. It fits poorly for low-traffic enterprise sales pages, long sales cycles, or heavily regulated flows - for those, it points to qualitative methods instead of forcing a split test where it doesn't belong.",
        },
      ],
      repoLink: "View on GitHub",
      demoLink: "Live demo",
    },
    finalCta: {
      title: "Let's talk growth.",
      body: "Whether it's a role, a project or a question about lifecycle marketing - my inbox is open.",
      button: "mehmetalidemirbas@gmail.com",
      linkedin: "Connect on LinkedIn",
    },
    footer: {
      left: "Ali Demirbaş, 2026",
      right: "Istanbul",
      quickLinks: "Quick links",
      projects: "Lab projects",
      connect: "Connect",
      home: "Home",
    },
  },
  tr: {
    nav: { about: "Hakkımda", aboutHref: "/tr/about", lab: "Lab", labHref: "/tr/lab", stack: "Yığın", stackHref: "/tr/stack", contact: "İletişim", contactHref: "/tr/contact", cta: "İletişime geç", lang: "EN", langHref: "/" },
    hero: {
      line1: "Ölçülebilir büyüme.",
      line2: "Kullanıcıyı tutan ürünler.",
      lead: "Ben Ali Demirbaş, mobil ürünler için growth marketer. Edinim, CRM ve lifecycle programlarını tahminle değil veriyle kuruyorum.",
      sub: "Şu an İstanbul'da Aksigorta'da mobil uygulama büyümesini yönetiyorum; öncesinde Vodafone, Getir ve Wingie Enuygun Group'ta growth rollerindeydim.",
      ctaPrimary: "İletişime geç",
      ctaSecondary: "LinkedIn",
      reassurance: ["Mobile App Growth Lead, Aksigorta", "Growth'ta 7+ yıl", "İstanbul"],
    },
    lab: {
      label: "Lab",
      title: "Yaptığım şeyler",
      intro: "Açık kaynak araçlar, deneyler ve yan projelerden oluşan bir koleksiyon. Çoğunlukla pazarlama ve growth, bazen değil.",
      viewAll: "Arşivi keşfet",
      projects: [
        {
          name: "Lifecycle Pazarlama Journey Üretici",
          slug: "claude-lifecycle",
          desc: "Zaten takip ettiğin müşteri verisine bakar, ölçebildiğin, segmentleyebildiğin ve aksiyon alabildiğin şeyler üzerine lifecycle journey'ler kurar.",
          tags: ["Claude Code Eklentisi", "CRM", "Lifecycle Pazarlama", "26 journey deseni", "9 sektör"],
          links: [
            { label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/claude-lifecycle" },
            { label: "Demoyu dene", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
          ],
        },
        {
          name: "CRM Journey İnceleme Arşivi",
          slug: "lifecycle-card-archive",
          desc: "70 lifecycle journey'den oluşan bir koleksiyon; her biri akışın nasıl işlediği, ne test edileceği, hangi metriklerin izleneceği ve nelerden kaçınılacağı üzerinden inceleniyor.",
          tags: ["CRM", "Lifecycle Pazarlama", "70 inceleme", "10 sektör", "TR/EN"],
          links: [{ label: "Arşivi keşfet", href: "/tr/lab/journeys" }],
        },
        {
          name: "A/B Test Playbook",
          slug: "ab-test-playbook",
          desc: "Gerçek ürün journey'leri üzerinden 211 A/B test senaryosu - ne test edileceği, ne ölçüleceği ve sonucu geçersiz kılabilecek şeyler konusunda rehberlikle birlikte.",
          tags: ["Claude Code Eklentisi", "A/B Test", "CRO", "211 senaryo"],
          links: [
            { label: "Playbook'u incele", href: "/tr/lab/ab-testing" },
            { label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/ab-test-playbook" },
          ],
        },
        {
          name: "Pazarlama Dashboard Üretici",
          slug: "dashboard-builder",
          desc: "Farklı pazarlama platformlarından gelen dağınık exportları alır, gerçekten karşılaştırılabilir olanı kontrol eder ve veriyi karar-hazır bir dashboard'a çevirir.",
          tags: ["Claude Code Eklentisi", "Pazarlama Analitiği", "11 dashboard şablonu", "17 test"],
          links: [{ label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/dashboard-builder" }],
        },
        {
          name: "Google Ads Değişiklik Geçmişi Gezgini",
          slug: "google-ads-change-history-dashboard",
          desc: "Google Ads değişiklik geçmişi export'unu aranabilir bir dashboard'a çevirir - ne değişti, kim değiştirdi, ne zaman ve ne kadar büyük bir değişiklikti.",
          tags: ["Python", "Google Ads", "Çevrimdışı Dashboard", "57 self-test"],
          links: [{ label: "GitHub'da görüntüle", href: "https://github.com/ali-demirbas/google-ads-change-history-dashboard" }],
        },
        {
          name: "Numerspace",
          slug: "numerspace",
          desc: "Finans, sağlık, kariyer, pazarlama ve günlük hayatı kapsayan 75+ ücretsiz hesaplama aracı - üyelik ya da ücret duvarı olmadan hızlı, doğru sonuç için kuruldu.",
          tags: ["Web Uygulaması", "Hesaplama Araçları", "75+ araç", "EN/TR"],
          links: [{ label: "numerspace.com'u ziyaret et", href: "https://www.numerspace.com" }],
        },
      ],
      shell: {
        backToSite: "Siteye dön",
      },
      page: {
        title: "CRM Journey Arşivi",
        intro: "Sektörler ve kanallar genelinde 70 lifecycle journey incelemesi. Sektöre veya kanala göre filtrele ya da ara - her kayıt araştırıp belgelediğim bir akış.",
        searchPlaceholder: "Journey ara...",
        sectorLabel: "Sektör",
        channelsLabel: "Kanallar",
        allSectors: "Tüm sektörler",
        allChannels: "Tüm kanallar",
        results: "journey",
        empty: "Bu filtrelerle eşleşen kayıt yok.",
        back: "Ana sayfaya dön",
      },
    },
    about: {
      metaTitle: "Hakkımda - Ali Demirbaş",
      metaDesc: "Dijital Pazarlama · Analitik · Büyüme Stratejisi",
      eyebrow: "Hakkımda",
      title: "Profesyonel Profil",
      sub: "Dijital Pazarlama · Analitik · Büyüme Stratejisi",
      moreLink: "Hakkımda daha fazlası",
      teaserLead:
        "Dijital ürünlerin sürdürülebilir şekilde büyümesine yardımcı olan güvenilir ölçümleme sistemleri kuruyorum. Çalışmalarım; GA4 ve GTM izleme sistemleri kurmayı, Adjust MMP kurulumlarını optimize etmeyi ve kullanıcı içgörülerini ölçülebilir iş büyümesine dönüştüren kanıta dayalı CRO programları tasarlamayı kapsıyor. Pazarlamaya; doğru veriye, yapılandırılmış deneylere ve sürekli optimizasyona dayanan yinelemeli bir süreç olarak yaklaşıyorum.",
      lead:
        "Dijital pazarlama ve büyüme alanında sekiz yılı aşkın deneyimimle, farklı ürünlerin ve iş modellerinin büyüme hedeflerini destekleyecek stratejiler üzerinde çalıştım.",
      body:
        "Deneyimim analitik, kullanıcı kazanımı, ürün ve büyüme stratejisini kapsıyor. Dijital pazarlama performansını değerlendirmek, kullanıcı davranışını anlamak ve büyüme fırsatlarını belirlemek için veriyi kullanıyorum. Kampanya yönetimi, ölçümleme ve optimizasyon boyunca, pazarlama girişimlerini iş hedefleriyle uyumlu tutmaya ve ölçülebilir sonuçlar üretmeye odaklanıyorum.",
      experience: "Deneyim",
      timeline: [
        {
          kind: "single",
          year: "2026",
          co: "Aksigorta",
          logo: "/logos/aksigorta.svg",
          role: "Mobil Uygulama Büyüme Lideri",
          period: "Nis 2026 – Günümüz",
          desc: "Türkiye'nin en büyük sigorta şirketlerinden biri için mobil uygulama büyüme stratejisini yönetiyor, kullanıcı kazanımı ve etkileşimi yürütüyorum.",
        },
        {
          kind: "single",
          year: "2024",
          co: "Vodafone",
          logo: "/logos/vodafone.svg",
          role: "Büyüme Pazarlaması Lideri",
          period: "Ağu 2024 – Nis 2026",
          desc: "Dijital kanallarda büyüme pazarlamasını yönettim; veriye dayalı kullanıcı kazanımını yaşam döngüsü programlarıyla birleştirdim.",
        },
        {
          kind: "single",
          year: "2023",
          co: "Getir",
          logo: "/logos/getir.svg",
          role: "Büyüme – CRM Analitiği Uzmanı",
          period: "Eyl 2023 – Ağu 2024",
          desc: "Hızlı ticaret için CRM analitiği ve büyüme girişimlerini yönettim; elde tutma ve yaşam boyu değeri optimize ettim.",
        },
        {
          kind: "group",
          year: "2021",
          co: "Wingie Enuygun Group",
          logo: "/logos/enuygun.png",
          span: "Tam zamanlı · 2 yıl",
          roles: [
            {
              role: "Kıdemli Yaşam Döngüsü Pazarlama Uzmanı (Büyüme)",
              period: "Oca 2023 – Ağu 2023",
              desc: "Grubun seyahat markaları genelinde yaşam döngüsü ve CRM programlarını uçtan uca yürüttüm.",
            },
            {
              role: "Yaşam Döngüsü Pazarlama Uzmanı (Büyüme)",
              period: "Eyl 2021 – Oca 2023",
              desc: "Önde gelen bir çevrimiçi seyahat platformu için yaşam döngüsü pazarlama programları kurdum ve yürüttüm.",
            },
          ],
        },
        {
          kind: "single",
          year: "2020",
          co: "Albayrak Grubu",
          logo: "/logos/albayrak.svg",
          role: "Dijital Pazarlama Uzmanı",
          period: "Eki 2020 – Ağu 2021",
          desc: "Grup şirketleri genelinde dijital pazarlama kampanyalarını yönettim.",
        },
        {
          kind: "single",
          year: "2019",
          co: "Doğuş Oto",
          logo: "/logos/dogus-oto.svg",
          role: "Jr. Dijital Pazarlama Uzmanı",
          period: "Eyl 2019 – Ağu 2020",
          desc: "Türkiye'nin önde gelen otomotiv bayi gruplarından biri için dijital pazarlama uygulamaları yürüttüm.",
        },
      ],
    },
    stack: {
      metaTitle: "Yığın - Ali Demirbaş",
      metaDesc: "Her gün büyümeyi ölçmek, sorgulamak ve optimize etmek için kullandığım araçlar.",
      eyebrow: "Yığın",
      title: "Yığın",
      sub: "Tasarlamak, üretmek, ölçmek ve büyümek için kullandığım araçlar.",
      homeTitle: "Kullandığım araçlar",
      homeIntro: "Deney tasarlamak, güvenilir ölçümleme kurmak, kullanıcı davranışını analiz etmek ve büyümeyi optimize etmek için kullandığım araçlar.",
      homeMore: "Araç setimi keşfet",
    },
    contact: {
      metaTitle: "İletişim - Ali Demirbaş",
      metaDesc: "Ali Demirbaş'a e-posta ile veya LinkedIn üzerinden ulaşın.",
      eyebrow: "İletişim",
      title: "Hadi güzel bir şey için iş birliği yapalım.",
      sub: "İlginç projelerde harika insanlarla iş birliği yapmaya her zaman açığım. Destek eli mi lazım? İki tane var bende!",
      linkedinLabel: "LinkedIn'de bağlantı kur",
      linkedinGo: "Profili görüntüle",
      emailLabel: "E-posta gönder",
      emailGo: "Bana e-posta at",
      emailPill: "E-posta",
      scheduleTitle: "Görüşme planla",
      scheduleSub: "30 dakikalık bir tanışma görüşmesi ayarlayın.",
      formTitle: "Mesaj gönder",
      formName: "İsim",
      formEmail: "E-posta",
      formCompany: "Şirket web sitesi",
      formMessage: "Mesajınız",
      formSubmit: "E-postada aç",
      formNote: "E-posta uygulamanızda hazır doldurulmuş bir taslak açar - bu sitede bunu sizin yerinize gönderecek bir sunucu yok.",
    },
    abTesting: {
      metaTitle: "A/B Test Playbook - Ali Demirbaş",
      metaDesc: "Claude Code için 211 gerçek büyüme testi senaryosu: ne test edilir, hangi KPI izlenir, ne yapılmamalı.",
      eyebrow: "Lab / A/B Test",
      title: "Guardrail'i atlamana izin vermeyen bir A/B test motoru.",
      sub: "ab-test-playbook, 211 gerçek e-ticaret, mobil uygulama ve SaaS büyüme testi senaryosundan kurulu, açık kaynak bir Claude Code eklentisi. Kullanıcının journey'deki yerine göre kanıtlanmış bir test seçmene yardım eder, yenilerini tek değişken disipliniyle tasarlar ve göz kararı yerine gerçek istatistiği çalıştırır.",
      install: {
        title: "Kurulum",
        options: [
          {
            label: "Plugin marketplace",
            code: "/plugin marketplace add ali-demirbas/ab-test-playbook\n/plugin install ab-test-playbook@ab-test-playbook",
          },
          {
            label: "Yerel klon",
            code: "git clone https://github.com/ali-demirbas/ab-test-playbook.git\nclaude --plugin-dir ./ab-test-playbook",
          },
          {
            label: "skills.sh",
            code: "npx skills add ali-demirbas/ab-test-playbook --all",
          },
        ],
      },
      framework: {
        title: "Her senaryo aynı üç kutu disiplinini izler",
        boxes: [
          { title: "Test edilmesi gerekenler", desc: "Deneyin cevaplaması gereken somut sorular - \"butonu test et\" değil, sonucun çözmesi gereken her hipotez." },
          { title: "Takip edilecek KPI'lar", desc: "Kazananı belirleyen tek bir birincil metrik, artı iyileşirken bozulmaması gereken en az bir guardrail." },
          { title: "Yapılmaması gerekenler", desc: "Testi sessizce geçersiz kılan hatalar - sonuçlar okunamaz hâle gelene kadar kimsenin fark etmediği türden." },
        ],
      },
      principlesTitle: "Eklentinin eğmediği beş kural",
      principles: [
        { title: "Her zaman tek değişken", desc: "Her varyant çifti tam olarak bir şeyi değiştirir. Çok değişkenli bir test istenirse ayrı testlere bölünür - ısrar edilirse çıktı açıkça 'sonuç hangi değişiklikten geldi bilinemeyecek' der." },
        { title: "Tek birincil metrik", desc: "Listedeki ilk KPI kazananı belirler. Beş metriği eşit önemde sunmak, tam olarak kaybeden bir testin kazanan ilan edilme yoludur." },
        { title: "Guardrail'siz senaryo yok", desc: "Her senaryo, bozulmaması gereken en az bir metrikle gelir - marj, iade oranı, hız, destek talebi. Bir değişiklik erişilebilirliği etkileyebilecekse, o da bir guardrail adayıdır." },
        { title: "Koruma bir büyüme kolu değildir", desc: "CAPTCHA, kimlik veya yaş doğrulama, iki adımlı giriş, yasal onay adımları - istense bile hiçbir zaman kaldırılacak sürtünme olarak önerilmez. Bunlar koruma içindir, dönüşüm için değil; eklenti bunu söyler ve senaryo üretmez." },
        { title: "Güven söylenir, ima edilmez", desc: "Her öneri, arkasındaki kanıtın ne kadar güçlü olduğunu söyler - kullanıcının kendi verisi, arşiv emsali, sektör örüntüsü ya da sezgi. Zayıf kanıtlı bir fikir yine sunulabilir ama asla kesinmiş gibi giydirilmez." },
      ],
      exampleTitle: "Arşivden gerçek bir senaryo",
      example: {
        idx: "ECOM-CART",
        title: "Açık kupon kodu alanı sepet terkini artırır mı?",
        intro: "Görünür bir kupon kutusu, kodu olmayan kullanıcıyı 'indirim arayayım' diye siteden çıkarabilir. Kodu bağlantı arkasına almak bu kaçağı kapatabilir ama kampanya kullanımını düşürebilir.",
        testBox: {
          label: "Test edilmesi gerekenler",
          items: [
            "Kaçak: Kupon alanını bağlantı arkasına almak terk oranını düşürüyor mu?",
            "Segment: Yeni ve dönen kullanıcıda kupon arama davranışı farklı mı?",
            "Metin: 'İndirim kodum var' ile 'Kupon kullan' farklı sonuç veriyor mu?",
            "Kampanya: Kampanya dönemlerinde etki tersine dönüyor mu?",
            "Hata: Kod girip başarısız olan kullanıcının terk oranı ne kadar?",
          ],
        },
        kpiBox: {
          label: "Takip edilecek KPI'lar",
          items: [
            "Ziyaretçi Başına Gelir (RPV) - birincil metrik",
            "Sipariş Tamamlama Oranı",
            "Kupon Kullanım Oranı (guardrail)",
            "Ödeme Adımı Terk Oranı",
            "Kampanya Katılımı (guardrail)",
          ],
        },
        dontBox: {
          label: "Yapılmaması gerekenler",
          items: [
            "Kupon alanını tamamen kaldırmayın; kodu olan kullanıcı öfkelenir.",
            "Geçersiz kod hatasını belirsiz bırakmayın.",
            "Test sırasında aktif kampanya kurmayın veya kaldırmayın.",
            "Kupon alanını fark edilmez hâle getirecek kadar gizlemeyin.",
            "Aynı testte hem konumu hem metni değiştirmeyin.",
          ],
        },
      },
      faqTitle: "SSS",
      faqIntro: "Cevaplar eklentinin kendi metodoloji dokümanlarından, dış kaynaklardan değil.",
      faq: [
        {
          q: "İlk olarak neyi A/B test etmeliyim?",
          a: "Adayları içgüdüyle değil ICE (Etki × Güven × Kolaylık) ile sıralayın. Yüksek trafikli bir sayfada düşük efor gerektiren bir test, düşük trafikli bir sayfadaki iddialı bir testten daha iyidir.",
        },
        {
          q: "Bir A/B test için kaç ziyaretçiye ihtiyacım var?",
          a: "Bu bir kestirme kural değil - gerçek baz dönüşüm oranınızdan ve önemsediğiniz minimum etki büyüklüğünden hesaplanır. Gerçek trafik verisi olmadan hiçbir süre veya örneklem vaadi verilmez.",
        },
        {
          q: "Sonuçlara erken bakıp anlamlı göründüğünde durabilir miyim?",
          a: "Hayır - bir testi tekrar tekrar kontrol edip anlamlı göründüğü an durmak, gerçek bir fark olmasa bile yanlış-pozitif oranını %5'in çok üzerine çıkarır. Örneklem büyüklüğünü veya süreyi baştan belirleyin, bir kez bakın. Tek istisna: bir guardrail metriğinin test ortasında gözle görülür şekilde bozulması.",
        },
        {
          q: "Neden en az iki tam hafta test çalıştırmalıyım?",
          a: "İstatistiksel güç gereksinimi değil - kapsama gereksinimi. Hafta içi/hafta sonu davranışı ve maaş günü etkilerinin veride temsil edilmesi gerekir, örneklem hedefine üç günde ulaşılsa bile.",
        },
        {
          q: "Bir sonucu geçersiz kılan yaygın A/B test hataları nelerdir?",
          a: "Aynı testte birden fazla değişkeni değiştirmek; ilk günlerin verisinden kazanan ilan etmek; bir fiyat testinde yalnızca dönüşüm oranına bakmak (CR artarken ziyaretçi başına gelir düşebilir); gerçek sayfa test edilirken 'Variant A'yı yeniden tasarlamak; aynı sayfaya çakışan trafikte iki test çalıştırmak.",
        },
        {
          q: "Bu playbook her ürün için doğru araç mı?",
          a: "Hayır, ve bunu açıkça söylüyor. B2C e-ticaret, tüketici mobil uygulamaları ve gerçek haftalık trafiği olan self-serve SaaS için uyar. Düşük trafikli kurumsal satış sayfaları, uzun satış döngüleri veya ağır regüle akışlar için daha az uyar - onlar için niteliksel yöntemlere işaret eder.",
        },
      ],
      repoLink: "GitHub'da görüntüle",
      demoLink: "Canlı demo",
    },
    finalCta: {
      title: "Büyümeyi konuşalım.",
      body: "Bir rol, bir proje ya da lifecycle marketing üzerine bir soru - kutum açık.",
      button: "mehmetalidemirbas@gmail.com",
      linkedin: "LinkedIn'de bağlan",
    },
    footer: {
      left: "Ali Demirbaş, 2026",
      right: "İstanbul",
      quickLinks: "Hızlı bağlantılar",
      projects: "Lab projeleri",
      connect: "Bağlan",
      home: "Ana sayfa",
    },
  },
} as const;

export const LINKEDIN = "https://www.linkedin.com/in/ali-demirbas/";
export const EMAIL = "mehmetalidemirbas@gmail.com";
