export type Lang = "en" | "tr";

export const copy = {
  en: {
    nav: { about: "About", aboutHref: "/about", expertise: "Expertise", experience: "Experience", lab: "Lab", labHref: "/lab", contact: "Contact", cta: "Get in touch", lang: "TR", langHref: "/tr" },
    hero: {
      line1: "Growth you can measure.",
      line2: "Products that keep users.",
      lead: "I'm Ali Demirbaş, a growth marketer for mobile products. I build acquisition, CRM and lifecycle programs on data - not guesswork.",
      sub: "Currently leading mobile app growth at Aksigorta in Istanbul, after growth roles at Vodafone, Getir and Wingie Enuygun Group.",
      ctaPrimary: "Get in touch",
      ctaSecondary: "LinkedIn",
      reassurance: ["Mobile App Growth Lead, Aksigorta", "7+ years in growth", "Istanbul"],
    },
    trust: "Growth experience across",
    stats: {
      title: "Track record",
      items: [
        { value: "7+", label: "years building growth, CRM and lifecycle programs" },
        { value: "6", label: "brands, from telco to insurance to q-commerce" },
        { value: "70+", label: "CRM journey teardowns researched and documented" },
        { value: "5", label: "industries: insurance, telco, delivery, travel, automotive" },
      ],
    },
    expertise: {
      label: "Expertise",
      title: "Three disciplines, one goal: retention that compounds.",
      cards: [
        { title: "Mobile app growth", body: "Acquisition and activation for iOS and Android products: store funnels, paid and organic loops, onboarding experiments that move retention." },
        { title: "CRM & lifecycle", body: "Journey design across push, email and in-app. Segmentation, triggers and campaigns that meet users at the right moment of their lifecycle." },
        { title: "Analytics & experimentation", body: "Measurement plans, cohort and funnel analysis, A/B testing discipline. Decisions argued with data, and reported so leadership can act on them." },
      ],
    },
    xp: {
      label: "Experience",
      title: "Where I've built it",
      rows: [
        { years: "2026 -", role: "Mobile App Growth Lead", co: "Aksigorta", logo: "/logos/aksigorta.svg" },
        { years: "2024 - 26", role: "Growth Marketing Lead", co: "Vodafone", logo: "/logos/vodafone.svg" },
        { years: "2023 - 24", role: "Growth, CRM Analytics", co: "Getir", logo: "/logos/getir.svg" },
        { years: "2021 - 23", role: "Lifecycle Marketing", co: "Wingie Enuygun Group", logo: "/logos/enuygun.png" },
        { years: "2020 - 21", role: "Digital Marketing", co: "Albayrak Grubu", logo: "/logos/albayrak.svg" },
        { years: "2019 - 20", role: "Digital Marketing", co: "Doğuş Oto", logo: "/logos/dogus-oto.svg" },
      ],
    },
    lab: {
      label: "Lab",
      title: "Where I test what I preach",
      intro: "Side projects that turn lifecycle practice into public, reusable work.",
      viewAll: "Explore the archive",
      projects: [
        {
          name: "claude-lifecycle",
          desc: "An open-source Claude plugin that drafts CRM journeys from proven patterns - 26 journey blueprints across 9 industries.",
          meta: "Open source - Claude plugin",
          links: [
            { label: "GitHub", href: "https://github.com/ali-demirbas/claude-lifecycle" },
            { label: "Live demo", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
          ],
        },
        {
          name: "CRM Journey Archive",
          desc: "70 lifecycle journey teardowns: how each flow is built, what to test, which KPI to track, which classic mistake to avoid.",
          meta: "70 teardowns - 5 channels",
          links: [{ label: "Browse the archive", href: "/lab" }],
        },
      ],
      shell: {
        backToSite: "Back to site",
        tools: "Tools",
        comingSoon: "Coming soon",
        soon: "Soon",
        library: [
          { name: "CRM Journey Archive", desc: "70 lifecycle teardowns", href: "/lab", active: true },
          { name: "claude-lifecycle", desc: "Claude plugin - GitHub", href: "https://github.com/ali-demirbas/claude-lifecycle" },
          { name: "Journey Canvas", desc: "Live demo", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
        ],
        planned: [
          { name: "Push benchmarks", desc: "Send-time and CTR data by vertical" },
          { name: "Subject line lab", desc: "Test archive with uplift notes" },
          { name: "RFM playground", desc: "Interactive segmentation sandbox" },
        ],
      },
      page: {
        title: "CRM Journey Archive",
        intro: "70 lifecycle journey teardowns across sectors and channels. Filter by sector or channel, or search - each entry is a flow I have researched and documented.",
        searchPlaceholder: "Search journeys...",
        sectorLabel: "Sector",
        channelsLabel: "Channels",
        allSectors: "All sectors",
        allChannels: "All channels",
        results: "journeys",
        empty: "Nothing matches those filters.",
        back: "Back to home",
      },
    },
    about: {
      metaTitle: "About - Ali Demirbaş",
      metaDesc: "Digital Marketing · Analytics · Growth Strategy",
      eyebrow: "About",
      title: "Professional Profile",
      sub: "Digital Marketing · Analytics · Growth Strategy",
      lead:
        "With over eight years of experience in digital marketing and growth, I have worked on strategies designed to support the growth objectives of different products and business models.",
      body:
        "My experience spans analytics, user acquisition, product, and growth strategy. I use data to evaluate digital marketing performance, understand user behavior, and identify opportunities for growth. Across campaign management, measurement, and optimization, I focus on keeping marketing initiatives aligned with business goals and delivering measurable outcomes.",
      experience: "Experience",
      timeline: [
        {
          kind: "single",
          year: "2026",
          co: "Aksigorta",
          logo: "/logos/aksigorta.svg",
          role: "Mobile App Growth Lead",
          period: "Apr 2026 – Present",
          desc: "Leading mobile app growth strategy, driving user acquisition and engagement for one of Turkey's largest insurers.",
        },
        {
          kind: "single",
          year: "2024",
          co: "Vodafone",
          logo: "/logos/vodafone.svg",
          role: "Growth Marketing Lead",
          period: "Aug 2024 – Apr 2026",
          desc: "Led growth marketing across digital channels, combining data-driven acquisition with lifecycle programs.",
        },
        {
          kind: "single",
          year: "2023",
          co: "Getir",
          logo: "/logos/getir.svg",
          role: "Growth – CRM Analytics Executive",
          period: "Sep 2023 – Aug 2024",
          desc: "Managed CRM analytics and growth initiatives for rapid commerce, optimizing retention and LTV.",
        },
        {
          kind: "group",
          year: "2021",
          co: "Wingie Enuygun Group",
          logo: "/logos/enuygun.png",
          span: "Full-time · 2 yrs",
          roles: [
            {
              role: "Experienced Lifecycle Marketing Specialist (Growth)",
              period: "Jan 2023 – Aug 2023",
              desc: "Owned lifecycle and CRM programs end-to-end across the group's travel brands.",
            },
            {
              role: "Lifecycle Marketing Specialist (Growth)",
              period: "Sep 2021 – Jan 2023",
              desc: "Built and ran lifecycle marketing programs for a leading online travel platform.",
            },
          ],
        },
        {
          kind: "single",
          year: "2020",
          co: "Albayrak Grubu",
          logo: "/logos/albayrak.svg",
          role: "Digital Marketing Specialist",
          period: "Oct 2020 – Aug 2021",
          desc: "Managed digital marketing campaigns across group companies.",
        },
        {
          kind: "single",
          year: "2019",
          co: "Doğuş Oto",
          logo: "/logos/dogus-oto.svg",
          role: "Jr. Digital Marketing Specialist",
          period: "Sep 2019 – Aug 2020",
          desc: "Digital marketing execution for one of Turkey's leading automotive dealer groups.",
        },
      ],
    },
    finalCta: {
      title: "Let's talk growth.",
      body: "Whether it's a role, a project or a question about lifecycle marketing - my inbox is open.",
      button: "mehmetalidemirbas@gmail.com",
      linkedin: "Connect on LinkedIn",
    },
    footer: { left: "Ali Demirbaş, 2026", right: "Istanbul" },
  },
  tr: {
    nav: { about: "Hakkımda", aboutHref: "/tr/about", expertise: "Uzmanlık", experience: "Deneyim", lab: "Lab", labHref: "/tr/lab", contact: "İletişim", cta: "İletişime geç", lang: "EN", langHref: "/" },
    hero: {
      line1: "Ölçülebilir büyüme.",
      line2: "Kullanıcıyı tutan ürünler.",
      lead: "Ben Ali Demirbaş, mobil ürünler için growth marketer. Edinim, CRM ve lifecycle programlarını tahminle değil veriyle kuruyorum.",
      sub: "Şu an İstanbul'da Aksigorta'da mobil uygulama büyümesini yönetiyorum; öncesinde Vodafone, Getir ve Wingie Enuygun Group'ta growth rollerindeydim.",
      ctaPrimary: "İletişime geç",
      ctaSecondary: "LinkedIn",
      reassurance: ["Mobile App Growth Lead, Aksigorta", "Growth'ta 7+ yıl", "İstanbul"],
    },
    trust: "Growth deneyimi",
    stats: {
      title: "Deneyim",
      items: [
        { value: "7+", label: "yıl growth, CRM ve lifecycle programları" },
        { value: "6", label: "marka; telekomdan sigortaya, q-commerce'e" },
        { value: "70+", label: "CRM journey incelemesi araştırıldı ve belgelendi" },
        { value: "5", label: "sektör: sigorta, telekom, teslimat, seyahat, otomotiv" },
      ],
    },
    expertise: {
      label: "Uzmanlık",
      title: "Üç disiplin, tek hedef: birikerek büyüyen retention.",
      cards: [
        { title: "Mobil uygulama büyümesi", body: "iOS ve Android ürünlerinde edinim ve aktivasyon: mağaza hunileri, ücretli ve organik döngüler, retention'ı hareket ettiren onboarding deneyleri." },
        { title: "CRM & lifecycle", body: "Push, e-posta ve in-app kanallarında journey tasarımı. Kullanıcıyı yaşam döngüsünün doğru anında yakalayan segmentasyon, tetikleyici ve kampanyalar." },
        { title: "Analitik & deney", body: "Ölçüm planları, kohort ve huni analizi, A/B test disiplini. Veriyle savunulan ve yönetimin aksiyon alabileceği şekilde raporlanan kararlar." },
      ],
    },
    xp: {
      label: "Deneyim",
      title: "Nerelerde kurdum",
      rows: [
        { years: "2026 -", role: "Mobile App Growth Lead", co: "Aksigorta", logo: "/logos/aksigorta.svg" },
        { years: "2024 - 26", role: "Growth Marketing Lead", co: "Vodafone", logo: "/logos/vodafone.svg" },
        { years: "2023 - 24", role: "Growth, CRM Analytics", co: "Getir", logo: "/logos/getir.svg" },
        { years: "2021 - 23", role: "Lifecycle Marketing", co: "Wingie Enuygun Group", logo: "/logos/enuygun.png" },
        { years: "2020 - 21", role: "Dijital Pazarlama", co: "Albayrak Grubu", logo: "/logos/albayrak.svg" },
        { years: "2019 - 20", role: "Dijital Pazarlama", co: "Doğuş Oto", logo: "/logos/dogus-oto.svg" },
      ],
    },
    lab: {
      label: "Lab",
      title: "Anlattığımı test ettiğim yer",
      intro: "Lifecycle pratiğini herkese açık, yeniden kullanılabilir işe dönüştüren yan projeler.",
      viewAll: "Arşivi keşfet",
      projects: [
        {
          name: "claude-lifecycle",
          desc: "Kanıtlanmış kalıplardan CRM journey'leri taslaklayan açık kaynak Claude eklentisi - 9 sektörde 26 journey şablonu.",
          meta: "Açık kaynak - Claude eklentisi",
          links: [
            { label: "GitHub", href: "https://github.com/ali-demirbas/claude-lifecycle" },
            { label: "Canlı demo", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
          ],
        },
        {
          name: "CRM Journey Arşivi",
          desc: "70 lifecycle journey incelemesi: her akış nasıl kurulur, ne test edilir, hangi KPI izlenir, hangi klasik hatadan kaçınılır.",
          meta: "70 inceleme - 5 kanal",
          links: [{ label: "Arşive göz at", href: "/tr/lab" }],
        },
      ],
      shell: {
        backToSite: "Siteye dön",
        tools: "Araçlar",
        comingSoon: "Yakında",
        soon: "Yakında",
        library: [
          { name: "CRM Journey Arşivi", desc: "70 lifecycle incelemesi", href: "/tr/lab", active: true },
          { name: "claude-lifecycle", desc: "Claude eklentisi - GitHub", href: "https://github.com/ali-demirbas/claude-lifecycle" },
          { name: "Journey Canvas", desc: "Canlı demo", href: "https://ali-demirbas.github.io/claude-lifecycle/demo/journey-canvas.html" },
        ],
        planned: [
          { name: "Push benchmark'ları", desc: "Sektöre göre gönderim saati ve CTR verisi" },
          { name: "Konu satırı lab'ı", desc: "Uplift notlarıyla test arşivi" },
          { name: "RFM playground", desc: "İnteraktif segmentasyon sahası" },
        ],
      },
      page: {
        title: "CRM Journey Arşivi",
        intro: "Sektörler ve kanallar genelinde 70 lifecycle journey incelemesi. Sektöre veya kanala göre filtrele ya da ara - her kayıt araştırıp belgelediğim bir akış.",
        searchPlaceholder: "Journey ara...",
        sectorLabel: "Sektör",
        channelsLabel: "Kanallar",
        allSectors: "Tüm sektörler",
        allChannels: "Tüm kanallar",
        results: "journey",
        empty: "Bu filtrelerle eşleşen kayıt yok.",
        back: "Ana sayfaya dön",
      },
    },
    about: {
      metaTitle: "Hakkımda - Ali Demirbaş",
      metaDesc: "Dijital Pazarlama · Analitik · Büyüme Stratejisi",
      eyebrow: "Hakkımda",
      title: "Profesyonel Profil",
      sub: "Dijital Pazarlama · Analitik · Büyüme Stratejisi",
      lead:
        "Dijital pazarlama ve büyüme alanında sekiz yılı aşkın deneyimimle, farklı ürünlerin ve iş modellerinin büyüme hedeflerini destekleyecek stratejiler üzerinde çalıştım.",
      body:
        "Deneyimim analitik, kullanıcı kazanımı, ürün ve büyüme stratejisini kapsıyor. Dijital pazarlama performansını değerlendirmek, kullanıcı davranışını anlamak ve büyüme fırsatlarını belirlemek için veriyi kullanıyorum. Kampanya yönetimi, ölçümleme ve optimizasyon boyunca, pazarlama girişimlerini iş hedefleriyle uyumlu tutmaya ve ölçülebilir sonuçlar üretmeye odaklanıyorum.",
      experience: "Deneyim",
      timeline: [
        {
          kind: "single",
          year: "2026",
          co: "Aksigorta",
          logo: "/logos/aksigorta.svg",
          role: "Mobil Uygulama Büyüme Lideri",
          period: "Nis 2026 – Günümüz",
          desc: "Türkiye'nin en büyük sigorta şirketlerinden biri için mobil uygulama büyüme stratejisini yönetiyor, kullanıcı kazanımı ve etkileşimi yürütüyorum.",
        },
        {
          kind: "single",
          year: "2024",
          co: "Vodafone",
          logo: "/logos/vodafone.svg",
          role: "Büyüme Pazarlaması Lideri",
          period: "Ağu 2024 – Nis 2026",
          desc: "Dijital kanallarda büyüme pazarlamasını yönettim; veriye dayalı kullanıcı kazanımını yaşam döngüsü programlarıyla birleştirdim.",
        },
        {
          kind: "single",
          year: "2023",
          co: "Getir",
          logo: "/logos/getir.svg",
          role: "Büyüme – CRM Analitiği Uzmanı",
          period: "Eyl 2023 – Ağu 2024",
          desc: "Hızlı ticaret için CRM analitiği ve büyüme girişimlerini yönettim; elde tutma ve yaşam boyu değeri optimize ettim.",
        },
        {
          kind: "group",
          year: "2021",
          co: "Wingie Enuygun Group",
          logo: "/logos/enuygun.png",
          span: "Tam zamanlı · 2 yıl",
          roles: [
            {
              role: "Kıdemli Yaşam Döngüsü Pazarlama Uzmanı (Büyüme)",
              period: "Oca 2023 – Ağu 2023",
              desc: "Grubun seyahat markaları genelinde yaşam döngüsü ve CRM programlarını uçtan uca yürüttüm.",
            },
            {
              role: "Yaşam Döngüsü Pazarlama Uzmanı (Büyüme)",
              period: "Eyl 2021 – Oca 2023",
              desc: "Önde gelen bir çevrimiçi seyahat platformu için yaşam döngüsü pazarlama programları kurdum ve yürüttüm.",
            },
          ],
        },
        {
          kind: "single",
          year: "2020",
          co: "Albayrak Grubu",
          logo: "/logos/albayrak.svg",
          role: "Dijital Pazarlama Uzmanı",
          period: "Eki 2020 – Ağu 2021",
          desc: "Grup şirketleri genelinde dijital pazarlama kampanyalarını yönettim.",
        },
        {
          kind: "single",
          year: "2019",
          co: "Doğuş Oto",
          logo: "/logos/dogus-oto.svg",
          role: "Jr. Dijital Pazarlama Uzmanı",
          period: "Eyl 2019 – Ağu 2020",
          desc: "Türkiye'nin önde gelen otomotiv bayi gruplarından biri için dijital pazarlama uygulamaları yürüttüm.",
        },
      ],
    },
    finalCta: {
      title: "Büyümeyi konuşalım.",
      body: "Bir rol, bir proje ya da lifecycle marketing üzerine bir soru - kutum açık.",
      button: "mehmetalidemirbas@gmail.com",
      linkedin: "LinkedIn'de bağlan",
    },
    footer: { left: "Ali Demirbaş, 2026", right: "İstanbul" },
  },
} as const;

export const LINKEDIN = "https://www.linkedin.com/in/ali-demirbas/";
export const EMAIL = "mehmetalidemirbas@gmail.com";
