export type PublicJourneyCopy = {
  shortName: string;
  name: string;
  purpose: string;
  reusableRule: string;
  entityScope: string;
  entityNote: string;
  guardrails: readonly string[];
};

type Pair = { en: PublicJourneyCopy; tr: PublicJourneyCopy };

const COPY: Readonly<Record<string, Pair>> = {
  "ACQ-01": { en:{shortName:"Anonymous Intent Qualification",name:"Anonymous intent → resolve identity → qualify or exit",purpose:"Turn meaningful anonymous intent into a known, eligible profile without treating identity resolution as permission to market.",reusableRule:"Resolve identity first, then evaluate eligibility. A known profile is not automatically a marketable lead.",entityScope:"Anonymous profile",entityNote:"The journey follows one anonymous profile until identity is resolved or the intent signal expires.",guardrails:["Do not infer identity from probabilistic signals alone.","Do not treat identity resolution as consent."]}, tr:{shortName:"Anonim Niyeti Nitelendirme",name:"Anonim niyet → kimliği doğrula → uygunluğu değerlendir → devam et veya çık",purpose:"Anlamlı anonim niyeti, kimlik veya izin varsaymadan bilinen ve uygun bir profile dönüştürmek.",reusableRule:"Önce kimliği doğrula, sonra uygunluğu değerlendir. Bilinen bir profil olmak tek başına iletişim izni anlamına gelmez.",entityScope:"Anonim profil",entityNote:"Journey, anonim profili kimlik doğrulanana veya niyet sinyali geçerliliğini yitirene kadar takip eder.",guardrails:["Yalnızca olasılıksal sinyallerle kimlik atama.","Kimliğin doğrulanmasını iletişim izni olarak yorumlama."]} },
  "ACQ-02": { en:{shortName:"Interest Qualification",name:"Interest captured → qualify → route to the right destination",purpose:"Route first-party interest according to what the user actually asked for and how ready they are to act.",reusableRule:"Captured interest is not automatically a sales lead. Route it according to the intent the signal actually supports.",entityScope:"Captured interest",entityNote:"The journey follows one explicit first-party interest signal and the destination it can legitimately support.",guardrails:["Keep consent separate from intent.","Do not force low-intent interest into a sales path."]}, tr:{shortName:"İlgiyi Nitelendirme",name:"İlgi yakalandı → niyeti değerlendir → doğru hedefe yönlendir",purpose:"Birinci taraf ilgi sinyalini, kullanıcının gerçekten istediği aksiyona ve hazır oluş seviyesine göre doğru sürece yönlendirmek.",reusableRule:"Yakalanan her ilgi satış lead'i değildir. Sinyalin gerçekten desteklediği niyete göre yönlendir.",entityScope:"Yakalanan ilgi",entityNote:"Journey, tek bir açık ilgi sinyalini ve bu sinyalin desteklediği hedefi takip eder.",guardrails:["İletişim iznini niyetten ayrı değerlendir.","Düşük niyetli ilgiyi zorla satış sürecine taşıma."]} },
  "ACQ-03": { en:{shortName:"Intent Escalation",name:"Intent strengthens → stop lower-intent messaging → hand off",purpose:"Move a user into the higher-intent journey when stronger behaviour makes the current journey no longer appropriate.",reusableRule:"Only escalate on a meaningful, current signal and stop the lower-intent journey before the handoff.",entityScope:"Intent state",entityNote:"The journey follows the strongest current intent for the same user and entity.",guardrails:["Do not escalate on a single weak or stale signal.","Suppress queued lower-intent messages before handoff."]}, tr:{shortName:"Niyet Yükseltme",name:"Niyet güçlendi → düşük niyetli iletişimi durdur → doğru sürece aktar",purpose:"Daha güçlü bir davranış sinyali geldiğinde kullanıcıyı doğru yüksek niyetli sürece taşımak ve önceki iletişimi durdurmak.",reusableRule:"Yalnızca anlamlı ve güncel bir sinyalde yükseltme yap; devirden önce düşük niyetli journey'yi durdur.",entityScope:"Niyet durumu",entityNote:"Journey, aynı kullanıcı ve bağlam için güncel en güçlü niyet seviyesini takip eder.",guardrails:["Tek bir zayıf veya eski sinyalle niyeti yükseltme.","Devirden önce kuyruktaki düşük niyetli mesajları durdur."]} },
  "ACQ-04": { en:{shortName:"High-Intent Routing",name:"High-intent action → qualify → human or automated path",purpose:"Route a serious commercial action to a human or automated next step based on the complexity of the request.",reusableRule:"Check the existing customer and opportunity state before creating anything new.",entityScope:"High-intent request",entityNote:"The journey follows one high-intent commercial request and its next owner.",guardrails:["Do not create duplicate opportunities for the same request.","Use human review only when it adds value."]}, tr:{shortName:"Yüksek Niyetli Lead Yönlendirme",name:"Yüksek niyetli aksiyon → nitelendir → insan veya otomatik sürece yönlendir",purpose:"Güçlü ticari niyet gösteren bir talebi, karmaşıklığına göre insan desteğine veya otomatik sürece yönlendirmek.",reusableRule:"Yeni kayıt oluşturmadan önce mevcut müşteri ve fırsat durumunu kontrol et.",entityScope:"Yüksek niyetli talep",entityNote:"Journey, tek bir yüksek niyetli ticari talebi ve sonraki sahibini takip eder.",guardrails:["Aynı talep için duplicate fırsat oluşturma.","İnsan değerlendirmesini yalnızca gerçekten değer kattığı yerde kullan."]} },
  "ACQ-05": { en:{shortName:"Qualification State Routing",name:"Qualification changes → reroute, recycle or exit",purpose:"Treat qualification as a changing state and route the lead according to why that state changed.",reusableRule:"A qualification result should carry both the current state and the reason behind it.",entityScope:"Qualification state",entityNote:"The journey follows changes in qualification for one lead or account.",guardrails:["Keep previous qualification states and reasons readable.","Do not recycle a lead without a real re-entry condition."]}, tr:{shortName:"Nitelik Durumu Yönlendirme",name:"Nitelik durumu değişti → yeniden yönlendir, beklet veya çık",purpose:"Lead'in nitelik durumunu sabit bir etiket yerine değişebilen bir durum olarak ele almak ve değişim nedenine göre yönlendirmek.",reusableRule:"Her nitelik sonucu hem güncel durumu hem de bu duruma neden olan bilgiyi taşımalı.",entityScope:"Nitelik durumu",entityNote:"Journey, tek bir lead veya hesabın nitelik durumundaki değişimleri takip eder.",guardrails:["Önceki durumları ve nedenlerini okunabilir tut.","Gerçek bir yeniden giriş koşulu olmadan lead'i recycle etme."]} },
  "ACQ-06": { en:{shortName:"Eligibility Recheck",name:"Eligibility changes → reassess → allow, block or reconcile",purpose:"Re-evaluate eligibility when the underlying data changes and apply the result without silently undoing existing commitments.",reusableRule:"Eligibility governs what can happen next; it does not automatically revoke what has already been granted.",entityScope:"Eligibility state",entityNote:"The journey follows one eligibility decision and the data changes that can reopen it.",guardrails:["Record the rule and input behind each decision.","Do not revoke an existing entitlement through this journey."]}, tr:{shortName:"Uygunluğu Yeniden Değerlendirme",name:"Uygunluk değişti → yeniden değerlendir → izin ver, engelle veya uzlaştır",purpose:"Temel veriler değiştiğinde uygunluğu yeniden değerlendirmek ve mevcut taahhütleri sessizce geri almadan sonucu uygulamak.",reusableRule:"Uygunluk bundan sonra ne yapılabileceğini belirler; daha önce verilmiş bir hakkı otomatik olarak geri almaz.",entityScope:"Uygunluk durumu",entityNote:"Journey, tek bir uygunluk kararını ve kararı yeniden açabilecek veri değişikliklerini takip eder.",guardrails:["Her kararın dayandığı kuralı ve girdiyi kaydet.","Mevcut bir hakkı bu journey üzerinden otomatik olarak geri alma."]} },
  "ACQ-07": { en:{shortName:"Intent Decay",name:"Intent weakens → lower priority → cool down or exit",purpose:"Reduce priority when the evidence behind a high-intent state becomes stale instead of pursuing the user indefinitely.",reusableRule:"Intent should decay when the supporting evidence no longer reflects current behaviour.",entityScope:"Intent state",entityNote:"The journey follows whether a previously strong intent signal remains credible over time.",guardrails:["Do not confuse declining intent with withdrawn consent.","Stop high-intent follow-up when the evidence no longer supports it."]}, tr:{shortName:"Niyet Zayıflaması",name:"Niyet zayıfladı → önceliği düşür → beklet veya çık",purpose:"Yüksek niyeti destekleyen sinyaller güncelliğini kaybettiğinde kullanıcıyı süresiz takip etmek yerine önceliği düşürmek.",reusableRule:"Niyet, onu destekleyen davranış artık güncel değilse zamanla zayıflamalı.",entityScope:"Niyet durumu",entityNote:"Journey, daha önce güçlü olan niyet sinyalinin zaman içinde hâlâ geçerli olup olmadığını takip eder.",guardrails:["Zayıflayan niyeti geri çekilmiş izinle karıştırma.","Kanıt artık desteklemiyorsa yüksek niyetli iletişimi durdur."]} },
  "ACQ-08": { en:{shortName:"Acquisition Exit Handoff",name:"Commercial goal reached → stop acquisition → hand off",purpose:"End acquisition messaging as soon as the commercial goal is recorded and hand ownership to the next lifecycle stage.",reusableRule:"Once the authoritative conversion event is recorded, acquisition no longer owns that entity.",entityScope:"Converted entity",entityNote:"The journey follows the order, subscription, booking or application that completed the acquisition goal.",guardrails:["Use an authoritative business event, not a proxy engagement signal.","Suppress queued acquisition messages before handoff."]}, tr:{shortName:"Kazanım Sonrası Devir",name:"Ticari hedef tamamlandı → kazanım iletişimini durdur → sonraki sürece aktar",purpose:"Ticari hedef gerçekleştiği anda acquisition iletişimini bitirmek ve sahipliği sonraki lifecycle aşamasına devretmek.",reusableRule:"Yetkili conversion olayı kaydedildiğinde acquisition artık o varlığın sahibi değildir.",entityScope:"Dönüşen varlık",entityNote:"Journey, acquisition hedefini tamamlayan sipariş, abonelik, rezervasyon veya başvuruyu takip eder.",guardrails:["Proxy etkileşim yerine yetkili iş olayını kullan.","Devirden önce kuyruktaki acquisition mesajlarını durdur."]} },
  "ACQ-10": { en:{shortName:"Commercial Decline Routing",name:"Commercial decline → classify reason → close, cool down or requalify",purpose:"Route a negative commercial outcome by its actual reason instead of treating every loss as the same state.",reusableRule:"The decline reason determines whether the opportunity should close, wait for a known condition or return to qualification.",entityScope:"Commercial opportunity",entityNote:"The journey follows one declined commercial opportunity and its recorded reason.",guardrails:["Do not invent a follow-up date when no re-entry condition exists.","Keep distinct decline reasons as separate historical facts."]}, tr:{shortName:"Ticari Ret Yönlendirme",name:"Ticari ret → nedeni sınıflandır → kapat, beklet veya yeniden nitelendir",purpose:"Olumsuz ticari sonucu tek bir 'kaybedildi' durumuna atmak yerine gerçek ret nedenine göre yönlendirmek.",reusableRule:"Ret nedeni; fırsatın kapanacağını, bilinen bir koşulu bekleyeceğini veya yeniden nitelendirileceğini belirler.",entityScope:"Ticari fırsat",entityNote:"Journey, reddedilen tek bir ticari fırsatı ve kaydedilen ret nedenini takip eder.",guardrails:["Gerçek bir yeniden giriş koşulu yoksa takip tarihi uydurma.","Farklı ret nedenlerini geçmişte ayrı gerçekler olarak koru."]} },
  "ACQ-285": { en:{shortName:"First Lead Response",name:"Interest captured → first response → engage, route or exit",purpose:"Respond quickly to newly captured interest and use the first meaningful response to decide what should happen next.",reusableRule:"The first touch should acknowledge the user's actual request and create a clear next step.",entityScope:"New lead",entityNote:"The journey follows one newly captured lead through the first meaningful response.",guardrails:["Do not send a generic first touch when the request context is known.","Stop or reroute when a stronger intent signal appears."]}, tr:{shortName:"İlk Lead Teması",name:"İlgi yakalandı → ilk teması yap → etkileşime göre yönlendir veya çık",purpose:"Yeni yakalanan ilgiye hızlı ve bağlama uygun ilk teması yapmak, ardından gelen sinyale göre sonraki adımı belirlemek.",reusableRule:"İlk temas kullanıcının gerçek talebini karşılamalı ve net bir sonraki adım sunmalı.",entityScope:"Yeni lead",entityNote:"Journey, yeni yakalanan bir lead'i ilk anlamlı yanıta kadar takip eder.",guardrails:["Talep bağlamı biliniyorsa genel bir ilk mesaj gönderme.","Daha güçlü bir niyet sinyali geldiğinde akışı durdur veya yeniden yönlendir."]} },
  "ACT-11": { en:{shortName:"Onboarding Route Selection",name:"New user → choose onboarding route → start the right path",purpose:"Choose the onboarding path based on the work required to reach value, before that work begins.",reusableRule:"Route by actual setup needs, not by plan tier or assumed customer value.",entityScope:"Onboarding",entityNote:"The journey follows one new user's onboarding route and any prerequisite that blocks the start.",guardrails:["Do not assign assisted onboarding when self-service is sufficient.","Do not start onboarding while a mandatory prerequisite is missing."]}, tr:{shortName:"Onboarding Rotası Seçimi",name:"Yeni kullanıcı → onboarding rotasını seç → doğru akışı başlat",purpose:"Kullanıcının değere ulaşmak için gerçekten ihtiyaç duyduğu kuruluma göre onboarding yolunu daha süreç başlamadan belirlemek.",reusableRule:"Rotayı plan seviyesine veya varsayılan müşteri değerine göre değil, gerçek kurulum ihtiyacına göre seç.",entityScope:"Onboarding",entityNote:"Journey, yeni kullanıcının onboarding rotasını ve başlangıcı engelleyen zorunlu koşulları takip eder.",guardrails:["Self-service yeterliyse destekli onboarding atama.","Zorunlu bir ön koşul eksikken onboarding'i başlatma."]} },
  "ACT-12": { en:{shortName:"Onboarding Next Step",name:"Onboarding progresses → identify next step → continue or complete",purpose:"Keep onboarding moving by selecting the next relevant step from the user's actual progress.",reusableRule:"The next step should come from current progress, not from a fixed message sequence.",entityScope:"Onboarding progress",entityNote:"The journey follows one user's completed and remaining onboarding steps.",guardrails:["Do not repeat completed steps.","Stop onboarding guidance when the activation goal is reached."]}, tr:{shortName:"Onboarding Sonraki Adım",name:"Onboarding ilerledi → sıradaki adımı belirle → devam et veya tamamla",purpose:"Kullanıcının gerçek ilerlemesine göre sıradaki anlamlı adımı belirleyerek onboarding'i ilerletmek.",reusableRule:"Sıradaki adım sabit bir mesaj dizisinden değil, kullanıcının güncel ilerlemesinden çıkmalı.",entityScope:"Onboarding ilerlemesi",entityNote:"Journey, kullanıcının tamamladığı ve kalan onboarding adımlarını takip eder.",guardrails:["Tamamlanmış adımları tekrar gösterme.","Aktivasyon hedefine ulaşıldığında onboarding yönlendirmesini durdur."]} },
  "ACT-13": { en:{shortName:"Activation Blocker Resolution",name:"Activation stalls → identify blocker → resolve or reroute",purpose:"Find the specific reason activation has stalled and route the user to the help that can remove it.",reusableRule:"Treat the blocker as a diagnosable state, not as generic inactivity.",entityScope:"Activation blocker",entityNote:"The journey follows the specific issue preventing one user from reaching activation.",guardrails:["Do not send generic reminders before identifying the blocker.","End or reroute as soon as the blocker is resolved."]}, tr:{shortName:"Aktivasyon Engelini Çözme",name:"Aktivasyon durdu → engeli belirle → çöz veya doğru desteğe yönlendir",purpose:"Aktivasyonun neden ilerlemediğini belirlemek ve kullanıcıyı bu engeli gerçekten çözebilecek aksiyona yönlendirmek.",reusableRule:"Engeli genel bir inaktivite olarak değil, teşhis edilebilir belirli bir durum olarak ele al.",entityScope:"Aktivasyon engeli",entityNote:"Journey, tek bir kullanıcının aktivasyona ulaşmasını engelleyen belirli sorunu takip eder.",guardrails:["Engeli belirlemeden genel hatırlatmalar gönderme.","Engel çözüldüğünde journey'yi bitir veya doğru sürece aktar."]} },
  "ACT-16": { en:{shortName:"Onboarding Completion Handoff",name:"Activation reached → stop onboarding → hand off to adoption",purpose:"End onboarding as soon as the activation goal is recorded and move the user into the next stage of product use.",reusableRule:"Once real product value is recorded, onboarding should stop even if operational tasks remain.",entityScope:"Activated user",entityNote:"The journey follows the activation event that closes onboarding and hands the user to adoption.",guardrails:["Use the product's authoritative activation event, not a proxy engagement signal.","Move remaining operational requirements into their own flow."]}, tr:{shortName:"Onboarding Tamamlama ve Devir",name:"Aktivasyona ulaşıldı → onboarding'i durdur → adoption sürecine aktar",purpose:"Aktivasyon hedefi gerçekleştiği anda onboarding'i bitirmek ve kullanıcıyı ürün kullanımının sonraki aşamasına taşımak.",reusableRule:"Gerçek ürün değeri kaydedildiğinde, operasyonel işler kalsa bile onboarding sona ermeli.",entityScope:"Aktive kullanıcı",entityNote:"Journey, onboarding'i kapatan aktivasyon olayını ve adoption sürecine devri takip eder.",guardrails:["Proxy etkileşim yerine ürünün yetkili aktivasyon olayını kullan.","Kalan operasyonel gereksinimleri ayrı bir akışa taşı."]} },
  "ACT-18": { en:{shortName:"Adoption Stall Diagnosis",name:"Adoption stalls → diagnose cause → recover or reroute",purpose:"Understand why repeat product use has stalled and respond to the actual barrier instead of sending generic re-engagement.",reusableRule:"Diagnose the reason for stalled adoption before choosing the intervention.",entityScope:"Product adoption",entityNote:"The journey follows a user whose repeat value-producing behaviour has slowed or stopped.",guardrails:["Do not assume inactivity means loss of interest.","Stop the recovery path when healthy repeat use returns."]}, tr:{shortName:"Adoption Durgunluğunu Çözme",name:"Adoption yavaşladı → nedeni belirle → toparla veya yeniden yönlendir",purpose:"Tekrarlanan ürün kullanımının neden durduğunu anlamak ve genel re-engagement yerine gerçek engele göre aksiyon almak.",reusableRule:"Müdahaleyi seçmeden önce adoption'ın neden yavaşladığını teşhis et.",entityScope:"Ürün adoption'ı",entityNote:"Journey, değer üreten tekrar davranışı yavaşlayan veya duran kullanıcıyı takip eder.",guardrails:["İnaktiviteyi otomatik olarak ilgi kaybı sayma.","Sağlıklı tekrar kullanım geri geldiğinde recovery akışını durdur."]} },

  "ACQ-09": {
    en: { shortName:"Lead Nurture", name:"Lead captured → assess intent → build interest → sales or exit", purpose:"Move an interested lead closer to purchase with a focused sequence that responds to changing intent.", reusableRule:"Each step should respond to the lead's latest intent signal. Once purchase intent is clear, nurture ends and sales or conversion takes over.", entityScope:"Lead", entityNote:"The journey follows one interested lead who has not yet entered a sales or purchase path.", guardrails:["End the journey as soon as the lead enters a sales or purchase path.","Do not keep nurturing when meaningful interest signals have stopped."] },
    tr: { shortName:"Satın Alma Niyetini Güçlendirme", name:"Aday müşteri oluştu → niyeti kontrol et → ilgiyi güçlendir → satışa aktar veya akışı bitir", purpose:"İlgi göstermiş ancak henüz satın almaya hazır olmayan adayı, niyet sinyallerine göre ilerleyen kısa bir iletişim akışıyla satın almaya yaklaştırmak.", reusableRule:"Her adım adayın son niyet sinyaline göre ilerler. Satın alma niyeti netleştiğinde nurture biter ve aday satış ya da conversion sürecine aktarılır.", entityScope:"Aday müşteri", entityNote:"Journey, ürün veya hizmete ilgi göstermiş ancak henüz satın alma sürecine geçmemiş tek bir adayı takip eder.", guardrails:["Aday satış veya satın alma sürecine geçtiğinde journey'yi sonlandır.","İlgi sinyali kalmadığında nurture mesajlarını sürdürme."] }
  },
  "ACQ-12": {
    en:{ shortName:"Saved Product Reminder", name:"Product saved → wait → check status → remind or exit", purpose:"Bring a user back to a product they deliberately saved, while stopping when they buy it or the product is no longer available.", reusableRule:"Saving a product is a strong interest signal, not a purchase decision. The messaging should preserve that distinction.", entityScope:"Saved product", entityNote:"The journey follows one specific product saved by one user and its current availability.", guardrails:["End the journey after purchase.","If the product is unavailable, hand off to the back-in-stock journey instead of promoting it."] },
    tr:{ shortName:"Kaydedilen Ürün Hatırlatması", name:"Ürün kaydedildi → bekle → güncel durumu kontrol et → hatırlat veya akışı bitir", purpose:"Kullanıcının kaydettiği ürünü yeniden değerlendirmesini sağlamak; satın alma gerçekleştiğinde veya ürün artık erişilebilir olmadığında iletişimi durdurmak.", reusableRule:"Ürünü kaydetmek güçlü bir ilgi sinyalidir ancak satın alma kararı değildir. İletişim bu farkı korumalı.", entityScope:"Kaydedilen ürün", entityNote:"Journey, tek bir kullanıcının kaydettiği belirli bir ürünü ve ürünün güncel durumunu takip eder.", guardrails:["Satın alma gerçekleştiğinde journey'yi sonlandır.","Ürün stokta değilse satış mesajı göndermek yerine stok bildirimi akışına aktar."] }
  },
  "ACQ-13": {
    en:{ shortName:"Browse Abandonment", name:"Product interest detected → wait → check behaviour → remind or exit", purpose:"Send one relevant reminder when a user repeatedly views the same product but does not add it to cart or buy it.", reusableRule:"Repeated views signal interest, not commitment. The message should not overstate what the user intended.", entityScope:"Viewed product", entityNote:"The journey follows the specific product the user repeatedly viewed and what they do next.", guardrails:["End the journey on add-to-cart or purchase.","Do not create urgency without real stock, price or promotion data."] },
    tr:{ shortName:"Ürün İnceleme Sonrası Hatırlatma", name:"Ürün ilgisi oluştu → bekle → davranışı kontrol et → hatırlat veya akışı bitir", purpose:"Aynı ürünü tekrar inceleyen ancak sepete eklemeyen veya satın almayan kullanıcıya, ilgisi hâlâ güncelse tek bir anlamlı hatırlatma yapmak.", reusableRule:"Tekrarlanan ürün görüntüleme ilgi gösterir; satın alma kararı göstermez. Mesaj bu sinyali olduğundan güçlü yorumlamamalı.", entityScope:"İncelenen ürün", entityNote:"Journey, kullanıcının tekrar görüntülediği belirli bir ürünü ve sonrasındaki davranışını takip eder.", guardrails:["Sepete ekleme veya satın alma gerçekleştiğinde journey'yi sonlandır.","Gerçek stok, fiyat veya kampanya verisi yoksa aciliyet yaratma."] }
  },
  "ACQ-287": {
    en:{ shortName:"Checkout Recovery", name:"Checkout started → not completed → remind → purchase, payment failure or exit", purpose:"Bring users back to an unfinished checkout at the right time and stop immediately when the purchase is completed.", reusableRule:"Checkout reminders end as soon as a purchase or a genuine payment failure is recorded.", entityScope:"Checkout", entityNote:"The journey follows one checkout attempt until it completes, fails at payment or reaches the end of the reminder window.", guardrails:["Hand genuine payment failures to Payment Failure Recovery.","Do not send another reminder after purchase."] },
    tr:{ shortName:"Checkout Tamamlama", name:"Checkout başladı → tamamlanmadı → hatırlat → satın alma, ödeme hatası veya çıkış", purpose:"Checkout'u başlatıp tamamlamayan kullanıcıyı doğru zamanda geri getirmek ve satın alma tamamlandığında iletişimi hemen durdurmak.", reusableRule:"Satın alma tamamlandığında veya gerçek bir ödeme hatası oluştuğunda checkout hatırlatmaları sona ermelidir.", entityScope:"Checkout", entityNote:"Journey, tek bir checkout denemesini tamamlanana, ödeme hatasına dönüşene veya hatırlatma süresi bitene kadar takip eder.", guardrails:["Gerçek bir ödeme hatası oluşursa Payment Failure Recovery journey'sine aktar.","Satın alma tamamlandıktan sonra yeni hatırlatma gönderme."] }
  },
  "ACQ-288": {
    en:{ shortName:"Cart Reminder", name:"Product added to cart → no checkout → remind → checkout, purchase or exit", purpose:"Bring back users who added products to cart but did not start checkout, using a more direct channel only when the cart value warrants it.", reusableRule:"Cart recovery ends when checkout begins. The checkout journey owns what happens next.", entityScope:"Active cart", entityNote:"The journey follows one active cart until checkout starts, a purchase happens or the reminder window ends.", guardrails:["End the journey after purchase.","Hand off as soon as checkout starts."] },
    tr:{ shortName:"Sepet Hatırlatma", name:"Ürün sepete eklendi → checkout başlamadı → hatırlat → checkout, satın alma veya çıkış", purpose:"Sepete ürün ekleyip checkout'a geçmeyen kullanıcıyı geri getirmek; yüksek değerli sepetlerde gerekirse daha doğrudan bir kanala geçmek.", reusableRule:"Checkout başladığı anda sepet journey'si biter; sonraki aşamayı checkout journey'si devralır.", entityScope:"Aktif sepet", entityNote:"Journey, kullanıcının aktif sepetini checkout başlayana, satın alma gerçekleşene veya süre dolana kadar takip eder.", guardrails:["Satın alma gerçekleştiğinde journey'yi sonlandır.","Checkout başladığında kullanıcıyı ilgili journey'ye aktar."] }
  },
  "ACQ-289": {
    en:{ shortName:"Back-in-Stock Alert", name:"Stock alert requested → product returns → notify → purchase or exit", purpose:"Notify a user when a product they explicitly asked about is available again, then stop once they purchase or the alert window ends.", reusableRule:"A back-in-stock alert is triggered by real availability, not by a marketing schedule.", entityScope:"Stock alert request", entityNote:"The journey follows one user's alert request for one specific product.", guardrails:["Do not notify before the product is genuinely available.","End the journey after purchase."] },
    tr:{ shortName:"Stok Bildirimi", name:"Stok bildirimi istendi → ürün yeniden stokta → bildir → satın alma veya çıkış", purpose:"Stok bildirimi isteyen kullanıcıya ürün yeniden satışa çıktığında haber vermek ve satın alma gerçekleştiğinde iletişimi durdurmak.", reusableRule:"Stok bildirimi kampanya takvimine göre değil, ürünün gerçek stok durumuna göre tetiklenir.", entityScope:"Stok bildirimi talebi", entityNote:"Journey, tek bir kullanıcının belirli bir ürün için verdiği stok bildirimi talebini takip eder.", guardrails:["Ürün gerçekten stokta değilse bildirim gönderme.","Satın alma gerçekleştiğinde journey'yi sonlandır."] }
  },
  "ACT-14": {
    en:{ shortName:"Onboarding Help", name:"User gets stuck → offer help → escalate if needed → continue or exit", purpose:"Help users who struggle during onboarding before the friction turns into abandonment.", reusableRule:"Start with the lightest useful help. Escalate only if the user still cannot move forward.", entityScope:"Onboarding flow", entityNote:"The journey follows the step where a user gets stuck and whether they make progress afterwards.", guardrails:["Do not restart onboarding steps that are already complete.","End the journey as soon as the user progresses successfully."] },
    tr:{ shortName:"Onboarding Yardımı", name:"Kullanıcı takıldı → yardım sun → gerekirse kanalı güçlendir → devam veya çıkış", purpose:"Onboarding sırasında ilerlemekte zorlanan kullanıcıya, süreç terk edilmeden önce ihtiyacına uygun destek sunmak.", reusableRule:"Önce en hafif ve bağlama uygun yardımı sun. Kullanıcı hâlâ ilerleyemiyorsa desteği kademeli olarak artır.", entityScope:"Onboarding süreci", entityNote:"Journey, onboarding sırasında kullanıcının takıldığı adımı ve sonrasındaki ilerlemeyi takip eder.", guardrails:["Tamamlanmış onboarding adımlarını yeniden başlatma.","Kullanıcı başarıyla ilerlediğinde journey'yi sonlandır."] }
  },
  "ACT-17": {
    en:{ shortName:"Adoption Nurture", name:"First value reached → encourage repeat use → stable usage or re-engagement", purpose:"Move a newly activated user from a first value moment toward repeat use at a cadence that fits the product.", reusableRule:"Adoption is not the completion of onboarding. It is repeated value from the product.", entityScope:"Product usage", entityNote:"The journey follows whether the user's core value-producing behaviour repeats after activation.", guardrails:["Do not push an upsell before repeat value is visible.","If the first behaviour does not repeat, guide the user toward another relevant path to value."] },
    tr:{ shortName:"Kullanım Alışkanlığı Geliştirme", name:"İlk değer oluştu → tekrar kullanımı destekle → düzenli kullanım veya yeniden etkileşim", purpose:"İlk değer anını yaşayan kullanıcıyı, ürünün gerçek kullanım ritmine uygun şekilde tekrarlanan ve düzenli kullanıma taşımak.", reusableRule:"Adoption, onboarding'in tamamlanmasıyla değil; kullanıcının üründen tekrar tekrar değer üretmesiyle oluşur.", entityScope:"Ürün kullanımı", entityNote:"Journey, aktivasyon sonrasında kullanıcının değer üreten temel davranışının tekrar edip etmediğini takip eder.", guardrails:["Tekrarlanan değer oluşmadan upsell'e geçme.","İlk davranış tekrarlanmıyorsa kullanıcıya bağlama uygun başka bir değer yolu göster."] }
  },
  "ACT-20": {
    en:{ shortName:"Dormant Lead Reactivation", name:"Lead goes dormant → inspect last behaviour → give a reason to return → requalify or exit", purpose:"Re-engage a dormant lead who never became a customer, using their last meaningful behaviour and a genuine reason to return.", reusableRule:"Reactivation should start from real prior interest or a meaningful new reason to return, not a generic 'we miss you' message.", entityScope:"Dormant lead", entityNote:"The journey follows a lead who has not become a paying customer and has stopped showing meaningful activity.", guardrails:["Do not route existing customers through this journey.","Treat purchase, quote and browsing signals as different outcomes."] },
    tr:{ shortName:"Pasif Lead'i Yeniden Aktifleştirme", name:"Lead pasifleşti → son davranışı kontrol et → geri dönüş nedeni sun → yeniden nitelendir veya çık", purpose:"Henüz müşteriye dönüşmemiş pasif bir lead'i, son anlamlı davranışına ve gerçek bir geri dönüş nedenine göre yeniden harekete geçirmek.", reusableRule:"Reactivation genel bir 'seni özledik' mesajıyla değil, lead'in daha önce gösterdiği ilgi veya yeni oluşan gerçek bir nedenle başlamalı.", entityScope:"Pasif lead", entityNote:"Journey, henüz ücretli müşteriye dönüşmemiş ve anlamlı aktivitesi durmuş bir lead'i takip eder.", guardrails:["Mevcut müşterileri bu journey'ye dahil etme.","Satın alma, teklif ve gezinme sinyallerini ayrı sonuçlar olarak değerlendir."] }
  },
  "RET-24": {
    en:{ shortName:"Churn Risk Management", name:"Churn risk rises → assess severity → apply the right intervention → recover or monitor", purpose:"Respond to rising churn risk with interventions matched to the severity and likely cause, rather than one generic retention campaign.", reusableRule:"As the risk signal strengthens, the intervention should become more direct and more specific to the likely problem.", entityScope:"Customer relationship", entityNote:"The journey follows the customer relationship while churn risk remains elevated and tracks whether it recovers.", guardrails:["End the journey when usage or purchase behaviour recovers.","Choose the final intervention around the most likely churn driver."] },
    tr:{ shortName:"Churn Riski Yönetimi", name:"Churn riski yükseldi → risk seviyesini belirle → uygun müdahaleyi uygula → toparla veya izle", purpose:"Yükselen churn riskine tek bir genel retention kampanyasıyla değil, risk seviyesine ve olası nedene göre kademeli aksiyonlarla yanıt vermek.", reusableRule:"Risk sinyali güçlendikçe müdahale daha doğrudan ve sorunun olası nedenine daha yakın olmalı.", entityScope:"Müşteri ilişkisi", entityNote:"Journey, churn riski yüksek kaldığı sürece müşteri ilişkisindeki sinyalleri ve toparlanmayı takip eder.", guardrails:["Kullanım veya satın alma davranışı toparlandığında journey'yi sonlandır.","Son müdahaleyi mümkün olduğunca gerçek churn nedenine göre seç."] }
  },
  "RET-31": {
    en:{ shortName:"Predicted Replenishment", name:"Predicted need → reminder → subscription or repurchase → exit", purpose:"Remind users before a repeat-use product is likely to run out, while clearly treating the timing as a prediction.", reusableRule:"Predicted replenishment works only when the prediction is reliable enough to be useful.", entityScope:"Repeat-purchase product", entityNote:"The journey follows one product the customer is expected to need again.", guardrails:["Do not message when prediction confidence is too low.","Stop when the item is repurchased."] },
    tr:{ shortName:"Tahmini Yenileme Hatırlatması", name:"Tahmini ihtiyaç → hatırlatma → abonelik veya yeniden satın alma → çıkış", purpose:"Düzenli tüketilen bir ürünün tahminen bitmesine yakın kullanıcıyı hatırlatmak; zamanlamanın bir tahmin olduğunu açık tutmak.", reusableRule:"Tahmini yenileme yalnızca tahmin yeterince güvenilir olduğunda çalıştırılmalıdır.", entityScope:"Tekrar satın alınan ürün", entityNote:"Akış, müşterinin yeniden ihtiyaç duyması beklenen tek ürünü takip eder.", guardrails:["Tahmin güvenilir değilse iletişim başlatma.","Ürün yeniden satın alındığında akışı durdur."] },
  },
  "RET-32": {
    en:{ shortName:"Lapsed Customer Win-Back", name:"Paid relationship ended → 30 days → value update → offer → return or exit", purpose:"Bring back a former paying customer after enough time has passed for a meaningful reason to return.", reusableRule:"Win-back should show what changed before it reaches for a discount.", entityScope:"Former customer", entityNote:"The journey follows a previously paid relationship that has already ended.", guardrails:["Do not run while the original cancellation window is still active.","Stop when the customer returns."] },
    tr:{ shortName:"Eski Müşteriyi Geri Kazanma", name:"Ücretli ilişki bitti → 30 gün → yenilikleri anlat → teklif → geri dönüş veya çıkış", purpose:"Ücretli ilişkisi sona ermiş müşteriyi, geri dönmesi için anlamlı bir neden oluştuğunda yeniden kazanmak.", reusableRule:"Geri kazanım önce 'ne değişti'yi anlatmalı; indirime hemen başlamamalıdır.", entityScope:"Eski müşteri", entityNote:"Akış, sona ermiş eski ücretli müşteri ilişkisini takip eder.", guardrails:["İptal süreci hâlâ devam ederken geri kazanım başlatma.","Müşteri geri döndüğünde akışı durdur."] },
  },
  "CON-272": {
    en:{ shortName:"Permission Recovery", name:"One channel permission closes → ask through another open channel → reopen or stop", purpose:"Recover a closed email or SMS permission by asking through the other channel that is still legitimately available.", reusableRule:"Never ask a closed channel to reopen itself.", entityScope:"Communication permission", entityNote:"The journey follows email and SMS marketing permission state for one person.", guardrails:["If both channels are closed, do not contact.","Only use an already-open channel to request the change."] },
    tr:{ shortName:"İletişim İzni Kurtarma", name:"Bir kanal izni kapandı → açık kanaldan sor → yeniden aç veya dur", purpose:"Kapanan e-posta veya SMS iznini, hâlâ açık olan diğer kanaldan izinli şekilde yeniden kazanmak.", reusableRule:"Kapalı bir kanala, kendisini yeniden açması için mesaj gönderilmez.", entityScope:"İletişim izni", entityNote:"Akış, tek kişinin e-posta ve SMS pazarlama izinlerini takip eder.", guardrails:["İki kanal da kapalıysa iletişim kurma.","İzin değişikliği istemek için yalnızca hâlihazırda açık olan kanalı kullan."] },
  },
  "RET-290": {
    en:{ shortName:"First-to-Second Purchase", name:"First purchase → natural repeat cycle → offer → second purchase or exit", purpose:"Turn a first-time buyer into a repeat customer around the natural time they are likely to need another purchase.", reusableRule:"The timing should follow the product's repeat-purchase cycle, not an arbitrary campaign calendar.", entityScope:"First-time buyer", entityNote:"The journey starts from the customer's first completed purchase.", guardrails:["Stop after the second purchase.","Keep the offer relevant to the first order or category."] },
    tr:{ shortName:"İlk Alışverişten İkinciye", name:"İlk satın alma → doğal tekrar süresi → teklif → ikinci satın alma veya çıkış", purpose:"İlk kez satın alan müşteriyi, ürünün doğal tekrar satın alma zamanında ikinci alışverişe taşımak.", reusableRule:"Zamanlama kampanya takvimine değil, ürünün doğal tekrar satın alma döngüsüne dayanmalıdır.", entityScope:"İlk kez satın alan müşteri", entityNote:"Akış müşterinin ilk tamamlanmış satın almasıyla başlar.", guardrails:["İkinci satın alma gerçekleştiğinde akışı durdur.","Teklifi ilk sipariş veya kategoriyle ilgili tut."] },
  },
  "RET-292": {
    en:{ shortName:"First Purchase Anniversary", name:"First-purchase anniversary → eligibility check → celebrate or exit", purpose:"Acknowledge the anniversary of a customer's first purchase with a single lightweight message.", reusableRule:"An anniversary message should recognise a real date, not invent a reward or status that does not exist.", entityScope:"Customer anniversary", entityNote:"The journey is tied to the date of the customer's first completed purchase.", guardrails:["Send at most once per anniversary period.","Do not imply a reward unless one actually exists."] },
    tr:{ shortName:"İlk Satın Alma Yıl Dönümü", name:"İlk satın alma yıl dönümü → uygunluk kontrolü → kutla veya çık", purpose:"Müşterinin ilk satın alma yıl dönümünü tek ve hafif bir mesajla hatırlamak.", reusableRule:"Yıl dönümü mesajı gerçek bir tarihi kutlamalı; olmayan ödül veya statü uydurmamalıdır.", entityScope:"Müşteri yıl dönümü", entityNote:"Akış müşterinin ilk tamamlanmış satın alma tarihine bağlıdır.", guardrails:["Her yıl dönümü döneminde en fazla bir kez gönder.","Gerçekte yoksa ödül varmış gibi yazma."] },
  },
  "RET-294": {
    en:{ shortName:"Cross-Sell / Complementary Offer", name:"Main product purchased → push → email → WhatsApp → complementary purchase or exit", purpose:"Offer a genuinely complementary product after the main purchase has had time to become useful.", reusableRule:"Cross-sell should explain why the second product complements the first, not simply push another item.", entityScope:"Purchased product", entityNote:"The journey links one purchased product to one relevant complementary offer.", guardrails:["Do not offer an item the customer already owns.","Stop immediately when the complementary product is purchased."] },
    tr:{ shortName:"Çapraz Satış / Tamamlayıcı Teklif", name:"Ana ürün alındı → push → e-posta → WhatsApp → tamamlayıcı satın alma veya çıkış", purpose:"Ana ürün kullanılmaya başladıktan sonra, gerçekten tamamlayıcı olan ürün veya hizmeti kademeli kanallarla teklif etmek.", reusableRule:"Çapraz satış, rastgele ikinci ürün satmak değil; ilk ürünü gerçekten tamamlayan şeyi anlatmaktır.", entityScope:"Satın alınan ana ürün", entityNote:"Akış tek bir ana ürünü ilgili tamamlayıcı teklif ile eşleştirir.", guardrails:["Müşterinin zaten sahip olduğu tamamlayıcı ürünü teklif etme.","Tamamlayıcı ürün alındığında akışı durdur."] },
  },
  "RET-295": {
    en:{ shortName:"Birthday & Milestone", name:"Birthday or milestone reached → eligibility check → acknowledge or exit", purpose:"Recognise a defined birthday or customer milestone with one relevant message.", reusableRule:"Milestone communication should be tied to a real, defined event.", entityScope:"Customer milestone", entityNote:"The journey follows one configured birthday or relationship milestone.", guardrails:["Do not fabricate a milestone or benefit.","Send once for each defined milestone occurrence."] },
    tr:{ shortName:"Doğum Günü & Dönüm Noktası", name:"Doğum günü / dönüm noktası geldi → uygunluk kontrolü → kutla veya çık", purpose:"Tanımlı bir doğum günü veya müşteri dönüm noktasını tek ve ilgili bir mesajla kutlamak.", reusableRule:"Dönüm noktası iletişimi gerçek ve tanımlı bir olaya dayanmalıdır.", entityScope:"Müşteri dönüm noktası", entityNote:"Akış tanımlı bir doğum günü veya ilişki dönüm noktasını takip eder.", guardrails:["Olmayan bir dönüm noktası veya fayda uydurma.","Her tanımlı olay için en fazla bir kez gönder."] },
  },
  "CON-300": {
    en:{ shortName:"Unengaged Subscriber Sunset", name:"No engagement → preference check → final campaign → reduce or stop marketing", purpose:"Reduce or stop non-essential marketing when a subscriber repeatedly ignores messages, while giving them a clear preference choice first.", reusableRule:"Silence should reduce pressure, not trigger more and more campaigns.", entityScope:"Marketing subscriber", entityNote:"The journey follows a person's engagement with non-essential marketing.", guardrails:["Keep service and mandatory messages separate from marketing suppression.","Respect any preference change immediately."] },
    tr:{ shortName:"Yanıt Vermeyen Aboneyi Sonlandırma", name:"Etkileşim yok → tercih kontrolü → son kampanya → pazarlamayı azalt veya durdur", purpose:"Pazarlama mesajlarına uzun süre yanıt vermeyen kişide iletişim baskısını azaltmak veya durdurmak; önce açık bir tercih seçeneği sunmak.", reusableRule:"Sessizlik daha fazla kampanya nedeni değil, iletişim baskısını azaltma sinyalidir.", entityScope:"Pazarlama abonesi", entityNote:"Akış kişinin zorunlu olmayan pazarlama iletişimleriyle etkileşimini takip eder.", guardrails:["Servis ve zorunlu mesajları pazarlama baskılamasından ayrı tut.","Tercih değişikliğini anında uygula."] },
  },
  "FBK-41": {
    en:{ shortName:"Feedback Request", name:"Experience completed → choose channel → ask → route by score", purpose:"Ask for feedback at the right moment and route the response differently for high, medium and low satisfaction.", reusableRule:"Ask only after the experience is complete and no unresolved issue should take priority.", entityScope:"Completed experience", entityNote:"The journey is tied to one completed purchase, delivery, onboarding or service experience.", guardrails:["Do not ask while an open complaint or unresolved issue exists.","Use only one eligible channel path at a time."] },
    tr:{ shortName:"Geri Bildirim Talebi", name:"Deneyim tamamlandı → kanal seç → geri bildirim iste → skora göre yönlendir", purpose:"Geri bildirimi doğru anda istemek ve yüksek, orta, düşük memnuniyeti farklı aksiyonlara yönlendirmek.", reusableRule:"Deneyim gerçekten bitmeden ve açık sorun varken geri bildirim isteme.", entityScope:"Tamamlanan deneyim", entityNote:"Akış tek bir satın alma, teslimat, onboarding veya servis deneyimine bağlıdır.", guardrails:["Açık şikâyet veya çözülmemiş sorun varsa soru sorma.","Aynı anda yalnızca bir uygun kanal yolunu kullan."] },
  },
  "FBK-43": {
    en:{ shortName:"Feedback Follow-Up", name:"Feedback received → classify → route → track promise → close", purpose:"Route feedback to the team or process that can act on it, and keep the record open until any promised follow-up is actually completed.", reusableRule:"If you promise a response or action, the feedback record stays open until that promise is fulfilled.", entityScope:"Feedback record", entityNote:"One journey instance follows one feedback submission and any action promised because of it.", guardrails:["Do not create work for feedback that needs no action.","Escalate when a promised follow-up misses its SLA."] },
    tr:{ shortName:"Geri Bildirim Takibi", name:"Geri bildirim alındı → sınıflandır → yönlendir → verilen sözü takip et → kapat", purpose:"Geri bildirimi aksiyon alabilecek ekibe veya sürece ulaştırmak; kullanıcıya söz verilen aksiyon tamamlanana kadar kaydı açık tutmak.", reusableRule:"Kullanıcıya geri dönüş veya aksiyon sözü verildiyse, bu söz yerine gelmeden kayıt kapanmaz.", entityScope:"Geri bildirim kaydı", entityNote:"Her akış tek bir geri bildirimi ve ona bağlı verilen sözü takip eder.", guardrails:["Aksiyon gerektirmeyen geri bildirim için gereksiz iş yaratma.","Söz verilen aksiyon SLA'yı aşarsa eskale et."] },
  },
  "ACC-261": {
    en:{ shortName:"Payment Delay & Access Restriction", name:"Payment overdue → reminders → access restriction → restore or remain restricted", purpose:"Warn users before overdue payment affects access, then restore access as soon as payment is completed.", reusableRule:"Restriction should never arrive as a surprise when there was time to warn the customer first.", entityScope:"Overdue payment and access", entityNote:"The journey links one overdue obligation to the access it can affect.", guardrails:["Stop restriction messages once payment is completed.","Explain exactly how access can be restored."] },
    tr:{ shortName:"Ödeme Gecikmesi ve Erişim Kısıtı", name:"Ödeme gecikti → hatırlat → erişimi kısıtla → geri aç veya kısıtlı bırak", purpose:"Geciken ödemenin erişimi etkilemesinden önce kullanıcıyı uyarmak; ödeme tamamlandığında erişimi hızlıca geri açmak.", reusableRule:"Uyarı vermek için zaman varsa erişim kısıtı kullanıcıya sürpriz olmamalıdır.", entityScope:"Geciken ödeme ve erişim", entityNote:"Akış tek bir gecikmiş ödeme ile bu ödemenin etkileyebileceği erişimi birlikte takip eder.", guardrails:["Ödeme tamamlanınca kısıtlama mesajlarını durdur.","Erişimin nasıl geri açılacağını net şekilde belirt."] },
  },
  "REL-284": {
    en:{ shortName:"Referral Reward", name:"Referral code created → wait → reward confirmation or sharing reminder", purpose:"Follow up after a user receives a referral code, rewarding successful use and nudging sharing only when the code is still unused.", reusableRule:"Referral communication should follow the real code state: used means reward, unused means sharing reminder.", entityScope:"Referral code", entityNote:"The journey follows one referral code and its use status.", guardrails:["Do not send a sharing reminder after the code is used.","Only promise the reward that is actually configured."] },
    tr:{ shortName:"Arkadaş Daveti Ödülü", name:"Davet kodu oluştu → bekle → ödül onayı veya paylaşım hatırlatması", purpose:"Davet kodu alan kullanıcıyı takip etmek; kod kullanıldıysa ödülü bildirmek, kullanılmadıysa paylaşımı hatırlatmak.", reusableRule:"Arkadaş daveti mesajı gerçek kod durumuna göre değişir: kullanıldıysa ödül, kullanılmadıysa paylaşım hatırlatması.", entityScope:"Davet kodu", entityNote:"Akış tek bir davet kodunu ve kullanım durumunu takip eder.", guardrails:["Kod kullanıldıktan sonra paylaşım hatırlatması gönderme.","Yalnızca gerçekten tanımlı ödülü vaat et."] },
  },
  "FIN-134": {
    en:{ shortName:"Payment Failure Recovery", name:"Payment failed → classify reason → recover → paid or exit", purpose:"Recover a failed payment with the right action and channel for the failure reason, instead of sending the same generic message every time.", reusableRule:"Never guess why a payment failed; act on the reason the payment system actually reports.", entityScope:"Payment attempt", entityNote:"The journey follows one failed payment and the obligation it was trying to settle.", guardrails:["Stop immediately when payment succeeds.","Do not expose internal risk or decline codes to the customer."] },
    tr:{ shortName:"Ödeme Başarısızlığından Kurtarma", name:"Ödeme başarısız → nedeni sınıflandır → kurtar → ödeme veya çıkış", purpose:"Başarısız ödemeyi gerçek hata nedenine göre doğru aksiyon ve kanalla kurtarmak; her durumda aynı genel mesajı göndermemek.", reusableRule:"Ödemenin neden başarısız olduğunu tahmin etme; ödeme sisteminin gerçekten bildirdiği nedene göre hareket et.", entityScope:"Ödeme denemesi", entityNote:"Akış tek bir başarısız ödeme denemesini ve kapatmaya çalıştığı borcu takip eder.", guardrails:["Ödeme başarılı olduğunda akışı hemen durdur.","Müşteriye dahili risk veya ret kodlarını gösterme."] },
  },
  "FIN-302": {
    en:{ shortName:"Refund Recovery", name:"Refund approved → refund completes → alternatives → repurchase or exit", purpose:"Keep the customer informed through the refund and, once it is complete, help them find a better alternative rather than ending the relationship at the refund.", reusableRule:"Do not start a recovery offer before the refund itself is complete.", entityScope:"Refunded purchase", entityNote:"The journey follows one refunded order and the customer's return-to-purchase behaviour afterward.", guardrails:["Separate refund status from the later commercial recovery.","Stop when the customer repurchases."] },
    tr:{ shortName:"İade Sonrası Geri Kazanım", name:"İade onaylandı → iade tamamlandı → alternatif öner → yeniden satın alma veya çıkış", purpose:"İade sürecinde kullanıcıyı bilgilendirmek; iade tamamlandıktan sonra daha uygun alternatiflerle ilişkiyi yeniden kurmaya çalışmak.", reusableRule:"İade tamamlanmadan geri kazanım teklifi başlatma.", entityScope:"İade edilen satın alma", entityNote:"Akış tek bir iade edilen siparişi ve sonrasındaki yeniden satın alma davranışını takip eder.", guardrails:["İade durumu ile ticari geri kazanımı birbirinden ayır.","Kullanıcı yeniden satın aldığında akışı durdur."] },
  },
  "FUL-146": {
    en:{ shortName:"Delivery Delay Management", name:"Delay detected → update ETA → monitor → recovery options or exit", purpose:"Tell the customer about a delivery delay before they have to discover it themselves, and escalate only if the revised date is missed too.", reusableRule:"A delay message should say what is known now and update when the estimate changes.", entityScope:"Delivery", entityNote:"The journey follows one delivery and its latest expected date.", guardrails:["Do not invent a new ETA when none is known.","Stop once the delivery is completed."] },
    tr:{ shortName:"Teslimat Gecikmesi Yönetimi", name:"Gecikme tespit edildi → tarihi güncelle → takip et → alternatif çözüm veya çıkış", purpose:"Teslimat gecikmesini kullanıcı fark etmeden önce bildirmek; yeni tarih de aşılırsa alternatif teslimat veya destek seçeneklerine geçmek.", reusableRule:"Gecikme mesajı o anda bilinen gerçeği söylemeli; tahmin değişirse bilgi de güncellenmelidir.", entityScope:"Teslimat", entityNote:"Akış tek bir teslimatı ve güncel tahmini teslim tarihini takip eder.", guardrails:["Yeni tarih bilinmiyorsa uydurma.","Teslimat tamamlandığında akışı durdur."] },
  },
  "FUL-148": {
    en:{ shortName:"Failed Delivery Recovery", name:"Delivery failed → classify reason → reschedule or alternative → complete or escalate", purpose:"Recover a failed delivery differently depending on whether the issue is the address, customer availability, operations or an impossible delivery.", reusableRule:"The recovery path should match the actual failure reason.", entityScope:"Failed delivery attempt", entityNote:"The journey follows one failed delivery attempt and its next resolution path.", guardrails:["Do not keep retrying when delivery is impossible.","Stop once delivery succeeds."] },
    tr:{ shortName:"Başarısız Teslimat Kurtarma", name:"Teslimat başarısız → nedeni ayır → yeniden planla veya alternatif sun → tamamla veya eskale et", purpose:"Başarısız teslimatı adres, müşterinin evde olmaması, operasyon veya teslimatın mümkün olmaması gibi gerçek nedene göre kurtarmak.", reusableRule:"Kurtarma yolu, teslimatın gerçek başarısızlık nedenine göre seçilmelidir.", entityScope:"Başarısız teslimat denemesi", entityNote:"Akış tek bir başarısız teslimat denemesini ve sonraki çözüm yolunu takip eder.", guardrails:["Teslimat mümkün değilse tekrar tekrar aynı denemeyi yapma.","Teslimat başarıyla tamamlandığında akışı durdur."] },
  },
  "FUL-291": {
    en:{ shortName:"Post-Purchase Follow-Up", name:"Purchase completed → thank you → rating → review request or exit", purpose:"Follow up after purchase, check satisfaction and ask for a public review only when the customer's own rating is positive.", reusableRule:"A low rating is a recovery signal, not a moment to ask for a public review.", entityScope:"Completed purchase", entityNote:"The journey follows one completed purchase and the customer's first satisfaction signal.", guardrails:["Do not ask for a public review after a low rating.","Do not send follow-up before the purchase is complete."] },
    tr:{ shortName:"Satın Alma Sonrası Takip", name:"Satın alma tamamlandı → teşekkür → puanlama → yorum iste veya çık", purpose:"Satın alma sonrasında müşteriye dönmek, memnuniyetini ölçmek ve yalnızca olumlu puan verdiğinde yorum istemek.", reusableRule:"Düşük puan yorum isteme anı değil, çözüm sinyalidir.", entityScope:"Tamamlanan satın alma", entityNote:"Akış tek bir tamamlanmış satın alma ve müşterinin ilk memnuniyet sinyalini takip eder.", guardrails:["Düşük puan sonrası herkese açık yorum isteme.","Satın alma tamamlanmadan takip mesajı gönderme."] },
  },
  "REM-151": {
    en:{ shortName:"Post-Purchase Issue Resolution", name:"Issue reported → route by issue type → resolve → follow up or escalate", purpose:"Send a post-purchase problem straight to the right resolution path instead of making the customer repeat the same explanation.", reusableRule:"Classify the issue first; do not delay obvious resolution paths with a generic holding sequence.", entityScope:"Post-purchase issue", entityNote:"The journey follows one reported issue tied to a completed purchase or delivery.", guardrails:["Route damaged, technical and missing-delivery issues differently.","Escalate when the selected resolution misses its SLA."] },
    tr:{ shortName:"Satış Sonrası Sorun Çözümü", name:"Sorun bildirildi → sorun tipine göre yönlendir → çöz → takip et veya eskale et", purpose:"Satış sonrası sorunu doğrudan doğru çözüm yoluna aktarmak; kullanıcıya aynı problemi tekrar tekrar anlattırmamak.", reusableRule:"Önce sorun tipini ayır; açıkça belli olan çözüm yolunu genel bir bekleme akışıyla geciktirme.", entityScope:"Satış sonrası sorun", entityNote:"Akış tamamlanmış satın alma veya teslimata bağlı tek bir sorunu takip eder.", guardrails:["Hasarlı ürün, teknik sorun ve eksik teslimatı farklı çözüm yollarına aktar.","Seçilen çözüm SLA'yı aşarsa eskale et."] },
  },
  "SCH-266": {
    en:{ shortName:"Appointment Reminder", name:"Appointment approaching → readiness check → push → SMS → ready or exit", purpose:"Prepare the user for an upcoming appointment and catch missing documents or information before the last reminder.", reusableRule:"A reminder is more useful when it also checks whether the user is actually ready for the appointment.", entityScope:"Appointment", entityNote:"The journey follows one scheduled appointment.", guardrails:["Stop if the appointment is cancelled.","Use the final reminder for the actual appointment, not as a substitute for missing preparation."] },
    tr:{ shortName:"Randevu Hatırlatması", name:"Randevu yaklaşıyor → hazırlık kontrolü → push → SMS → hazır veya çık", purpose:"Yaklaşan randevuyu hatırlatmak ve son mesaja kalmadan eksik bilgi veya belgeleri tamamlatmak.", reusableRule:"İyi bir randevu hatırlatması yalnızca tarihi söylemez; kullanıcının gerçekten hazır olup olmadığını da kontrol eder.", entityScope:"Randevu", entityNote:"Akış tek bir planlanmış randevuyu takip eder.", guardrails:["Randevu iptal edildiyse mesajları durdur.","Eksik hazırlığı son randevu hatırlatmasının içine sıkıştırma."] },
  },
  "SCH-282": {
    en:{ shortName:"Availability Search Abandonment", name:"Availability searched → no booking → same slot, alternatives or waitlist", purpose:"Bring back someone who checked availability but did not book, using the live state of the requested slot.", reusableRule:"Availability recovery should respond to what is still bookable now.", entityScope:"Availability search", entityNote:"The journey follows one availability search and the requested time.", guardrails:["Do not advertise a slot that is no longer available.","Stop after booking."] },
    tr:{ shortName:"Müsaitlik Arama Terki", name:"Müsaitlik arandı → rezervasyon yok → aynı saat, alternatif veya bekleme listesi", purpose:"Müsaitlik arayıp rezervasyon yapmayan kullanıcıyı, aradığı saatin güncel durumuna göre geri getirmek.", reusableRule:"Müsaitlik kurtarma, o anda gerçekten rezervasyon yapılabilen seçeneklere göre çalışmalıdır.", entityScope:"Müsaitlik araması", entityNote:"Akış tek bir müsaitlik aramasını ve aranan zamanı takip eder.", guardrails:["Artık müsait olmayan saati müsaitmiş gibi gösterme.","Rezervasyon yapıldığında akışı durdur."] },
  },
  "SCH-303": {
    en:{ shortName:"Reservation Payment Reminder", name:"Reservation created → payment pending → reminders → confirm or release", purpose:"Protect a reservation while payment is pending, with reminders tied to the actual hold and payment deadline.", reusableRule:"Reservation payment reminders should count down to the real deadline, not manufacture urgency.", entityScope:"Reservation", entityNote:"The journey follows one reservation and its pending payment.", guardrails:["Stop when payment is completed.","Release the reservation when the real payment window expires."] },
    tr:{ shortName:"Rezervasyon Ödeme Hatırlatması", name:"Rezervasyon oluştu → ödeme bekliyor → hatırlat → onayla veya serbest bırak", purpose:"Ödemesi bekleyen rezervasyonu gerçek ödeme süresi içinde korumak ve son tarihe göre hatırlatmak.", reusableRule:"Rezervasyon ödeme hatırlatması gerçek son tarihe dayanmalı; yapay aciliyet üretmemelidir.", entityScope:"Rezervasyon", entityNote:"Akış tek bir rezervasyonu ve bekleyen ödemesini takip eder.", guardrails:["Ödeme tamamlandığında akışı durdur.","Gerçek ödeme süresi dolduğunda rezervasyonu serbest bırak."] },
  },
  "SUB-163": {
    en:{ shortName:"Renewal Reminder", name:"Renewal window → auto / manual path → renew, payment recovery or win-back", purpose:"Handle automatic and manual renewals differently, with the right reminders and downstream handoffs for each.", reusableRule:"Auto-renew and manual-renew customers should not receive the same journey.", entityScope:"Subscription renewal", entityNote:"The journey follows one subscription approaching its renewal date.", guardrails:["Send payment failures to Payment Failure Recovery.","If a manual renewal lapses, hand it to Win-Back instead of extending reminders forever."] },
    tr:{ shortName:"Yenileme Hatırlatması", name:"Yenileme dönemi → otomatik / manuel kol → yenileme, ödeme kurtarma veya geri kazanım", purpose:"Otomatik ve manuel yenilenen üyelikleri farklı akışlarla yönetmek; her birinde doğru hatırlatma ve devri yapmak.", reusableRule:"Otomatik yenilenen ve kullanıcının kendisinin yenilemesi gereken üyelikler aynı akışı almamalıdır.", entityScope:"Abonelik yenilemesi", entityNote:"Akış yenileme tarihi yaklaşan tek bir aboneliği takip eder.", guardrails:["Ödeme hatasını Ödeme Başarısızlığından Kurtarma akışına aktar.","Manuel yenileme sona erdiyse hatırlatmayı sonsuza uzatmak yerine geri kazanım akışına devret."] },
  },
  "SUB-262": {
    en:{ shortName:"Cancellation Confirmation", name:"Cancellation confirmed → access countdown → return offer → reactivate or exit", purpose:"Guide the customer from confirmed cancellation through the real access end date, then make one bounded return offer if they do not reactivate.", reusableRule:"Cancellation confirmation should make the access end date clear before any win-back offer begins.", entityScope:"Cancelled subscription", entityNote:"The journey follows one confirmed cancellation until access ends or the subscription is reactivated.", guardrails:["Stop immediately if the subscription is reactivated.","Do not start the return offer before access actually ends."] },
    tr:{ shortName:"İptal Onayı", name:"İptal onaylandı → erişim bitişi → geri dönüş teklifi → yeniden aktif veya çıkış", purpose:"İptal edilen üyeliği gerçek erişim bitişine kadar yönetmek; yeniden aktif olmadıysa sınırlı bir geri dönüş teklifi sunmak.", reusableRule:"Geri dönüş teklifi başlamadan önce kullanıcı erişimin ne zaman biteceğini net olarak bilmeli.", entityScope:"İptal edilen abonelik", entityNote:"Akış tek bir onaylanmış iptali, erişim bitene veya üyelik yeniden aktif olana kadar takip eder.", guardrails:["Üyelik yeniden aktif olduğunda akışı hemen durdur.","Erişim gerçekten bitmeden geri dönüş teklifine başlama."] },
  },
  "SUB-296": {
    en:{ shortName:"Loyalty Program Activation", name:"Join program → first earn → progress → first reward → first redemption", purpose:"Turn a new loyalty member into an active one by getting them from enrolment to their first earned points and first usable reward.", reusableRule:"Loyalty activation is complete when the member starts earning and using value, not when enrolment alone is recorded.", entityScope:"Loyalty membership", entityNote:"The journey follows one new loyalty membership through its first meaningful milestones.", guardrails:["Do not celebrate points or rewards before they exist.","Stop pushing first-earn prompts after the member has already earned."] },
    tr:{ shortName:"Sadakat Programı Aktivasyonu", name:"Programa katıl → ilk puan → ilerleme → ilk ödül → ilk kullanım", purpose:"Yeni sadakat üyesini yalnızca kayıtlı kullanıcı olmaktan çıkarıp ilk puanını kazanan ve ilk ödülünü kullanan aktif üyeye dönüştürmek.", reusableRule:"Sadakat aktivasyonu kayıt olmakla değil, üyenin değer kazanıp kullanmaya başlamasıyla tamamlanır.", entityScope:"Sadakat üyeliği", entityNote:"Akış yeni bir sadakat üyeliğini ilk anlamlı kazanım ve kullanım adımlarına kadar takip eder.", guardrails:["Puan veya ödül gerçekten oluşmadan varmış gibi kutlama yapma.","İlk puan kazanıldıktan sonra ilk kazanım hatırlatmalarını durdur."] },
  },
  "SUB-297": {
    en:{ shortName:"Unused Loyalty Reward", name:"Unused reward → push → email → use or expire", purpose:"Remind a loyalty member about a real, unused reward without turning it into an endless nurture cadence.", reusableRule:"The journey exists for one unused reward and ends when that reward is used or the reminder window closes.", entityScope:"Loyalty reward", entityNote:"The journey follows one usable, unredeemed reward.", guardrails:["Stop once the reward is used.","Use the reward's real expiry date when one exists."] },
    tr:{ shortName:"Kullanılmayan Sadakat Ödülü", name:"Kullanılmayan ödül → push → e-posta → kullan veya süreyi kapat", purpose:"Gerçekten kullanılabilir ama henüz kullanılmamış sadakat ödülünü sınırlı bir diziyle hatırlatmak.", reusableRule:"Bu akış tek bir kullanılmamış ödül içindir; ödül kullanıldığında veya hatırlatma penceresi kapandığında biter.", entityScope:"Sadakat ödülü", entityNote:"Akış tek bir kullanılabilir ve kullanılmamış ödülü takip eder.", guardrails:["Ödül kullanıldığında mesajları durdur.","Son kullanma tarihi varsa gerçek tarihi kullan."] },
  },
  "SUB-298": {
    en:{ shortName:"Reward Confirmation", name:"Wheel reward won → in-app confirmation → 3 days → use or reminder", purpose:"Confirm a concrete reward immediately, then send one reminder only if the reward code remains unused.", reusableRule:"Reward communication should reflect the exact reward that was actually won.", entityScope:"Earned reward", entityNote:"The journey follows one reward and its redemption code.", guardrails:["Do not send the reminder after redemption.","Do not invent a different value, expiry or benefit."] },
    tr:{ shortName:"Ödül Onayı", name:"Çark ödülü kazanıldı → uygulama içi onay → 3 gün → kullan veya hatırlat", purpose:"Kazanılan somut ödülü hemen göstermek; kod kullanılmadıysa yalnızca bir kez hatırlatmak.", reusableRule:"Ödül iletişimi kullanıcının gerçekten kazandığı ödülü aynen yansıtmalıdır.", entityScope:"Kazanılan ödül", entityNote:"Akış tek bir ödülü ve kullanım kodunu takip eder.", guardrails:["Kod kullanıldıysa hatırlatma gönderme.","Farklı tutar, son tarih veya fayda uydurma."] },
  },
  "SUB-299": {
    en:{ shortName:"Loyalty Tier Change", name:"Tier changes → upgrade celebration or downgrade recovery → exit", purpose:"Handle loyalty upgrades and downgrades differently: celebrate new benefits on the way up and offer a clear recovery path on the way down.", reusableRule:"An upgrade and a downgrade are different customer moments and should not share the same message.", entityScope:"Loyalty tier", entityNote:"The journey follows one change in a member's loyalty tier.", guardrails:["Do not present an old benefit as newly unlocked.","Use downgrade recovery only when there is a real path back to the higher tier."] },
    tr:{ shortName:"Sadakat Seviyesi Değişimi", name:"Seviye değişti → yükselişi kutla veya düşüşü geri kazan → çık", purpose:"Sadakat seviyesi yükselişini ve düşüşünü farklı yönetmek; yükselişte yeni avantajları anlatmak, düşüşte üst seviyeye dönüş yolunu göstermek.", reusableRule:"Seviye yükselişi ve düşüşü farklı müşteri anlarıdır; aynı mesajla yönetilmemelidir.", entityScope:"Sadakat seviyesi", entityNote:"Akış tek bir sadakat seviyesi değişimini takip eder.", guardrails:["Eski avantajı yeni açılmış gibi anlatma.","Üst seviyeye gerçek bir dönüş yolu yoksa seviye geri kazanım kampanyası yapma."] },
  },
  "DOC-214": {
    en:{ shortName:"Missing Document Follow-Up", name:"Document missing → email → push → final SMS → complete or manual follow-up", purpose:"Help a user complete missing documents before the application deadline, escalating only when the documents remain incomplete.", reusableRule:"Every reminder should say exactly what is missing and how to submit it.", entityScope:"Document requirement", entityNote:"The journey follows the missing documents for one application or process.", guardrails:["Stop when all required documents are received.","Do not silently close the process at the deadline without the intended handoff."] },
    tr:{ shortName:"Eksik Belge Takibi", name:"Belge eksik → e-posta → push → son SMS → tamamla veya manuel takip", purpose:"Başvuru veya süreçte eksik belgeleri son tarihten önce tamamlatmak; eksik kalırsa kontrollü şekilde manuel takibe aktarmak.", reusableRule:"Her hatırlatma hangi belgenin eksik olduğunu ve nasıl gönderileceğini açıkça söylemelidir.", entityScope:"Belge gerekliliği", entityNote:"Akış tek bir başvuru veya sürecin eksik belgelerini takip eder.", guardrails:["Tüm belgeler geldiğinde akışı durdur.","Son tarihte süreci sessizce kapatmak yerine tanımlı manuel takibe aktar."] },
  },
  "RLT-279": {
    en:{ shortName:"Upgrade Completion Reminder", name:"Upgrade started → missing step → email → push → complete or exit", purpose:"Bring a user back to an upgrade they started but did not finish, pointing them directly to the missing step.", reusableRule:"A completion reminder should name the one thing still blocking the upgrade.", entityScope:"Upgrade attempt", entityNote:"The journey follows one upgrade attempt until it completes or the reminder sequence ends.", guardrails:["Stop once the upgrade completes.","Do not keep reminding after the upgrade is no longer valid."] },
    tr:{ shortName:"Yükseltme Tamamlama Hatırlatması", name:"Yükseltme başladı → eksik adım → e-posta → push → tamamla veya çık", purpose:"Başlayıp tamamlanmayan yükseltmeyi, eksik kalan adıma doğrudan yönlendirerek tamamlatmak.", reusableRule:"Tamamlama hatırlatması, yükseltmenin önünde kalan tek somut adımı açıkça göstermelidir.", entityScope:"Yükseltme denemesi", entityNote:"Akış tek bir yükseltme girişimini tamamlanana veya hatırlatma dizisi bitene kadar takip eder.", guardrails:["Yükseltme tamamlandığında akışı durdur.","Yükseltme artık geçerli değilse hatırlatmayı sürdürme."] },
  },
  "RSK-273": {
    en:{ shortName:"Usage Limit Management", name:"Limit reached → explain options → alternative, upgrade or reset → exit", purpose:"Help a user who hits a usage limit understand what happened and the fastest legitimate way to continue.", reusableRule:"A limit message should explain the limit, reset timing and available options without blaming the user.", entityScope:"Usage limit", entityNote:"The journey follows one limit event and the available path to continue.", guardrails:["Do not invent a reset time or upgrade path.","If a free alternative fully solves the problem, show it before upsell."] },
    tr:{ shortName:"Kullanım Limiti Yönetimi", name:"Limite ulaşıldı → seçenekleri açıkla → alternatif, yükseltme veya yenilenme → çık", purpose:"Kullanım limitine takılan kullanıcıya ne olduğunu ve devam edebileceği en hızlı geçerli yolu göstermek.", reusableRule:"Limit mesajı kullanıcıyı suçlamadan limiti, yenilenme zamanını ve gerçek seçenekleri anlatmalıdır.", entityScope:"Kullanım limiti", entityNote:"Akış tek bir limit olayını ve devam etmek için mevcut yolları takip eder.", guardrails:["Yenilenme zamanı veya paket seçeneği yoksa uydurma.","Ücretsiz bir alternatif ihtiyacı tamamen karşılıyorsa önce onu göster."] },
  },
};

export function publicJourneyCopy(id: string, lang: "en" | "tr"): PublicJourneyCopy | null {
  return COPY[id]?.[lang] ?? null;
}

export const PUBLIC_JOURNEY_COPY_IDS = new Set(Object.keys(COPY));
