import type { Lang } from "@/lib/content";

export type PractitionerJourneyNotes = {
  trigger: string;
  eligibility: readonly string[];
  kpis: readonly string[];
};

const NOTES: Readonly<Record<string, Readonly<Record<Lang, PractitionerJourneyNotes>>>> = {
  "ACQ-09": {
    tr: {
      trigger: "Aday müşteri oluşması veya teklif talebinin alınması.",
      eligibility: [
        "Ürün veya hizmete ilgi göstermiş ancak henüz satın almaya hazır olmayan adaylar.",
        "İletişim izni bulunan ve satış / satın alma sürecine henüz geçmemiş adaylar.",
      ],
      kpis: [
        "Yeniden etkileşim oranı",
        "Satış / conversion sürecine aktarım oranı",
        "Journey kaynaklı dönüşüm oranı",
      ],
    },
    en: {
      trigger: "A lead is captured or a quote request is received.",
      eligibility: [
        "Leads who have shown interest in the product or service but are not yet ready to buy.",
        "Leads who can be contacted and have not yet entered the sales / purchase path.",
      ],
      kpis: [
        "Re-engagement rate",
        "Sales / conversion handoff rate",
        "Journey-attributed conversion rate",
      ],
    },
  },
  "ACQ-01": { tr:{trigger:"Anonim profilde anlamlı yüksek niyet sinyalinin oluşması.",eligibility:["Kimliği henüz doğrulanmamış, güçlü davranış sinyali veren profiller."],kpis:["Kimlik doğrulama oranı","Uygun profile dönüşüm oranı"]}, en:{trigger:"Meaningful high-intent behaviour is detected on an anonymous profile.",eligibility:["Anonymous profiles showing meaningful high-intent behaviour."],kpis:["Identity resolution rate","Eligible-profile rate"]} },
  "ACQ-02": { tr:{trigger:"Birinci taraf ilgi sinyalinin alınması.",eligibility:["Açık bir talep veya ilgi sinyali bırakmış kişiler."],kpis:["Doğru hedefe yönlendirme oranı","Satış / nurture aktarım oranı"]}, en:{trigger:"A first-party interest signal is captured.",eligibility:["People who submitted an explicit request or interest signal."],kpis:["Correct-routing rate","Sales / nurture handoff rate"]} },
  "ACQ-03": { tr:{trigger:"Mevcut journey'den daha güçlü bir niyet sinyalinin oluşması.",eligibility:["Aktif düşük niyet journey'sinde bulunan ve güçlü yeni sinyal üreten kullanıcılar."],kpis:["Yüksek niyetli sürece aktarım oranı","Devir sonrası conversion oranı"]}, en:{trigger:"A stronger intent signal appears than the one that opened the current journey.",eligibility:["Users in a lower-intent journey who produce a stronger current signal."],kpis:["Higher-intent handoff rate","Post-handoff conversion rate"]} },
  "ACQ-04": { tr:{trigger:"Yüksek niyetli ticari aksiyonun alınması.",eligibility:["Ticari niyeti netleşmiş lead'ler."],kpis:["Doğru routing oranı","İnsan desteğine aktarım oranı"]}, en:{trigger:"A high-intent commercial action is recorded.",eligibility:["Leads with clear commercial intent."],kpis:["Correct-routing rate","Human-assistance handoff rate"]} },
  "ACQ-05": { tr:{trigger:"Lead veya hesabın nitelik durumunun değişmesi.",eligibility:["Nitelik durumu ve değişim nedeni kaydedilebilen lead veya hesaplar."],kpis:["Yeniden nitelendirme oranı","Doğru yönlendirme oranı"]}, en:{trigger:"A lead or account qualification state changes.",eligibility:["Leads or accounts with a recorded qualification state and reason."],kpis:["Requalification rate","Correct-routing rate"]} },
  "ACQ-06": { tr:{trigger:"Uygunluğu etkileyen temel verinin değişmesi.",eligibility:["Uygunluk kararı yeniden hesaplanabilen kullanıcı veya hesaplar."],kpis:["Uygunluk değişim oranı","Doğru engelleme / izin verme oranı"]}, en:{trigger:"Underlying data that affects eligibility changes.",eligibility:["Users or accounts whose eligibility can be recalculated."],kpis:["Eligibility-change rate","Correct allow / block rate"]} },
  "ACQ-07": { tr:{trigger:"Güçlü niyet sinyalinin tazelik penceresini aşması.",eligibility:["Yüksek niyet durumu aktif olup yeni güçlü sinyal üretmeyen kullanıcılar."],kpis:["Niyet düşürme oranı","Yeniden yükselme oranı"]}, en:{trigger:"A strong intent signal passes its freshness window.",eligibility:["Users with an active high-intent state but no new strong signal."],kpis:["Intent-downgrade rate","Re-escalation rate"]} },
  "ACQ-08": { tr:{trigger:"Yetkili ticari hedef olayının gerçekleşmesi.",eligibility:["Acquisition journey'sinde aktif olup hedefi tamamlayan kullanıcılar."],kpis:["Acquisition sonrası suppression oranı","Sonraki sürece devir oranı"]}, en:{trigger:"The authoritative commercial conversion event is recorded.",eligibility:["Users in an active acquisition journey who complete its goal."],kpis:["Post-conversion suppression rate","Next-stage handoff rate"]} },
  "ACQ-10": { tr:{trigger:"Ticari fırsatın açık bir ret veya kayıp sonucuyla kapanması.",eligibility:["Ret nedeni kaydedilmiş fırsatlar."],kpis:["Ret nedeni dağılımı","Yeniden giriş oranı"]}, en:{trigger:"A commercial opportunity closes with an explicit decline or loss outcome.",eligibility:["Opportunities with a recorded decline reason."],kpis:["Decline-reason distribution","Re-entry rate"]} },
  "ACQ-285": { tr:{trigger:"Yeni lead veya ilgi kaydının oluşması.",eligibility:["İlk teması henüz yapılmamış yeni lead'ler."],kpis:["İlk temas süresi","İlk temas etkileşim oranı"]}, en:{trigger:"A new lead or captured-interest record is created.",eligibility:["New leads that have not yet received a first response."],kpis:["Time to first response","First-touch engagement rate"]} },
  "ACT-11": { tr:{trigger:"Yeni hesap, trial, abonelik veya onboarding kaydının oluşması.",eligibility:["Onboarding rotası henüz belirlenmemiş yeni kullanıcı veya hesaplar."],kpis:["Onboarding başlama oranı","Doğru rota seçimi oranı"]}, en:{trigger:"A new account, trial, subscription or onboarding instance is recorded.",eligibility:["New users or accounts without an assigned onboarding route."],kpis:["Onboarding start rate","Correct-route rate"]} },
  "ACT-12": { tr:{trigger:"Kullanıcının onboarding içinde anlamlı bir adımı tamamlaması.",eligibility:["Onboarding'i devam eden kullanıcılar."],kpis:["Onboarding ilerleme oranı","Sonraki adım tamamlama oranı"]}, en:{trigger:"A user completes a meaningful onboarding step.",eligibility:["Users with onboarding still in progress."],kpis:["Onboarding progression rate","Next-step completion rate"]} },
  "ACT-13": { tr:{trigger:"Aktivasyon ilerlemesinin durması veya belirli bir blocker oluşması.",eligibility:["Aktivasyon hedefine henüz ulaşmamış kullanıcılar."],kpis:["Blocker çözüm oranı","Aktivasyona dönüş oranı"]}, en:{trigger:"Activation progress stalls or a specific blocker is detected.",eligibility:["Users who have not yet reached activation."],kpis:["Blocker-resolution rate","Recovery-to-activation rate"]} },
  "ACT-16": { tr:{trigger:"Ürünün yetkili aktivasyon olayının gerçekleşmesi.",eligibility:["Onboarding'i aktif olan ve temel değer anına ulaşan kullanıcılar."],kpis:["Onboarding kapanış oranı","Adoption sürecine aktarım oranı"]}, en:{trigger:"The product's authoritative activation event is recorded.",eligibility:["Users in active onboarding who reach the core value moment."],kpis:["Onboarding close rate","Adoption handoff rate"]} },
  "ACT-18": { tr:{trigger:"Tekrarlanan değer davranışının belirgin biçimde yavaşlaması veya durması.",eligibility:["Daha önce aktivasyon ve tekrar kullanım göstermiş kullanıcılar."],kpis:["Sağlıklı kullanıma dönüş oranı","Re-engagement oranı"]}, en:{trigger:"Repeat value-producing behaviour slows materially or stops.",eligibility:["Users who previously activated and showed repeat use."],kpis:["Healthy-usage recovery rate","Re-engagement rate"]} },
  "RET-31": { tr:{trigger:"Tahmini yeniden satın alma zamanının yaklaşması.",eligibility:["Tekrar satın alma ihtiyacı güvenilir biçimde tahmin edilebilen müşteriler."],kpis:["Yeniden satın alma oranı"]}, en:{trigger:"The predicted replenishment window approaches.",eligibility:["Customers whose repeat-purchase timing can be predicted reliably."],kpis:["Repurchase rate"]} },
  "RET-32": { tr:{trigger:"Müşteri ilişkisinin sona ermesi ve win-back penceresinin açılması.",eligibility:["Ücretli ilişkisi sona ermiş ve geri dönüş için anlamlı bir neden sunulabilen eski müşteriler."],kpis:["Geri kazanım oranı"]}, en:{trigger:"A former customer reaches the defined win-back window.",eligibility:["Former paying customers with a meaningful reason to return."],kpis:["Win-back conversion rate"]} },
  "CON-272": { tr:{trigger:"Bir iletişim kanalının izninin kapanması.",eligibility:["Başka bir izinli kanal veya aktif oturum üzerinden ulaşılabilen kişiler."],kpis:["İzin yeniden açma oranı"]}, en:{trigger:"Permission closes on one communication channel.",eligibility:["People reachable through another permitted channel or active session."],kpis:["Permission recovery rate"]} },
  "RET-290": { tr:{trigger:"İlk satın almanın tamamlanması.",eligibility:["Doğal tekrar satın alma döngüsü bulunan ilk kez satın alan müşteriler."],kpis:["İkinci satın alma oranı"]}, en:{trigger:"A customer's first purchase is completed.",eligibility:["First-time buyers with a meaningful repeat-purchase cycle."],kpis:["Second-purchase rate"]} },
  "RET-292": { tr:{trigger:"İlk satın alma yıl dönümünün yaklaşması.",eligibility:["İlk satın alma tarihi doğrulanmış aktif müşteriler."],kpis:["Mesaj etkileşim oranı"]}, en:{trigger:"The anniversary of the first purchase approaches.",eligibility:["Active customers with a verified first-purchase date."],kpis:["Message engagement rate"]} },
  "RET-294": { tr:{trigger:"Ana ürün satın alındıktan sonra tamamlayıcı teklif penceresinin açılması.",eligibility:["Gerçekten ilgili bir tamamlayıcı ürüne uygun müşteriler."],kpis:["Tamamlayıcı ürün conversion oranı"]}, en:{trigger:"The complementary-offer window opens after the main purchase.",eligibility:["Customers eligible for a genuinely complementary product."],kpis:["Complementary-product conversion rate"]} },
  "RET-295": { tr:{trigger:"Tanımlı doğum günü veya müşteri dönüm noktasının gelmesi.",eligibility:["Olay tarihi doğrulanmış ve iletişime uygun müşteriler."],kpis:["Milestone mesaj etkileşim oranı"]}, en:{trigger:"A defined birthday or customer milestone occurs.",eligibility:["Contactable customers with a verified milestone date."],kpis:["Milestone-message engagement rate"]} },
  "CON-300": { tr:{trigger:"Pazarlama iletişiminde tanımlı süre boyunca etkileşim görülmemesi.",eligibility:["İzni açık ancak pazarlama mesajlarına uzun süredir yanıt vermeyen kişiler."],kpis:["Tercih güncelleme oranı"]}, en:{trigger:"No marketing engagement is recorded for the defined period.",eligibility:["Permitted subscribers with sustained non-engagement."],kpis:["Preference-update rate"]} },
  "FBK-41": { tr:{trigger:"Satın alma, teslimat, onboarding veya hizmet deneyiminin tamamlanması.",eligibility:["Açık şikâyeti veya çözülmemiş sorunu olmayan müşteriler."],kpis:["Geri bildirim yanıtlama oranı"]}, en:{trigger:"A purchase, delivery, onboarding or service experience is completed.",eligibility:["Customers without an open complaint or unresolved issue."],kpis:["Feedback response rate"]} },
  "FBK-43": { tr:{trigger:"Müşteri geri bildiriminin alınması.",eligibility:["Aksiyon veya takip gerektiren geri bildirim kayıtları."],kpis:["Söz verilen aksiyon tamamlama oranı"]}, en:{trigger:"Customer feedback is received.",eligibility:["Feedback records that require action or follow-up."],kpis:["Promised-action completion rate"]} },
  "ACC-261": { tr:{trigger:"Geciken ödemenin erişimi etkileyecek seviyeye gelmesi.",eligibility:["Ödemesi gecikmiş ve erişim etkisi açıkça tanımlı müşteriler."],kpis:["Ödeme kurtarma oranı"]}, en:{trigger:"An overdue payment reaches the point where access may be affected.",eligibility:["Customers with an overdue payment and a defined access consequence."],kpis:["Payment recovery rate"]} },
  "REL-284": { tr:{trigger:"Davet kodunun oluşturulması.",eligibility:["Aktif ve geçerli davet koduna sahip kullanıcılar."],kpis:["Davet kodu kullanım oranı"]}, en:{trigger:"A referral code is created.",eligibility:["Users with an active, valid referral code."],kpis:["Referral-code usage rate"]} },
  "FIN-134": { tr:{trigger:"Ödeme denemesinin başarısız olması.",eligibility:["Hata nedeni ödeme sisteminden alınabilen başarısız ödeme denemeleri."],kpis:["Ödeme kurtarma oranı"]}, en:{trigger:"A payment attempt fails.",eligibility:["Failed payment attempts with a known system-reported reason."],kpis:["Payment recovery rate"]} },
  "FIN-302": { tr:{trigger:"İadenin tamamlanması.",eligibility:["İadesi tamamlanmış ve yeniden satın almaya uygun müşteriler."],kpis:["İade sonrası yeniden satın alma oranı"]}, en:{trigger:"A refund is completed.",eligibility:["Refunded customers eligible for a relevant next purchase."],kpis:["Post-refund repurchase rate"]} },
  "FUL-146": { tr:{trigger:"Teslimat gecikmesinin doğrulanması.",eligibility:["Güncel teslimat durumu ve ETA bilgisi izlenebilen siparişler."],kpis:["Gecikme sonrası teslimat tamamlama oranı"]}, en:{trigger:"A delivery delay is confirmed.",eligibility:["Orders with trackable delivery status and ETA."],kpis:["Post-delay delivery completion rate"]} },
  "FUL-148": { tr:{trigger:"Teslimat denemesinin başarısız olması.",eligibility:["Başarısızlık nedeni bilinen teslimat denemeleri."],kpis:["Başarılı yeniden teslimat oranı"]}, en:{trigger:"A delivery attempt fails.",eligibility:["Failed delivery attempts with a known reason."],kpis:["Successful redelivery rate"]} },
  "FUL-291": { tr:{trigger:"Satın alma ve ilgili teslimat / kullanım anının tamamlanması.",eligibility:["İlk memnuniyet sinyali istenebilecek müşteriler."],kpis:["Puanlama yanıtlama oranı"]}, en:{trigger:"The purchase and relevant delivery or use moment are complete.",eligibility:["Customers eligible for an initial satisfaction check."],kpis:["Rating response rate"]} },
  "REM-151": { tr:{trigger:"Satış sonrası sorunun bildirilmesi.",eligibility:["Sorun tipi sınıflandırılabilen tamamlanmış satın alma veya teslimatlar."],kpis:["Sorun çözüm oranı"]}, en:{trigger:"A post-purchase issue is reported.",eligibility:["Completed purchases or deliveries with a classifiable issue."],kpis:["Issue resolution rate"]} },
  "SCH-266": { tr:{trigger:"Randevunun hatırlatma penceresine girmesi.",eligibility:["Aktif ve iptal edilmemiş randevular."],kpis:["Randevuya katılım oranı"]}, en:{trigger:"An appointment enters its reminder window.",eligibility:["Active, non-cancelled appointments."],kpis:["Appointment attendance rate"]} },
  "SCH-282": { tr:{trigger:"Müsaitlik aranıp rezervasyon yapılmadan çıkılması.",eligibility:["Aranan zaman veya alternatifleri hâlâ değerlendirilebilir kullanıcılar."],kpis:["Rezervasyona dönüş oranı"]}, en:{trigger:"A user searches availability but leaves without booking.",eligibility:["Users whose requested time or alternatives can still be evaluated."],kpis:["Booking recovery rate"]} },
  "SCH-303": { tr:{trigger:"Rezervasyon oluşturulup ödemenin beklemede kalması.",eligibility:["Gerçek ödeme süresi devam eden rezervasyonlar."],kpis:["Ödeme tamamlama oranı"]}, en:{trigger:"A reservation is created with payment still pending.",eligibility:["Reservations still within the real payment window."],kpis:["Payment completion rate"]} },
  "SUB-163": { tr:{trigger:"Aboneliğin yenileme penceresine girmesi.",eligibility:["Yenileme yöntemi ve tarihi bilinen aktif abonelikler."],kpis:["Yenileme oranı"]}, en:{trigger:"A subscription enters its renewal window.",eligibility:["Active subscriptions with a known renewal method and date."],kpis:["Renewal rate"]} },
  "SUB-262": { tr:{trigger:"Abonelik iptalinin onaylanması.",eligibility:["Erişim bitiş tarihi bilinen iptal edilmiş abonelikler."],kpis:["Yeniden aktivasyon oranı"]}, en:{trigger:"A subscription cancellation is confirmed.",eligibility:["Cancelled subscriptions with a known access end date."],kpis:["Reactivation rate"]} },
  "SUB-296": { tr:{trigger:"Sadakat programına yeni üyelik oluşturulması.",eligibility:["İlk kazanımını henüz yapmamış yeni sadakat üyeleri."],kpis:["İlk puan kazanma oranı"]}, en:{trigger:"A new loyalty membership is created.",eligibility:["New loyalty members who have not yet earned value."],kpis:["First-earn rate"]} },
  "SUB-297": { tr:{trigger:"Kullanılabilir bir sadakat ödülünün kullanılmadan beklemesi.",eligibility:["Geçerli ve kullanılmamış ödülü bulunan üyeler."],kpis:["Ödül kullanım oranı"]}, en:{trigger:"A usable loyalty reward remains unredeemed.",eligibility:["Members with a valid, unused reward."],kpis:["Reward redemption rate"]} },
  "SUB-298": { tr:{trigger:"Somut bir ödülün kazanılması.",eligibility:["Kullanım kodu veya ödül kaydı oluşturulmuş kullanıcılar."],kpis:["Ödül kullanım oranı"]}, en:{trigger:"A concrete reward is earned.",eligibility:["Users with a recorded reward or redemption code."],kpis:["Reward redemption rate"]} },
  "SUB-299": { tr:{trigger:"Sadakat seviyesinin değişmesi.",eligibility:["Seviye değişimi ve yeni hakları doğrulanabilen üyeler."],kpis:["Seviye sonrası etkileşim oranı"]}, en:{trigger:"A loyalty tier changes.",eligibility:["Members with a verified tier change and benefit set."],kpis:["Post-tier-change engagement rate"]} },
  "DOC-214": { tr:{trigger:"Başvuru veya süreçte zorunlu belgenin eksik kalması.",eligibility:["Eksik belge ve son tarihi açıkça bilinen başvurular."],kpis:["Belge tamamlama oranı"]}, en:{trigger:"A required document is missing from an application or process.",eligibility:["Applications with a clearly identified missing document and deadline."],kpis:["Document completion rate"]} },
  "RLT-279": { tr:{trigger:"Yükseltme sürecinin eksik bir adımda kalması.",eligibility:["Yükseltmesi hâlâ geçerli ve eksik adımı belirlenebilen kullanıcılar."],kpis:["Yükseltme tamamlama oranı"]}, en:{trigger:"An upgrade stalls on an incomplete step.",eligibility:["Users with a still-valid upgrade and a known missing step."],kpis:["Upgrade completion rate"]} },
  "RSK-273": { tr:{trigger:"Kullanım limitine ulaşılması.",eligibility:["Limit, reset zamanı ve devam seçenekleri belirlenebilen kullanıcılar."],kpis:["Limit sonrası devam oranı"]}, en:{trigger:"A usage limit is reached.",eligibility:["Users with a known limit, reset timing and continuation options."],kpis:["Post-limit continuation rate"]} },

};

export function practitionerJourneyNotes(id: string, lang: Lang): PractitionerJourneyNotes | null {
  return NOTES[id]?.[lang] ?? null;
}
