export type PublicJourneyCopy = {
  shortName: string;
  name: string;
  purpose: string;
  reusableRule: string;
  entityScope: string;
  entityNote: string;
  guardrails: readonly string[];
};

type Pair = { en: PublicJourneyCopy; tr: PublicJourneyCopy };

const COPY: Readonly<Record<string, Pair>> = {
  "ACQ-09": {
    en: { shortName:"Lead Nurture", name:"Lead captured → educate → re-engage → sales or exit", purpose:"Help a lead who is interested but not yet ready to buy move forward with a short, channelled sequence that stops when intent changes.", reusableRule:"Nurture should react to what the lead does next, not run as an endless drip.", entityScope:"Lead", entityNote:"One journey instance follows one lead and the product or request that created it.", guardrails:["Stop as soon as the lead moves into a sales or purchase path.","Do not keep sending education after the lead stops showing interest."] },
    tr: { shortName:"Aday Müşteri Geliştirme", name:"Aday müşteri oluştu → bilgilendir → yeniden ilgiyi ölç → satışa aktar veya kapat", purpose:"İlgisi olan ama henüz satın almaya hazır olmayan adayı kısa ve kanallı bir akışla ilerletmek; niyet değiştiğinde akışı durdurmak.", reusableRule:"Aday geliştirme, sonsuz bir mesaj dizisi değil; kullanıcının bir sonraki davranışına göre ilerleyen sınırlı bir akıştır.", entityScope:"Aday müşteri", entityNote:"Her akış, tek bir aday müşteriyi ve o adayı oluşturan ürün ya da talebi takip eder.", guardrails:["Aday satış veya satın alma aşamasına geçtiğinde bu akışı durdur.","İlgi kalmadığında bilgilendirme mesajlarını sürdürme."] },
  },
  "ACQ-12": {
    en:{ shortName:"Saved Product Reminder", name:"Product saved → wait → remind → purchase, stock alert or exit", purpose:"Bring someone back to a product they deliberately saved, while stopping immediately if they buy it or it goes out of stock.", reusableRule:"A saved product is explicit interest, but it is not a purchase commitment.", entityScope:"Saved product", entityNote:"The journey follows one saved product for one user.", guardrails:["Never message after purchase.","If the product is unavailable, move to the back-in-stock journey instead of promoting it."] },
    tr:{ shortName:"Kaydedilen Ürün Hatırlatması", name:"Ürün kaydedildi → bekle → hatırlat → satın alma, stok takibi veya çıkış", purpose:"Kullanıcının özellikle kaydettiği ürüne geri dönmesini sağlamak; ürün satın alındığında veya stoktan çıktığında hatırlatmayı hemen durdurmak.", reusableRule:"Kaydedilen ürün net bir ilgi sinyalidir; satın alma sözü değildir.", entityScope:"Kaydedilen ürün", entityNote:"Akış, tek kullanıcı için tek bir kaydedilmiş ürünü takip eder.", guardrails:["Satın alma gerçekleştiyse bir daha mesaj gönderme.","Ürün stokta değilse tanıtım yapmak yerine stok bildirimi akışına aktar."] },
  },
  "ACQ-13": {
    en:{ shortName:"Browse Abandonment", name:"Repeated product views → wait → remind → cart, purchase or exit", purpose:"Bring back a user who repeatedly viewed the same product but did not add it to cart or buy it.", reusableRule:"Repeated product views can justify one reminder; they do not justify pretending the user already chose the product.", entityScope:"Viewed product", entityNote:"The journey is tied to the specific product that was viewed repeatedly.", guardrails:["Stop on purchase or add-to-cart.","Do not invent scarcity, discounts or reserved stock."] },
    tr:{ shortName:"Ürün İnceleme Sonrası Hatırlatma", name:"Aynı ürün tekrar görüntülendi → bekle → hatırlat → sepet, satın alma veya çıkış", purpose:"Aynı ürüne tekrar tekrar bakan ama sepete eklemeyen veya satın almayan kullanıcıyı tek bir anlamlı hatırlatmayla geri getirmek.", reusableRule:"Tekrarlanan ürün görüntüleme bir hatırlatma için yeterlidir; kullanıcının ürünü seçtiği anlamına gelmez.", entityScope:"İncelenen ürün", entityNote:"Akış, tekrar görüntülenen tek ürüne bağlıdır.", guardrails:["Satın alma veya sepete ekleme olduğunda akışı durdur.","Stok, indirim veya aciliyet bilgisi sistemde yoksa varmış gibi yazma."] },
  },
  "ACQ-287": {
    en:{ shortName:"Checkout Abandonment Recovery", name:"Checkout started → reminder sequence → purchase, payment recovery or exit", purpose:"Recover a checkout that started but did not finish, escalating the channel only when the order value justifies it.", reusableRule:"A checkout reminder must stop the moment purchase or a real payment failure is recorded.", entityScope:"Checkout", entityNote:"One instance follows one checkout attempt.", guardrails:["Hand payment errors to Payment Failure Recovery.","Never send another reminder after purchase."] },
    tr:{ shortName:"Checkout Tamamlama Kurtarma", name:"Checkout başladı → hatırlatma dizisi → satın alma, ödeme kurtarma veya çıkış", purpose:"Başlayıp tamamlanmayan checkout'u geri kazanmak; yalnızca yüksek değerli işlemlerde daha doğrudan kanala geçmek.", reusableRule:"Satın alma veya gerçek bir ödeme hatası görüldüğü anda checkout hatırlatması durmalıdır.", entityScope:"Checkout", entityNote:"Her akış tek bir checkout denemesini takip eder.", guardrails:["Ödeme hatası varsa Ödeme Başarısızlığından Kurtarma akışına aktar.","Satın alma sonrası bir daha hatırlatma gönderme."] },
  },
  "ACQ-288": {
    en:{ shortName:"Cart Abandonment Recovery", name:"Product added to cart → no checkout → remind → checkout, purchase or exit", purpose:"Bring back someone who added products to cart but never started checkout, with a stronger final channel only for high-value carts.", reusableRule:"Cart recovery ends as soon as checkout starts; checkout abandonment owns the next stage.", entityScope:"Cart", entityNote:"The journey follows one active cart.", guardrails:["Stop after purchase.","Hand off immediately when checkout starts."] },
    tr:{ shortName:"Sepet Terk Etme Kurtarma", name:"Sepete ürün eklendi → checkout başlamadı → hatırlat → checkout, satın alma veya çıkış", purpose:"Sepete ürün ekleyip checkout'a geçmeyen kullanıcıyı geri getirmek; yalnızca yüksek değerli sepetlerde son adımda daha doğrudan kanala geçmek.", reusableRule:"Checkout başladığı anda sepet kurtarma biter; sonraki adımı Checkout Abandonment devralır.", entityScope:"Sepet", entityNote:"Akış tek bir aktif sepeti takip eder.", guardrails:["Satın alma gerçekleştiğinde mesajları durdur.","Checkout başlar başlamaz ilgili akışa devret."] },
  },
  "ACQ-289": {
    en:{ shortName:"Back-in-Stock Alert", name:"Stock alert requested → product returns → push → email → SMS", purpose:"Notify a user who explicitly asked for a stock alert, using a simple three-channel sequence until they buy or the sequence ends.", reusableRule:"A back-in-stock message is triggered by real availability, not by a marketing schedule.", entityScope:"Product stock alert", entityNote:"One instance belongs to one user and one requested product.", guardrails:["Do not send before stock is actually available.","Stop after purchase."] },
    tr:{ shortName:"Stok Yenilendiğinde Haber Ver", name:"Stok bildirimi istendi → ürün geldi → push → e-posta → SMS", purpose:"Stok bildirimi isteyen kullanıcıya ürün gerçekten geri geldiğinde haber vermek ve satın alma olursa diziyi durdurmak.", reusableRule:"Stok bildirimi takvimle değil, ürün gerçekten yeniden satışa çıktığında tetiklenir.", entityScope:"Ürün stok bildirimi", entityNote:"Her akış tek kullanıcı ve tek ürün talebine bağlıdır.", guardrails:["Ürün gerçekten stokta değilse mesaj gönderme.","Satın alma gerçekleştiğinde akışı durdur."] },
  },
  "ACT-14": {
    en:{ shortName:"Onboarding Help", name:"Struggle detected → in-app help → push → email → complete or exit", purpose:"Help users who get stuck during onboarding before the friction turns into abandonment.", reusableRule:"Offer the lightest useful help first and escalate only if the user still cannot continue.", entityScope:"Onboarding session", entityNote:"The journey follows the onboarding flow and the step where the user is struggling.", guardrails:["Do not restart completed onboarding steps.","Stop as soon as the user continues successfully."] },
    tr:{ shortName:"Onboarding Yardımı", name:"Zorlanma sinyali → in-app yardım → push → e-posta → tamamla veya çık", purpose:"Onboarding sırasında takılan kullanıcıya, süreç tamamen terk edilmeden önce doğru seviyede yardım sunmak.", reusableRule:"Önce en hafif yardımı göster; kullanıcı hâlâ ilerleyemiyorsa kanalı ve desteği güçlendir.", entityScope:"Onboarding oturumu", entityNote:"Akış, onboarding sürecini ve kullanıcının zorlandığı adımı takip eder.", guardrails:["Tamamlanmış onboarding adımlarını yeniden başlatma.","Kullanıcı başarıyla devam ettiğinde akışı durdur."] },
  },
  "ACT-17": {
    en:{ shortName:"Adoption Nurture", name:"First meaningful action → repeat usage → stable use, re-engagement or upsell", purpose:"Move a newly activated user from a first value moment toward repeat, stable product use.", reusableRule:"Adoption is about repeated value, not simply completing onboarding.", entityScope:"User adoption", entityNote:"The journey follows the user's key value-producing behaviour after activation.", guardrails:["Do not push an upsell before repeat value is visible.","Use a different relevant feature when the first behaviour does not repeat."] },
    tr:{ shortName:"Kullanım Alışkanlığı Geliştirme", name:"İlk önemli aksiyon → tekrar kullanım → düzenli kullanım, yeniden etkileşim veya upsell", purpose:"İlk değer anını yaşayan kullanıcıyı düzenli ve tekrarlanan kullanıma taşımak.", reusableRule:"Adoption, onboarding'i bitirmek değil; üründen tekrar tekrar değer üretmektir.", entityScope:"Kullanım alışkanlığı", entityNote:"Akış, aktivasyon sonrasında kullanıcının değer üreten temel davranışını takip eder.", guardrails:["Tekrar kullanım oluşmadan upsell'e geçme.","İlk davranış tekrarlanmıyorsa farklı ve ilgili bir özelliği dene."] },
  },
  "ACT-20": {
    en:{ shortName:"Dormant Lead Reactivation", name:"first_open → 10 days inactive → behaviour-based reactivation → return or exit", purpose:"Re-engage a non-customer who opened the product but never progressed, using their last meaningful behaviour to choose the message.", reusableRule:"A dormant lead should be reactivated from what they actually showed interest in, not with a generic 'we miss you' message.", entityScope:"Non-customer lead", entityNote:"The journey follows a user who has not yet become a paying customer.", guardrails:["Do not route an existing customer through this journey.","Use purchase, quote and browsing behaviour as separate outcomes."] },
    tr:{ shortName:"Uyuyan Aday Yeniden Aktifleştirme", name:"first_open → 10 gün aksiyon yok → davranışa göre yeniden aktifleştirme → dönüş veya çıkış", purpose:"Ürünü açmış ama ilerlememiş potansiyel müşteriyi, son anlamlı davranışına göre yeniden harekete geçirmek.", reusableRule:"Uyuyan adaya genel bir 'seni özledik' mesajı değil, gerçekten ilgilendiği şeye göre dönüş nedeni ver.", entityScope:"Müşteri olmayan aday", entityNote:"Akış, henüz ücretli müşteriye dönüşmemiş kullanıcıyı takip eder.", guardrails:["Mevcut müşteriyi bu akışa alma.","Satın alma, teklif ve gezinme davranışlarını ayrı sonuçlar olarak ele al."] },
  },
  "RET-24": {
    en:{ shortName:"Churn Risk Escalation", name:"Churn risk rises → low / medium / high intervention → recover or monitor", purpose:"Respond to increasing churn risk with progressively stronger, problem-specific interventions rather than one generic retention campaign.", reusableRule:"The stronger the risk signal, the more direct and problem-specific the intervention should become.", entityScope:"Customer relationship", entityNote:"The journey follows the customer relationship while churn risk remains elevated.", guardrails:["Stop when usage or purchase behaviour recovers.","Use the likely reason for churn to choose the final intervention."] },
    tr:{ shortName:"Churn Riski Yükselmesi", name:"Churn riski yükseldi → düşük / orta / yüksek müdahale → toparla veya izle", purpose:"Artan churn riskine tek bir genel kampanya yerine, risk seviyesine ve sorunun nedenine göre güçlenen aksiyonlarla yanıt vermek.", reusableRule:"Risk güçlendikçe müdahale daha doğrudan ve soruna özel olmalıdır.", entityScope:"Müşteri ilişkisi", entityNote:"Akış, churn riski yüksek kaldığı sürece müşteri ilişkisini takip eder.", guardrails:["Kullanım veya satın alma toparlandığında akışı durdur.","Son müdahaleyi mümkün olduğunca gerçek risk nedenine göre seç."] },
  },
  "RET-31": {
    en:{ shortName:"Predicted Replenishment", name:"Predicted need → reminder → subscription or repurchase → exit", purpose:"Remind users before a repeat-use product is likely to run out, while clearly treating the timing as a prediction.", reusableRule:"Predicted replenishment works only when the prediction is reliable enough to be useful.", entityScope:"Repeat-purchase product", entityNote:"The journey follows one product the customer is expected to need again.", guardrails:["Do not message when prediction confidence is too low.","Stop when the item is repurchased."] },
    tr:{ shortName:"Tahmini Yenileme Hatırlatması", name:"Tahmini ihtiyaç → hatırlatma → abonelik veya yeniden satın alma → çıkış", purpose:"Düzenli tüketilen bir ürünün tahminen bitmesine yakın kullanıcıyı hatırlatmak; zamanlamanın bir tahmin olduğunu açık tutmak.", reusableRule:"Tahmini yenileme yalnızca tahmin yeterince güvenilir olduğunda çalıştırılmalıdır.", entityScope:"Tekrar satın alınan ürün", entityNote:"Akış, müşterinin yeniden ihtiyaç duyması beklenen tek ürünü takip eder.", guardrails:["Tahmin güvenilir değilse iletişim başlatma.","Ürün yeniden satın alındığında akışı durdur."] },
  },
  "RET-32": {
    en:{ shortName:"Lapsed Customer Win-Back", name:"Paid relationship ended → 30 days → value update → offer → return or exit", purpose:"Bring back a former paying customer after enough time has passed for a meaningful reason to return.", reusableRule:"Win-back should show what changed before it reaches for a discount.", entityScope:"Former customer", entityNote:"The journey follows a previously paid relationship that has already ended.", guardrails:["Do not run while the original cancellation window is still active.","Stop when the customer returns."] },
    tr:{ shortName:"Eski Müşteriyi Geri Kazanma", name:"Ücretli ilişki bitti → 30 gün → yenilikleri anlat → teklif → geri dönüş veya çıkış", purpose:"Ücretli ilişkisi sona ermiş müşteriyi, geri dönmesi için anlamlı bir neden oluştuğunda yeniden kazanmak.", reusableRule:"Win-back önce 'ne değişti'yi anlatmalı; indirime hemen başlamamalıdır.", entityScope:"Eski müşteri", entityNote:"Akış, sona ermiş eski ücretli müşteri ilişkisini takip eder.", guardrails:["İptal süreci hâlâ devam ederken win-back başlatma.","Müşteri geri döndüğünde akışı durdur."] },
  },
  "CON-272": {
    en:{ shortName:"Permission Recovery", name:"One channel permission closes → ask through another open channel → reopen or stop", purpose:"Recover a closed email or SMS permission by asking through the other channel that is still legitimately available.", reusableRule:"Never ask a closed channel to reopen itself.", entityScope:"Communication permission", entityNote:"The journey follows email and SMS marketing permission state for one person.", guardrails:["If both channels are closed, do not contact.","Only use an already-open channel to request the change."] },
    tr:{ shortName:"İletişim İzni Kurtarma", name:"Bir kanal izni kapandı → açık kanaldan sor → yeniden aç veya dur", purpose:"Kapanan e-posta veya SMS iznini, hâlâ açık olan diğer kanaldan izinli şekilde yeniden kazanmak.", reusableRule:"Kapalı bir kanala, kendisini yeniden açması için mesaj gönderilmez.", entityScope:"İletişim izni", entityNote:"Akış, tek kişinin e-posta ve SMS pazarlama izinlerini takip eder.", guardrails:["İki kanal da kapalıysa iletişim kurma.","İzin değişikliği istemek için yalnızca hâlihazırda açık olan kanalı kullan."] },
  },
  "RET-290": {
    en:{ shortName:"First-to-Second Purchase", name:"First purchase → natural repeat cycle → offer → second purchase or exit", purpose:"Turn a first-time buyer into a repeat customer around the natural time they are likely to need another purchase.", reusableRule:"The timing should follow the product's repeat-purchase cycle, not an arbitrary campaign calendar.", entityScope:"First-time buyer", entityNote:"The journey starts from the customer's first completed purchase.", guardrails:["Stop after the second purchase.","Keep the offer relevant to the first order or category."] },
    tr:{ shortName:"İlk Alışverişten İkinciye", name:"İlk satın alma → doğal tekrar süresi → teklif → ikinci satın alma veya çıkış", purpose:"İlk kez satın alan müşteriyi, ürünün doğal tekrar satın alma zamanında ikinci alışverişe taşımak.", reusableRule:"Zamanlama kampanya takvimine değil, ürünün doğal tekrar satın alma döngüsüne dayanmalıdır.", entityScope:"İlk kez satın alan müşteri", entityNote:"Akış müşterinin ilk tamamlanmış satın almasıyla başlar.", guardrails:["İkinci satın alma gerçekleştiğinde akışı durdur.","Teklifi ilk sipariş veya kategoriyle ilgili tut."] },
  },
  "RET-292": {
    en:{ shortName:"First Purchase Anniversary", name:"First-purchase anniversary → eligibility check → celebrate or exit", purpose:"Acknowledge the anniversary of a customer's first purchase with a single lightweight message.", reusableRule:"An anniversary message should recognise a real date, not invent a reward or status that does not exist.", entityScope:"Customer anniversary", entityNote:"The journey is tied to the date of the customer's first completed purchase.", guardrails:["Send at most once per anniversary period.","Do not imply a reward unless one actually exists."] },
    tr:{ shortName:"İlk Satın Alma Yıl Dönümü", name:"İlk satın alma yıl dönümü → uygunluk kontrolü → kutla veya çık", purpose:"Müşterinin ilk satın alma yıl dönümünü tek ve hafif bir mesajla hatırlamak.", reusableRule:"Yıl dönümü mesajı gerçek bir tarihi kutlamalı; olmayan ödül veya statü uydurmamalıdır.", entityScope:"Müşteri yıl dönümü", entityNote:"Akış müşterinin ilk tamamlanmış satın alma tarihine bağlıdır.", guardrails:["Her yıl dönümü döneminde en fazla bir kez gönder.","Gerçekte yoksa ödül varmış gibi yazma."] },
  },
  "RET-294": {
    en:{ shortName:"Cross-Sell / Complementary Offer", name:"Main product purchased → push → email → WhatsApp → complementary purchase or exit", purpose:"Offer a genuinely complementary product after the main purchase has had time to become useful.", reusableRule:"Cross-sell should explain why the second product complements the first, not simply push another item.", entityScope:"Purchased product", entityNote:"The journey links one purchased product to one relevant complementary offer.", guardrails:["Do not offer an item the customer already owns.","Stop immediately when the complementary product is purchased."] },
    tr:{ shortName:"Çapraz Satış / Tamamlayıcı Teklif", name:"Ana ürün alındı → push → e-posta → WhatsApp → tamamlayıcı satın alma veya çıkış", purpose:"Ana ürün kullanılmaya başladıktan sonra, gerçekten tamamlayıcı olan ürün veya hizmeti kademeli kanallarla teklif etmek.", reusableRule:"Cross-sell, rastgele ikinci ürün satmak değil; ilk ürünü gerçekten tamamlayan şeyi anlatmaktır.", entityScope:"Satın alınan ana ürün", entityNote:"Akış tek bir ana ürünü ilgili tamamlayıcı teklif ile eşleştirir.", guardrails:["Müşterinin zaten sahip olduğu tamamlayıcı ürünü teklif etme.","Tamamlayıcı ürün alındığında akışı durdur."] },
  },
  "RET-295": {
    en:{ shortName:"Birthday & Milestone", name:"Birthday or milestone reached → eligibility check → acknowledge or exit", purpose:"Recognise a defined birthday or customer milestone with one relevant message.", reusableRule:"Milestone communication should be tied to a real, defined event.", entityScope:"Customer milestone", entityNote:"The journey follows one configured birthday or relationship milestone.", guardrails:["Do not fabricate a milestone or benefit.","Send once for each defined milestone occurrence."] },
    tr:{ shortName:"Doğum Günü & Dönüm Noktası", name:"Doğum günü / dönüm noktası geldi → uygunluk kontrolü → kutla veya çık", purpose:"Tanımlı bir doğum günü veya müşteri dönüm noktasını tek ve ilgili bir mesajla kutlamak.", reusableRule:"Dönüm noktası iletişimi gerçek ve tanımlı bir olaya dayanmalıdır.", entityScope:"Müşteri dönüm noktası", entityNote:"Akış tanımlı bir doğum günü veya ilişki dönüm noktasını takip eder.", guardrails:["Olmayan bir dönüm noktası veya fayda uydurma.","Her tanımlı olay için en fazla bir kez gönder."] },
  },
  "CON-300": {
    en:{ shortName:"Unengaged Subscriber Sunset", name:"No engagement → preference check → final campaign → reduce or stop marketing", purpose:"Reduce or stop non-essential marketing when a subscriber repeatedly ignores messages, while giving them a clear preference choice first.", reusableRule:"Silence should reduce pressure, not trigger more and more campaigns.", entityScope:"Marketing subscriber", entityNote:"The journey follows a person's engagement with non-essential marketing.", guardrails:["Keep service and mandatory messages separate from marketing suppression.","Respect any preference change immediately."] },
    tr:{ shortName:"Yanıt Vermeyen Aboneyi Sonlandırma", name:"Etkileşim yok → tercih kontrolü → son kampanya → pazarlamayı azalt veya durdur", purpose:"Pazarlama mesajlarına uzun süre yanıt vermeyen kişide iletişim baskısını azaltmak veya durdurmak; önce açık bir tercih seçeneği sunmak.", reusableRule:"Sessizlik daha fazla kampanya nedeni değil, iletişim baskısını azaltma sinyalidir.", entityScope:"Pazarlama abonesi", entityNote:"Akış kişinin zorunlu olmayan pazarlama iletişimleriyle etkileşimini takip eder.", guardrails:["Servis ve zorunlu mesajları pazarlama baskılamasından ayrı tut.","Tercih değişikliğini anında uygula."] },
  },
  "FBK-41": {
    en:{ shortName:"Feedback Request", name:"Experience completed → choose channel → ask → route by score", purpose:"Ask for feedback at the right moment and route the response differently for high, medium and low satisfaction.", reusableRule:"Ask only after the experience is complete and no unresolved issue should take priority.", entityScope:"Completed experience", entityNote:"The journey is tied to one completed purchase, delivery, onboarding or service experience.", guardrails:["Do not ask while an open complaint or unresolved issue exists.","Use only one eligible channel path at a time."] },
    tr:{ shortName:"Geri Bildirim Talebi", name:"Deneyim tamamlandı → kanal seç → geri bildirim iste → skora göre yönlendir", purpose:"Geri bildirimi doğru anda istemek ve yüksek, orta, düşük memnuniyeti farklı aksiyonlara yönlendirmek.", reusableRule:"Deneyim gerçekten bitmeden ve açık sorun varken geri bildirim isteme.", entityScope:"Tamamlanan deneyim", entityNote:"Akış tek bir satın alma, teslimat, onboarding veya servis deneyimine bağlıdır.", guardrails:["Açık şikâyet veya çözülmemiş sorun varsa soru sorma.","Aynı anda yalnızca bir uygun kanal yolunu kullan."] },
  },
  "FBK-43": {
    en:{ shortName:"Feedback Follow-Up", name:"Feedback received → classify → route → track promise → close", purpose:"Route feedback to the team or process that can act on it, and keep the record open until any promised follow-up is actually completed.", reusableRule:"If you promise a response or action, the feedback record stays open until that promise is fulfilled.", entityScope:"Feedback record", entityNote:"One journey instance follows one feedback submission and any action promised because of it.", guardrails:["Do not create work for feedback that needs no action.","Escalate when a promised follow-up misses its SLA."] },
    tr:{ shortName:"Geri Bildirim Takibi", name:"Geri bildirim alındı → sınıflandır → yönlendir → verilen sözü takip et → kapat", purpose:"Geri bildirimi aksiyon alabilecek ekibe veya sürece ulaştırmak; kullanıcıya söz verilen aksiyon tamamlanana kadar kaydı açık tutmak.", reusableRule:"Kullanıcıya geri dönüş veya aksiyon sözü verildiyse, bu söz yerine gelmeden kayıt kapanmaz.", entityScope:"Geri bildirim kaydı", entityNote:"Her akış tek bir geri bildirimi ve ona bağlı verilen sözü takip eder.", guardrails:["Aksiyon gerektirmeyen geri bildirim için gereksiz iş yaratma.","Söz verilen aksiyon SLA'yı aşarsa eskale et."] },
  },
  "ACC-261": {
    en:{ shortName:"Payment Delay & Access Restriction", name:"Payment overdue → reminders → access restriction → restore or remain restricted", purpose:"Warn users before overdue payment affects access, then restore access as soon as payment is completed.", reusableRule:"Restriction should never arrive as a surprise when there was time to warn the customer first.", entityScope:"Overdue payment and access", entityNote:"The journey links one overdue obligation to the access it can affect.", guardrails:["Stop restriction messages once payment is completed.","Explain exactly how access can be restored."] },
    tr:{ shortName:"Ödeme Gecikmesi ve Erişim Kısıtı", name:"Ödeme gecikti → hatırlat → erişimi kısıtla → geri aç veya kısıtlı bırak", purpose:"Geciken ödemenin erişimi etkilemesinden önce kullanıcıyı uyarmak; ödeme tamamlandığında erişimi hızlıca geri açmak.", reusableRule:"Uyarı vermek için zaman varsa erişim kısıtı kullanıcıya sürpriz olmamalıdır.", entityScope:"Geciken ödeme ve erişim", entityNote:"Akış tek bir gecikmiş ödeme ile bu ödemenin etkileyebileceği erişimi birlikte takip eder.", guardrails:["Ödeme tamamlanınca kısıtlama mesajlarını durdur.","Erişimin nasıl geri açılacağını net şekilde belirt."] },
  },
  "REL-284": {
    en:{ shortName:"Referral Reward", name:"Referral code created → wait → reward confirmation or sharing reminder", purpose:"Follow up after a user receives a referral code, rewarding successful use and nudging sharing only when the code is still unused.", reusableRule:"Referral communication should follow the real code state: used means reward, unused means sharing reminder.", entityScope:"Referral code", entityNote:"The journey follows one referral code and its use status.", guardrails:["Do not send a sharing reminder after the code is used.","Only promise the reward that is actually configured."] },
    tr:{ shortName:"Arkadaş Daveti Ödülü", name:"Davet kodu oluştu → bekle → ödül onayı veya paylaşım hatırlatması", purpose:"Davet kodu alan kullanıcıyı takip etmek; kod kullanıldıysa ödülü bildirmek, kullanılmadıysa paylaşımı hatırlatmak.", reusableRule:"Referral mesajı gerçek kod durumuna göre değişir: kullanıldıysa ödül, kullanılmadıysa paylaşım hatırlatması.", entityScope:"Davet kodu", entityNote:"Akış tek bir davet kodunu ve kullanım durumunu takip eder.", guardrails:["Kod kullanıldıktan sonra paylaşım hatırlatması gönderme.","Yalnızca gerçekten tanımlı ödülü vaat et."] },
  },
  "FIN-134": {
    en:{ shortName:"Payment Failure Recovery", name:"Payment failed → classify reason → recover → paid or exit", purpose:"Recover a failed payment with the right action and channel for the failure reason, instead of sending the same generic message every time.", reusableRule:"Never guess why a payment failed; act on the reason the payment system actually reports.", entityScope:"Payment attempt", entityNote:"The journey follows one failed payment and the obligation it was trying to settle.", guardrails:["Stop immediately when payment succeeds.","Do not expose internal risk or decline codes to the customer."] },
    tr:{ shortName:"Ödeme Başarısızlığından Kurtarma", name:"Ödeme başarısız → nedeni sınıflandır → kurtar → ödeme veya çıkış", purpose:"Başarısız ödemeyi gerçek hata nedenine göre doğru aksiyon ve kanalla kurtarmak; her durumda aynı genel mesajı göndermemek.", reusableRule:"Ödemenin neden başarısız olduğunu tahmin etme; ödeme sisteminin gerçekten bildirdiği nedene göre hareket et.", entityScope:"Ödeme denemesi", entityNote:"Akış tek bir başarısız ödeme denemesini ve kapatmaya çalıştığı borcu takip eder.", guardrails:["Ödeme başarılı olduğunda akışı hemen durdur.","Müşteriye dahili risk veya ret kodlarını gösterme."] },
  },
  "FIN-302": {
    en:{ shortName:"Refund Recovery", name:"Refund approved → refund completes → alternatives → repurchase or exit", purpose:"Keep the customer informed through the refund and, once it is complete, help them find a better alternative rather than ending the relationship at the refund.", reusableRule:"Do not start a recovery offer before the refund itself is complete.", entityScope:"Refunded purchase", entityNote:"The journey follows one refunded order and the customer's return-to-purchase behaviour afterward.", guardrails:["Separate refund status from the later commercial recovery.","Stop when the customer repurchases."] },
    tr:{ shortName:"İade Sonrası Geri Kazanım", name:"İade onaylandı → iade tamamlandı → alternatif öner → yeniden satın alma veya çıkış", purpose:"İade sürecinde kullanıcıyı bilgilendirmek; iade tamamlandıktan sonra daha uygun alternatiflerle ilişkiyi yeniden kurmaya çalışmak.", reusableRule:"İade tamamlanmadan geri kazanım teklifi başlatma.", entityScope:"İade edilen satın alma", entityNote:"Akış tek bir iade edilen siparişi ve sonrasındaki yeniden satın alma davranışını takip eder.", guardrails:["İade durumu ile ticari geri kazanımı birbirinden ayır.","Kullanıcı yeniden satın aldığında akışı durdur."] },
  },
  "FUL-146": {
    en:{ shortName:"Delivery Delay Management", name:"Delay detected → update ETA → monitor → recovery options or exit", purpose:"Tell the customer about a delivery delay before they have to discover it themselves, and escalate only if the revised date is missed too.", reusableRule:"A delay message should say what is known now and update when the estimate changes.", entityScope:"Delivery", entityNote:"The journey follows one delivery and its latest expected date.", guardrails:["Do not invent a new ETA when none is known.","Stop once the delivery is completed."] },
    tr:{ shortName:"Teslimat Gecikmesi Yönetimi", name:"Gecikme tespit edildi → tarihi güncelle → takip et → alternatif çözüm veya çıkış", purpose:"Teslimat gecikmesini kullanıcı fark etmeden önce bildirmek; yeni tarih de aşılırsa alternatif teslimat veya destek seçeneklerine geçmek.", reusableRule:"Gecikme mesajı o anda bilinen gerçeği söylemeli; tahmin değişirse bilgi de güncellenmelidir.", entityScope:"Teslimat", entityNote:"Akış tek bir teslimatı ve güncel tahmini teslim tarihini takip eder.", guardrails:["Yeni tarih bilinmiyorsa uydurma.","Teslimat tamamlandığında akışı durdur."] },
  },
  "FUL-148": {
    en:{ shortName:"Failed Delivery Recovery", name:"Delivery failed → classify reason → reschedule or alternative → complete or escalate", purpose:"Recover a failed delivery differently depending on whether the issue is the address, customer availability, operations or an impossible delivery.", reusableRule:"The recovery path should match the actual failure reason.", entityScope:"Failed delivery attempt", entityNote:"The journey follows one failed delivery attempt and its next resolution path.", guardrails:["Do not keep retrying when delivery is impossible.","Stop once delivery succeeds."] },
    tr:{ shortName:"Başarısız Teslimat Kurtarma", name:"Teslimat başarısız → nedeni ayır → yeniden planla veya alternatif sun → tamamla veya eskale et", purpose:"Başarısız teslimatı adres, müşterinin evde olmaması, operasyon veya teslimatın mümkün olmaması gibi gerçek nedene göre kurtarmak.", reusableRule:"Kurtarma yolu, teslimatın gerçek başarısızlık nedenine göre seçilmelidir.", entityScope:"Başarısız teslimat denemesi", entityNote:"Akış tek bir başarısız teslimat denemesini ve sonraki çözüm yolunu takip eder.", guardrails:["Teslimat mümkün değilse tekrar tekrar aynı denemeyi yapma.","Teslimat başarıyla tamamlandığında akışı durdur."] },
  },
  "FUL-291": {
    en:{ shortName:"Post-Purchase Follow-Up", name:"Purchase completed → thank you → rating → review request or exit", purpose:"Follow up after purchase, check satisfaction and ask for a public review only when the customer's own rating is positive.", reusableRule:"A low rating is a recovery signal, not a moment to ask for a public review.", entityScope:"Completed purchase", entityNote:"The journey follows one completed purchase and the customer's first satisfaction signal.", guardrails:["Do not ask for a public review after a low rating.","Do not send follow-up before the purchase is complete."] },
    tr:{ shortName:"Satın Alma Sonrası Takip", name:"Satın alma tamamlandı → teşekkür → puanlama → yorum iste veya çık", purpose:"Satın alma sonrasında müşteriye dönmek, memnuniyetini ölçmek ve yalnızca olumlu puan verdiğinde yorum istemek.", reusableRule:"Düşük puan yorum isteme anı değil, çözüm sinyalidir.", entityScope:"Tamamlanan satın alma", entityNote:"Akış tek bir tamamlanmış satın alma ve müşterinin ilk memnuniyet sinyalini takip eder.", guardrails:["Düşük puan sonrası herkese açık yorum isteme.","Satın alma tamamlanmadan takip mesajı gönderme."] },
  },
  "REM-151": {
    en:{ shortName:"Post-Purchase Issue Resolution", name:"Issue reported → route by issue type → resolve → follow up or escalate", purpose:"Send a post-purchase problem straight to the right resolution path instead of making the customer repeat the same explanation.", reusableRule:"Classify the issue first; do not delay obvious resolution paths with a generic holding sequence.", entityScope:"Post-purchase issue", entityNote:"The journey follows one reported issue tied to a completed purchase or delivery.", guardrails:["Route damaged, technical and missing-delivery issues differently.","Escalate when the selected resolution misses its SLA."] },
    tr:{ shortName:"Satış Sonrası Sorun Çözümü", name:"Sorun bildirildi → sorun tipine göre yönlendir → çöz → takip et veya eskale et", purpose:"Satış sonrası sorunu doğrudan doğru çözüm yoluna aktarmak; kullanıcıya aynı problemi tekrar tekrar anlattırmamak.", reusableRule:"Önce sorun tipini ayır; açıkça belli olan çözüm yolunu genel bir bekleme akışıyla geciktirme.", entityScope:"Satış sonrası sorun", entityNote:"Akış tamamlanmış satın alma veya teslimata bağlı tek bir sorunu takip eder.", guardrails:["Hasarlı ürün, teknik sorun ve eksik teslimatı farklı çözüm yollarına aktar.","Seçilen çözüm SLA'yı aşarsa eskale et."] },
  },
  "SCH-266": {
    en:{ shortName:"Appointment Reminder", name:"Appointment approaching → readiness check → push → SMS → ready or exit", purpose:"Prepare the user for an upcoming appointment and catch missing documents or information before the last reminder.", reusableRule:"A reminder is more useful when it also checks whether the user is actually ready for the appointment.", entityScope:"Appointment", entityNote:"The journey follows one scheduled appointment.", guardrails:["Stop if the appointment is cancelled.","Use the final reminder for the actual appointment, not as a substitute for missing preparation."] },
    tr:{ shortName:"Randevu Hatırlatması", name:"Randevu yaklaşıyor → hazırlık kontrolü → push → SMS → hazır veya çık", purpose:"Yaklaşan randevuyu hatırlatmak ve son mesaja kalmadan eksik bilgi veya belgeleri tamamlatmak.", reusableRule:"İyi bir randevu hatırlatması yalnızca tarihi söylemez; kullanıcının gerçekten hazır olup olmadığını da kontrol eder.", entityScope:"Randevu", entityNote:"Akış tek bir planlanmış randevuyu takip eder.", guardrails:["Randevu iptal edildiyse mesajları durdur.","Eksik hazırlığı son randevu hatırlatmasının içine sıkıştırma."] },
  },
  "SCH-282": {
    en:{ shortName:"Availability Search Abandonment", name:"Availability searched → no booking → same slot, alternatives or waitlist", purpose:"Bring back someone who checked availability but did not book, using the live state of the requested slot.", reusableRule:"Availability recovery should respond to what is still bookable now.", entityScope:"Availability search", entityNote:"The journey follows one availability search and the requested time.", guardrails:["Do not advertise a slot that is no longer available.","Stop after booking."] },
    tr:{ shortName:"Müsaitlik Arama Terki", name:"Müsaitlik arandı → rezervasyon yok → aynı saat, alternatif veya bekleme listesi", purpose:"Müsaitlik arayıp rezervasyon yapmayan kullanıcıyı, aradığı saatin güncel durumuna göre geri getirmek.", reusableRule:"Müsaitlik kurtarma, o anda gerçekten rezervasyon yapılabilen seçeneklere göre çalışmalıdır.", entityScope:"Müsaitlik araması", entityNote:"Akış tek bir müsaitlik aramasını ve aranan zamanı takip eder.", guardrails:["Artık müsait olmayan saati müsaitmiş gibi gösterme.","Rezervasyon yapıldığında akışı durdur."] },
  },
  "SCH-303": {
    en:{ shortName:"Reservation Payment Reminder", name:"Reservation created → payment pending → reminders → confirm or release", purpose:"Protect a reservation while payment is pending, with reminders tied to the actual hold and payment deadline.", reusableRule:"Reservation payment reminders should count down to the real deadline, not manufacture urgency.", entityScope:"Reservation", entityNote:"The journey follows one reservation and its pending payment.", guardrails:["Stop when payment is completed.","Release the reservation when the real payment window expires."] },
    tr:{ shortName:"Rezervasyon Ödeme Hatırlatması", name:"Rezervasyon oluştu → ödeme bekliyor → hatırlat → onayla veya serbest bırak", purpose:"Ödemesi bekleyen rezervasyonu gerçek ödeme süresi içinde korumak ve son tarihe göre hatırlatmak.", reusableRule:"Rezervasyon ödeme hatırlatması gerçek son tarihe dayanmalı; yapay aciliyet üretmemelidir.", entityScope:"Rezervasyon", entityNote:"Akış tek bir rezervasyonu ve bekleyen ödemesini takip eder.", guardrails:["Ödeme tamamlandığında akışı durdur.","Gerçek ödeme süresi dolduğunda rezervasyonu serbest bırak."] },
  },
  "SUB-163": {
    en:{ shortName:"Renewal Reminder", name:"Renewal window → auto / manual path → renew, payment recovery or win-back", purpose:"Handle automatic and manual renewals differently, with the right reminders and downstream handoffs for each.", reusableRule:"Auto-renew and manual-renew customers should not receive the same journey.", entityScope:"Subscription renewal", entityNote:"The journey follows one subscription approaching its renewal date.", guardrails:["Send payment failures to Payment Failure Recovery.","If a manual renewal lapses, hand it to Win-Back instead of extending reminders forever."] },
    tr:{ shortName:"Yenileme Hatırlatması", name:"Yenileme dönemi → otomatik / manuel kol → yenileme, ödeme kurtarma veya win-back", purpose:"Otomatik ve manuel yenilenen üyelikleri farklı akışlarla yönetmek; her birinde doğru hatırlatma ve devri yapmak.", reusableRule:"Otomatik yenilenen ve kullanıcının kendisinin yenilemesi gereken üyelikler aynı journey'yi almamalıdır.", entityScope:"Abonelik yenilemesi", entityNote:"Akış yenileme tarihi yaklaşan tek bir aboneliği takip eder.", guardrails:["Ödeme hatasını Ödeme Başarısızlığından Kurtarma akışına aktar.","Manuel yenileme sona erdiyse hatırlatmayı sonsuza uzatmak yerine Win-Back'e devret."] },
  },
  "SUB-262": {
    en:{ shortName:"Cancellation Confirmation", name:"Cancellation confirmed → access countdown → return offer → reactivate or exit", purpose:"Guide the customer from confirmed cancellation through the real access end date, then make one bounded return offer if they do not reactivate.", reusableRule:"Cancellation confirmation should make the access end date clear before any win-back offer begins.", entityScope:"Cancelled subscription", entityNote:"The journey follows one confirmed cancellation until access ends or the subscription is reactivated.", guardrails:["Stop immediately if the subscription is reactivated.","Do not start the return offer before access actually ends."] },
    tr:{ shortName:"İptal Onayı", name:"İptal onaylandı → erişim bitişi → geri dönüş teklifi → yeniden aktif veya çıkış", purpose:"İptal edilen üyeliği gerçek erişim bitişine kadar yönetmek; yeniden aktif olmadıysa sınırlı bir geri dönüş teklifi sunmak.", reusableRule:"Geri dönüş teklifi başlamadan önce kullanıcı erişimin ne zaman biteceğini net olarak bilmeli.", entityScope:"İptal edilen abonelik", entityNote:"Akış tek bir onaylanmış iptali, erişim bitene veya üyelik yeniden aktif olana kadar takip eder.", guardrails:["Üyelik yeniden aktif olduğunda akışı hemen durdur.","Erişim gerçekten bitmeden geri dönüş teklifine başlama."] },
  },
  "SUB-296": {
    en:{ shortName:"Loyalty Program Activation", name:"Join program → first earn → progress → first reward → first redemption", purpose:"Turn a new loyalty member into an active one by getting them from enrolment to their first earned points and first usable reward.", reusableRule:"Loyalty activation is complete when the member starts earning and using value, not when enrolment alone is recorded.", entityScope:"Loyalty membership", entityNote:"The journey follows one new loyalty membership through its first meaningful milestones.", guardrails:["Do not celebrate points or rewards before they exist.","Stop pushing first-earn prompts after the member has already earned."] },
    tr:{ shortName:"Sadakat Programı Aktivasyonu", name:"Programa katıl → ilk puan → ilerleme → ilk ödül → ilk kullanım", purpose:"Yeni sadakat üyesini yalnızca kayıtlı kullanıcı olmaktan çıkarıp ilk puanını kazanan ve ilk ödülünü kullanan aktif üyeye dönüştürmek.", reusableRule:"Sadakat aktivasyonu kayıt olmakla değil, üyenin değer kazanıp kullanmaya başlamasıyla tamamlanır.", entityScope:"Sadakat üyeliği", entityNote:"Akış yeni bir sadakat üyeliğini ilk anlamlı kazanım ve kullanım adımlarına kadar takip eder.", guardrails:["Puan veya ödül gerçekten oluşmadan varmış gibi kutlama yapma.","İlk puan kazanıldıktan sonra ilk kazanım hatırlatmalarını durdur."] },
  },
  "SUB-297": {
    en:{ shortName:"Unused Loyalty Reward", name:"Unused reward → push → email → use or expire", purpose:"Remind a loyalty member about a real, unused reward without turning it into an endless nurture cadence.", reusableRule:"The journey exists for one unused reward and ends when that reward is used or the reminder window closes.", entityScope:"Loyalty reward", entityNote:"The journey follows one usable, unredeemed reward.", guardrails:["Stop once the reward is used.","Use the reward's real expiry date when one exists."] },
    tr:{ shortName:"Kullanılmayan Sadakat Ödülü", name:"Kullanılmayan ödül → push → e-posta → kullan veya süreyi kapat", purpose:"Gerçekten kullanılabilir ama henüz kullanılmamış sadakat ödülünü sınırlı bir diziyle hatırlatmak.", reusableRule:"Bu akış tek bir kullanılmamış ödül içindir; ödül kullanıldığında veya hatırlatma penceresi kapandığında biter.", entityScope:"Sadakat ödülü", entityNote:"Akış tek bir kullanılabilir ve kullanılmamış ödülü takip eder.", guardrails:["Ödül kullanıldığında mesajları durdur.","Son kullanma tarihi varsa gerçek tarihi kullan."] },
  },
  "SUB-298": {
    en:{ shortName:"Reward Confirmation", name:"Wheel reward won → in-app confirmation → 3 days → use or reminder", purpose:"Confirm a concrete reward immediately, then send one reminder only if the reward code remains unused.", reusableRule:"Reward communication should reflect the exact reward that was actually won.", entityScope:"Earned reward", entityNote:"The journey follows one reward and its redemption code.", guardrails:["Do not send the reminder after redemption.","Do not invent a different value, expiry or benefit."] },
    tr:{ shortName:"Ödül Onayı", name:"Çark ödülü kazanıldı → in-app onay → 3 gün → kullan veya hatırlat", purpose:"Kazanılan somut ödülü hemen göstermek; kod kullanılmadıysa yalnızca bir kez hatırlatmak.", reusableRule:"Ödül iletişimi kullanıcının gerçekten kazandığı ödülü aynen yansıtmalıdır.", entityScope:"Kazanılan ödül", entityNote:"Akış tek bir ödülü ve kullanım kodunu takip eder.", guardrails:["Kod kullanıldıysa hatırlatma gönderme.","Farklı tutar, son tarih veya fayda uydurma."] },
  },
  "SUB-299": {
    en:{ shortName:"Loyalty Tier Change", name:"Tier changes → upgrade celebration or downgrade recovery → exit", purpose:"Handle loyalty upgrades and downgrades differently: celebrate new benefits on the way up and offer a clear recovery path on the way down.", reusableRule:"An upgrade and a downgrade are different customer moments and should not share the same message.", entityScope:"Loyalty tier", entityNote:"The journey follows one change in a member's loyalty tier.", guardrails:["Do not present an old benefit as newly unlocked.","Use downgrade recovery only when there is a real path back to the higher tier."] },
    tr:{ shortName:"Sadakat Seviyesi Değişimi", name:"Seviye değişti → yükselişi kutla veya düşüşü geri kazan → çık", purpose:"Sadakat seviyesi yükselişini ve düşüşünü farklı yönetmek; yükselişte yeni avantajları anlatmak, düşüşte üst seviyeye dönüş yolunu göstermek.", reusableRule:"Seviye yükselişi ve düşüşü farklı müşteri anlarıdır; aynı mesajla yönetilmemelidir.", entityScope:"Sadakat seviyesi", entityNote:"Akış tek bir sadakat seviyesi değişimini takip eder.", guardrails:["Eski avantajı yeni açılmış gibi anlatma.","Üst seviyeye gerçek bir dönüş yolu yoksa downgrade kampanyası yapma."] },
  },
  "DOC-214": {
    en:{ shortName:"Missing Document Follow-Up", name:"Document missing → email → push → final SMS → complete or manual follow-up", purpose:"Help a user complete missing documents before the application deadline, escalating only when the documents remain incomplete.", reusableRule:"Every reminder should say exactly what is missing and how to submit it.", entityScope:"Document requirement", entityNote:"The journey follows the missing documents for one application or process.", guardrails:["Stop when all required documents are received.","Do not silently close the process at the deadline without the intended handoff."] },
    tr:{ shortName:"Eksik Belge Takibi", name:"Belge eksik → e-posta → push → son SMS → tamamla veya manuel takip", purpose:"Başvuru veya süreçte eksik belgeleri son tarihten önce tamamlatmak; eksik kalırsa kontrollü şekilde manuel takibe aktarmak.", reusableRule:"Her hatırlatma hangi belgenin eksik olduğunu ve nasıl gönderileceğini açıkça söylemelidir.", entityScope:"Belge gerekliliği", entityNote:"Akış tek bir başvuru veya sürecin eksik belgelerini takip eder.", guardrails:["Tüm belgeler geldiğinde akışı durdur.","Son tarihte süreci sessizce kapatmak yerine tanımlı manuel takibe aktar."] },
  },
  "RLT-279": {
    en:{ shortName:"Upgrade Completion Reminder", name:"Upgrade started → missing step → email → push → complete or exit", purpose:"Bring a user back to an upgrade they started but did not finish, pointing them directly to the missing step.", reusableRule:"A completion reminder should name the one thing still blocking the upgrade.", entityScope:"Upgrade attempt", entityNote:"The journey follows one upgrade attempt until it completes or the reminder sequence ends.", guardrails:["Stop once the upgrade completes.","Do not keep reminding after the upgrade is no longer valid."] },
    tr:{ shortName:"Yükseltme Tamamlama Hatırlatması", name:"Yükseltme başladı → eksik adım → e-posta → push → tamamla veya çık", purpose:"Başlayıp tamamlanmayan yükseltmeyi, eksik kalan adıma doğrudan yönlendirerek tamamlatmak.", reusableRule:"Tamamlama hatırlatması, yükseltmenin önünde kalan tek somut adımı açıkça göstermelidir.", entityScope:"Yükseltme denemesi", entityNote:"Akış tek bir yükseltme girişimini tamamlanana veya hatırlatma dizisi bitene kadar takip eder.", guardrails:["Yükseltme tamamlandığında akışı durdur.","Yükseltme artık geçerli değilse hatırlatmayı sürdürme."] },
  },
  "RSK-273": {
    en:{ shortName:"Usage Limit Management", name:"Limit reached → explain options → alternative, upgrade or reset → exit", purpose:"Help a user who hits a usage limit understand what happened and the fastest legitimate way to continue.", reusableRule:"A limit message should explain the limit, reset timing and available options without blaming the user.", entityScope:"Usage limit", entityNote:"The journey follows one limit event and the available path to continue.", guardrails:["Do not invent a reset time or upgrade path.","If a free alternative fully solves the problem, show it before upsell."] },
    tr:{ shortName:"Kullanım Limiti Yönetimi", name:"Limite ulaşıldı → seçenekleri açıkla → alternatif, yükseltme veya yenilenme → çık", purpose:"Kullanım limitine takılan kullanıcıya ne olduğunu ve devam edebileceği en hızlı geçerli yolu göstermek.", reusableRule:"Limit mesajı kullanıcıyı suçlamadan limiti, yenilenme zamanını ve gerçek seçenekleri anlatmalıdır.", entityScope:"Kullanım limiti", entityNote:"Akış tek bir limit olayını ve devam etmek için mevcut yolları takip eder.", guardrails:["Yenilenme zamanı veya paket seçeneği yoksa uydurma.","Ücretsiz bir alternatif ihtiyacı tamamen karşılıyorsa önce onu göster."] },
  },
};

export function publicJourneyCopy(id: string, lang: "en" | "tr"): PublicJourneyCopy | null {
  return COPY[id]?.[lang] ?? null;
}

export const PUBLIC_JOURNEY_COPY_IDS = new Set(Object.keys(COPY));
