import type { ChannelId } from "@/canonical/types";
import type { FlowEdge, FlowNode } from "@/lib/canonical-view";
import type { Lang } from "@/lib/content";

/*
  Public journey-flow corrections agreed during the 2026-09 journey-library
  review. The canonical corpus remains the engine/audit source of truth; this
  file owns the practitioner-facing canvas shape where the product decision
  deliberately simplified or repurposed an older canonical state machine.

  Keep this file about FLOW only. Copy polish belongs in journey-tr-overrides.
  Once a canonical journey is rebuilt to the same shape, its entry can be
  deleted from here.
*/

type FlowSpec = {
  channels?: readonly ChannelId[];
  en: readonly FlowNode[];
  tr: readonly FlowNode[];
};

const edge = (to: string, label: string | null = null, detail: string | null = null): FlowEdge => ({
  label,
  detail,
  to,
  href: null,
  kind: "node",
  back: false,
});

const n = (
  id: string,
  kind: FlowNode["kind"],
  headline: string,
  edges: readonly FlowEdge[] = [],
  opts: Partial<FlowNode> = {},
): FlowNode => ({
  id,
  kind,
  headline,
  eventId: kind === "trigger" ? id.replace(/^t\./, "") : null,
  detail: null,
  meta: [],
  edges,
  isEntry: kind === "trigger",
  terminal: kind === "exit",
  ...opts,
});

const ch = (...channels: ChannelId[]) => channels;

const SPECS: Readonly<Record<string, FlowSpec>> = {
  "SUB-298": {
    channels: ch("in-app", "push"),
    en: [
      n("t.reward", "trigger", "User spins the wheel and wins a 100 TL reward", [edge("a.inapp")]),
      n("a.inapp", "action", "In-app: 100 TL reward earned + code", [edge("w.3d")], { execution: "communication", channelPriority: ch("in-app") }),
      n("w.3d", "wait", "Wait 3 days", [edge("c.used")]),
      n("c.used", "condition", "Was the reward code used?", [edge("x.used", "Yes"), edge("a.push", "No")], { branchCount: 2 }),
      n("a.push", "action", "Push: Use your reward before it expires", [edge("x.unused")], { execution: "communication", channelPriority: ch("push") }),
      n("x.used", "exit", "Reward used"),
      n("x.unused", "exit", "Reminder sent; journey ends"),
    ],
    tr: [
      n("t.reward", "trigger", "Kullanıcı çark çevirdi ve 100 TL ödül kazandı", [edge("a.inapp")]),
      n("a.inapp", "action", "In-app: 100 TL kazandın + ödül kodu", [edge("w.3d")], { execution: "communication", channelPriority: ch("in-app") }),
      n("w.3d", "wait", "3 gün bekle", [edge("c.used")]),
      n("c.used", "condition", "Ödül kodu kullanıldı mı?", [edge("x.used", "Evet"), edge("a.push", "Hayır")], { branchCount: 2 }),
      n("a.push", "action", "Push: Ödülün dolmadan kullan", [edge("x.unused")], { execution: "communication", channelPriority: ch("push") }),
      n("x.used", "exit", "Ödül kullanıldı"),
      n("x.unused", "exit", "Hatırlatma gönderildi; journey bitti"),
    ],
  },

  "FUL-291": {
    channels: ch("email", "push"),
    en: [
      n("t.purchase", "trigger", "Purchase completed", [edge("a.thanks")]),
      n("a.thanks", "action", "Email: Thank you + first-use information", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "Wait 3 days", [edge("a.rate")]),
      n("a.rate", "action", "Ask: Are you satisfied? Rate the product", [edge("c.rating")], { execution: "communication", channelPriority: ch("email", "push") }),
      n("c.rating", "condition", "How was the rating?", [edge("x.low", "Low rating"), edge("a.review", "High rating")], { branchCount: 2 }),
      n("a.review", "action", "Ask for a public review", [edge("x.high")], { execution: "communication", channelPriority: ch("email") }),
      n("x.low", "exit", "Low rating: do not ask for a review"),
      n("x.high", "exit", "High rating: review request sent"),
    ],
    tr: [
      n("t.purchase", "trigger", "Satın alma tamamlandı", [edge("a.thanks")]),
      n("a.thanks", "action", "E-posta: Teşekkür + ilk kullanım bilgisi", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "3 gün bekle", [edge("a.rate")]),
      n("a.rate", "action", "Üründen memnun kaldın mı? Ürünü puanla", [edge("c.rating")], { execution: "communication", channelPriority: ch("email", "push") }),
      n("c.rating", "condition", "Verilen puan nasıl?", [edge("x.low", "Düşük puan"), edge("a.review", "Yüksek puan")], { branchCount: 2 }),
      n("a.review", "action", "Yorum iste", [edge("x.high")], { execution: "communication", channelPriority: ch("email") }),
      n("x.low", "exit", "Düşük puan: yorum isteme"),
      n("x.high", "exit", "Yüksek puan: yorum talebi gönderildi"),
    ],
  },

  "ACT-17": {
    channels: ch("push"),
    en: [
      n("t.first", "trigger", "User completes the first meaningful action", [edge("w.3d")]),
      n("w.3d", "wait", "Wait 3 days", [edge("c.repeat")]),
      n("c.repeat", "condition", "Did they repeat the same or a second meaningful action?", [edge("h.upsell", "Yes"), edge("a.feature", "No")], { branchCount: 2 }),
      n("a.feature", "action", "Push: Highlight a different useful feature", [edge("c.stable")], { execution: "communication", channelPriority: ch("push") }),
      n("c.stable", "condition", "Did usage become regular?", [edge("x.stable", "Yes"), edge("h.reengage", "No")], { branchCount: 2 }),
      n("h.upsell", "handoff", "Move to the upsell journey"),
      n("h.reengage", "handoff", "Move to nurture / re-engagement"),
      n("x.stable", "exit", "Stable user"),
    ],
    tr: [
      n("t.first", "trigger", "Kullanıcı ilk önemli aksiyonu yaptı", [edge("w.3d")]),
      n("w.3d", "wait", "3 gün bekle", [edge("c.repeat")]),
      n("c.repeat", "condition", "Aynı veya ikinci önemli aksiyonu tekrar yaptı mı?", [edge("h.upsell", "Evet"), edge("a.feature", "Hayır")], { branchCount: 2 }),
      n("a.feature", "action", "Push: Farklı ve ilgili bir özelliği öne çıkar", [edge("c.stable")], { execution: "communication", channelPriority: ch("push") }),
      n("c.stable", "condition", "Düzenli kullanıma geçti mi?", [edge("x.stable", "Evet"), edge("h.reengage", "Hayır")], { branchCount: 2 }),
      n("h.upsell", "handoff", "Upsell journey'sine taşı"),
      n("h.reengage", "handoff", "Nurture / re-engagement akışına taşı"),
      n("x.stable", "exit", "Düzenli kullanıcı"),
    ],
  },

  "RET-294": {
    channels: ch("push", "email", "whatsapp"),
    en: [
      n("t.purchase", "trigger", "Main product purchased", [edge("w.3d")]),
      n("w.3d", "wait", "Wait 3 days", [edge("c.active")]),
      n("c.active", "condition", "Is the main product still active and not returned?", [edge("c.already", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("c.already", "condition", "Has the complementary product already been purchased?", [edge("x.end", "Yes"), edge("a.push", "No")], { branchCount: 2 }),
      n("a.push", "action", "Push: We have a suggestion that complements what you bought", [edge("w.1d")], { execution: "communication", channelPriority: ch("push") }),
      n("w.1d", "wait", "Wait 1 day", [edge("c.buy1")]),
      n("c.buy1", "condition", "Complementary product purchased?", [edge("x.end", "Yes"), edge("a.email", "No")], { branchCount: 2 }),
      n("a.email", "action", "Email: Explain why it complements the product, benefits and offer", [edge("w.2d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.2d", "wait", "Wait 2 days", [edge("c.buy2")]),
      n("c.buy2", "condition", "Purchased?", [edge("x.end", "Yes"), edge("a.wa", "No")], { branchCount: 2 }),
      n("a.wa", "action", "WhatsApp: Final, direct complementary-product offer", [edge("c.buy3")], { execution: "communication", channelPriority: ch("whatsapp") }),
      n("c.buy3", "condition", "Purchased?", [edge("x.end", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.purchase", "trigger", "Ana ürün satın alındı", [edge("w.3d")]),
      n("w.3d", "wait", "3 gün bekle", [edge("c.active")]),
      n("c.active", "condition", "Ana ürün hâlâ aktif / geçerli / iade edilmemiş mi?", [edge("c.already", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("c.already", "condition", "Tamamlayıcı ürün daha önce satın alındı mı?", [edge("x.end", "Evet"), edge("a.push", "Hayır")], { branchCount: 2 }),
      n("a.push", "action", "Push: Aldığın ürünü tamamlayacak bir önerimiz var", [edge("w.1d")], { execution: "communication", channelPriority: ch("push") }),
      n("w.1d", "wait", "1 gün bekle", [edge("c.buy1")]),
      n("c.buy1", "condition", "Tamamlayıcı ürün satın alındı mı?", [edge("x.end", "Evet"), edge("a.email", "Hayır")], { branchCount: 2 }),
      n("a.email", "action", "E-posta: Neden tamamlayıcı olduğunu, faydasını ve varsa avantajı anlat", [edge("w.2d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.2d", "wait", "2 gün bekle", [edge("c.buy2")]),
      n("c.buy2", "condition", "Satın alındı mı?", [edge("x.end", "Evet"), edge("a.wa", "Hayır")], { branchCount: 2 }),
      n("a.wa", "action", "WhatsApp: Satın aldığın ürünü tamamlayacak öneri burada", [edge("c.buy3")], { execution: "communication", channelPriority: ch("whatsapp") }),
      n("c.buy3", "condition", "Satın alındı mı?", [edge("x.end", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "SUB-299": {
    channels: ch("email", "push"),
    en: [
      n("t.changed", "trigger", "Loyalty tier changed", [edge("c.direction")]),
      n("c.direction", "condition", "Did the tier go up or down?", [edge("a.up-email", "Up"), edge("a.down-push", "Down")], { branchCount: 2 }),
      n("a.up-email", "action", "Email: Announce the higher tier and what changed", [edge("w.up")], { execution: "communication", channelPriority: ch("email") }),
      n("w.up", "wait", "Wait a short period", [edge("a.up-push")]),
      n("a.up-push", "action", "Push: Remind the member of the new tier benefits", [edge("x.end")], { execution: "communication", channelPriority: ch("push") }),
      n("a.down-push", "action", "Push: Campaign to regain the higher tier", [edge("w.down")], { execution: "communication", channelPriority: ch("push") }),
      n("w.down", "wait", "Wait through the campaign window", [edge("c.restored")]),
      n("c.restored", "condition", "Was the higher tier regained?", [edge("x.end", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.changed", "trigger", "Sadakat seviyesi değişti", [edge("c.direction")]),
      n("c.direction", "condition", "Seviye yükseldi mi, düştü mü?", [edge("a.up-email", "Yükseldi"), edge("a.down-push", "Düştü")], { branchCount: 2 }),
      n("a.up-email", "action", "E-posta: Seviye yükselişini ve yeni avantajları duyur", [edge("w.up")], { execution: "communication", channelPriority: ch("email") }),
      n("w.up", "wait", "Kısa bir süre bekle", [edge("a.up-push")]),
      n("a.up-push", "action", "Push: Yeni seviyenin avantajlarını hatırlat", [edge("x.end")], { execution: "communication", channelPriority: ch("push") }),
      n("a.down-push", "action", "Push: Üst seviyeye geri çıkma kampanyasını gönder", [edge("w.down")], { execution: "communication", channelPriority: ch("push") }),
      n("w.down", "wait", "Kampanya süresi boyunca bekle", [edge("c.restored")]),
      n("c.restored", "condition", "Üst seviye geri kazanıldı mı?", [edge("x.end", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "SUB-296": {
    channels: ch("email", "in-app", "push"),
    en: [
      n("t.joined", "trigger", "Joined the loyalty program", [edge("a.welcome")]),
      n("a.welcome", "action", "Email: Welcome + current tier/points + how to earn + first reward", [edge("a.area")], { execution: "communication", channelPriority: ch("email") }),
      n("a.area", "action", "In-app: Show the loyalty area and progress", [edge("c.first-earn")], { execution: "communication", channelPriority: ch("in-app") }),
      n("c.first-earn", "condition", "Has the member earned points for the first time?", [edge("a.progress", "Yes"), edge("w.3d", "No")], { branchCount: 2 }),
      n("w.3d", "wait", "Wait 3 days", [edge("a.earn-push")]),
      n("a.earn-push", "action", "Push: Earn your first points", [edge("c.earned-after")], { execution: "communication", channelPriority: ch("push") }),
      n("c.earned-after", "condition", "First points earned?", [edge("a.progress", "Yes"), edge("x.no-activation", "No")], { branchCount: 2 }),
      n("a.progress", "action", "Push / in-app: Show points earned and distance to first reward", [edge("c.reward")], { execution: "communication", channelPriority: ch("push", "in-app") }),
      n("c.reward", "condition", "Is the first reward available?", [edge("a.reward-email", "Yes"), edge("x.active", "Not yet")], { branchCount: 2 }),
      n("a.reward-email", "action", "Email: Your reward is ready", [edge("w.reward")], { execution: "communication", channelPriority: ch("email") }),
      n("w.reward", "wait", "Wait 5–7 days", [edge("c.redeemed")]),
      n("c.redeemed", "condition", "Was the reward used?", [edge("x.active", "Yes"), edge("a.reward-push", "No")], { branchCount: 2 }),
      n("a.reward-push", "action", "Push: Your reward is waiting", [edge("x.active")], { execution: "communication", channelPriority: ch("push") }),
      n("x.active", "exit", "Active loyalty member"),
      n("x.no-activation", "exit", "No first earn; journey closes"),
    ],
    tr: [
      n("t.joined", "trigger", "Sadakat programına katıldı", [edge("a.welcome")]),
      n("a.welcome", "action", "E-posta: Hoş geldin + mevcut seviye/puan + nasıl kazanılır + ilk ödül", [edge("a.area")], { execution: "communication", channelPriority: ch("email") }),
      n("a.area", "action", "In-app: Sadakat alanını ve ilerlemeyi göster", [edge("c.first-earn")], { execution: "communication", channelPriority: ch("in-app") }),
      n("c.first-earn", "condition", "İlk puan kazanıldı mı?", [edge("a.progress", "Evet"), edge("w.3d", "Hayır")], { branchCount: 2 }),
      n("w.3d", "wait", "3 gün bekle", [edge("a.earn-push")]),
      n("a.earn-push", "action", "Push: İlk puanını kazan", [edge("c.earned-after")], { execution: "communication", channelPriority: ch("push") }),
      n("c.earned-after", "condition", "İlk puan kazanıldı mı?", [edge("a.progress", "Evet"), edge("x.no-activation", "Hayır")], { branchCount: 2 }),
      n("a.progress", "action", "Push / in-app: Kazandığın puanı ve ilk ödüle ne kadar kaldığını göster", [edge("c.reward")], { execution: "communication", channelPriority: ch("push", "in-app") }),
      n("c.reward", "condition", "İlk ödül kullanılabilir mi?", [edge("a.reward-email", "Evet"), edge("x.active", "Henüz değil")], { branchCount: 2 }),
      n("a.reward-email", "action", "E-posta: Ödülün hazır", [edge("w.reward")], { execution: "communication", channelPriority: ch("email") }),
      n("w.reward", "wait", "5–7 gün bekle", [edge("c.redeemed")]),
      n("c.redeemed", "condition", "Ödül kullanıldı mı?", [edge("x.active", "Evet"), edge("a.reward-push", "Hayır")], { branchCount: 2 }),
      n("a.reward-push", "action", "Push: Ödülün seni bekliyor", [edge("x.active")], { execution: "communication", channelPriority: ch("push") }),
      n("x.active", "exit", "Aktif sadakat üyesi"),
      n("x.no-activation", "exit", "İlk kazanım olmadı; journey kapandı"),
    ],
  },

  "SUB-297": {
    channels: ch("push", "email"),
    en: [
      n("t.reward", "trigger", "Unused loyalty reward is available", [edge("w.3d")]),
      n("w.3d", "wait", "Wait 3 days", [edge("c.used1")]),
      n("c.used1", "condition", "Was the reward used?", [edge("x.used", "Yes"), edge("a.push", "No")], { branchCount: 2 }),
      n("a.push", "action", "Push: Your reward is waiting", [edge("w.2d")], { execution: "communication", channelPriority: ch("push") }),
      n("w.2d", "wait", "Wait 2 days", [edge("c.used2")]),
      n("c.used2", "condition", "Was the reward used?", [edge("x.used", "Yes"), edge("a.email", "No")], { branchCount: 2 }),
      n("a.email", "action", "Email: Reward + how to use it + expiry date", [edge("w.expiry")], { execution: "communication", channelPriority: ch("email") }),
      n("w.expiry", "wait", "Wait 3–7 days based on expiry", [edge("c.used3")]),
      n("c.used3", "condition", "Was the reward used?", [edge("x.used", "Yes"), edge("x.unused", "No")], { branchCount: 2 }),
      n("x.used", "exit", "Reward used"),
      n("x.unused", "exit", "Reward remained unused"),
    ],
    tr: [
      n("t.reward", "trigger", "Kullanılmayan sadakat ödülü kullanılabilir durumda", [edge("w.3d")]),
      n("w.3d", "wait", "3 gün bekle", [edge("c.used1")]),
      n("c.used1", "condition", "Ödül kullanıldı mı?", [edge("x.used", "Evet"), edge("a.push", "Hayır")], { branchCount: 2 }),
      n("a.push", "action", "Push: Ödülün seni bekliyor", [edge("w.2d")], { execution: "communication", channelPriority: ch("push") }),
      n("w.2d", "wait", "2 gün bekle", [edge("c.used2")]),
      n("c.used2", "condition", "Ödül kullanıldı mı?", [edge("x.used", "Evet"), edge("a.email", "Hayır")], { branchCount: 2 }),
      n("a.email", "action", "E-posta: Ödül + nasıl kullanılır + son kullanma tarihi", [edge("w.expiry")], { execution: "communication", channelPriority: ch("email") }),
      n("w.expiry", "wait", "Son kullanma tarihine göre 3–7 gün bekle", [edge("c.used3")]),
      n("c.used3", "condition", "Ödül kullanıldı mı?", [edge("x.used", "Evet"), edge("x.unused", "Hayır")], { branchCount: 2 }),
      n("x.used", "exit", "Ödül kullanıldı"),
      n("x.unused", "exit", "Ödül kullanılmadan kapandı"),
    ],
  },

  "RLT-279": {
    channels: ch("email", "push"),
    en: [
      n("t.started", "trigger", "Upgrade started but not completed", [edge("a.find")]),
      n("a.find", "action", "Identify the incomplete step", [edge("a.email")]),
      n("a.email", "action", "Email: One step remains to complete your upgrade", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "Wait 2–3 days", [edge("c.done1")]),
      n("c.done1", "condition", "Upgrade completed?", [edge("x.done", "Yes"), edge("a.push", "No")], { branchCount: 2 }),
      n("a.push", "action", "Push: Complete your upgrade", [edge("w.short")], { execution: "communication", channelPriority: ch("push") }),
      n("w.short", "wait", "Wait a short period", [edge("c.done2")]),
      n("c.done2", "condition", "Upgrade completed?", [edge("x.done", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("x.done", "exit", "Upgrade completed"),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.started", "trigger", "Upgrade süreci başladı ama tamamlanmadı", [edge("a.find")]),
      n("a.find", "action", "Eksik kalan adımı belirle", [edge("a.email")]),
      n("a.email", "action", "E-posta: Yükseltmeyi tamamlamak için son bir adım kaldı", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "2–3 gün bekle", [edge("c.done1")]),
      n("c.done1", "condition", "Yükseltme tamamlandı mı?", [edge("x.done", "Evet"), edge("a.push", "Hayır")], { branchCount: 2 }),
      n("a.push", "action", "Push: Yükseltmeni tamamla", [edge("w.short")], { execution: "communication", channelPriority: ch("push") }),
      n("w.short", "wait", "Kısa bir süre bekle", [edge("c.done2")]),
      n("c.done2", "condition", "Yükseltme tamamlandı mı?", [edge("x.done", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("x.done", "exit", "Yükseltme tamamlandı"),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "FIN-302": {
    channels: ch("email", "in-app", "push", "sms"),
    en: [
      n("t.refund", "trigger", "Refund approved", [edge("a.status")]),
      n("a.status", "action", "Email: Refund approved + amount + expected processing information", [edge("c.complete")], { execution: "communication", channelPriority: ch("email") }),
      n("c.complete", "condition", "Has the refund completed?", [edge("w.5d", "Yes"), edge("h.support", "No")], { branchCount: 2 }),
      n("h.support", "handoff", "Track the refund / support until completed"),
      n("w.5d", "wait", "Wait 3–5 days after completion", [edge("c.repurchase")]),
      n("c.repurchase", "condition", "Has the customer purchased again?", [edge("x.end", "Yes"), edge("a.alternatives", "No")], { branchCount: 2 }),
      n("a.alternatives", "action", "Email: Recommend better-fitting alternatives", [edge("w.2d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.2d", "wait", "Wait 2–3 days", [edge("c.buy2")]),
      n("c.buy2", "condition", "Purchased?", [edge("x.end", "Yes"), edge("a.inapp", "No")], { branchCount: 2 }),
      n("a.inapp", "action", "In-app / push: Personalized alternatives or a small return incentive", [edge("w.last")], { execution: "communication", channelPriority: ch("in-app", "push") }),
      n("w.last", "wait", "Wait a short period", [edge("c.buy3")]),
      n("c.buy3", "condition", "Purchased?", [edge("x.end", "Yes"), edge("a.sms", "No")], { branchCount: 2 }),
      n("a.sms", "action", "SMS: Final return-to-shop offer", [edge("x.end")], { execution: "communication", channelPriority: ch("sms") }),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.refund", "trigger", "İade onaylandı", [edge("a.status")]),
      n("a.status", "action", "E-posta: İade onayı + tutar + işlem bilgisi", [edge("c.complete")], { execution: "communication", channelPriority: ch("email") }),
      n("c.complete", "condition", "İade tamamlandı mı?", [edge("w.5d", "Evet"), edge("h.support", "Hayır")], { branchCount: 2 }),
      n("h.support", "handoff", "İade tamamlanana kadar durum takibi / destek"),
      n("w.5d", "wait", "Tamamlandıktan sonra 3–5 gün bekle", [edge("c.repurchase")]),
      n("c.repurchase", "condition", "Kullanıcı yeniden alışveriş yaptı mı?", [edge("x.end", "Evet"), edge("a.alternatives", "Hayır")], { branchCount: 2 }),
      n("a.alternatives", "action", "E-posta: Daha uygun alternatif ürünleri öner", [edge("w.2d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.2d", "wait", "2–3 gün bekle", [edge("c.buy2")]),
      n("c.buy2", "condition", "Satın aldı mı?", [edge("x.end", "Evet"), edge("a.inapp", "Hayır")], { branchCount: 2 }),
      n("a.inapp", "action", "In-app / Push: Kişiselleştirilmiş alternatif veya küçük geri dönüş avantajı", [edge("w.last")], { execution: "communication", channelPriority: ch("in-app", "push") }),
      n("w.last", "wait", "Kısa bir süre bekle", [edge("c.buy3")]),
      n("c.buy3", "condition", "Satın aldı mı?", [edge("x.end", "Evet"), edge("a.sms", "Hayır")], { branchCount: 2 }),
      n("a.sms", "action", "SMS: Son geri dönüş teklifi", [edge("x.end")], { execution: "communication", channelPriority: ch("sms") }),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "ACQ-09": {
    channels: ch("email", "push", "sales"),
    en: [
      n("t.lead", "trigger", "Lead captured / quote request received", [edge("c.ready")]),
      n("c.ready", "condition", "Ready to buy?", [edge("h.sales", "Yes"), edge("a.email1", "No")], { branchCount: 2 }),
      n("a.email1", "action", "Email: Explain benefits relevant to the lead's need", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "Wait 3 days", [edge("a.push")]),
      n("a.push", "action", "Push: Remind the product or service they showed interest in", [edge("w.5d")], { execution: "communication", channelPriority: ch("push") }),
      n("w.5d", "wait", "Wait 3–5 days", [edge("c.intent")]),
      n("c.intent", "condition", "Did the lead re-engage?", [edge("h.sales", "Quote / checkout"), edge("a.email2", "Content only"), edge("a.email2", "No action")], { branchCount: 3 }),
      n("a.email2", "action", "Email: Explain how the product works, who it fits and the main benefits", [edge("w.7d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.7d", "wait", "Wait 5–7 days", [edge("c.ready2")]),
      n("c.ready2", "condition", "Ready to buy now?", [edge("h.sales", "Yes"), edge("a.final", "Still interested"), edge("x.end", "No interest")], { branchCount: 3 }),
      n("a.final", "action", "Push: Final reminder", [edge("c.return")], { execution: "communication", channelPriority: ch("push") }),
      n("c.return", "condition", "Did they re-engage?", [edge("h.sales", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("h.sales", "handoff", "Move to sales / conversion"),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.lead", "trigger", "Aday müşteri oluştu / teklif talebi geldi", [edge("c.ready")]),
      n("c.ready", "condition", "Satın almaya hazır mı?", [edge("h.sales", "Evet"), edge("a.email1", "Hayır")], { branchCount: 2 }),
      n("a.email1", "action", "E-posta: İhtiyacına uygun faydaları anlat", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "3 gün bekle", [edge("a.push")]),
      n("a.push", "action", "Push: İlgilendiği ürün veya hizmeti hatırlat", [edge("w.5d")], { execution: "communication", channelPriority: ch("push") }),
      n("w.5d", "wait", "3–5 gün bekle", [edge("c.intent")]),
      n("c.intent", "condition", "Kullanıcı yeniden ilgilendi mi?", [edge("h.sales", "Teklif / checkout"), edge("a.email2", "Sadece içerik"), edge("a.email2", "Aksiyon yok")], { branchCount: 3 }),
      n("a.email2", "action", "E-posta: Ürünü daha detaylı anlat; nasıl çalışır, kimler için uygun, faydaları", [edge("w.7d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.7d", "wait", "5–7 gün bekle", [edge("c.ready2")]),
      n("c.ready2", "condition", "Satın almaya hazır hale geldi mi?", [edge("h.sales", "Evet"), edge("a.final", "Hayır ama ilgili"), edge("x.end", "İlgilenmiyor")], { branchCount: 3 }),
      n("a.final", "action", "Push: Son hatırlatma", [edge("c.return")], { execution: "communication", channelPriority: ch("push") }),
      n("c.return", "condition", "Tekrar ilgilendi mi?", [edge("h.sales", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("h.sales", "handoff", "Satış / conversion sürecine aktar"),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "ACT-20": {
    channels: ch("email", "push", "sms"),
    en: [
      n("t.first-open", "trigger", "first_open", [edge("w.10d")]),
      n("w.10d", "wait", "Wait 10 days", [edge("c.meaningful")]),
      n("c.meaningful", "condition", "Any meaningful action in the last 10 days?", [edge("x.active", "Yes"), edge("c.last", "No")], { branchCount: 2 }),
      n("c.last", "condition", "What was the last meaningful behavior?", [edge("a.email-close", "Close to purchase"), edge("a.push-interest", "Product / category interest"), edge("a.email-content", "Content only")], { branchCount: 3 }),
      n("a.email-close", "action", "Email: Continue where you left off + current offer / product update", [edge("w.response")], { execution: "communication", channelPriority: ch("email") }),
      n("a.push-interest", "action", "Push: There is something new in the product / feature you viewed", [edge("w.response")], { execution: "communication", channelPriority: ch("push") }),
      n("a.email-content", "action", "Email: Relevant use case / benefit content", [edge("w.response")], { execution: "communication", channelPriority: ch("email") }),
      n("w.response", "wait", "Wait 3–5 days", [edge("c.return")]),
      n("c.return", "condition", "Did they come back?", [edge("c.did", "Yes"), edge("a.sms", "No")], { branchCount: 2 }),
      n("c.did", "condition", "What did they do?", [edge("h.convert", "Checkout / purchase intent"), edge("h.sales", "Quote / demo"), edge("h.browse", "Browsed again"), edge("x.active", "Purchased")], { branchCount: 4 }),
      n("a.sms", "action", "SMS: Limited first-purchase incentive / return offer", [edge("w.offer")], { execution: "communication", channelPriority: ch("sms") }),
      n("w.offer", "wait", "Wait through the offer window", [edge("c.return2")]),
      n("c.return2", "condition", "Did they return?", [edge("c.did", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("h.convert", "handoff", "Move to conversion journey"),
      n("h.sales", "handoff", "Move to lead nurture / sales"),
      n("h.browse", "handoff", "Move to browse / interest journey"),
      n("x.active", "exit", "Active / converted"),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.first-open", "trigger", "first_open", [edge("w.10d")]),
      n("w.10d", "wait", "10 gün bekle", [edge("c.meaningful")]),
      n("c.meaningful", "condition", "Son 10 günde anlamlı bir aksiyon yaptı mı?", [edge("x.active", "Evet"), edge("c.last", "Hayır")], { branchCount: 2 }),
      n("c.last", "condition", "Son anlamlı davranışı neydi?", [edge("a.email-close", "Satın almaya çok yaklaştı"), edge("a.push-interest", "Ürün / kategori ilgisi"), edge("a.email-content", "Sadece içerik")], { branchCount: 3 }),
      n("a.email-close", "action", "E-posta: Kaldığın yerden devam et + güncel teklif / ürün gelişmesi", [edge("w.response")], { execution: "communication", channelPriority: ch("email") }),
      n("a.push-interest", "action", "Push: İlgilendiğin ürün veya özellikte yenilik var", [edge("w.response")], { execution: "communication", channelPriority: ch("push") }),
      n("a.email-content", "action", "E-posta: İlgi alanına göre use case / fayda anlat", [edge("w.response")], { execution: "communication", channelPriority: ch("email") }),
      n("w.response", "wait", "3–5 gün bekle", [edge("c.return")]),
      n("c.return", "condition", "Geri döndü mü?", [edge("c.did", "Evet"), edge("a.sms", "Hayır")], { branchCount: 2 }),
      n("c.did", "condition", "Ne yaptı?", [edge("h.convert", "Checkout / satın alma niyeti"), edge("h.sales", "Teklif / demo"), edge("h.browse", "Tekrar gezindi"), edge("x.active", "Satın aldı")], { branchCount: 4 }),
      n("a.sms", "action", "SMS: Sınırlı süreli ilk alışveriş indirimi / geri dönüş teşviki", [edge("w.offer")], { execution: "communication", channelPriority: ch("sms") }),
      n("w.offer", "wait", "Teklif süresi boyunca bekle", [edge("c.return2")]),
      n("c.return2", "condition", "Geri döndü mü?", [edge("c.did", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("h.convert", "handoff", "Conversion journey'sine aktar"),
      n("h.sales", "handoff", "Lead nurture / satış sürecine aktar"),
      n("h.browse", "handoff", "Browse / interest journey'sine aktar"),
      n("x.active", "exit", "Aktif / dönüştü"),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "ACC-261": {
    channels: ch("email", "push"),
    en: [
      n("t.overdue", "trigger", "Payment is overdue", [edge("a.email")]),
      n("a.email", "action", "Email: Payment delay notice + grace-period end date", [edge("w.lead")], { execution: "communication", channelPriority: ch("email") }),
      n("w.lead", "wait", "Wait until 3 days before the grace period ends", [edge("a.push")]),
      n("a.push", "action", "Push: Your access will be restricted soon", [edge("w.end")], { execution: "communication", channelPriority: ch("push") }),
      n("w.end", "wait", "Wait until the grace period ends", [edge("c.paid1")]),
      n("c.paid1", "condition", "Payment completed?", [edge("x.continue", "Yes"), edge("a.restrict", "No")], { branchCount: 2 }),
      n("a.restrict", "action", "Restrict access and send email / push explaining how to restore it", [edge("w.after")], { execution: "communication", channelPriority: ch("email", "push") }),
      n("w.after", "wait", "Wait 2–3 days", [edge("c.paid2")]),
      n("c.paid2", "condition", "Payment completed?", [edge("a.restore", "Yes"), edge("x.restricted", "No")], { branchCount: 2 }),
      n("a.restore", "action", "Restore access and confirm it", [edge("x.continue")], { execution: "communication", channelPriority: ch("email") }),
      n("x.continue", "exit", "Access continues / restored"),
      n("x.restricted", "exit", "Access remains restricted"),
    ],
    tr: [
      n("t.overdue", "trigger", "Ödeme gecikti", [edge("a.email")]),
      n("a.email", "action", "E-posta: Ödeme gecikmesi + ek sürenin biteceği tarih", [edge("w.lead")], { execution: "communication", channelPriority: ch("email") }),
      n("w.lead", "wait", "Ek sürenin bitmesine 3 gün kalana kadar bekle", [edge("a.push")]),
      n("a.push", "action", "Push: Erişimin yakında kısıtlanacak", [edge("w.end")], { execution: "communication", channelPriority: ch("push") }),
      n("w.end", "wait", "Ek süre sonuna kadar bekle", [edge("c.paid1")]),
      n("c.paid1", "condition", "Ödeme tamamlandı mı?", [edge("x.continue", "Evet"), edge("a.restrict", "Hayır")], { branchCount: 2 }),
      n("a.restrict", "action", "Erişimi kısıtla; e-posta + push ile nedeni ve geri açma yolunu bildir", [edge("w.after")], { execution: "communication", channelPriority: ch("email", "push") }),
      n("w.after", "wait", "2–3 gün bekle", [edge("c.paid2")]),
      n("c.paid2", "condition", "Ödeme tamamlandı mı?", [edge("a.restore", "Evet"), edge("x.restricted", "Hayır")], { branchCount: 2 }),
      n("a.restore", "action", "Erişimi geri aç ve kullanıcıya bildir", [edge("x.continue")], { execution: "communication", channelPriority: ch("email") }),
      n("x.continue", "exit", "Erişim devam ediyor / geri açıldı"),
      n("x.restricted", "exit", "Erişim kısıtlı kaldı"),
    ],
  },

  "ACQ-13": {
    channels: ch("push"),
    en: [
      n("t.view", "trigger", "Same product viewed at least twice", [edge("w.settle")]),
      n("w.settle", "wait", "Wait 6–24 hours", [edge("c.converted")]),
      n("c.converted", "condition", "Purchased or added to cart?", [edge("x.purchase", "Purchased"), edge("h.cart", "Added to cart"), edge("a.push", "Neither")], { branchCount: 3 }),
      n("a.push", "action", "Push: The product you viewed is still available", [edge("c.after")], { execution: "communication", channelPriority: ch("push") }),
      n("c.after", "condition", "What happened after the reminder?", [edge("x.purchase", "Purchased"), edge("h.cart", "Added to cart"), edge("x.end", "No action")], { branchCount: 3 }),
      n("h.cart", "handoff", "Move to cart abandonment / cart journey"),
      n("x.purchase", "exit", "Purchased"),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.view", "trigger", "Aynı ürün en az 2 kez görüntülendi", [edge("w.settle")]),
      n("w.settle", "wait", "6–24 saat bekle", [edge("c.converted")]),
      n("c.converted", "condition", "Satın aldı veya sepete ekledi mi?", [edge("x.purchase", "Satın aldı"), edge("h.cart", "Sepete ekledi"), edge("a.push", "Hayır")], { branchCount: 3 }),
      n("a.push", "action", "Push: Baktığın ürün hâlâ seni bekliyor", [edge("c.after")], { execution: "communication", channelPriority: ch("push") }),
      n("c.after", "condition", "Hatırlatma sonrası ne oldu?", [edge("x.purchase", "Satın aldı"), edge("h.cart", "Sepete ekledi"), edge("x.end", "Aksiyon yok")], { branchCount: 3 }),
      n("h.cart", "handoff", "Sepet journey'sine aktar"),
      n("x.purchase", "exit", "Satın aldı"),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "SUB-262": {
    channels: ch("email", "push"),
    en: [
      n("t.cancelled", "trigger", "Subscription cancellation confirmed", [edge("a.email1")]),
      n("a.email1", "action", "Email: Cancellation confirmation + access end date", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "Wait until 3 days before access ends", [edge("a.push")]),
      n("a.push", "action", "Push: Your access will end soon", [edge("w.end")], { execution: "communication", channelPriority: ch("push") }),
      n("w.end", "wait", "Wait until the access end date", [edge("c.active1")]),
      n("c.active1", "condition", "Subscription active again?", [edge("x.end", "Yes"), edge("a.offer", "No")], { branchCount: 2 }),
      n("a.offer", "action", "Email: Come-back discount / coupon", [edge("w.offer")], { execution: "communication", channelPriority: ch("email") }),
      n("w.offer", "wait", "Wait through the offer window", [edge("c.active2")]),
      n("c.active2", "condition", "Subscription active again?", [edge("x.end", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.cancelled", "trigger", "Abonelik iptali onaylandı", [edge("a.email1")]),
      n("a.email1", "action", "E-posta: İptal onayı + erişimin biteceği tarih", [edge("w.3d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.3d", "wait", "Bitişe 3 gün kalana kadar bekle", [edge("a.push")]),
      n("a.push", "action", "Push: Erişimin yakında sona erecek", [edge("w.end")], { execution: "communication", channelPriority: ch("push") }),
      n("w.end", "wait", "Bitiş tarihine kadar bekle", [edge("c.active1")]),
      n("c.active1", "condition", "Abonelik yeniden aktif mi?", [edge("x.end", "Evet"), edge("a.offer", "Hayır")], { branchCount: 2 }),
      n("a.offer", "action", "E-posta: Geri dönüş indirimi / kuponu", [edge("w.offer")], { execution: "communication", channelPriority: ch("email") }),
      n("w.offer", "wait", "Teklif süresi boyunca bekle", [edge("c.active2")]),
      n("c.active2", "condition", "Abonelik yeniden aktif mi?", [edge("x.end", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "CON-272": {
    channels: ch("email", "sms"),
    en: [
      n("t.closed", "trigger", "One or more marketing channel permissions are off", [edge("c.email")]),
      n("c.email", "condition", "Is email permission on?", [edge("c.sms-if-email", "Yes"), edge("c.sms-if-no-email", "No")], { branchCount: 2 }),
      n("c.sms-if-email", "condition", "Is SMS permission on?", [edge("x.open", "Yes"), edge("a.email", "No")], { branchCount: 2 }),
      n("c.sms-if-no-email", "condition", "Is SMS permission on?", [edge("a.sms", "Yes"), edge("x.none", "No")], { branchCount: 2 }),
      n("a.email", "action", "Email: Ask the user to re-enable SMS permission", [edge("x.end")], { execution: "communication", channelPriority: ch("email") }),
      n("a.sms", "action", "SMS: Ask the user to re-enable email permission", [edge("x.end")], { execution: "communication", channelPriority: ch("sms") }),
      n("x.open", "exit", "Both channels already available"),
      n("x.none", "exit", "No email or SMS permission; do not contact"),
      n("x.end", "exit", "Permission-reopen request sent"),
    ],
    tr: [
      n("t.closed", "trigger", "E-posta veya SMS iletişim izni kapalı", [edge("c.email")]),
      n("c.email", "condition", "E-posta izni açık mı?", [edge("c.sms-if-email", "Evet"), edge("c.sms-if-no-email", "Hayır")], { branchCount: 2 }),
      n("c.sms-if-email", "condition", "SMS izni açık mı?", [edge("x.open", "Evet"), edge("a.email", "Hayır")], { branchCount: 2 }),
      n("c.sms-if-no-email", "condition", "SMS izni açık mı?", [edge("a.sms", "Evet"), edge("x.none", "Hayır")], { branchCount: 2 }),
      n("a.email", "action", "E-posta: SMS iznini yeniden açmasını iste", [edge("x.end")], { execution: "communication", channelPriority: ch("email") }),
      n("a.sms", "action", "SMS: E-posta iznini yeniden açmasını iste", [edge("x.end")], { execution: "communication", channelPriority: ch("sms") }),
      n("x.open", "exit", "İki kanal da zaten açık"),
      n("x.none", "exit", "E-posta ve SMS izni yok; iletişim kurma"),
      n("x.end", "exit", "İzin açma talebi gönderildi"),
    ],
  },

  "FIN-134": {
    channels: ch("email", "push", "in-app", "whatsapp"),
    en: [
      n("t.failure", "trigger", "Payment failed", [edge("c.reason")]),
      n("c.reason", "condition", "Why did the payment fail?", [
        edge("a.balance", "Insufficient balance"),
        edge("a.expired", "Expired card"),
        edge("a.3ds", "3D Secure / verification"),
        edge("a.bank", "Bank decline / payment-method issue"),
        edge("w.retry", "Temporary system error"),
        edge("a.unknown", "Unknown"),
      ], { branchCount: 6 }),
      n("a.balance", "action", "Push: Check balance or try another card", [edge("w.1d")], { execution: "communication", channelPriority: ch("push") }),
      n("a.expired", "action", "Email: Update your card details", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("a.3ds", "action", "In-app: Retry verification", [edge("w.1d")], { execution: "communication", channelPriority: ch("in-app") }),
      n("a.bank", "action", "Email: Try another payment method", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.retry", "wait", "Wait briefly and retry automatically", [edge("w.1d")]),
      n("a.unknown", "action", "Offer an alternative payment method or support", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.1d", "wait", "Wait 1 day", [edge("c.paid1")]),
      n("c.paid1", "condition", "Payment completed?", [edge("x.paid", "Yes"), edge("a.wa", "No")], { branchCount: 2 }),
      n("a.wa", "action", "WhatsApp: Complete payment with an alternative method", [edge("w.2d")], { execution: "communication", channelPriority: ch("whatsapp") }),
      n("w.2d", "wait", "Wait 1–2 days", [edge("c.paid2")]),
      n("c.paid2", "condition", "Payment completed?", [edge("x.paid", "Yes"), edge("c.valid", "No")], { branchCount: 2 }),
      n("c.valid", "condition", "Is the transaction / reservation / membership still valid?", [edge("a.final", "Yes"), edge("x.end", "No")], { branchCount: 2 }),
      n("a.final", "action", "Email: Final payment reminder", [edge("x.end")], { execution: "communication", channelPriority: ch("email") }),
      n("x.paid", "exit", "Payment completed"),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.failure", "trigger", "Ödeme başarısız oldu", [edge("c.reason")]),
      n("c.reason", "condition", "Ödeme neden başarısız oldu?", [
        edge("a.balance", "Yetersiz bakiye"),
        edge("a.expired", "Kartın süresi dolmuş"),
        edge("a.3ds", "3D Secure / doğrulama"),
        edge("a.bank", "Banka reddi / ödeme yöntemi"),
        edge("w.retry", "Geçici sistem hatası"),
        edge("a.unknown", "Neden bilinmiyor"),
      ], { branchCount: 6 }),
      n("a.balance", "action", "Push: Bakiyeyi kontrol et veya başka kart dene", [edge("w.1d")], { execution: "communication", channelPriority: ch("push") }),
      n("a.expired", "action", "E-posta: Kart bilgilerini güncelle", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("a.3ds", "action", "In-app: Doğrulamayı tekrar dene", [edge("w.1d")], { execution: "communication", channelPriority: ch("in-app") }),
      n("a.bank", "action", "E-posta: Başka bir ödeme yöntemi dene", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.retry", "wait", "Kısa süre bekle ve otomatik tekrar dene", [edge("w.1d")]),
      n("a.unknown", "action", "Alternatif ödeme yöntemi veya destek sun", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.1d", "wait", "1 gün bekle", [edge("c.paid1")]),
      n("c.paid1", "condition", "Ödeme tamamlandı mı?", [edge("x.paid", "Evet"), edge("a.wa", "Hayır")], { branchCount: 2 }),
      n("a.wa", "action", "WhatsApp: Alternatif yöntemle ödemeni tamamla", [edge("w.2d")], { execution: "communication", channelPriority: ch("whatsapp") }),
      n("w.2d", "wait", "1–2 gün bekle", [edge("c.paid2")]),
      n("c.paid2", "condition", "Ödeme tamamlandı mı?", [edge("x.paid", "Evet"), edge("c.valid", "Hayır")], { branchCount: 2 }),
      n("c.valid", "condition", "İşlem / rezervasyon / üyelik hâlâ geçerli mi?", [edge("a.final", "Evet"), edge("x.end", "Hayır")], { branchCount: 2 }),
      n("a.final", "action", "E-posta: Son ödeme hatırlatması", [edge("x.end")], { execution: "communication", channelPriority: ch("email") }),
      n("x.paid", "exit", "Ödeme tamamlandı"),
      n("x.end", "exit", "Journey bitti"),
    ],
  },

  "FUL-148": {
    channels: ch("email", "push", "sms", "whatsapp"),
    en: [
      n("t.failed", "trigger", "Delivery attempt failed", [edge("c.reason")]),
      n("c.reason", "condition", "Why did delivery fail?", [
        edge("a.address", "Wrong / missing address"),
        edge("a.absent", "Customer unavailable"),
        edge("a.ops", "Courier / operational issue"),
        edge("a.alternative", "Delivery not possible"),
      ], { branchCount: 4 }),
      n("a.address", "action", "Email: Update the delivery address", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("a.absent", "action", "Push: Choose a new delivery time", [edge("w.1d")], { execution: "communication", channelPriority: ch("push") }),
      n("a.ops", "action", "Email: Apology + new delivery date", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("a.alternative", "action", "Offer an alternative pickup point or refund", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.1d", "wait", "Wait 1 day", [edge("c.replanned")]),
      n("c.replanned", "condition", "Was delivery rescheduled?", [edge("c.delivered", "Yes"), edge("a.final", "No")], { branchCount: 2 }),
      n("a.final", "action", "SMS / WhatsApp: Final reminder to reschedule or choose an alternative", [edge("c.delivered")], { execution: "communication", channelPriority: ch("sms", "whatsapp") }),
      n("c.delivered", "condition", "Was delivery completed successfully?", [edge("x.done", "Yes"), edge("h.resolve", "No")], { branchCount: 2 }),
      n("h.resolve", "handoff", "Move to refund / support / alternative-delivery resolution"),
      n("x.done", "exit", "Delivery completed"),
    ],
    tr: [
      n("t.failed", "trigger", "Teslimat başarısız oldu", [edge("c.reason")]),
      n("c.reason", "condition", "Teslimat neden başarısız oldu?", [
        edge("a.address", "Adres hatalı / eksik"),
        edge("a.absent", "Müşteri adreste yoktu"),
        edge("a.ops", "Kurye / operasyon kaynaklı"),
        edge("a.alternative", "Teslimat mümkün değil"),
      ], { branchCount: 4 }),
      n("a.address", "action", "E-posta: Adresi güncelle", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("a.absent", "action", "Push: Yeni teslimat zamanı seç", [edge("w.1d")], { execution: "communication", channelPriority: ch("push") }),
      n("a.ops", "action", "E-posta: Özür + yeni teslimat tarihi", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("a.alternative", "action", "Alternatif teslimat noktası veya iade seçeneği sun", [edge("w.1d")], { execution: "communication", channelPriority: ch("email") }),
      n("w.1d", "wait", "1 gün bekle", [edge("c.replanned")]),
      n("c.replanned", "condition", "Teslimat yeniden planlandı mı?", [edge("c.delivered", "Evet"), edge("a.final", "Hayır")], { branchCount: 2 }),
      n("a.final", "action", "SMS / WhatsApp: Yeniden planlama veya alternatif için son hatırlatma", [edge("c.delivered")], { execution: "communication", channelPriority: ch("sms", "whatsapp") }),
      n("c.delivered", "condition", "Teslimat başarıyla tamamlandı mı?", [edge("x.done", "Evet"), edge("h.resolve", "Hayır")], { branchCount: 2 }),
      n("h.resolve", "handoff", "İade / destek / alternatif teslimat çözümüne aktar"),
      n("x.done", "exit", "Teslimat tamamlandı"),
    ],
  },

  "RSK-273": {
    channels: ch("in-app", "email", "push"),
    en: [
      n("t.limit", "trigger", "Usage limit reached", [edge("a.explain")]),
      n("a.explain", "action", "In-app: Explain the limit, reset time and available options", [edge("c.alternative")], { execution: "communication", channelPriority: ch("in-app") }),
      n("c.alternative", "condition", "Is there an alternative way to continue now?", [edge("a.alt", "Yes"), edge("c.upgrade", "No")], { branchCount: 2 }),
      n("a.alt", "action", "In-app: Continue with the available alternative", [edge("x.end")], { execution: "communication", channelPriority: ch("in-app") }),
      n("c.upgrade", "condition", "Would a higher plan increase the limit?", [edge("a.upgrade", "Yes"), edge("w.reset", "No")], { branchCount: 2 }),
      n("a.upgrade", "action", "In-app / email: Show the upgrade option", [edge("w.reset")], { execution: "communication", channelPriority: ch("in-app", "email") }),
      n("w.reset", "wait", "Wait until the usage limit resets", [edge("a.reset")]),
      n("a.reset", "action", "Push: Your usage allowance has renewed", [edge("x.end")], { execution: "communication", channelPriority: ch("push") }),
      n("x.end", "exit", "Journey ends"),
    ],
    tr: [
      n("t.limit", "trigger", "Kullanım limitine ulaşıldı", [edge("a.explain")]),
      n("a.explain", "action", "In-app: Hangi limite ulaşıldığını, ne zaman yenileneceğini ve seçenekleri göster", [edge("c.alternative")], { execution: "communication", channelPriority: ch("in-app") }),
      n("c.alternative", "condition", "Şimdi devam edebileceği alternatif bir yol var mı?", [edge("a.alt", "Evet"), edge("c.upgrade", "Hayır")], { branchCount: 2 }),
      n("a.alt", "action", "In-app: Mevcut alternatifle devam et", [edge("x.end")], { execution: "communication", channelPriority: ch("in-app") }),
      n("c.upgrade", "condition", "Daha yüksek paket limiti artırıyor mu?", [edge("a.upgrade", "Evet"), edge("w.reset", "Hayır")], { branchCount: 2 }),
      n("a.upgrade", "action", "In-app / E-posta: Paket yükseltme seçeneğini göster", [edge("w.reset")], { execution: "communication", channelPriority: ch("in-app", "email") }),
      n("w.reset", "wait", "Limit yenilenme zamanına kadar bekle", [edge("a.reset")]),
      n("a.reset", "action", "Push: Kullanım hakkın yenilendi", [edge("x.end")], { execution: "communication", channelPriority: ch("push") }),
      n("x.end", "exit", "Journey bitti"),
    ],
  },
};

export function publicJourneyFlowOverride(id: string, lang: Lang): FlowSpec | null {
  const spec = SPECS[id];
  if (!spec) return null;
  return spec;
}

export function publicJourneyFlowNodes(id: string, lang: Lang): readonly FlowNode[] | null {
  const spec = SPECS[id];
  return spec ? spec[lang] : null;
}

export function publicJourneyFlowChannels(id: string): readonly ChannelId[] | null {
  return SPECS[id]?.channels ?? null;
}
