/* GENERATED by scripts/fetch-numerspace-catalog.mjs on 2026-09-06 from
   numerspace.com's own sitemap and category pages - do not edit by hand,
   re-run the script. Every name, description and link is the site's own. */

export type NumerspaceCalculator = { slug: string; name: string; description: string; href: string };
export type NumerspaceCategory = { slug: string; name: string; href: string; count: number; items: NumerspaceCalculator[] };

export const NUMERSPACE_CATALOG: Record<"en" | "tr", NumerspaceCategory[]> = {
  "en": [
    {
      "slug": "finance-investment",
      "name": "Finance & Investment Calculators",
      "href": "https://www.numerspace.com/en/finance-investment",
      "count": 8,
      "items": [
        {
          "slug": "loan-calculator",
          "name": "Loan Calculator",
          "description": "Monthly payment, total repayment and amortization schedule",
          "href": "https://www.numerspace.com/en/finance-investment/loan-calculator"
        },
        {
          "slug": "deposit-return-calculator",
          "name": "Deposit Interest Calculator",
          "description": "Net yield and 15% withholding tax calculation",
          "href": "https://www.numerspace.com/en/finance-investment/deposit-return-calculator"
        },
        {
          "slug": "rent-increase-calculator",
          "name": "Rent Increase Calculator",
          "description": "CPI-based rent increase rate and new rental amount",
          "href": "https://www.numerspace.com/en/finance-investment/rent-increase-calculator"
        },
        {
          "slug": "dividend-calculator",
          "name": "Dividend Calculator",
          "description": "Dividend yield and net income calculation",
          "href": "https://www.numerspace.com/en/finance-investment/dividend-calculator"
        },
        {
          "slug": "inflation-calculator",
          "name": "Inflation Calculator",
          "description": "Purchasing power and inflation impact based on CPI",
          "href": "https://www.numerspace.com/en/finance-investment/inflation-calculator"
        },
        {
          "slug": "gold-crypto-exchange-calculator",
          "name": "Gold, Crypto & Currency Calculator",
          "description": "Convert gold, Bitcoin and currencies at live prices",
          "href": "https://www.numerspace.com/en/finance-investment/gold-crypto-exchange-calculator"
        },
        {
          "slug": "credit-card-minimum-payment-calculator",
          "name": "Credit Card Minimum Payment Calculator",
          "description": "Total cost and payoff time with minimum payments",
          "href": "https://www.numerspace.com/en/finance-investment/credit-card-minimum-payment-calculator"
        },
        {
          "slug": "wedding-budget-calculator",
          "name": "Wedding Budget Calculator",
          "description": "Wedding expenses and cost per person planning",
          "href": "https://www.numerspace.com/en/finance-investment/wedding-budget-calculator"
        }
      ]
    },
    {
      "slug": "health-fitness",
      "name": "Health & Fitness Calculators",
      "href": "https://www.numerspace.com/en/health-fitness",
      "count": 15,
      "items": [
        {
          "slug": "bmi-calculator",
          "name": "BMI Calculator",
          "description": "Body mass index and healthy weight range",
          "href": "https://www.numerspace.com/en/health-fitness/bmi-calculator"
        },
        {
          "slug": "daily-calorie-calculator",
          "name": "Daily Calorie Need Calculator",
          "description": "BMR and TDEE calculation (Mifflin-St Jeor)",
          "href": "https://www.numerspace.com/en/health-fitness/daily-calorie-calculator"
        },
        {
          "slug": "ideal-weight-calculator",
          "name": "Ideal Weight Calculator",
          "description": "Ideal weight via Devine, Hamwi and BMI formulas",
          "href": "https://www.numerspace.com/en/health-fitness/ideal-weight-calculator"
        },
        {
          "slug": "basal-metabolic-rate-calculator",
          "name": "Basal Metabolic Rate Calculator",
          "description": "Daily calorie needs at rest (BMR)",
          "href": "https://www.numerspace.com/en/health-fitness/basal-metabolic-rate-calculator"
        },
        {
          "slug": "daily-water-intake-calculator",
          "name": "Daily Water Intake Calculator",
          "description": "Daily water needs by weight and activity level",
          "href": "https://www.numerspace.com/en/health-fitness/daily-water-intake-calculator"
        },
        {
          "slug": "pregnancy-calculator",
          "name": "Pregnancy Calculator",
          "description": "Estimated due date and week from last period",
          "href": "https://www.numerspace.com/en/health-fitness/pregnancy-calculator"
        },
        {
          "slug": "quit-smoking-calculator",
          "name": "Quit Smoking Savings Calculator",
          "description": "Money saved and health gains after quitting smoking",
          "href": "https://www.numerspace.com/en/health-fitness/quit-smoking-calculator"
        },
        {
          "slug": "protein-intake-calculator",
          "name": "Protein Intake Calculator",
          "description": "Daily protein needs based on body weight",
          "href": "https://www.numerspace.com/en/health-fitness/protein-intake-calculator"
        },
        {
          "slug": "maximum-heart-rate-calculator",
          "name": "Maximum Heart Rate Calculator",
          "description": "Maximum and target heart rate range by age",
          "href": "https://www.numerspace.com/en/health-fitness/maximum-heart-rate-calculator"
        },
        {
          "slug": "calorie-burn-calculator",
          "name": "Calorie Burn Calculator",
          "description": "Calories burned by exercise type and duration",
          "href": "https://www.numerspace.com/en/health-fitness/calorie-burn-calculator"
        },
        {
          "slug": "jump-rope-calorie-calculator",
          "name": "Jump Rope Calorie Calculator",
          "description": "Calories burned jumping rope",
          "href": "https://www.numerspace.com/en/health-fitness/jump-rope-calorie-calculator"
        },
        {
          "slug": "stair-climbing-calorie-calculator",
          "name": "Stair Climbing Calorie Calculator",
          "description": "Calories burned climbing stairs",
          "href": "https://www.numerspace.com/en/health-fitness/stair-climbing-calorie-calculator"
        },
        {
          "slug": "swimming-calorie-calculator",
          "name": "Swimming Calorie Calculator",
          "description": "Calories burned by swimming style and duration",
          "href": "https://www.numerspace.com/en/health-fitness/swimming-calorie-calculator"
        },
        {
          "slug": "lean-body-mass-calculator",
          "name": "Lean Body Mass Calculator",
          "description": "Body mass excluding fat tissue",
          "href": "https://www.numerspace.com/en/health-fitness/lean-body-mass-calculator"
        },
        {
          "slug": "hair-growth-calculator",
          "name": "Hair Growth Calculator",
          "description": "Hair growth time and target length calculation",
          "href": "https://www.numerspace.com/en/health-fitness/hair-growth-calculator"
        }
      ]
    },
    {
      "slug": "business-career",
      "name": "Work & Career Calculators",
      "href": "https://www.numerspace.com/en/business-career",
      "count": 7,
      "items": [
        {
          "slug": "salary-calculator",
          "name": "Salary Calculator",
          "description": "All SGK and tax deductions from gross to net salary",
          "href": "https://www.numerspace.com/en/business-career/salary-calculator"
        },
        {
          "slug": "annual-leave-calculator",
          "name": "Annual Leave Calculator",
          "description": "Annual leave entitlement and balance by seniority",
          "href": "https://www.numerspace.com/en/business-career/annual-leave-calculator"
        },
        {
          "slug": "overtime-calculator",
          "name": "Overtime Pay Calculator",
          "description": "Overtime wage calculation based on hourly rate",
          "href": "https://www.numerspace.com/en/business-career/overtime-calculator"
        },
        {
          "slug": "notice-period-calculator",
          "name": "Notice Period Calculator",
          "description": "Notice period and severance by length of service",
          "href": "https://www.numerspace.com/en/business-career/notice-period-calculator"
        },
        {
          "slug": "vat-calculator",
          "name": "VAT Calculator",
          "description": "Calculate price with or without VAT",
          "href": "https://www.numerspace.com/en/business-career/vat-calculator"
        },
        {
          "slug": "withholding-tax-calculator",
          "name": "Withholding Tax Calculator",
          "description": "Withholding tax for rent and freelance income",
          "href": "https://www.numerspace.com/en/business-career/withholding-tax-calculator"
        },
        {
          "slug": "salary-raise-calculator",
          "name": "Salary Raise Calculator",
          "description": "Salary raise with inflation and percentage",
          "href": "https://www.numerspace.com/en/business-career/salary-raise-calculator"
        }
      ]
    },
    {
      "slug": "time-date",
      "name": "Time & Date Calculators",
      "href": "https://www.numerspace.com/en/time-date",
      "count": 8,
      "items": [
        {
          "slug": "age-calculator",
          "name": "Age Calculator",
          "description": "Exact age in years, days and weeks from birth date",
          "href": "https://www.numerspace.com/en/time-date/age-calculator"
        },
        {
          "slug": "date-difference-calculator",
          "name": "Date Difference Calculator",
          "description": "Days, weeks, months, years and business days between dates",
          "href": "https://www.numerspace.com/en/time-date/date-difference-calculator"
        },
        {
          "slug": "time-difference-calculator",
          "name": "Time Difference Calculator",
          "description": "Calculate the difference between two times",
          "href": "https://www.numerspace.com/en/time-date/time-difference-calculator"
        },
        {
          "slug": "business-days-calculator",
          "name": "Business Days Calculator",
          "description": "Add business days to a start date to find the end date",
          "href": "https://www.numerspace.com/en/time-date/business-days-calculator"
        },
        {
          "slug": "day-of-birth-calculator",
          "name": "Day of Birth Calculator",
          "description": "Find the day of the week you were born",
          "href": "https://www.numerspace.com/en/time-date/day-of-birth-calculator"
        },
        {
          "slug": "world-clocks",
          "name": "World Clocks",
          "description": "Current time in cities around the world",
          "href": "https://www.numerspace.com/en/time-date/world-clocks"
        },
        {
          "slug": "stopwatch",
          "name": "Stopwatch",
          "description": "Online stopwatch and countdown timer",
          "href": "https://www.numerspace.com/en/time-date/stopwatch"
        },
        {
          "slug": "roman-numeral-date-converter",
          "name": "Roman Numeral Date Converter",
          "description": "Convert dates to Roman numerals",
          "href": "https://www.numerspace.com/en/time-date/roman-numeral-date-converter"
        }
      ]
    },
    {
      "slug": "math-converter",
      "name": "Math & Converter Calculators",
      "href": "https://www.numerspace.com/en/math-converter",
      "count": 13,
      "items": [
        {
          "slug": "percentage-calculator",
          "name": "Percentage Calculator",
          "description": "Percentage increase, decrease and ratio calculations",
          "href": "https://www.numerspace.com/en/math-converter/percentage-calculator"
        },
        {
          "slug": "standard-deviation-calculator",
          "name": "Standard Deviation Calculator",
          "description": "Standard deviation and variance of a data set",
          "href": "https://www.numerspace.com/en/math-converter/standard-deviation-calculator"
        },
        {
          "slug": "calculator",
          "name": "Calculator",
          "description": "Calculator for basic arithmetic operations",
          "href": "https://www.numerspace.com/en/math-converter/calculator"
        },
        {
          "slug": "scientific-calculator",
          "name": "Scientific Calculator",
          "description": "Trigonometry, logarithm and exponent calculations",
          "href": "https://www.numerspace.com/en/math-converter/scientific-calculator"
        },
        {
          "slug": "mean-median-mode-calculator",
          "name": "Mean, Median, Mode Calculator",
          "description": "Statistical central tendency measures",
          "href": "https://www.numerspace.com/en/math-converter/mean-median-mode-calculator"
        },
        {
          "slug": "square-meter-calculator",
          "name": "Square Meter Calculator",
          "description": "Calculate room and area in square meters",
          "href": "https://www.numerspace.com/en/math-converter/square-meter-calculator"
        },
        {
          "slug": "weight-converter",
          "name": "Weight Converter",
          "description": "Convert between kg, pounds, ounces, grams and tonnes",
          "href": "https://www.numerspace.com/en/math-converter/weight-converter"
        },
        {
          "slug": "length-converter",
          "name": "Length Converter",
          "description": "Convert meters, miles, inches, feet, yards, km",
          "href": "https://www.numerspace.com/en/math-converter/length-converter"
        },
        {
          "slug": "dimensional-weight-calculator",
          "name": "Dimensional Weight Calculator",
          "description": "Dimensional weight for shipping and cargo",
          "href": "https://www.numerspace.com/en/math-converter/dimensional-weight-calculator"
        },
        {
          "slug": "roman-numeral-converter",
          "name": "Roman Numeral Converter",
          "description": "Convert numbers to Roman numerals",
          "href": "https://www.numerspace.com/en/math-converter/roman-numeral-converter"
        },
        {
          "slug": "random-number-generator",
          "name": "Random Number Generator",
          "description": "Generate random numbers for draws and games",
          "href": "https://www.numerspace.com/en/math-converter/random-number-generator"
        },
        {
          "slug": "password-combination-calculator",
          "name": "Password Combination Calculator",
          "description": "Password security strength and combination count",
          "href": "https://www.numerspace.com/en/math-converter/password-combination-calculator"
        },
        {
          "slug": "coin-flip",
          "name": "Coin Flip",
          "description": "Digital coin toss simulator",
          "href": "https://www.numerspace.com/en/math-converter/coin-flip"
        }
      ]
    },
    {
      "slug": "education-productivity",
      "name": "Education & Productivity Tools",
      "href": "https://www.numerspace.com/en/education-productivity",
      "count": 4,
      "items": [
        {
          "slug": "gpa-calculator",
          "name": "University GPA Calculator",
          "description": "GPA and cumulative GPA from course grades and credits",
          "href": "https://www.numerspace.com/en/education-productivity/gpa-calculator"
        },
        {
          "slug": "reading-time-calculator",
          "name": "Reading Time Calculator",
          "description": "Estimated reading time based on text length",
          "href": "https://www.numerspace.com/en/education-productivity/reading-time-calculator"
        },
        {
          "slug": "typing-speed-calculator",
          "name": "Typing Speed Calculator",
          "description": "WPM and words-per-minute typing speed test",
          "href": "https://www.numerspace.com/en/education-productivity/typing-speed-calculator"
        },
        {
          "slug": "pomodoro-timer",
          "name": "Pomodoro Timer",
          "description": "Productivity technique with 25-min focus and 5-min break",
          "href": "https://www.numerspace.com/en/education-productivity/pomodoro-timer"
        }
      ]
    },
    {
      "slug": "home-living",
      "name": "Home & Living Calculators",
      "href": "https://www.numerspace.com/en/home-living",
      "count": 6,
      "items": [
        {
          "slug": "paint-calculator",
          "name": "Paint Calculator",
          "description": "Paint quantity needed based on room size and coats",
          "href": "https://www.numerspace.com/en/home-living/paint-calculator"
        },
        {
          "slug": "electricity-bill-calculator",
          "name": "Electricity Bill Calculator",
          "description": "Device power, usage time and energy cost",
          "href": "https://www.numerspace.com/en/home-living/electricity-bill-calculator"
        },
        {
          "slug": "tv-size-calculator",
          "name": "TV Size Calculator",
          "description": "Ideal TV size based on viewing distance",
          "href": "https://www.numerspace.com/en/home-living/tv-size-calculator"
        },
        {
          "slug": "tv-mount-height-calculator",
          "name": "TV Mount Height Calculator",
          "description": "Ideal TV mount height based on room size",
          "href": "https://www.numerspace.com/en/home-living/tv-mount-height-calculator"
        },
        {
          "slug": "curtain-size-calculator",
          "name": "Curtain Size Calculator",
          "description": "Curtain length and width from window measurements",
          "href": "https://www.numerspace.com/en/home-living/curtain-size-calculator"
        },
        {
          "slug": "lighting-calculator",
          "name": "Lighting Calculator",
          "description": "Lumens and bulb count needed for room size",
          "href": "https://www.numerspace.com/en/home-living/lighting-calculator"
        }
      ]
    },
    {
      "slug": "clothing-size",
      "name": "Clothing & Size Calculators",
      "href": "https://www.numerspace.com/en/clothing-size",
      "count": 4,
      "items": [
        {
          "slug": "bra-size-calculator",
          "name": "Bra Size Calculator",
          "description": "Bra size from bust and underbust measurements",
          "href": "https://www.numerspace.com/en/clothing-size/bra-size-calculator"
        },
        {
          "slug": "belt-size-calculator",
          "name": "Belt Size Calculator",
          "description": "Correct belt size from waist measurement",
          "href": "https://www.numerspace.com/en/clothing-size/belt-size-calculator"
        },
        {
          "slug": "jacket-size-calculator",
          "name": "Jacket Size Calculator",
          "description": "Jacket and suit size from chest measurement",
          "href": "https://www.numerspace.com/en/clothing-size/jacket-size-calculator"
        },
        {
          "slug": "body-type-calculator",
          "name": "Body Type Calculator",
          "description": "Body type analysis based on measurements",
          "href": "https://www.numerspace.com/en/clothing-size/body-type-calculator"
        }
      ]
    },
    {
      "slug": "marketing-analytics",
      "name": "Marketing & Analytics Calculators",
      "href": "https://www.numerspace.com/en/marketing-analytics",
      "count": 17,
      "items": [
        {
          "slug": "roas-calculator",
          "name": "ROAS Calculator",
          "description": "Return on ad spend calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/roas-calculator"
        },
        {
          "slug": "cr-calculator",
          "name": "Conversion Rate (CR) Calculator",
          "description": "Visitor-to-customer conversion rate",
          "href": "https://www.numerspace.com/en/marketing-analytics/cr-calculator"
        },
        {
          "slug": "cac-calculator",
          "name": "CAC Calculator",
          "description": "Customer acquisition cost calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/cac-calculator"
        },
        {
          "slug": "ltv-calculator",
          "name": "LTV Calculator",
          "description": "Customer lifetime value calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/ltv-calculator"
        },
        {
          "slug": "ctr-calculator",
          "name": "CTR Calculator",
          "description": "Click-through rate and ad performance",
          "href": "https://www.numerspace.com/en/marketing-analytics/ctr-calculator"
        },
        {
          "slug": "cpc-calculator",
          "name": "CPC Calculator",
          "description": "Cost per click and ad performance",
          "href": "https://www.numerspace.com/en/marketing-analytics/cpc-calculator"
        },
        {
          "slug": "cpm-calculator",
          "name": "CPM Calculator",
          "description": "Cost per thousand impressions calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/cpm-calculator"
        },
        {
          "slug": "cpl-calculator",
          "name": "CPL Calculator",
          "description": "Cost per lead calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/cpl-calculator"
        },
        {
          "slug": "aov-calculator",
          "name": "AOV Calculator",
          "description": "Average order value calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/aov-calculator"
        },
        {
          "slug": "ab-test-calculator",
          "name": "A/B Test Calculator",
          "description": "Statistical significance and conversion rate analysis",
          "href": "https://www.numerspace.com/en/marketing-analytics/ab-test-calculator"
        },
        {
          "slug": "marketing-roi-calculator",
          "name": "Marketing ROI Calculator",
          "description": "Marketing return on investment calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/marketing-roi-calculator"
        },
        {
          "slug": "profit-margin-calculator",
          "name": "Profit Margin Calculator",
          "description": "Gross and net profit margin calculation",
          "href": "https://www.numerspace.com/en/marketing-analytics/profit-margin-calculator"
        },
        {
          "slug": "customer-retention-rate-calculator",
          "name": "Customer Retention Rate Calculator",
          "description": "Customer loyalty and churn rate analysis",
          "href": "https://www.numerspace.com/en/marketing-analytics/customer-retention-rate-calculator"
        },
        {
          "slug": "cart-abandonment-calculator",
          "name": "Cart Abandonment Calculator",
          "description": "E-commerce cart abandonment rate analysis",
          "href": "https://www.numerspace.com/en/marketing-analytics/cart-abandonment-calculator"
        },
        {
          "slug": "web-engagement-rate-calculator",
          "name": "Web Engagement Rate Calculator",
          "description": "Page engagement and retention rate",
          "href": "https://www.numerspace.com/en/marketing-analytics/web-engagement-rate-calculator"
        },
        {
          "slug": "utm-builder",
          "name": "UTM Builder",
          "description": "Create UTM-tagged URLs for campaign tracking",
          "href": "https://www.numerspace.com/en/marketing-analytics/utm-builder"
        },
        {
          "slug": "character-counter",
          "name": "Character Counter",
          "description": "Count characters, words and sentences in text",
          "href": "https://www.numerspace.com/en/marketing-analytics/character-counter"
        }
      ]
    },
    {
      "slug": "pet",
      "name": "Pet Calculators",
      "href": "https://www.numerspace.com/en/pet",
      "count": 4,
      "items": [
        {
          "slug": "cat-age-calculator",
          "name": "Cat Age Calculator",
          "description": "Find out your cat's age in human years",
          "href": "https://www.numerspace.com/en/pet/cat-age-calculator"
        },
        {
          "slug": "dog-age-calculator",
          "name": "Dog Age Calculator",
          "description": "Find out your dog's age in human years by breed",
          "href": "https://www.numerspace.com/en/pet/dog-age-calculator"
        },
        {
          "slug": "cat-pregnancy-calculator",
          "name": "Cat Pregnancy Calculator",
          "description": "Estimated due date from cat's mating date",
          "href": "https://www.numerspace.com/en/pet/cat-pregnancy-calculator"
        },
        {
          "slug": "dog-pregnancy-calculator",
          "name": "Dog Pregnancy Calculator",
          "description": "Estimated due date from dog's mating date",
          "href": "https://www.numerspace.com/en/pet/dog-pregnancy-calculator"
        }
      ]
    },
    {
      "slug": "cars-travel",
      "name": "Vehicle & Travel Calculators",
      "href": "https://www.numerspace.com/en/cars-travel",
      "count": 2,
      "items": [
        {
          "slug": "fuel-consumption-calculator",
          "name": "Fuel Consumption Calculator",
          "description": "Fuel cost by distance and consumption rate",
          "href": "https://www.numerspace.com/en/cars-travel/fuel-consumption-calculator"
        },
        {
          "slug": "distance-calculator",
          "name": "Distance Calculator",
          "description": "Calculate the distance between two points",
          "href": "https://www.numerspace.com/en/cars-travel/distance-calculator"
        }
      ]
    },
    {
      "slug": "faith",
      "name": "Faith Tools",
      "href": "https://www.numerspace.com/en/faith",
      "count": 4,
      "items": [
        {
          "slug": "prayer-times",
          "name": "Prayer Times",
          "description": "Daily prayer times by city",
          "href": "https://www.numerspace.com/en/faith/prayer-times"
        },
        {
          "slug": "zakat-calculator",
          "name": "Zakat Calculator",
          "description": "Zakat on your gold and cash savings",
          "href": "https://www.numerspace.com/en/faith/zakat-calculator"
        },
        {
          "slug": "imsakiye-ramadan-calendar",
          "name": "Ramadan Timetable",
          "description": "Suhoor and iftar times by city",
          "href": "https://www.numerspace.com/en/faith/imsakiye-ramadan-calendar"
        },
        {
          "slug": "hijri-gregorian-rumi-converter",
          "name": "Hijri-Gregorian-Rumi Converter",
          "description": "Convert between Hijri, Gregorian and Rumi calendars",
          "href": "https://www.numerspace.com/en/faith/hijri-gregorian-rumi-converter"
        }
      ]
    },
    {
      "slug": "astrology",
      "name": "Astrology Calculators",
      "href": "https://www.numerspace.com/en/astrology",
      "count": 5,
      "items": [
        {
          "slug": "zodiac-compatibility-calculator",
          "name": "Zodiac Compatibility Calculator",
          "description": "Astrological compatibility analysis between two signs",
          "href": "https://www.numerspace.com/en/astrology/zodiac-compatibility-calculator"
        },
        {
          "slug": "rising-sign",
          "name": "Rising Sign Calculator",
          "description": "Your rising sign based on birth time and location",
          "href": "https://www.numerspace.com/en/astrology/rising-sign"
        },
        {
          "slug": "moon-sign",
          "name": "Moon Sign Calculator",
          "description": "Your moon sign based on birth date",
          "href": "https://www.numerspace.com/en/astrology/moon-sign"
        },
        {
          "slug": "chinese-zodiac",
          "name": "Chinese Zodiac Calculator",
          "description": "Your Chinese zodiac sign and traits by birth year",
          "href": "https://www.numerspace.com/en/astrology/chinese-zodiac"
        },
        {
          "slug": "birth-chart",
          "name": "Birth Chart Calculator",
          "description": "Detailed astrology chart based on your birth moment",
          "href": "https://www.numerspace.com/en/astrology/birth-chart"
        }
      ]
    }
  ],
  "tr": [
    {
      "slug": "finans-yatirim",
      "name": "Finans & Yatırım Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/finans-yatirim",
      "count": 8,
      "items": [
        {
          "slug": "kredi-hesaplama",
          "name": "Kredi Hesaplama",
          "description": "Aylık taksit, toplam geri ödeme ve amortisman planı",
          "href": "https://www.numerspace.com/tr/finans-yatirim/kredi-hesaplama"
        },
        {
          "slug": "mevduat-getirisi-hesaplama",
          "name": "Mevduat Getirisi Hesaplama",
          "description": "Net getiri ve %15 stopaj hesabı",
          "href": "https://www.numerspace.com/tr/finans-yatirim/mevduat-getirisi-hesaplama"
        },
        {
          "slug": "kira-artis-hesaplama",
          "name": "Kira Artış Hesaplama",
          "description": "TÜFE bazlı kira artış oranı ve yeni kira bedeli",
          "href": "https://www.numerspace.com/tr/finans-yatirim/kira-artis-hesaplama"
        },
        {
          "slug": "temettu-hesaplama",
          "name": "Temettü Hesaplama",
          "description": "Temettü verimi ve net gelir hesabı",
          "href": "https://www.numerspace.com/tr/finans-yatirim/temettu-hesaplama"
        },
        {
          "slug": "enflasyon-hesaplama",
          "name": "Enflasyon Hesaplama",
          "description": "TÜFE'ye göre satın alma gücü ve enflasyon etkisi",
          "href": "https://www.numerspace.com/tr/finans-yatirim/enflasyon-hesaplama"
        },
        {
          "slug": "altin-kripto-doviz-hesaplama",
          "name": "Altın, Kripto & Döviz Hesaplama",
          "description": "Anlık fiyatlarla altın, Bitcoin ve döviz dönüşümü",
          "href": "https://www.numerspace.com/tr/finans-yatirim/altin-kripto-doviz-hesaplama"
        },
        {
          "slug": "kredi-karti-asgari-odeme-hesaplama",
          "name": "Kredi Kartı Asgari Ödeme Hesaplama",
          "description": "Asgari ödeme ile toplam maliyet ve kurtulma süresi",
          "href": "https://www.numerspace.com/tr/finans-yatirim/kredi-karti-asgari-odeme-hesaplama"
        },
        {
          "slug": "dugun-butcesi-hesaplama",
          "name": "Düğün Bütçesi Hesaplama",
          "description": "Düğün masrafları ve kişi başı maliyet planlaması",
          "href": "https://www.numerspace.com/tr/finans-yatirim/dugun-butcesi-hesaplama"
        }
      ]
    },
    {
      "slug": "saglik-fitness",
      "name": "Sağlık & Fitness Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/saglik-fitness",
      "count": 15,
      "items": [
        {
          "slug": "bmi-vki-hesaplama",
          "name": "Vücut Kitle İndeksi (BMI) Hesaplama",
          "description": "Vücut kitle indeksi ve sağlıklı kilo aralığı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/bmi-vki-hesaplama"
        },
        {
          "slug": "gunluk-kalori-ihtiyaci-hesaplama",
          "name": "Günlük Kalori İhtiyacı Hesaplama",
          "description": "BMR ve TDEE hesaplama (Mifflin-St Jeor)",
          "href": "https://www.numerspace.com/tr/saglik-fitness/gunluk-kalori-ihtiyaci-hesaplama"
        },
        {
          "slug": "ideal-kilo-hesaplama",
          "name": "İdeal Kilo Hesaplama",
          "description": "Devine, Hamwi ve BMI formülleriyle ideal kilo",
          "href": "https://www.numerspace.com/tr/saglik-fitness/ideal-kilo-hesaplama"
        },
        {
          "slug": "bazal-metabolizma-hesaplama",
          "name": "Bazal Metabolizma Hesaplama",
          "description": "Dinlenme halinde günlük kalori ihtiyacı (BMR)",
          "href": "https://www.numerspace.com/tr/saglik-fitness/bazal-metabolizma-hesaplama"
        },
        {
          "slug": "gunluk-su-ihtiyaci-hesaplama",
          "name": "Günlük Su İhtiyacı Hesaplama",
          "description": "Kilo ve aktiviteye göre günlük su ihtiyacı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/gunluk-su-ihtiyaci-hesaplama"
        },
        {
          "slug": "gebelik-hesaplama",
          "name": "Gebelik Hesaplama",
          "description": "Son adet tarihine göre tahmini doğum ve hafta",
          "href": "https://www.numerspace.com/tr/saglik-fitness/gebelik-hesaplama"
        },
        {
          "slug": "sigara-birakma-kazanc-hesaplama",
          "name": "Sigara Bırakma Kazanç Hesaplama",
          "description": "Sigara bırakınca biriken para ve sağlık kazanımları",
          "href": "https://www.numerspace.com/tr/saglik-fitness/sigara-birakma-kazanc-hesaplama"
        },
        {
          "slug": "protein-ihtiyaci-hesaplama",
          "name": "Protein İhtiyacı Hesaplama",
          "description": "Vücut ağırlığına göre günlük protein ihtiyacı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/protein-ihtiyaci-hesaplama"
        },
        {
          "slug": "maksimum-nabiz-hesaplama",
          "name": "Maksimum Nabız Hesaplama",
          "description": "Yaşa göre maksimum ve hedef nabız aralığı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/maksimum-nabiz-hesaplama"
        },
        {
          "slug": "kalori-yakimi-hesaplama",
          "name": "Kalori Yakımı Hesaplama",
          "description": "Egzersiz türü ve süresine göre yakılan kalori",
          "href": "https://www.numerspace.com/tr/saglik-fitness/kalori-yakimi-hesaplama"
        },
        {
          "slug": "ip-atlama-kalori-hesaplama",
          "name": "İp Atlama Kalori Hesaplama",
          "description": "İp atlama ile yakılan kalori hesabı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/ip-atlama-kalori-hesaplama"
        },
        {
          "slug": "merdiven-cikma-kalori-hesaplama",
          "name": "Merdiven Çıkma Kalori Hesaplama",
          "description": "Merdiven çıkarak yakılan kalori hesabı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/merdiven-cikma-kalori-hesaplama"
        },
        {
          "slug": "yuzme-kalori-hesaplama",
          "name": "Yüzme Kalori Hesaplama",
          "description": "Yüzme stili ve süresine göre yakılan kalori",
          "href": "https://www.numerspace.com/tr/saglik-fitness/yuzme-kalori-hesaplama"
        },
        {
          "slug": "yagsiz-vucut-kitlesi-hesaplama",
          "name": "Yağsız Vücut Kitlesi Hesaplama",
          "description": "Yağ dokusu hariç vücut kitlesi hesabı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/yagsiz-vucut-kitlesi-hesaplama"
        },
        {
          "slug": "sac-uzamasi-hesaplama",
          "name": "Saç Uzaması Hesaplama",
          "description": "Saç uzama süresi ve hedef uzunluk hesabı",
          "href": "https://www.numerspace.com/tr/saglik-fitness/sac-uzamasi-hesaplama"
        }
      ]
    },
    {
      "slug": "is-kariyer",
      "name": "İş & Kariyer Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/is-kariyer",
      "count": 7,
      "items": [
        {
          "slug": "maas-hesaplama",
          "name": "Maaş Hesaplama",
          "description": "Brüt maaştan net ödemeye tüm SGK ve vergi kesintileri",
          "href": "https://www.numerspace.com/tr/is-kariyer/maas-hesaplama"
        },
        {
          "slug": "yillik-izin-hesaplama",
          "name": "Yıllık İzin Hesaplama",
          "description": "Kıdeme göre yıllık izin hak ve bakiye hesabı",
          "href": "https://www.numerspace.com/tr/is-kariyer/yillik-izin-hesaplama"
        },
        {
          "slug": "fazla-mesai-hesaplama",
          "name": "Fazla Mesai Hesaplama",
          "description": "Saatlik ücret bazında fazla mesai ücreti hesabı",
          "href": "https://www.numerspace.com/tr/is-kariyer/fazla-mesai-hesaplama"
        },
        {
          "slug": "ihbar-suresi-hesaplama",
          "name": "İhbar Süresi Hesaplama",
          "description": "Kıdeme göre ihbar süresi ve tazminat hesaplama",
          "href": "https://www.numerspace.com/tr/is-kariyer/ihbar-suresi-hesaplama"
        },
        {
          "slug": "kdv-hesaplama",
          "name": "KDV Hesaplama",
          "description": "KDV dahil, hariç ve tevkifat hesaplama",
          "href": "https://www.numerspace.com/tr/is-kariyer/kdv-hesaplama"
        },
        {
          "slug": "stopaj-hesaplama",
          "name": "Stopaj Hesaplama",
          "description": "Kira ve SMM stopaj kesintisi hesaplama",
          "href": "https://www.numerspace.com/tr/is-kariyer/stopaj-hesaplama"
        },
        {
          "slug": "maas-zammi-hesaplama",
          "name": "Maaş Zammı Hesaplama",
          "description": "Enflasyon farkı ve yüzdelik zam hesaplama",
          "href": "https://www.numerspace.com/tr/is-kariyer/maas-zammi-hesaplama"
        }
      ]
    },
    {
      "slug": "zaman-tarih",
      "name": "Zaman & Tarih Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/zaman-tarih",
      "count": 8,
      "items": [
        {
          "slug": "yas-hesaplama",
          "name": "Yaş Hesaplama",
          "description": "Doğum tarihine göre tam yaş, gün ve hafta",
          "href": "https://www.numerspace.com/tr/zaman-tarih/yas-hesaplama"
        },
        {
          "slug": "tarih-farki-hesaplama",
          "name": "Tarih Farkı Hesaplama",
          "description": "İki tarih arası gün, hafta, ay, yıl ve iş günü",
          "href": "https://www.numerspace.com/tr/zaman-tarih/tarih-farki-hesaplama"
        },
        {
          "slug": "saat-farki-hesaplama",
          "name": "Saat Farkı Hesaplama",
          "description": "İki saat arasındaki farkı hesapla",
          "href": "https://www.numerspace.com/tr/zaman-tarih/saat-farki-hesaplama"
        },
        {
          "slug": "is-gunu-hesaplama",
          "name": "İş Günü Hesaplama",
          "description": "Başlangıç tarihine iş günü ekle, bitiş tarihini bul",
          "href": "https://www.numerspace.com/tr/zaman-tarih/is-gunu-hesaplama"
        },
        {
          "slug": "hangi-gun-dogdum-hesaplama",
          "name": "Hangi Gün Doğdum Hesaplama",
          "description": "Doğum tarihine göre haftanın günü",
          "href": "https://www.numerspace.com/tr/zaman-tarih/hangi-gun-dogdum-hesaplama"
        },
        {
          "slug": "dunya-saatleri",
          "name": "Dünya Saatleri",
          "description": "Tüm dünya şehirlerinin anlık saati",
          "href": "https://www.numerspace.com/tr/zaman-tarih/dunya-saatleri"
        },
        {
          "slug": "kronometre",
          "name": "Kronometre",
          "description": "Online kronometre ve geri sayım sayacı",
          "href": "https://www.numerspace.com/tr/zaman-tarih/kronometre"
        },
        {
          "slug": "roma-rakamli-tarih-cevirici",
          "name": "Roma Rakamlı Tarih Çevirici",
          "description": "Tarihleri Roma rakamlarına çevir",
          "href": "https://www.numerspace.com/tr/zaman-tarih/roma-rakamli-tarih-cevirici"
        }
      ]
    },
    {
      "slug": "matematik-ceviri",
      "name": "Matematik & Çeviri Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/matematik-ceviri",
      "count": 13,
      "items": [
        {
          "slug": "yuzde-hesaplama",
          "name": "Yüzde Hesaplama",
          "description": "Yüzde artış, azalış ve oran hesaplamaları",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/yuzde-hesaplama"
        },
        {
          "slug": "standart-sapma-hesaplama",
          "name": "Standart Sapma Hesaplama",
          "description": "Veri setinin standart sapması ve varyansı",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/standart-sapma-hesaplama"
        },
        {
          "slug": "hesap-makinesi",
          "name": "Hesap Makinesi",
          "description": "Temel aritmetik işlemler için hesap makinesi",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/hesap-makinesi"
        },
        {
          "slug": "bilimsel-hesap-makinesi",
          "name": "Bilimsel Hesap Makinesi",
          "description": "Trigonometri, logaritma ve üs hesaplama",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/bilimsel-hesap-makinesi"
        },
        {
          "slug": "ortalama-medyan-mod-hesaplama",
          "name": "Ortalama, Medyan, Mod Hesaplama",
          "description": "İstatistiksel merkezi eğilim ölçümleri",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/ortalama-medyan-mod-hesaplama"
        },
        {
          "slug": "metrekare-hesaplama",
          "name": "Metrekare Hesaplama",
          "description": "Oda ve alan metrekare hesaplama",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/metrekare-hesaplama"
        },
        {
          "slug": "agirlik-donusturucu",
          "name": "Ağırlık Dönüştürücü",
          "description": "Kg, pound, ons, gram ve ton birimleri arası dönüşüm",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/agirlik-donusturucu"
        },
        {
          "slug": "uzunluk-donusturucu",
          "name": "Uzunluk Dönüştürücü",
          "description": "Metre, mil, inç, feet, yard, km dönüşümü",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/uzunluk-donusturucu"
        },
        {
          "slug": "boyut-agirlik-hesaplama",
          "name": "Boyut Ağırlık Hesaplama",
          "description": "Kargo için boyutsal ağırlık (desi) hesaplama",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/boyut-agirlik-hesaplama"
        },
        {
          "slug": "roma-rakami-cevirici",
          "name": "Roma Rakamı Çevirici",
          "description": "Sayıları Roma rakamlarına çevir",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/roma-rakami-cevirici"
        },
        {
          "slug": "rastgele-sayi-uretici",
          "name": "Rastgele Sayı Üretici",
          "description": "Çekiliş ve şans için rastgele sayı üret",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/rastgele-sayi-uretici"
        },
        {
          "slug": "sifre-kombinasyon-hesaplama",
          "name": "Şifre Kombinasyon Hesaplama",
          "description": "Şifrenizin güvenlik gücü ve kombinasyon sayısı",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/sifre-kombinasyon-hesaplama"
        },
        {
          "slug": "yazi-tura-atma",
          "name": "Yazı Tura Atma",
          "description": "Dijital para atma simülatörü",
          "href": "https://www.numerspace.com/tr/matematik-ceviri/yazi-tura-atma"
        }
      ]
    },
    {
      "slug": "egitim-uretkenlik",
      "name": "Eğitim & Üretkenlik Araçları",
      "href": "https://www.numerspace.com/tr/egitim-uretkenlik",
      "count": 4,
      "items": [
        {
          "slug": "universite-not-ortalamasi-hesaplama",
          "name": "Üniversite Not Ortalaması Hesaplama",
          "description": "Ders notları ve kredilerle GPA ve AGNO hesabı",
          "href": "https://www.numerspace.com/tr/egitim-uretkenlik/universite-not-ortalamasi-hesaplama"
        },
        {
          "slug": "okuma-suresi-hesaplama",
          "name": "Okuma Süresi Hesaplama",
          "description": "Metin uzunluğuna göre tahmini okuma süresi",
          "href": "https://www.numerspace.com/tr/egitim-uretkenlik/okuma-suresi-hesaplama"
        },
        {
          "slug": "yazma-hizi-hesaplama",
          "name": "Yazma Hızı Hesaplama",
          "description": "WPM ve dakika başı kelime hızı testi",
          "href": "https://www.numerspace.com/tr/egitim-uretkenlik/yazma-hizi-hesaplama"
        },
        {
          "slug": "pomodoro-zamanlayici",
          "name": "Pomodoro Zamanlayıcı",
          "description": "25 dakika odak, 5 dakika mola ile üretkenlik tekniği",
          "href": "https://www.numerspace.com/tr/egitim-uretkenlik/pomodoro-zamanlayici"
        }
      ]
    },
    {
      "slug": "ev-yasam",
      "name": "Ev & Yaşam Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/ev-yasam",
      "count": 6,
      "items": [
        {
          "slug": "boya-hesaplama",
          "name": "Boya Hesaplama",
          "description": "Oda boyutuna göre gereken boya miktarı",
          "href": "https://www.numerspace.com/tr/ev-yasam/boya-hesaplama"
        },
        {
          "slug": "elektrik-faturasi-hesaplama",
          "name": "Elektrik Faturası Hesaplama",
          "description": "Cihaz güç, kullanım süresi ve enerji maliyeti",
          "href": "https://www.numerspace.com/tr/ev-yasam/elektrik-faturasi-hesaplama"
        },
        {
          "slug": "tv-boyut-hesaplama",
          "name": "TV Boyut Hesaplama",
          "description": "İzleme mesafesine göre ideal TV boyutu",
          "href": "https://www.numerspace.com/tr/ev-yasam/tv-boyut-hesaplama"
        },
        {
          "slug": "tv-montaj-hesaplama",
          "name": "TV Montaj Yüksekliği Hesaplama",
          "description": "Oda boyutuna göre ideal TV montaj yüksekliği",
          "href": "https://www.numerspace.com/tr/ev-yasam/tv-montaj-hesaplama"
        },
        {
          "slug": "perde-olcusu-hesaplama",
          "name": "Perde Ölçüsü Hesaplama",
          "description": "Pencere ölçülerine göre perde boyu ve genişliği",
          "href": "https://www.numerspace.com/tr/ev-yasam/perde-olcusu-hesaplama"
        },
        {
          "slug": "aydinlatma-ihtiyaci-hesaplama",
          "name": "Aydınlatma İhtiyacı Hesaplama",
          "description": "Oda boyutuna göre lümen ve ampul sayısı",
          "href": "https://www.numerspace.com/tr/ev-yasam/aydinlatma-ihtiyaci-hesaplama"
        }
      ]
    },
    {
      "slug": "giyim-beden",
      "name": "Giyim & Beden Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/giyim-beden",
      "count": 4,
      "items": [
        {
          "slug": "sutyen-bedeni-hesaplama",
          "name": "Sütyen Bedeni Hesaplama",
          "description": "Göğüs ve göğüs altı ölçüsüne göre sütyen bedeni",
          "href": "https://www.numerspace.com/tr/giyim-beden/sutyen-bedeni-hesaplama"
        },
        {
          "slug": "kemer-olcusu-hesaplama",
          "name": "Kemer Ölçüsü Hesaplama",
          "description": "Bel ölçüsüne göre doğru kemer bedeni",
          "href": "https://www.numerspace.com/tr/giyim-beden/kemer-olcusu-hesaplama"
        },
        {
          "slug": "ceket-bedeni-hesaplama",
          "name": "Ceket Bedeni Hesaplama",
          "description": "Göğüs ölçüsüne göre ceket ve takım bedeni",
          "href": "https://www.numerspace.com/tr/giyim-beden/ceket-bedeni-hesaplama"
        },
        {
          "slug": "vucut-tipi-hesaplama",
          "name": "Vücut Tipi Hesaplama",
          "description": "Beden ölçülerine göre vücut tipi analizi",
          "href": "https://www.numerspace.com/tr/giyim-beden/vucut-tipi-hesaplama"
        }
      ]
    },
    {
      "slug": "pazarlama-analitik",
      "name": "Pazarlama & Analitik Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/pazarlama-analitik",
      "count": 17,
      "items": [
        {
          "slug": "roas-hesaplama",
          "name": "ROAS Hesaplama",
          "description": "Reklam harcamasının geri dönüş oranı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/roas-hesaplama"
        },
        {
          "slug": "cr-hesaplama",
          "name": "CR Hesaplama",
          "description": "Ziyaretçiden müşteriye dönüşüm oranı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/cr-hesaplama"
        },
        {
          "slug": "cac-hesaplama",
          "name": "CAC Hesaplama",
          "description": "Müşteri edinme maliyeti hesabı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/cac-hesaplama"
        },
        {
          "slug": "ltv-hesaplama",
          "name": "LTV Hesaplama",
          "description": "Müşteri yaşam boyu değeri hesabı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/ltv-hesaplama"
        },
        {
          "slug": "ctr-hesaplama",
          "name": "CTR Hesaplama",
          "description": "Tıklama oranı ve reklam performansı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/ctr-hesaplama"
        },
        {
          "slug": "cpc-hesaplama",
          "name": "CPC Hesaplama",
          "description": "Tıklama başına maliyet ve reklam verimi",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/cpc-hesaplama"
        },
        {
          "slug": "cpm-hesaplama",
          "name": "CPM Hesaplama",
          "description": "Bin gösterim başına maliyet hesabı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/cpm-hesaplama"
        },
        {
          "slug": "cpl-hesaplama",
          "name": "CPL Hesaplama",
          "description": "Potansiyel müşteri başına maliyet",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/cpl-hesaplama"
        },
        {
          "slug": "aov-hesaplama",
          "name": "AOV Hesaplama",
          "description": "Ortalama sipariş değeri hesabı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/aov-hesaplama"
        },
        {
          "slug": "ab-testi-hesaplama",
          "name": "A/B Testi Hesaplama",
          "description": "İstatistiksel anlamlılık ve dönüşüm oranı analizi",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/ab-testi-hesaplama"
        },
        {
          "slug": "pazarlama-roi-hesaplama",
          "name": "Pazarlama ROI Hesaplama",
          "description": "Pazarlama yatırımının geri dönüş oranı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/pazarlama-roi-hesaplama"
        },
        {
          "slug": "kar-marji-hesaplama",
          "name": "Kâr Marjı Hesaplama",
          "description": "Brüt ve net kâr marjı hesabı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/kar-marji-hesaplama"
        },
        {
          "slug": "musteri-elde-tutma-orani-hesaplama",
          "name": "Müşteri Elde Tutma Oranı Hesaplama",
          "description": "Müşteri sadakati ve kayıp oranı analizi",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/musteri-elde-tutma-orani-hesaplama"
        },
        {
          "slug": "sepet-terk-orani-hesaplama",
          "name": "Sepet Terk Oranı Hesaplama",
          "description": "E-ticaret sepet terk oranı analizi",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/sepet-terk-orani-hesaplama"
        },
        {
          "slug": "web-etkilesim-orani-hesaplama",
          "name": "Web Etkileşim Oranı Hesaplama",
          "description": "Sayfa etkileşim ve bağlılık oranı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/web-etkilesim-orani-hesaplama"
        },
        {
          "slug": "utm-olusturucu",
          "name": "UTM Oluşturucu",
          "description": "Kampanya takibi için UTM parametreli URL oluşturma",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/utm-olusturucu"
        },
        {
          "slug": "karakter-sayaci",
          "name": "Karakter Sayacı",
          "description": "Metin karakter, kelime ve cümle sayımı",
          "href": "https://www.numerspace.com/tr/pazarlama-analitik/karakter-sayaci"
        }
      ]
    },
    {
      "slug": "evcil-hayvan",
      "name": "Evcil Hayvan Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/evcil-hayvan",
      "count": 4,
      "items": [
        {
          "slug": "kedi-yasi-hesaplama",
          "name": "Kedi Yaşı Hesaplama",
          "description": "Kedinizin yaşının insan yaşı karşılığını hesaplayın",
          "href": "https://www.numerspace.com/tr/evcil-hayvan/kedi-yasi-hesaplama"
        },
        {
          "slug": "kopek-yasi-hesaplama",
          "name": "Köpek Yaşı Hesaplama",
          "description": "Köpeğinizin yaşının insan yaşı karşılığını hesaplayın",
          "href": "https://www.numerspace.com/tr/evcil-hayvan/kopek-yasi-hesaplama"
        },
        {
          "slug": "kedi-gebelik-hesaplama",
          "name": "Kedi Gebelik Hesaplama",
          "description": "Çiftleşme tarihinden tahmini doğum tarihi",
          "href": "https://www.numerspace.com/tr/evcil-hayvan/kedi-gebelik-hesaplama"
        },
        {
          "slug": "kopek-gebelik-hesaplama",
          "name": "Köpek Gebelik Hesaplama",
          "description": "Çiftleşme tarihinden tahmini doğum tarihi",
          "href": "https://www.numerspace.com/tr/evcil-hayvan/kopek-gebelik-hesaplama"
        }
      ]
    },
    {
      "slug": "arac-seyahat",
      "name": "Araç & Seyahat Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/arac-seyahat",
      "count": 2,
      "items": [
        {
          "slug": "yakit-tuketimi-hesaplama",
          "name": "Yakıt Tüketimi Hesaplama",
          "description": "Mesafe ve tüketime göre yakıt maliyeti",
          "href": "https://www.numerspace.com/tr/arac-seyahat/yakit-tuketimi-hesaplama"
        },
        {
          "slug": "mesafe-hesaplama",
          "name": "Mesafe Hesaplama",
          "description": "İki nokta arasındaki mesafeyi hesapla",
          "href": "https://www.numerspace.com/tr/arac-seyahat/mesafe-hesaplama"
        }
      ]
    },
    {
      "slug": "inanc",
      "name": "İnanç Araçları",
      "href": "https://www.numerspace.com/tr/inanc",
      "count": 4,
      "items": [
        {
          "slug": "namaz-vakitleri",
          "name": "Namaz Vakitleri",
          "description": "Şehir bazlı günlük namaz vakitleri",
          "href": "https://www.numerspace.com/tr/inanc/namaz-vakitleri"
        },
        {
          "slug": "zekat-hesaplama",
          "name": "Zekat Hesaplama",
          "description": "Altın ve para birikimlerinizin zekatı",
          "href": "https://www.numerspace.com/tr/inanc/zekat-hesaplama"
        },
        {
          "slug": "imsakiye",
          "name": "İmsakiye",
          "description": "Şehre göre sahur ve iftar vakitleri",
          "href": "https://www.numerspace.com/tr/inanc/imsakiye"
        },
        {
          "slug": "hicri-miladi-rumi-cevirici",
          "name": "Hicri-Miladi-Rumi Çevirici",
          "description": "Hicri, Miladi ve Rumi takvim dönüşümü",
          "href": "https://www.numerspace.com/tr/inanc/hicri-miladi-rumi-cevirici"
        }
      ]
    },
    {
      "slug": "astroloji",
      "name": "Astroloji Hesaplayıcıları",
      "href": "https://www.numerspace.com/tr/astroloji",
      "count": 5,
      "items": [
        {
          "slug": "burc-uyumu-hesaplama",
          "name": "Burç Uyumu Hesaplama",
          "description": "İki burç arasındaki astrolojik uyum analizi",
          "href": "https://www.numerspace.com/tr/astroloji/burc-uyumu-hesaplama"
        },
        {
          "slug": "yukselen-burc-hesaplama",
          "name": "Yükselen Burç Hesaplama",
          "description": "Doğum saati ve yerine göre yükselen burcunuz",
          "href": "https://www.numerspace.com/tr/astroloji/yukselen-burc-hesaplama"
        },
        {
          "slug": "ay-burcu-hesaplama",
          "name": "Ay Burcu Hesaplama",
          "description": "Doğum tarihinize göre ay burcunuz",
          "href": "https://www.numerspace.com/tr/astroloji/ay-burcu-hesaplama"
        },
        {
          "slug": "cin-burcu-hesaplama",
          "name": "Çin Burcu Hesaplama",
          "description": "Doğum yılınıza göre Çin burcu ve özellikleriniz",
          "href": "https://www.numerspace.com/tr/astroloji/cin-burcu-hesaplama"
        },
        {
          "slug": "dogum-haritasi-hesaplama",
          "name": "Doğum Haritası Hesaplama",
          "description": "Doğum anınıza göre detaylı astroloji haritası",
          "href": "https://www.numerspace.com/tr/astroloji/dogum-haritasi-hesaplama"
        }
      ]
    }
  ]
};
