/* Applies a reviewer's decisions to drafted specs and records the review.

   A review file is an array of entries:
     { "id": "ACT-13", "note": "why the draft was changed",
       "set": { "journey.contact.defaultPriority": "lifecycle", "entity.instanceKey": [...] },
       "touch": { "t2": { "destination": {...}, "label": "RECOMMENDED_DEFAULT" } },   // merged into that touch
       "wait": { "w.x": { "timeout": { "after": {...}, "relativeTo": "attribute", "attribute": "..." } } },  // merged
       "exits": { "x.y": "timeout" }, "actions": {...}, "handoffs": {...}, "trigger": {...},
       "aliases": [...], "useCases": [...],   // shorthand for discovery
       "drop": ["journey.measurement.businessOutcome"] }
   Each entry is applied to <draft-dir>/<id>.json, written to <draft-dir>/<id>.reviewed.json,
   and recorded in production/vnext-migration-reviews.json with the paths it changed.
   A review with no changes is still recorded: "read, accepted as drafted" is a decision.

     node scripts/vnext-review.mjs <draft-dir> <reviews.json>   */
import { readFile, writeFile } from "node:fs/promises";

const [dir, reviewsPath] = process.argv.slice(2);
const reviews = JSON.parse(await readFile(reviewsPath, "utf8"));
let log; try { log = JSON.parse(await readFile("production/vnext-migration-reviews.json", "utf8")); } catch { log = { _about: "One record per customer journey migrated in Gate 4: who read it, what the draft got wrong, what was changed. Generated by scripts/vnext-review.mjs from the reviewer's decision files; the draft generator never writes here.", reviews: [] }; }

const setPath = (obj, path, value) => { const ks = path.split("."); let o = obj; for (const k of ks.slice(0, -1)) { if (o[k] === undefined || o[k] === null || typeof o[k] !== "object") o[k] = {}; o = o[k]; } o[ks.at(-1)] = value; };
const dropPath = (obj, path) => { const ks = path.split("."); let o = obj; for (const k of ks.slice(0, -1)) { if (!o[k]) return; o = o[k]; } delete o[ks.at(-1)]; };
const merge = (a, b) => { for (const [k, v] of Object.entries(b)) if (v === null) delete a[k]; else a[k] = v && typeof v === "object" && !Array.isArray(v) && a[k] && typeof a[k] === "object" && !Array.isArray(a[k]) ? merge(a[k], v) : v; return a; };

const out = [];
for (const r of reviews) {
  const spec = JSON.parse(await readFile(`${dir}/${r.id}.json`, "utf8"));
  const changed = [];
  for (const [p, v] of Object.entries(r.set ?? {})) { setPath(spec, p, v); changed.push(p); }
  for (const p of r.drop ?? []) { dropPath(spec, p); changed.push("-" + p); }
  if (r.touch) for (const [tid, patch] of Object.entries(r.touch)) { const t = spec.journey.orchestration.touches.find((x) => x.id === tid); if (!t) throw new Error(`${r.id}: touch ${tid} not in draft`); merge(t, patch); changed.push(`touch ${tid}`); }
  if (r.wait) for (const [wid, patch] of Object.entries(r.wait)) { spec.waits[wid] = merge(spec.waits[wid] ?? {}, patch); changed.push(`wait ${wid}`); }
  if (r.exits) { spec.exits = { ...(spec.exits ?? {}), ...r.exits }; changed.push("exits"); }
  if (r.actions) { spec.actions = spec.actions ?? {}; for (const [aid, patch] of Object.entries(r.actions)) spec.actions[aid] = merge(spec.actions[aid] ?? {}, patch); changed.push("actions"); }
  if (r.handoffs) { spec.handoffs = { ...(spec.handoffs ?? {}), ...r.handoffs }; changed.push("handoffs"); }
  if (r.trigger) { spec.trigger = r.trigger; changed.push("trigger"); }
  if (r.aliases) { spec.journey.discovery.aliases = r.aliases; changed.push("aliases"); }
  if (r.useCases) { spec.journey.discovery.useCases = r.useCases; changed.push("useCases"); }
  if (r.suppressions) { spec.journey.suppressions = r.suppressions; if (spec.journey.orchestration) spec.journey.orchestration.noAction = r.suppressions.map((s) => s.id); changed.push("suppressions"); }
  if (r.eligibility) { spec.journey.eligibility = r.eligibility; changed.push("eligibility"); }
  if (r.objective) { spec.journey.objective = r.objective; changed.push("objective"); }
  if (r.presets) { spec.journey.discovery.presets = r.presets; changed.push("presets"); }
  if (spec.trigger?.insufficientAlone?.some((s) => /REVIEW:/.test(s))) throw new Error(`${r.id}: trigger insufficientAlone still carries the draft placeholder - the review must name the proxies`);
  delete spec._draft;
  await writeFile(`${dir}/${r.id}.reviewed.json`, JSON.stringify(spec, null, 1));
  const entry = { id: r.id, reviewedBy: r.reviewedBy ?? "migration pass, Gate 4 (per-journey read)", reviewedAt: r.reviewedAt ?? "2026-09-02", note: r.note, changes: changed.length ? changed : ["read; accepted as drafted"] };
  const i = log.reviews.findIndex((x) => x.id === r.id); if (i >= 0) log.reviews[i] = entry; else log.reviews.push(entry);
  out.push(`${dir}/${r.id}.reviewed.json`);
  console.log(`${r.id}: ${entry.changes.join(", ")}`);
}
await writeFile("production/vnext-migration-reviews.json", JSON.stringify(log, null, 1));
await writeFile(`${dir}/.last-reviewed`, out.join("\n"));
