// One-off generator for calculator-catalog.json (Phase 4). Hand-authored
// per-calculator specs below; mechanical fields (category/subcategory/
// formulaFamily/relatedCalculators) are cross-checked against
// calculator-candidates.json + calculator-formula-families.json so the
// catalog can never silently drift from the research files.
import { readFileSync, writeFileSync } from "fs";

const cand = JSON.parse(readFileSync(new URL("./calculator-candidates.json", import.meta.url))).candidates;
const fam = JSON.parse(readFileSync(new URL("./calculator-formula-families.json", import.meta.url))).families;
const byId = Object.fromEntries(cand.map((c) => [c.id, c]));
const famMembersOf = {};
for (const f of fam) {
  const members = [...f.standaloneCalculators, ...(f.keptSeparate || [])];
  for (const id of members) famMembersOf[id] = members.filter((x) => x !== id);
}

// [id, priority, aliases[], formula, formulaPlainEnglish, inputs[{key,label,unit}],
//  outputs[{key,label,unit}], acceptedRanges, validationRules[], edgeCases[],
//  exampleInput{}, exampleOutput{}, relatedMetrics[]]
const R = "ratio"; const PCT = "%"; const CUR = "currency"; const CNT = "count"; const DAYS = "days";

const specs = [
  // --- advertising ---
  ["roas", "P0", ["Return on Ad Spend"], "revenue / adSpend", "Revenue generated per unit of ad spend.",
    [["revenue","Revenue from ads",CUR],["spend","Ad spend",CUR]],
    [["roas","ROAS","x (multiplier)"]],
    { revenue: ">=0", spend: ">0" },
    ["spend must be > 0 (undefined otherwise)", "output is a multiplier (2.5x), not a percentage - do not append %"],
    ["spend = 0 -> undefined, show '-' not Infinity", "revenue = 0 -> valid, ROAS = 0x"],
    { revenue: 5000, spend: 1000 }, { roas: "5.00x" },
    ["Marketing ROI", "Break-Even ROAS"]],
  ["marketing-roi", "P0", ["ROI"], "(revenue - cost) / cost", "Net return on marketing investment as a percentage of cost.",
    [["revenue","Revenue attributed to marketing",CUR],["cost","Marketing cost",CUR]],
    [["roi","Marketing ROI",PCT]],
    { revenue: ">=0", cost: ">0" },
    ["cost must be > 0", "output is a percentage, distinct from ROAS's multiplier - do not conflate the two on the same page"],
    ["cost = 0 -> undefined", "revenue < cost -> negative ROI is valid and expected"],
    { revenue: 5000, cost: 1000 }, { roi: "400.00%" },
    ["ROAS", "Profit Margin"]],
  ["incremental-roas", "P2", [], "(testRevenue - controlRevenue) / spend", "Revenue actually caused by the ad spend (from a holdout test), divided by that spend.",
    [["testRevenue","Revenue, exposed group",CUR],["controlRevenue","Revenue, holdout group",CUR],["spend","Ad spend",CUR]],
    [["iroas","Incremental ROAS","x (multiplier)"]],
    { testRevenue: ">=0", controlRevenue: ">=0", spend: ">0" },
    ["requires a true randomized holdout; a non-random control group invalidates the result", "spend must be > 0"],
    ["controlRevenue > testRevenue -> negative incremental ROAS is valid (ads suppressed organic-equivalent behavior)"],
    { testRevenue: 12000, controlRevenue: 9000, spend: 2000 }, { iroas: "1.50x" },
    ["ROAS"]],
  ["ctr", "P0", ["Click-Through Rate"], "clicks / impressions", "Share of impressions that were clicked.",
    [["clicks","Clicks",CNT],["impressions","Impressions",CNT]],
    [["ctr","CTR",PCT]],
    { clicks: ">=0", impressions: ">0" },
    ["clicks should not exceed impressions in normal ad delivery", "impressions must be > 0"],
    ["impressions = 0 -> undefined", "clicks = impressions -> 100%, flag as suspicious click fraud pattern"],
    { clicks: 240, impressions: 12000 }, { ctr: "2.00%" },
    ["CPC", "Conversion Rate"]],
  ["cpc", "P0", ["Cost per Click"], "spend / clicks", "Average price paid per click.",
    [["spend","Total spend",CUR],["clicks","Clicks",CNT]],
    [["cpc","CPC",CUR]],
    { spend: ">=0", clicks: ">0" },
    ["clicks must be > 0"], ["clicks = 0 -> undefined"],
    { spend: 500, clicks: 250 }, { cpc: "2.00" },
    ["CPM", "CTR"]],
  ["cpm", "P0", ["Cost per Mille", "Cost per 1,000 Impressions"], "(spend / impressions) * 1000", "Cost to reach 1,000 impressions.",
    [["spend","Total spend",CUR],["impressions","Impressions",CNT]],
    [["cpm","CPM",CUR]],
    { spend: ">=0", impressions: ">0" },
    ["impressions must be > 0", "the x1000 factor is part of the definition - do not report raw cost-per-impression"],
    ["impressions = 0 -> undefined"],
    { spend: 300, impressions: 150000 }, { cpm: "2.00" },
    ["CPC", "Effective CPM"]],
  ["cpa", "P0", ["Cost per Acquisition", "Cost per Conversion"], "spend / conversions", "Average price paid per conversion.",
    [["spend","Total spend",CUR],["conversions","Conversions",CNT]],
    [["cpa","CPA",CUR]],
    { spend: ">=0", conversions: ">0" },
    ["conversions must be > 0", "keep the conversion definition (lead vs sale vs signup) explicit next to the result - the same spend against a looser definition silently understates CPA"],
    ["conversions = 0 -> undefined"],
    { spend: 4000, conversions: 80 }, { cpa: "50.00" },
    ["CPL", "CAC"]],
  ["cpl", "P0", ["Cost per Lead"], "spend / leads", "Average price paid per lead generated.",
    [["spend","Total spend",CUR],["leads","Leads generated",CNT]],
    [["cpl","CPL",CUR]],
    { spend: ">=0", leads: ">0" },
    ["leads must be > 0"], ["leads = 0 -> undefined"],
    { spend: 2000, leads: 100 }, { cpl: "20.00" },
    ["CPA", "CAC"]],
  ["cpi", "P1", ["Cost per Install"], "spend / installs", "Average price paid per app install.",
    [["spend","Total spend",CUR],["installs","Installs",CNT]],
    [["cpi","CPI",CUR]],
    { spend: ">=0", installs: ">0" },
    ["installs must be > 0"], ["installs = 0 -> undefined"],
    { spend: 1500, installs: 500 }, { cpi: "3.00" },
    ["Activation Rate", "Mobile LTV"]],
  ["cpv", "P1", ["Cost per View"], "spend / views", "Average price paid per (qualifying) video view.",
    [["spend","Total spend",CUR],["views","Qualifying views",CNT]],
    [["cpv","CPV",CUR]],
    { spend: ">=0", views: ">0" },
    ["'view' definition (e.g. 30s watched, or completed) must be stated - platforms differ", "views must be > 0"],
    ["views = 0 -> undefined"],
    { spend: 800, views: 8000 }, { cpv: "0.10" },
    ["Video Completion Rate", "CPM"]],
  ["cpe", "P2", ["Cost per Engagement"], "spend / engagements", "Average price paid per tracked engagement action.",
    [["spend","Total spend",CUR],["engagements","Engagements",CNT]],
    [["cpe","CPE",CUR]],
    { spend: ">=0", engagements: ">0" },
    ["'engagement' has no fixed cross-platform definition (like, share, save, swipe-up all count on different platforms) - state which events are included", "engagements must be > 0"],
    ["engagements = 0 -> undefined"],
    { spend: 600, engagements: 3000 }, { cpe: "0.20" },
    ["Web Engagement Rate"]],
  ["frequency", "P1", [], "impressions / reach", "Average number of times a unique person was exposed to the ad.",
    [["impressions","Impressions",CNT],["reach","Unique reach",CNT]],
    [["frequency","Frequency","x (avg exposures)"]],
    { impressions: ">=0", reach: ">0" },
    ["reach must be > 0", "frequency is always >= 1 in a correct dataset; a result < 1 signals a data error, not a real value"],
    ["reach = 0 -> undefined"],
    { impressions: 500000, reach: 100000 }, { frequency: "5.00x" },
    ["Reach", "Impression Share"]],
  ["video-completion-rate", "P1", [], "completions / starts", "Share of started video views that played to completion.",
    [["completions","Completed views",CNT],["starts","Video starts",CNT]],
    [["completionRate","Video Completion Rate",PCT]],
    { completions: ">=0", starts: ">0" },
    ["starts must be > 0", "completions should not exceed starts"],
    ["starts = 0 -> undefined"],
    { completions: 4200, starts: 6000 }, { completionRate: "70.00%" },
    ["CPV", "Video View-Through Rate"]],
  ["share-of-voice", "P2", [], "ownImpressions / totalMarketImpressions", "Your share of total category ad impressions in a market.",
    [["ownImpressions","Your impressions",CNT],["totalMarketImpressions","Total market impressions",CNT]],
    [["sov","Share of Voice",PCT]],
    { ownImpressions: ">=0", totalMarketImpressions: ">0" },
    ["totalMarketImpressions is rarely directly known - usually estimated from a competitive intelligence tool; state the source", "ownImpressions must be <= totalMarketImpressions"],
    ["totalMarketImpressions = 0 -> undefined"],
    { ownImpressions: 50000, totalMarketImpressions: 400000 }, { sov: "12.50%" },
    ["Frequency", "Reach"]],

  // --- acquisition ---
  ["cac", "P0", ["Customer Acquisition Cost"], "spend / customers", "Total acquisition spend divided by new customers acquired.",
    [["spend","Total acquisition spend",CUR],["customers","New customers acquired",CNT]],
    [["cac","CAC",CUR]],
    { spend: ">=0", customers: ">0" },
    ["customers must be > 0", "spend should include the full acquisition cost base being measured (paid-only vs blended) - state which"],
    ["customers = 0 -> undefined"],
    { spend: 10000, customers: 200 }, { cac: "50.00" },
    ["LTV:CAC Ratio", "CAC Payback Period"]],
  ["blended-cac", "P1", [], "totalSpendAllChannels / totalNewCustomersAllSources", "Total acquisition spend across every channel (including $0-cost organic) divided by all new customers, regardless of source.",
    [["totalSpend","Total spend, all channels",CUR],["totalCustomers","New customers, all sources",CNT]],
    [["blendedCac","Blended CAC",CUR]],
    { totalSpend: ">=0", totalCustomers: ">0" },
    ["totalCustomers must include organic/referral customers, not only paid-attributed ones, or the result is really Paid CAC mislabeled", "totalCustomers must be > 0"],
    ["totalCustomers = 0 -> undefined"],
    { totalSpend: 10000, totalCustomers: 400 }, { blendedCac: "25.00" },
    ["CAC"]],

  // --- e-commerce ---
  ["aov", "P0", ["Average Order Value", "Average Basket Size", "Revenue per Order"], "revenue / orders", "Average revenue per completed order.",
    [["revenue","Total revenue",CUR],["orders","Number of orders",CNT]],
    [["aov","AOV",CUR]],
    { revenue: ">=0", orders: ">0" },
    ["orders must be > 0"], ["orders = 0 -> undefined"],
    { revenue: 45000, orders: 900 }, { aov: "50.00" },
    ["Units per Transaction", "Revenue per Visitor"]],
  ["units-per-transaction", "P3", [], "unitsSold / orders", "Average number of items per completed order.",
    [["unitsSold","Units sold",CNT],["orders","Number of orders",CNT]],
    [["upt","Units per Transaction","x (avg items)"]],
    { unitsSold: ">=0", orders: ">0" },
    ["orders must be > 0"], ["orders = 0 -> undefined"],
    { unitsSold: 2100, orders: 900 }, { upt: "2.33" },
    ["AOV"]],
  ["revenue-per-visitor", "P1", ["RPV"], "revenue / visitors", "Average revenue generated per site visitor.",
    [["revenue","Total revenue",CUR],["visitors","Total visitors",CNT]],
    [["rpv","Revenue per Visitor",CUR]],
    { revenue: ">=0", visitors: ">0" },
    ["visitors must be > 0"], ["visitors = 0 -> undefined"],
    { revenue: 45000, visitors: 30000 }, { rpv: "1.50" },
    ["AOV", "Conversion Rate"]],
  ["cart-abandonment-rate", "P1", ["Checkout Abandonment Rate"], "(cartsCreated - completedPurchases) / cartsCreated", "Share of started carts that never converted, at a chosen funnel stage.",
    [["stage","Stage","enum(cart/checkout)"],["cartsCreated","Carts (or checkouts) started",CNT],["completedPurchases","Completed purchases",CNT]],
    [["abandonmentRate","Abandonment Rate",PCT]],
    { cartsCreated: ">0", completedPurchases: ">=0" },
    ["completedPurchases should not exceed cartsCreated", "cartsCreated must be > 0", "the stage label must be shown in the result, since cart-stage and checkout-stage numbers are not comparable to each other"],
    ["cartsCreated = 0 -> undefined", "completedPurchases = cartsCreated -> 0% abandonment"],
    { stage: "cart", cartsCreated: 1000, completedPurchases: 280 }, { abandonmentRate: "72.00%" },
    ["Conversion Rate", "Landing Page Bounce Rate"]],
  ["discount-rate", "P2", [], "discountAmount / originalPrice", "Discount given as a share of original price.",
    [["discountAmount","Discount amount",CUR],["originalPrice","Original price",CUR]],
    [["discountRate","Discount Rate",PCT]],
    { discountAmount: ">=0", originalPrice: ">0" },
    ["discountAmount should not exceed originalPrice", "originalPrice must be > 0"],
    ["originalPrice = 0 -> undefined"],
    { discountAmount: 15, originalPrice: 60 }, { discountRate: "25.00%" },
    ["Profit Margin"]],
  ["return-rate", "P1", [], "returnedUnits / soldUnits", "Share of sold units later returned.",
    [["returnedUnits","Returned units",CNT],["soldUnits","Sold units",CNT]],
    [["returnRate","Return Rate",PCT]],
    { returnedUnits: ">=0", soldUnits: ">0" },
    ["soldUnits must be > 0", "measured in units - do not silently substitute a revenue figure (see Refund Rate for the currency-based counterpart)"],
    ["soldUnits = 0 -> undefined"],
    { returnedUnits: 60, soldUnits: 1200 }, { returnRate: "5.00%" },
    ["Refund Rate"]],
  ["refund-rate", "P2", [], "refundedRevenue / grossRevenue", "Refunded revenue as a share of gross revenue - the currency-based counterpart to Return Rate's unit count.",
    [["refundedRevenue","Refunded revenue",CUR],["grossRevenue","Gross revenue",CUR]],
    [["refundRate","Refund Rate",PCT]],
    { refundedRevenue: ">=0", grossRevenue: ">0" },
    ["grossRevenue must be > 0", "state explicitly that this is currency-based, not unit-based, so it is never silently compared to Return Rate as if identical"],
    ["grossRevenue = 0 -> undefined"],
    { refundedRevenue: 3000, grossRevenue: 45000 }, { refundRate: "6.67%" },
    ["Return Rate"]],
  ["inventory-turnover", "P2", [], "cogs / averageInventoryValue", "How many times inventory is sold and replaced over a period.",
    [["cogs","Cost of goods sold",CUR],["averageInventoryValue","Average inventory value",CUR]],
    [["turnover","Inventory Turnover","x (times per period)"]],
    { cogs: ">=0", averageInventoryValue: ">0" },
    ["averageInventoryValue must be > 0", "cogs and inventory value must cover the same period"],
    ["averageInventoryValue = 0 -> undefined"],
    { cogs: 240000, averageInventoryValue: 40000 }, { turnover: "6.00x" },
    ["Sell-Through Rate"]],
  ["sell-through-rate", "P2", [], "unitsSold / unitsReceived", "Share of received inventory that has sold.",
    [["unitsSold","Units sold",CNT],["unitsReceived","Units received",CNT]],
    [["sellThroughRate","Sell-Through Rate",PCT]],
    { unitsSold: ">=0", unitsReceived: ">0" },
    ["unitsReceived must be > 0", "unitsSold should not exceed unitsReceived within one stocking period"],
    ["unitsReceived = 0 -> undefined"],
    { unitsSold: 850, unitsReceived: 1000 }, { sellThroughRate: "85.00%" },
    ["Inventory Turnover"]],
  ["shipping-cost-ratio", "P3", [], "shippingCost / orderValue", "Shipping cost as a share of order value.",
    [["shippingCost","Shipping cost",CUR],["orderValue","Order value",CUR]],
    [["shippingRatio","Shipping Cost Ratio",PCT]],
    { shippingCost: ">=0", orderValue: ">0" },
    ["orderValue must be > 0"], ["orderValue = 0 -> undefined"],
    { shippingCost: 6, orderValue: 60 }, { shippingRatio: "10.00%" },
    ["Contribution Margin"]],
  ["gross-margin", "P0", [], "(revenue - cogs) / revenue", "Revenue remaining after the direct cost of goods sold.",
    [["revenue","Revenue",CUR],["cogs","Cost of goods sold",CUR]],
    [["grossMargin","Gross Margin",PCT]],
    { revenue: ">0", cogs: ">=0" },
    ["revenue must be > 0", "cogs only - do not fold in shipping/payment fees here, that is Contribution Margin's job"],
    ["cogs > revenue -> negative margin is valid and should display as such, not clamp to 0"],
    { revenue: 100000, cogs: 40000 }, { grossMargin: "60.00%" },
    ["Contribution Margin", "Profit Margin"]],
  ["contribution-margin", "P1", [], "(revenue - cogs - variableCosts) / revenue", "Revenue remaining after cost of goods sold AND other variable costs (shipping, payment fees, etc).",
    [["revenue","Revenue",CUR],["cogs","Cost of goods sold",CUR],["variableCosts","Other variable costs",CUR]],
    [["contributionMargin","Contribution Margin",PCT]],
    { revenue: ">0", cogs: ">=0", variableCosts: ">=0" },
    ["revenue must be > 0", "variableCosts must exclude fixed costs (rent, salaries) - those belong in Break-Even, not here"],
    ["cogs + variableCosts > revenue -> negative margin is valid"],
    { revenue: 100000, cogs: 40000, variableCosts: 8000 }, { contributionMargin: "52.00%" },
    ["Gross Margin", "Break-Even Point"]],
  ["profit-margin", "P1", ["Net Margin"], "(revenue - cost) / revenue", "Net profit as a percentage of revenue, fully loaded.",
    [["revenue","Revenue",CUR],["cost","Total cost",CUR]],
    [["profitMargin","Profit Margin",PCT]],
    { revenue: ">0", cost: ">=0" },
    ["revenue must be > 0", "cost here is fully loaded (all costs), unlike Gross/Contribution Margin's partial cost bases"],
    ["cost > revenue -> negative margin is valid"],
    { revenue: 100000, cost: 55000 }, { profitMargin: "45.00%" },
    ["Marketing ROI", "Gross Margin"]],

  // --- lifecycle & retention ---
  ["retention-rate", "P0", [], "(endCustomers - acquiredCustomers) / startCustomers", "Share of existing customers retained over a period; Churn Rate is its complement (1 - retention).",
    [["startCustomers","Customers at period start",CNT],["endCustomers","Customers at period end",CNT],["acquiredCustomers","New customers acquired",CNT]],
    [["retentionRate","Retention Rate",PCT],["churnRate","Churn Rate",PCT]],
    { startCustomers: ">0", endCustomers: ">=0", acquiredCustomers: ">=0" },
    ["startCustomers must be > 0", "churnRate is always reported as 1 - retentionRate, never independently re-derived"],
    ["endCustomers - acquiredCustomers can be negative if churn exceeded start - display as a negative retention rate, don't clamp"],
    { startCustomers: 1000, endCustomers: 1050, acquiredCustomers: 150 }, { retentionRate: "90.00%", churnRate: "10.00%" },
    ["Reactivation Rate", "Logo Churn"]],
  ["loyalty-participation-rate", "P3", [], "enrolledMembers / totalCustomers", "Share of customers enrolled in the loyalty program.",
    [["enrolledMembers","Enrolled members",CNT],["totalCustomers","Total customers",CNT]],
    [["participationRate","Loyalty Participation Rate",PCT]],
    { enrolledMembers: ">=0", totalCustomers: ">0" },
    ["totalCustomers must be > 0", "enrolledMembers should not exceed totalCustomers"],
    ["totalCustomers = 0 -> undefined"],
    { enrolledMembers: 360, totalCustomers: 1200 }, { participationRate: "30.00%" },
    ["Repeat Purchase Rate"]],
  ["reactivation-rate", "P1", ["Win-Back Rate"], "reactivatedCustomers / lapsedCustomers", "Share of lapsed customers who returned.",
    [["reactivatedCustomers","Reactivated customers",CNT],["lapsedCustomers","Lapsed customers targeted",CNT]],
    [["reactivationRate","Reactivation Rate",PCT]],
    { reactivatedCustomers: ">=0", lapsedCustomers: ">0" },
    ["lapsedCustomers must be > 0", "reactivatedCustomers should not exceed lapsedCustomers"],
    ["lapsedCustomers = 0 -> undefined"],
    { reactivatedCustomers: 80, lapsedCustomers: 1000 }, { reactivationRate: "8.00%" },
    ["Retention Rate"]],
  ["customer-lifetime", "P2", [], "1 / churnRate", "Modeled average customer lifetime (in the same period unit as the churn rate), not an observed fact.",
    [["churnRate","Period churn rate",PCT]],
    [["lifetime","Average Customer Lifetime","periods"]],
    { churnRate: ">0 and <=1" },
    ["churnRate must be > 0 (a 0% churn model implies infinite lifetime - reject, don't return Infinity)", "this is a steady-state model, not a cohort-observed number - label it as modeled"],
    ["churnRate = 1 -> lifetime = 1 period exactly"],
    { churnRate: 0.05 }, { lifetime: "20.0 periods" },
    ["LTV", "Retention Rate"]],
  ["logo-churn", "P1", [], "lostCustomers / startCustomers", "Customer-count churn (as opposed to revenue churn) - the SaaS-standard framing of Churn Rate.",
    [["lostCustomers","Customers lost",CNT],["startCustomers","Customers at period start",CNT]],
    [["logoChurn","Logo Churn",PCT]],
    { lostCustomers: ">=0", startCustomers: ">0" },
    ["startCustomers must be > 0", "counts customers/accounts, not revenue - see Revenue Retention Calculator for the dollar-weighted version"],
    ["startCustomers = 0 -> undefined"],
    { lostCustomers: 12, startCustomers: 240 }, { logoChurn: "5.00%" },
    ["Retention Rate", "Gross Revenue Retention"]],
  ["repeat-purchase-rate", "P2", ["Repeat Customer Rate"], "repeatCustomers / totalCustomers", "Share of customers who purchased more than once.",
    [["repeatCustomers","Customers with 2+ orders",CNT],["totalCustomers","Total customers",CNT]],
    [["repeatRate","Repeat Purchase Rate",PCT]],
    { repeatCustomers: ">=0", totalCustomers: ">0" },
    ["totalCustomers must be > 0", "repeatCustomers should not exceed totalCustomers"],
    ["totalCustomers = 0 -> undefined"],
    { repeatCustomers: 300, totalCustomers: 1200 }, { repeatRate: "25.00%" },
    ["Retention Rate", "LTV"]],

  // --- CRM & email ---
  ["delivery-rate", "P1", [], "delivered / sent", "Share of sent emails that were actually delivered.",
    [["delivered","Delivered",CNT],["sent","Sent",CNT]],
    [["deliveryRate","Delivery Rate",PCT]],
    { delivered: ">=0", sent: ">0" },
    ["sent must be > 0", "delivered should not exceed sent"],
    ["sent = 0 -> undefined"],
    { delivered: 9800, sent: 10000 }, { deliveryRate: "98.00%" },
    ["Bounce Rate"]],
  ["open-rate", "P0", [], "opens / delivered", "Share of delivered emails that were opened.",
    [["opens","Opens",CNT],["delivered","Delivered",CNT]],
    [["openRate","Open Rate",PCT]],
    { opens: ">=0", delivered: ">0" },
    ["delivered must be > 0", "Apple MPP and similar privacy features inflate opens - flag results near or above 100% as unreliable, not impossible"],
    ["delivered = 0 -> undefined", "opens > delivered can legitimately occur due to proxy pre-fetching - do not clamp to 100%, but flag it"],
    { opens: 2500, delivered: 10000 }, { openRate: "25.00%" },
    ["CTOR", "CTR"]],
  ["ctor", "P1", ["Click-to-Open Rate"], "clicks / opens", "Of the people who opened, the share who clicked - isolates content/offer quality from deliverability.",
    [["clicks","Clicks",CNT],["opens","Opens",CNT]],
    [["ctor","CTOR",PCT]],
    { clicks: ">=0", opens: ">0" },
    ["opens must be > 0", "do not confuse with Email CTR (clicks/delivered) - CTOR removes deliverability/open-rate noise from the content-quality question"],
    ["opens = 0 -> undefined"],
    { clicks: 400, opens: 2500 }, { ctor: "16.00%" },
    ["Open Rate", "CTR"]],
  ["bounce-rate-email", "P2", [], "bounced / sent", "Share of sent emails that bounced.",
    [["bounced","Bounced",CNT],["sent","Sent",CNT]],
    [["bounceRate","Bounce Rate",PCT]],
    { bounced: ">=0", sent: ">0" },
    ["sent must be > 0", "hard bounces and soft bounces should be labeled separately if the input distinguishes them - a blended number hides list-hygiene problems"],
    ["sent = 0 -> undefined"],
    { bounced: 150, sent: 10000 }, { bounceRate: "1.50%" },
    ["Delivery Rate"]],
  ["unsubscribe-rate", "P1", [], "unsubscribes / delivered", "Share of delivered emails that triggered an unsubscribe.",
    [["unsubscribes","Unsubscribes",CNT],["delivered","Delivered",CNT]],
    [["unsubRate","Unsubscribe Rate",PCT]],
    { unsubscribes: ">=0", delivered: ">0" },
    ["delivered must be > 0"], ["delivered = 0 -> undefined"],
    { unsubscribes: 20, delivered: 10000 }, { unsubRate: "0.20%" },
    ["Complaint Rate", "List Growth Rate"]],
  ["complaint-rate", "P2", [], "complaints / delivered", "Share of delivered emails marked as spam.",
    [["complaints","Spam complaints",CNT],["delivered","Delivered",CNT]],
    [["complaintRate","Complaint Rate",PCT]],
    { complaints: ">=0", delivered: ">0" },
    ["delivered must be > 0", "rates above ~0.1% put sender reputation at risk - worth a threshold note, not a hard validation error"],
    ["delivered = 0 -> undefined"],
    { complaints: 5, delivered: 10000 }, { complaintRate: "0.05%" },
    ["Unsubscribe Rate"]],
  ["list-growth-rate", "P2", [], "(newSubscribers - unsubscribes) / listStart", "Net change in list size over a period.",
    [["newSubscribers","New subscribers",CNT],["unsubscribes","Unsubscribes (incl. hard bounces)",CNT],["listStart","List size at period start",CNT]],
    [["listGrowthRate","List Growth Rate",PCT]],
    { newSubscribers: ">=0", unsubscribes: ">=0", listStart: ">0" },
    ["listStart must be > 0", "can be negative if losses exceed gains - do not clamp"],
    ["listStart = 0 -> undefined"],
    { newSubscribers: 500, unsubscribes: 300, listStart: 10000 }, { listGrowthRate: "2.00%" },
    ["Unsubscribe Rate"]],
  ["revenue-per-recipient", "P1", ["Revenue per Email"], "revenue / emailsSent", "Average revenue generated per email sent.",
    [["revenue","Revenue attributed",CUR],["emailsSent","Emails sent",CNT]],
    [["rpr","Revenue per Recipient",CUR]],
    { revenue: ">=0", emailsSent: ">0" },
    ["emailsSent must be > 0"], ["emailsSent = 0 -> undefined"],
    { revenue: 8000, emailsSent: 40000 }, { rpr: "0.20" },
    ["Revenue per Visitor"]],

  // --- mobile growth ---
  ["activation-rate", "P1", [], "activatedUsers / installs", "Share of installs who reached the product's defined activation event.",
    [["activatedUsers","Activated users",CNT],["installs","Installs",CNT]],
    [["activationRate","Activation Rate",PCT]],
    { activatedUsers: ">=0", installs: ">0" },
    ["installs must be > 0", "the activation event is product-defined - state it next to the result, it is not a generic funnel step"],
    ["installs = 0 -> undefined"],
    { activatedUsers: 3200, installs: 8000 }, { activationRate: "40.00%" },
    ["D1 Retention", "CPI"]],
  ["dau-mau-stickiness", "P1", ["DAU/WAU Stickiness"], "dau / mau", "How often the average monthly user returns daily - a proxy for habit formation.",
    [["dau","Average daily active users",CNT],["mau","Monthly active users",CNT]],
    [["stickiness","DAU/MAU Stickiness",PCT]],
    { dau: ">=0", mau: ">0" },
    ["mau must be > 0", "dau should not exceed mau"],
    ["mau = 0 -> undefined"],
    { dau: 20000, mau: 100000 }, { stickiness: "20.00%" },
    ["D1 Retention"]],
  ["d1-retention", "P1", ["D7 Retention", "D30 Retention"], "usersReturnedOnDayN / cohortSize", "Share of a signup cohort that returned on day N (N is an input, not a fixed day).",
    [["day","Day N","enum(1/7/14/30)"],["usersReturnedOnDayN","Users returned on day N",CNT],["cohortSize","Original cohort size",CNT]],
    [["retentionN","Day-N Retention",PCT]],
    { usersReturnedOnDayN: ">=0", cohortSize: ">0" },
    ["cohortSize must be > 0", "usersReturnedOnDayN should not exceed cohortSize", "the day value must be shown in the result - D1 and D30 numbers are never comparable to each other"],
    ["cohortSize = 0 -> undefined"],
    { day: 7, usersReturnedOnDayN: 1800, cohortSize: 10000 }, { retentionN: "18.00%" },
    ["Activation Rate", "DAU/MAU Stickiness"]],
  ["uninstall-rate", "P2", [], "uninstalls / installs", "Share of installs later uninstalled.",
    [["uninstalls","Uninstalls",CNT],["installs","Installs",CNT]],
    [["uninstallRate","Uninstall Rate",PCT]],
    { uninstalls: ">=0", installs: ">0" },
    ["installs must be > 0", "uninstalls should not exceed installs within the measured window"],
    ["installs = 0 -> undefined"],
    { uninstalls: 1600, installs: 8000 }, { uninstallRate: "20.00%" },
    ["D1 Retention"]],
  ["session-length-avg", "P3", [], "totalSessionDuration / sessionCount", "Average duration of a session.",
    [["totalSessionDuration","Total session duration (min)","minutes"],["sessionCount","Session count",CNT]],
    [["avgSessionLength","Average Session Length","minutes"]],
    { totalSessionDuration: ">=0", sessionCount: ">0" },
    ["sessionCount must be > 0"], ["sessionCount = 0 -> undefined"],
    { totalSessionDuration: 4500, sessionCount: 1000 }, { avgSessionLength: "4.50 min" },
    ["Sessions per User"]],
  ["sessions-per-user", "P3", [], "sessionCount / dau", "Average number of sessions per active user in the period.",
    [["sessionCount","Session count",CNT],["dau","Active users",CNT]],
    [["sessionsPerUser","Sessions per User","x (avg sessions)"]],
    { sessionCount: ">=0", dau: ">0" },
    ["dau must be > 0"], ["dau = 0 -> undefined"],
    { sessionCount: 3000, dau: 1000 }, { sessionsPerUser: "3.00" },
    ["DAU/MAU Stickiness"]],
  ["arpdau", "P2", [], "revenue / dau", "Average revenue per daily active user - a daily-window metric, not to be confused with monthly ARPU.",
    [["revenue","Daily revenue",CUR],["dau","Daily active users",CNT]],
    [["arpdau","ARPDAU",CUR]],
    { revenue: ">=0", dau: ">0" },
    ["dau must be > 0", "revenue and dau must both be measured on the SAME day - mixing a monthly revenue figure with a single day's DAU misstates the result by ~30x"],
    ["dau = 0 -> undefined"],
    { revenue: 4000, dau: 20000 }, { arpdau: "0.20" },
    ["ARPU"]],

  // --- SaaS ---
  ["mrr", "P1", ["ARR", "MRR Growth Rate"], "sum(activeSubscriptionValue)", "Sum of all active subscription value normalized to a monthly figure; ARR = MRR x 12, growth rate compares two periods' MRR.",
    [["currentMrr","Current MRR",CUR],["priorMrr","Prior period MRR (optional)",CUR]],
    [["mrr","MRR",CUR],["arr","ARR",CUR],["mrrGrowthRate","MRR Growth Rate",PCT]],
    { currentMrr: ">=0", priorMrr: ">=0" },
    ["annual contracts must be normalized to a monthly value before summing, not counted at face value", "mrrGrowthRate is only computed when priorMrr is provided and > 0"],
    ["priorMrr omitted or 0 -> growth rate omitted from output, not shown as 0% or Infinity"],
    { currentMrr: 50000, priorMrr: 45000 }, { mrr: "50,000", arr: "600,000", mrrGrowthRate: "11.11%" },
    ["ARPU", "SaaS Quick Ratio"]],
  ["arpu", "P1", ["ARPA"], "mrr / activeAccounts", "Average revenue per account; optionally divided again by avg seats per account for a true per-user figure.",
    [["mrr","MRR",CUR],["activeAccounts","Active accounts",CNT],["avgSeatsPerAccount","Avg seats per account (optional)",CNT]],
    [["arpu","ARPU",CUR],["arpuPerSeat","ARPU per seat (if seats given)",CUR]],
    { mrr: ">=0", activeAccounts: ">0", avgSeatsPerAccount: ">0 or omitted" },
    ["activeAccounts must be > 0", "ARPU and ARPA are the same number unless avgSeatsPerAccount is supplied - only then do they diverge"],
    ["activeAccounts = 0 -> undefined", "avgSeatsPerAccount omitted -> only arpu is returned"],
    { mrr: 50000, activeAccounts: 250 }, { arpu: "200.00" },
    ["MRR", "Annual Contract Value"]],
  ["nrr", "P0", ["GRR", "Net Dollar Retention", "Revenue Churn"], "(startingMrr + expansion - contraction - churn) / startingMrr", "Revenue retained from the existing base, with (NRR) or without (GRR) expansion revenue counted.",
    [["startingMrr","Starting MRR",CUR],["expansion","Expansion MRR",CUR],["contraction","Contraction MRR",CUR],["churnedMrr","Churned MRR",CUR]],
    [["nrr","Net Revenue Retention (NRR)",PCT],["grr","Gross Revenue Retention (GRR)",PCT]],
    { startingMrr: ">0", expansion: ">=0", contraction: ">=0", churnedMrr: ">=0" },
    ["startingMrr must be > 0", "GRR excludes expansion by definition (numerator caps at startingMrr) - it can equal but never exceed 100%; NRR has no such cap and can exceed 100%"],
    ["contraction + churnedMrr > startingMrr -> both metrics can go negative, valid"],
    { startingMrr: 100000, expansion: 8000, contraction: 2000, churnedMrr: 5000 }, { nrr: "101.00%", grr: "93.00%" },
    ["Logo Churn", "MRR"]],
  ["saas-quick-ratio", "P1", [], "(newMrr + expansionMrr) / (churnedMrr + contractionMrr)", "Growth MRR relative to lost MRR - how much you're growing for every dollar lost.",
    [["newMrr","New MRR",CUR],["expansionMrr","Expansion MRR",CUR],["churnedMrr","Churned MRR",CUR],["contractionMrr","Contraction MRR",CUR]],
    [["quickRatio","SaaS Quick Ratio","x (ratio)"]],
    { newMrr: ">=0", expansionMrr: ">=0", churnedMrr: ">=0", contractionMrr: ">=0" },
    ["denominator (churned + contraction) must be > 0"], ["churnedMrr + contractionMrr = 0 -> undefined (infinite ratio), show '-' not Infinity"],
    { newMrr: 15000, expansionMrr: 5000, churnedMrr: 4000, contractionMrr: 1000 }, { quickRatio: "4.00x" },
    ["Net Revenue Retention", "MRR Growth Rate"]],
  ["magic-number", "P1", [], "netNewArr / priorQuarterSalesMarketingSpend", "Net new ARR generated per dollar of the PRIOR quarter's sales & marketing spend.",
    [["netNewArr","Net new ARR, this quarter",CUR],["priorSmSpend","Prior quarter S&M spend",CUR]],
    [["magicNumber","Magic Number","x (ratio)"]],
    { netNewArr: ">=0", priorSmSpend: ">0" },
    ["must use the PRIOR quarter's spend, not the current quarter's - using the same quarter for both understates efficiency because current spend hasn't converted yet", "priorSmSpend must be > 0"],
    ["priorSmSpend = 0 -> undefined"],
    { netNewArr: 300000, priorSmSpend: 400000 }, { magicNumber: "0.75x" },
    ["SaaS Quick Ratio", "Burn Multiple"]],
  ["rule-of-40", "P1", [], "revenueGrowthRate + profitMargin", "Combined growth-plus-profitability health check.",
    [["revenueGrowthRate","Revenue Growth Rate",PCT],["profitMargin","Profit Margin",PCT]],
    [["ruleOf40Score","Rule of 40 Score","percentage points"]],
    { revenueGrowthRate: "any real number, as %", profitMargin: "any real number, as %" },
    ["both inputs are percentages already, and are ADDED as percentage points - never multiply or compound them", "either input may legitimately be negative"],
    ["both negative -> a valid (very low) score, not an error"],
    { revenueGrowthRate: 30, profitMargin: 15 }, { ruleOf40Score: "45 pts" },
    ["MRR Growth Rate", "Profit Margin"]],
  ["burn-multiple", "P2", [], "netBurn / netNewArr", "Cash burned per dollar of new ARR generated - lower is more efficient.",
    [["netBurn","Net burn",CUR],["netNewArr","Net new ARR",CUR]],
    [["burnMultiple","Burn Multiple","x (ratio)"]],
    { netBurn: ">=0", netNewArr: ">0" },
    ["netNewArr must be > 0 (undefined if ARR shrank - the ratio is not meaningful for a contracting business)"],
    ["netNewArr = 0 or negative -> undefined, show '-' with an explanatory note rather than a misleading negative multiple"],
    { netBurn: 1200000, netNewArr: 3000000 }, { burnMultiple: "0.40x" },
    ["Magic Number"]],
  ["annual-contract-value", "P3", ["ACV"], "totalContractValue / contractYears", "Average annualized value of a contract.",
    [["totalContractValue","Total contract value",CUR],["contractYears","Contract length (years)",CNT]],
    [["acv","Annual Contract Value",CUR]],
    { totalContractValue: ">=0", contractYears: ">0" },
    ["contractYears must be > 0", "ACV is per-contract, distinct from ARPU which is per-account across the whole base"],
    ["contractYears = 0 -> undefined"],
    { totalContractValue: 90000, contractYears: 3 }, { acv: "30,000" },
    ["ARPU"]],
  ["seat-utilization-rate", "P3", [], "activeSeats / purchasedSeats", "Share of purchased seats actually in active use.",
    [["activeSeats","Active seats",CNT],["purchasedSeats","Purchased seats",CNT]],
    [["seatUtilization","Seat Utilization Rate",PCT]],
    { activeSeats: ">=0", purchasedSeats: ">0" },
    ["purchasedSeats must be > 0", "activeSeats should not exceed purchasedSeats"],
    ["purchasedSeats = 0 -> undefined"],
    { activeSeats: 180, purchasedSeats: 250 }, { seatUtilization: "72.00%" },
    ["ARPU"]],

  // --- unit economics ---
  ["ltv", "P0", ["Customer Lifetime Value", "LTV (simple model)"], "aov * purchaseFrequency * customerLifespan", "Simple/historic model: average order value times annual purchase frequency times customer lifespan in years. Two other legitimate models exist - see calculator-architecture.md.",
    [["aov","Average order value",CUR],["purchaseFrequency","Purchases per year",CNT],["customerLifespan","Customer lifespan (years)","years"]],
    [["ltv","LTV (simple model)",CUR]],
    { aov: ">=0", purchaseFrequency: ">=0", customerLifespan: ">=0" },
    ["this is the simple/historic model, not margin-adjusted - it overstates LTV for low-margin businesses; the margin-adjusted model is the one to use for LTV:CAC decisions", "all three inputs must cover consistent units (per-year figures)"],
    ["any input = 0 -> LTV = 0, which is valid, not an error"],
    { aov: 60, purchaseFrequency: 4, customerLifespan: 3 }, { ltv: "720.00" },
    ["LTV:CAC Ratio", "CAC"]],
  ["ltv-cac-ratio", "P0", [], "ltv / cac", "How many times a customer's lifetime value exceeds the cost to acquire them.",
    [["ltv","LTV",CUR],["cac","CAC",CUR]],
    [["ltvCacRatio","LTV:CAC Ratio","x (ratio)"]],
    { ltv: ">=0", cac: ">0" },
    ["cac must be > 0", "use the margin-adjusted LTV model here, not the simple/historic one, or the ratio overstates payback economics - flag which model fed the input"],
    ["cac = 0 -> undefined"],
    { ltv: 720, cac: 240 }, { ltvCacRatio: "3.00x" },
    ["LTV", "CAC", "CAC Payback Period"]],
  ["cac-payback-period", "P0", [], "cac / (arpu * grossMarginPct)", "Months to recover the cost of acquiring a customer, adjusted for gross margin.",
    [["cac","CAC",CUR],["arpu","Monthly ARPU",CUR],["grossMarginPct","Gross margin",PCT]],
    [["paybackMonths","CAC Payback Period","months"]],
    { cac: ">=0", arpu: ">0", grossMarginPct: ">0 and <=1" },
    ["arpu and grossMarginPct must both be > 0 (denominator is arpu * grossMarginPct)", "the margin adjustment is required, not optional - omitting it (using arpu alone) is the single most common error in this calculation"],
    ["arpu = 0 or grossMarginPct = 0 -> undefined"],
    { cac: 600, arpu: 100, grossMarginPct: 75 }, { paybackMonths: "8.0 months" },
    ["CAC", "LTV:CAC Ratio"]],
  ["break-even-point", "P1", ["Break-Even CAC", "Break-Even ROAS"], "fixedCosts / contributionMarginPerUnit", "Units, CAC ceiling, and ROAS floor needed to cover fixed costs, from one shared margin input.",
    [["fixedCosts","Fixed costs",CUR],["pricePerUnit","Price per unit",CUR],["variableCostPerUnit","Variable cost per unit",CUR]],
    [["breakEvenUnits","Break-Even Units",CNT],["breakEvenCac","Break-Even CAC",CUR],["breakEvenRoas","Break-Even ROAS","x (multiplier)"]],
    { fixedCosts: ">=0", pricePerUnit: ">0", variableCostPerUnit: ">=0 and < pricePerUnit" },
    ["variableCostPerUnit must be < pricePerUnit or contribution margin is zero/negative and break-even is never reached", "pricePerUnit must be > 0"],
    ["variableCostPerUnit >= pricePerUnit -> undefined, no break-even exists at this price"],
    { fixedCosts: 50000, pricePerUnit: 100, variableCostPerUnit: 40 }, { breakEvenUnits: "834", breakEvenCac: "60.00", breakEvenRoas: "1.67x" },
    ["Contribution Margin", "ROAS", "CAC"]],

  // --- CRO & funnel ---
  ["cr", "P0", ["Conversion Rate"], "conversions / opportunities", "Share of opportunities (visitors, leads, etc.) that completed the target action. Universal calculator - see calculator-formula-families.json for the 16 industry-naming variants it covers.",
    [["conversions","Conversions",CNT],["opportunities","Total opportunities (visitors/leads/etc.)",CNT]],
    [["conversionRate","Conversion Rate",PCT]],
    { conversions: ">=0", opportunities: ">0" },
    ["opportunities must be > 0", "conversions should not exceed opportunities"],
    ["opportunities = 0 -> undefined"],
    { conversions: 340, opportunities: 8000 }, { conversionRate: "4.25%" },
    ["CTR", "Funnel Analysis"]],
  ["funnel-analysis-multistep", "P1", ["Step Conversion Rate", "Drop-off Rate"], "stage[i+1].count / stage[i].count, per step", "Enter N ordered funnel stages; get per-step conversion, cumulative conversion, and drop-off at each stage.",
    [["stages","Ordered list of {label, count}","array (2-10 stages)"]],
    [["stepConversions","Per-step conversion rates","array of %"],["overallConversion","Overall conversion (first to last stage)",PCT],["dropOffByStage","Drop-off count/rate per stage","array"]],
    { stages: "each count >= 0, non-increasing is expected but not enforced" },
    ["at least 2 stages required", "a stage count higher than the previous stage is allowed but should be visually flagged as a likely data error, not silently accepted"],
    ["any stage count = 0 -> that step's conversion is undefined, remaining downstream steps are not computable"],
    { stages: [{ label: "Visit", count: 10000 }, { label: "Add to cart", count: 1800 }, { label: "Checkout", count: 900 }, { label: "Purchase", count: 620 }] },
    { stepConversions: [18, 50, 68.89], overallConversion: 6.2, dropOffByStage: [82, 50, 31.11] },
    ["Conversion Rate", "Cart Abandonment Rate"]],
  ["field-abandonment-rate", "P2", [], "usersAbandoningAtField / usersReachingField", "Share of users who reach a specific form field and abandon there - a per-field diagnostic, distinct from whole-form completion.",
    [["usersAbandoningAtField","Users abandoning at this field",CNT],["usersReachingField","Users reaching this field",CNT]],
    [["fieldAbandonment","Field Abandonment Rate",PCT]],
    { usersAbandoningAtField: ">=0", usersReachingField: ">0" },
    ["usersReachingField must be > 0", "requires field-level instrumentation (e.g. focus/blur events) - state that as a prerequisite"],
    ["usersReachingField = 0 -> undefined"],
    { usersAbandoningAtField: 220, usersReachingField: 1000 }, { fieldAbandonment: "22.00%" },
    ["Form Completion Rate"]],
  ["exit-rate", "P2", [], "exits / pageviews", "Share of pageviews on a page that were the last in the session - distinct from Bounce Rate, which counts only single-page sessions.",
    [["exits","Exits",CNT],["pageviews","Pageviews of this page",CNT]],
    [["exitRate","Exit Rate",PCT]],
    { exits: ">=0", pageviews: ">0" },
    ["pageviews must be > 0", "must not be presented next to Bounce Rate without the distinction explained - a high-traffic page can have a high exit rate and a low bounce rate simultaneously, and that is not a contradiction"],
    ["pageviews = 0 -> undefined"],
    { exits: 400, pageviews: 2000 }, { exitRate: "20.00%" },
    ["Landing Page Bounce Rate"]],
  ["bounce-rate-landing", "P3", [], "singlePageSessions / totalSessions", "Share of sessions that viewed only one page.",
    [["singlePageSessions","Single-page sessions",CNT],["totalSessions","Total sessions",CNT]],
    [["bounceRate","Bounce Rate",PCT]],
    { singlePageSessions: ">=0", totalSessions: ">0" },
    ["totalSessions must be > 0", "session-based, not funnel-step-based - not directly comparable to Cart Abandonment Rate despite the superficially similar shape"],
    ["totalSessions = 0 -> undefined"],
    { singlePageSessions: 1400, totalSessions: 4000 }, { bounceRate: "35.00%" },
    ["Exit Rate"]],
  ["engagement-rate", "P1", ["Web Engagement Rate"], "engagedSessions / totalSessions", "Engaged sessions (meeting a platform's engagement threshold) as a share of total sessions.",
    [["engagedSessions","Engaged sessions",CNT],["totalSessions","Total sessions",CNT]],
    [["engagementRate","Engagement Rate",PCT]],
    { engagedSessions: ">=0", totalSessions: ">0" },
    ["totalSessions must be > 0", "the 'engaged' threshold (e.g. GA4's 10s+/conversion/2+ pageviews definition) should be stated, since it is platform-defined"],
    ["totalSessions = 0 -> undefined"],
    { engagedSessions: 2600, totalSessions: 4000 }, { engagementRate: "65.00%" },
    ["Bounce Rate"]],

  // --- experimentation ---
  ["ab-test-significance", "P0", ["Two-Proportion Z-Test"], "z = (p2 - p1) / SE(pooled)", "Two-proportion z-test for whether a variant's conversion rate differs significantly from control.",
    [["visitorsA","Control visitors",CNT],["conversionsA","Control conversions",CNT],["visitorsB","Variant visitors",CNT],["conversionsB","Variant conversions",CNT]],
    [["controlRate","Control rate",PCT],["variantRate","Variant rate",PCT],["absoluteUplift","Absolute uplift","percentage points"],["relativeUplift","Relative uplift",PCT],["zScore","z-score","number"],["pValue","p-value","number"],["significant","Significant at 95%?","boolean"]],
    { visitorsA: ">0", conversionsA: ">=0 and <=visitorsA", visitorsB: ">0", conversionsB: ">=0 and <=visitorsB" },
    ["both visitor counts must be > 0", "frequentist method - see Bayesian Probability to Beat Control for the documented alternative method, do not present this as the only valid approach"],
    ["conversionsA = 0 or conversionsB = 0 -> valid, z-test still computes", "very small samples (<30 per arm) -> flag result as low-confidence even if p < 0.05"],
    { visitorsA: 5000, conversionsA: 250, visitorsB: 5000, conversionsB: 290 }, { pValue: "0.0847", significant: false },
    ["Sample Size Calculator", "Confidence Interval"]],
  ["confidence-interval-calculator", "P1", [], "p ± z* * sqrt(p(1-p)/n)", "Confidence interval around one observed conversion rate.",
    [["conversions","Conversions",CNT],["visitors","Visitors",CNT],["confidenceLevel","Confidence level","enum(90/95/99)"]],
    [["pointEstimate","Observed rate",PCT],["lowerBound","Lower bound",PCT],["upperBound","Upper bound",PCT]],
    { conversions: ">=0 and <=visitors", visitors: ">0" },
    ["visitors must be > 0", "normal-approximation interval - accurate for reasonably large n and p not near 0 or 1; flag when n*p or n*(1-p) < 5"],
    ["visitors = 0 -> undefined"],
    { conversions: 250, visitors: 5000, confidenceLevel: 95 }, { pointEstimate: "5.00%", lowerBound: "4.40%", upperBound: "5.60%" },
    ["A/B Test Significance"]],
  ["bayesian-probability-to-beat", "P2", [], "P(variant_rate > control_rate | data), via Beta posteriors", "Bayesian alternative to the frequentist z-test: probability the variant is actually better than control.",
    [["visitorsA","Control visitors",CNT],["conversionsA","Control conversions",CNT],["visitorsB","Variant visitors",CNT],["conversionsB","Variant conversions",CNT],["priorAlpha","Prior alpha (default 1)",CNT],["priorBeta","Prior beta (default 1)",CNT]],
    [["probabilityBToBeatA","Probability B beats A",PCT]],
    { visitorsA: ">0", visitorsB: ">0" },
    ["a flat (1,1) prior is the honest default unless the user states a real informative prior - do not silently invent one", "this answers a genuinely different question from the frequentist p-value (probability of superiority, not probability of the data under a null) - never present the two numbers as interchangeable"],
    ["extreme priors can dominate a small sample - flag low-traffic results as prior-sensitive"],
    { visitorsA: 5000, conversionsA: 250, visitorsB: 5000, conversionsB: 290 }, { probabilityBToBeatA: "93.40%" },
    ["A/B Test Significance"]],
  ["multi-variant-test-significance", "P2", [], "pairwise z-tests with Bonferroni-corrected alpha", "A/B/n significance across 3+ variants with a multiple-comparison correction.",
    [["variants","Array of {label, visitors, conversions}, 3-8 variants","array"],["controlIndex","Which variant is control",CNT]],
    [["pairwiseResults","Per-variant-vs-control results with corrected significance","array"]],
    { variants: "each visitors > 0, conversions <= visitors" },
    ["at least 3 variants required (2 is just the standard A/B test)", "alpha must be divided by the number of comparisons (Bonferroni) - running N uncorrected z-tests inflates the false-positive rate and must not be shipped as the default"],
    ["a variant with 0 conversions -> still computable, its rate is 0%"],
    { variants: [{ label: "Control", visitors: 4000, conversions: 200 }, { label: "B", visitors: 4000, conversions: 230 }, { label: "C", visitors: 4000, conversions: 180 }], controlIndex: 0 },
    { pairwiseResults: [{ variant: "B", significant: false, correctedAlpha: 0.025 }, { variant: "C", significant: false, correctedAlpha: 0.025 }] },
    ["A/B Test Significance", "Sample Size Calculator"]],
  ["sample-size-calculator", "P1", ["Power Analysis"], "n = 2 * ((z_alpha/2 + z_beta)^2 * p(1-p)) / (baselineRate * mde)^2", "Required sample size per variant, given a baseline rate, a RELATIVE minimum detectable lift, power and significance level.",
    [["baselineRate","Baseline conversion rate",PCT],["mde","Minimum detectable effect (relative lift)",PCT],["power","Statistical power","enum(80/90)"],["significanceLevel","Significance level","enum(90/95/99)"]],
    [["samplePerVariant","Required sample size per variant",CNT]],
    { baselineRate: ">0 and <1", mde: ">0" },
    ["baselineRate must be strictly between 0 and 1", "mde is RELATIVE (10 means 'detect a 10% relative lift') - resolved explicitly during implementation after this was flagged as an unresolved ambiguity; converted to an absolute effect internally as baselineRate x mde before use in the formula"],
    ["mde very small relative to baseline -> sample size can become impractically large; surface the raw number rather than capping it silently"],
    { baselineRate: 5, mde: 10, power: 80, significanceLevel: 95 }, { samplePerVariant: "29,827" },
    ["Minimum Detectable Effect", "Test Duration Estimator"]],
  ["minimum-detectable-effect", "P1", [], "MDE = sqrt(2 * (z_alpha/2 + z_beta)^2 * p(1-p) / n)", "Given available traffic and test duration, the smallest effect size the test can reliably detect - the inverse of Sample Size.",
    [["baselineRate","Baseline conversion rate",PCT],["samplePerVariant","Available sample per variant",CNT],["power","Statistical power","enum(80/90)"],["significanceLevel","Significance level","enum(90/95/99)"]],
    [["mde","Minimum Detectable Effect",PCT]],
    { baselineRate: ">0 and <1", samplePerVariant: ">0" },
    ["samplePerVariant must be > 0", "solves the same equation as Sample Size Calculator for a different unknown - kept as its own tool because users arrive asking 'what can I detect', not 'how many visitors do I need'"],
    ["samplePerVariant very small -> MDE become very large (>100%), display as-is with a 'test is underpowered' flag rather than erroring"],
    { baselineRate: 0.05, samplePerVariant: 5000, power: 80, significanceLevel: 95 }, { mde: "25.30%" },
    ["Sample Size Calculator"]],
  ["test-duration-estimator", "P1", ["Required Runtime"], "requiredSamplePerVariant / dailyTrafficPerVariant", "Days needed to reach the required sample size at current traffic.",
    [["requiredSamplePerVariant","Required sample per variant",CNT],["dailyTrafficPerVariant","Daily traffic per variant",CNT]],
    [["days","Estimated Duration","days"]],
    { requiredSamplePerVariant: ">0", dailyTrafficPerVariant: ">0" },
    ["dailyTrafficPerVariant must be > 0", "round the result UP to the nearest full week - stopping mid-week reintroduces day-of-week bias even if the raw day count is reached"],
    ["dailyTrafficPerVariant very small -> very large day counts are valid output, not an error"],
    { requiredSamplePerVariant: 29827, dailyTrafficPerVariant: 1000 }, { days: "35 days (5 weeks)" },
    ["Sample Size Calculator"]],
  ["srm-check", "P2", ["Sample Ratio Mismatch"], "chi-square goodness-of-fit test on observed vs expected traffic split", "Checks whether the actual traffic split between variants matches the intended split - a guardrail on the test's validity, not on its outcome.",
    [["variants","Array of {label, expectedShare, observedVisitors}","array"]],
    [["chiSquare","Chi-square statistic","number"],["pValue","p-value","number"],["mismatchDetected","SRM detected?","boolean"]],
    { variants: "expectedShare values sum to 1, observedVisitors >= 0" },
    ["expectedShare values across variants must sum to 1", "a low p-value here (e.g. <0.01) means the TEST ITSELF is broken (bucketing bug, bot filtering asymmetry) - it says nothing about which variant is better and must never be read as a significance result"],
    ["a perfectly even split with small samples can still trigger a false SRM flag - note that low-traffic tests are noisier on this check too"],
    { variants: [{ label: "A", expectedShare: 0.5, observedVisitors: 5100 }, { label: "B", expectedShare: 0.5, observedVisitors: 4900 }] },
    { pValue: "0.317", mismatchDetected: false },
    ["A/B Test Significance"]],
];

// Two catalog research-ids collide with URLs already shipped and public
// under different, shorter slugs from before Phase 1 existed
// (src/lib/calculators.ts). Per the Phase 2 migration brief: preserve
// existing public URLs whenever possible rather than force a redirect.
// The research id (used for family cross-refs, candidate lookups, the
// `id` field) is untouched; only the URL-facing `slug` is overridden.
const SLUG_OVERRIDES = {
  "ab-test-significance": "ab-test",
  "cart-abandonment-rate": "cart-abandonment",
};

// LTV is documented in calculator-architecture.md Phase 5 as having THREE
// legitimate models. Phase 1's tuple only captured the simple model's
// inputs - implementation surfaced that gap, so it is fixed at the
// source here (not patched downstream) and documented in the Phase 2
// section of calculator-architecture.md.
const MODES = {
  ltv: [
    {
      id: "simple", label: "Simple (historic)",
      formula: "aov * purchaseFrequency * customerLifespan",
      inputs: [{ key: "aov", label: "Average order value", unit: CUR }, { key: "purchaseFrequency", label: "Purchases per year", unit: CNT }, { key: "customerLifespan", label: "Customer lifespan (years)", unit: "years" }],
      outputs: [{ key: "ltv", label: "LTV (simple model)", unit: CUR }],
    },
    {
      id: "margin-adjusted", label: "Margin-adjusted (predictive)",
      formula: "(aov * purchaseFrequency * grossMarginPct) / churnRate",
      inputs: [{ key: "aov", label: "Average order value", unit: CUR }, { key: "purchaseFrequency", label: "Purchases per year", unit: CNT }, { key: "grossMarginPct", label: "Gross margin", unit: PCT }, { key: "churnRate", label: "Annual churn rate", unit: PCT }],
      outputs: [{ key: "ltv", label: "LTV (margin-adjusted model)", unit: CUR }],
    },
    {
      id: "mobile-arpdau", label: "Mobile (ARPDAU-based)",
      formula: "arpdau * avgLifetimeDays",
      inputs: [{ key: "arpdau", label: "ARPDAU", unit: CUR }, { key: "avgLifetimeDays", label: "Average lifetime (days)", unit: DAYS }],
      outputs: [{ key: "ltv", label: "LTV (mobile model)", unit: CUR }],
    },
  ],
};

// Phase 3 addition: an editorially-written, human-readable formula for
// the handful of entries whose raw `formula` string uses notation
// (^, ±, |, subscripts, brackets) that the runtime auto-prettifier
// (CalculatorTool.tsx's prettyFormula) correctly refuses to touch and
// falls back to showing raw. Written by hand, not generated - exactly
// what instruction 14 asked for ("not generated through risky automatic
// prettification"). Mathematically equivalent to `formula`, never a
// substitute for it in calc-registry.ts.
const FORMULA_DISPLAY = {
  "funnel-analysis-multistep": "Stage conversion = Next stage count ÷ Previous stage count",
  "ab-test-significance": "z-score = (Variant rate − Control rate) ÷ Standard error",
  "confidence-interval-calculator": "Confidence interval = Observed rate ± (z-value × Standard error)",
  "bayesian-probability-to-beat": "Probability variant beats control, estimated from Beta distributions fitted to both observed conversion rates",
  "sample-size-calculator": "Sample size per variant = 2 × (z-values for power and significance, summed)² × Baseline rate × (1 − Baseline rate) ÷ (Baseline rate × Relative MDE)²",
  "minimum-detectable-effect": "Minimum detectable effect = √(2 × (z-values for power and significance, summed)² × Baseline rate × (1 − Baseline rate) ÷ Sample size)",
};

// Phase 3 addition (instruction 15): calculators with `modes` need a
// worked example PER mode, not just the default one - the top-level
// exampleInput/exampleOutput only ever covered "simple". These numbers
// are not invented for this doc: they are the exact values
// test-calculators.mjs already verifies against calc-registry.ts's ltv()
// function (see that file's "Phase 28" mode tests), promoted here as the
// canonical per-mode example rather than living only inside a test file.
// %-unit inputs are written as whole numbers (60 = 60%), matching the
// same UI convention as every other example in this catalog.
const EXAMPLES_BY_MODE = {
  ltv: {
    simple: { input: { aov: 60, purchaseFrequency: 4, customerLifespan: 3 }, output: { ltv: "720.00" } },
    "margin-adjusted": { input: { aov: 60, purchaseFrequency: 4, grossMarginPct: 60, churnRate: 20 }, output: { ltv: "720.00" } },
    "mobile-arpdau": { input: { arpdau: 0.2, avgLifetimeDays: 400 }, output: { ltv: "80.00" } },
  },
};

// name (minus " Calculator"/parenthetical, normalized) -> slug, for resolving
// relatedMetrics text into real relatedCalculators slugs when a metric named
// there is itself a shipped calculator. Metrics that don't resolve (e.g.
// "Reach", a glossary entry) are simply not linked - that's correct, not a bug.
const normName = (s) => s.toLowerCase().replace(/\([^)]*\)/g, "").replace(/[^a-z0-9]/g, "");
const nameToSlug = new Map(specs.map(([id]) => [normName(byId[id].name), id]));

const catalog = specs.map(([id, priority, aliases, formula, formulaPlainEnglish, inputs, outputs, acceptedRanges, validationRules, edgeCases, exampleInput, exampleOutput, relatedMetrics]) => {
  const c = byId[id];
  if (!c) throw new Error("Unknown candidate id in specs: " + id);
  const famEntry = fam.find((f) => [...f.standaloneCalculators, ...(f.keptSeparate || [])].includes(id));
  const famRelated = famMembersOf[id] || [];
  const metricRelated = relatedMetrics
    .map((m) => nameToSlug.get(normName(m)))
    .filter((s) => s && s !== id);
  const relatedCalculators = [...new Set([...famRelated, ...metricRelated])];
  return {
    id: "CALC-" + id.toUpperCase(),
    // A few candidate names already end in "Calculator" (e.g. "Sample Size
    // Calculator") - found via live-page review during Phase 2 implementation,
    // not caught by Phase 1 validation since it only checks structural
    // fields, not name suffix duplication. Strip before appending so the
    // catalog never ships "X Calculator Calculator".
    name: /\bcalculator$/i.test(c.name.trim()) ? c.name.trim() : c.name + " Calculator",
    slug: id,
    category: c.category,
    subcategory: c.subcategory,
    classification: c.classification,
    priority,
    status: ["roas","cr","cac","ltv","ctr","cpc","cpm","cpl","aov","ab-test-significance","marketing-roi","profit-margin","retention-rate","cart-abandonment-rate","engagement-rate"].includes(id) ? "implemented" : "recommended",
    formula,
    formulaPlainEnglish,
    inputs: inputs.map(([key, label, unit]) => ({ key, label, unit })),
    outputs: outputs.map(([key, label, unit]) => ({ key, label, unit })),
    inputUnits: Object.fromEntries(inputs.map(([key, , unit]) => [key, unit])),
    outputUnits: Object.fromEntries(outputs.map(([key, , unit]) => [key, unit])),
    acceptedRanges,
    validationRules,
    edgeCases,
    exampleInput,
    exampleOutput,
    relatedMetrics,
    relatedCalculators,
    formulaFamily: famEntry ? famEntry.id : c.family,
    aliases,
    ...(MODES[id] ? { modes: MODES[id] } : {}),
    ...(FORMULA_DISPLAY[id] ? { formulaDisplay: FORMULA_DISPLAY[id] } : {}),
    ...(EXAMPLES_BY_MODE[id] ? { examplesByMode: EXAMPLES_BY_MODE[id] } : {}),
  };
});

// Apply slug overrides after the full catalog is built, so every
// relatedCalculators reference gets rewritten consistently too - a
// record pointing at "ab-test-significance" must end up pointing at
// "ab-test" once that record's own slug is overridden.
for (const rec of catalog) {
  if (SLUG_OVERRIDES[rec.slug]) rec.slug = SLUG_OVERRIDES[rec.slug];
  rec.relatedCalculators = rec.relatedCalculators.map((s) => SLUG_OVERRIDES[s] || s);
}

writeFileSync(new URL("./calculator-catalog.json", import.meta.url), JSON.stringify({
  _description: "Phase 4 catalog: full specification for every candidate recommended as a real calculator (classification calculator or calculator-educational). Formula families and category/subcategory are cross-validated against calculator-candidates.json and calculator-formula-families.json at generation time, not hand-copied.",
  generatedFrom: ["calculator-candidates.json", "calculator-formula-families.json"],
  count: catalog.length,
  calculators: catalog,
}, null, 2) + "\n");

console.log("wrote", catalog.length, "catalog entries");
const byPriority = {};
for (const c of catalog) byPriority[c.priority] = (byPriority[c.priority]||0)+1;
console.log(byPriority);
